import {
  aLendaDoHeroiProfissionalExample,
  atravesseProfissionalExample,
  cacaEstelarProfissionalExample,
  cercoNaBaseProfissionalExample,
  chefaoDasSombrasExample,
  corridaInfinitaProfissionalExample,
  defesaDaTorreExample,
  guardiaoDoPortalExample,
  labirintoDosRobosProfissionalExample,
  minaDeCristaisProfissionalExample,
  mundoDeBlocosProfissionalExample,
  parkourDoVulcaoExample,
  patrulhaEspacialProfissionalExample,
  quadraMalucaExample,
  reunirRebanhoProfissionalExample,
  saltoNasNuvensExample,
  tiroAoAlvoExample,
} from './examples'

export const gameKit3DExamples = [
  defesaDaTorreExample,
  saltoNasNuvensExample,
  parkourDoVulcaoExample,
  quadraMalucaExample,
  guardiaoDoPortalExample,
  tiroAoAlvoExample,
  chefaoDasSombrasExample,
  corridaInfinitaProfissionalExample,
  labirintoDosRobosProfissionalExample,
  mundoDeBlocosProfissionalExample,
  patrulhaEspacialProfissionalExample,
  atravesseProfissionalExample,
  reunirRebanhoProfissionalExample,
  aLendaDoHeroiProfissionalExample,
  cacaEstelarProfissionalExample,
  cercoNaBaseProfissionalExample,
  minaDeCristaisProfissionalExample,
] as const
