// Generated by scripts/gen-snow-descent.ts. Do not edit.
import type { SZIRV2 } from '../ir'
export const SNOW_IR = {
  version: 2,
  html: [],
  css: [],
  behavior: {
    start: [
      {
        type: 'g2d:setupStage',
        width: {
          type: 'num',
          value: 640,
        },
        height: {
          type: 'num',
          value: 720,
        },
        bg: '#102d46',
      },
      {
        type: 'g2d:setStageDescription',
        description:
          'Desça a montanha, pegue estrelas e desvie das bandeiras. Setas ou A/D para virar; arraste na neve no celular. Enter ou toque começa. P ou o botão no canto pausa. Chegue ao fim com pelo menos uma das três vidas. R reinicia.',
      },
      {
        type: 'g2d:sceneCommand',
        method: 'addSceneBackdrop',
        args: [
          {
            type: 'str',
            value: 'ceu',
          },
          {
            type: 'str',
            value: 'neve-ceu',
          },
          {
            type: 'str',
            value: 'far',
          },
        ],
      },
      {
        type: 'g2d:sceneCommand',
        method: 'addSceneBackdrop',
        args: [
          {
            type: 'str',
            value: 'montanhas',
          },
          {
            type: 'str',
            value: 'neve-montanhas',
          },
          {
            type: 'str',
            value: 'back',
          },
        ],
      },
      {
        type: 'g2d:sceneCommand',
        method: 'sceneBackdropMotion',
        args: [
          {
            type: 'str',
            value: 'montanhas',
          },
          {
            type: 'num',
            value: 40,
          },
        ],
      },
      {
        type: 'g2d:sceneCommand',
        method: 'addSceneBackdrop',
        args: [
          {
            type: 'str',
            value: 'chao',
          },
          {
            type: 'str',
            value: 'neve-pista',
          },
          {
            type: 'str',
            value: 'back',
          },
        ],
      },
      {
        type: 'g2d:sceneCommand',
        method: 'addSceneBackdrop',
        args: [
          {
            type: 'str',
            value: 'flocos',
          },
          {
            type: 'str',
            value: 'neve-brilho',
          },
          {
            type: 'str',
            value: 'front',
          },
        ],
      },
      {
        type: 'g2d:sceneCommand',
        method: 'createSpriteTrack',
        args: [
          {
            type: 'str',
            value: 'pista',
          },
        ],
      },
      {
        type: 'g2d:createImageSprite',
        varName: 'jogador',
        x: {
          type: 'num',
          value: 0,
        },
        y: {
          type: 'num',
          value: 0,
        },
        w: {
          type: 'num',
          value: 26,
        },
        h: {
          type: 'num',
          value: 42,
        },
        image: 'neve-esquiador',
      },
      {
        type: 'g2d:sceneCommand',
        method: 'sceneAnimation',
        args: [
          {
            type: 'var',
            name: 'jogador',
          },
          {
            type: 'str',
            value: 'neve-esquiador-animado',
          },
          {
            type: 'str',
            value: 'deslizar',
          },
          {
            type: 'bool',
            value: false,
          },
        ],
      },
      {
        type: 'g2d:sceneCommand',
        method: 'trackPlayer',
        args: [
          {
            type: 'str',
            value: 'pista',
          },
          {
            type: 'var',
            name: 'jogador',
          },
          {
            type: 'num',
            value: 3,
          },
        ],
      },
      {
        type: 'g2d:sceneCommand',
        method: 'trackControls',
        args: [
          {
            type: 'str',
            value: 'pista',
          },
          {
            type: 'num',
            value: 140,
          },
          {
            type: 'num',
            value: 120,
          },
        ],
      },
      {
        type: 'g2d:sceneCommand',
        method: 'trackTravel',
        args: [
          {
            type: 'str',
            value: 'pista',
          },
          {
            type: 'num',
            value: 320,
          },
          {
            type: 'num',
            value: 6600,
          },
        ],
      },
      {
        type: 'g2d:createImageSprite',
        varName: 'estrela',
        x: {
          type: 'num',
          value: 0,
        },
        y: {
          type: 'num',
          value: 0,
        },
        w: {
          type: 'num',
          value: 22,
        },
        h: {
          type: 'num',
          value: 22,
        },
        image: 'neve-estrela',
      },
      {
        type: 'g2d:sceneCommand',
        method: 'putTrackSprite',
        args: [
          {
            type: 'str',
            value: 'pista',
          },
          {
            type: 'var',
            name: 'estrela',
          },
          {
            type: 'num',
            value: -80,
          },
          {
            type: 'num',
            value: 600,
          },
        ],
      },
      {
        type: 'g2d:sceneCommand',
        method: 'repeatTrackSprite',
        args: [
          {
            type: 'str',
            value: 'pista',
          },
          {
            type: 'var',
            name: 'estrela',
          },
          {
            type: 'num',
            value: 12,
          },
          {
            type: 'num',
            value: 480,
          },
          {
            type: 'str',
            value: 'weave',
          },
        ],
      },
      {
        type: 'g2d:createImageSprite',
        varName: 'bandeira',
        x: {
          type: 'num',
          value: 0,
        },
        y: {
          type: 'num',
          value: 0,
        },
        w: {
          type: 'num',
          value: 28,
        },
        h: {
          type: 'num',
          value: 60,
        },
        image: 'neve-bandeira',
      },
      {
        type: 'g2d:sceneCommand',
        method: 'putTrackSprite',
        args: [
          {
            type: 'str',
            value: 'pista',
          },
          {
            type: 'var',
            name: 'bandeira',
          },
          {
            type: 'num',
            value: 80,
          },
          {
            type: 'num',
            value: 840,
          },
        ],
      },
      {
        type: 'g2d:sceneCommand',
        method: 'repeatTrackSprite',
        args: [
          {
            type: 'str',
            value: 'pista',
          },
          {
            type: 'var',
            name: 'bandeira',
          },
          {
            type: 'num',
            value: 6,
          },
          {
            type: 'num',
            value: 960,
          },
          {
            type: 'str',
            value: 'alternate',
          },
        ],
      },
      {
        type: 'g2d:createImageSprite',
        varName: 'bandeiraDireita',
        x: {
          type: 'num',
          value: 0,
        },
        y: {
          type: 'num',
          value: 0,
        },
        w: {
          type: 'num',
          value: 28,
        },
        h: {
          type: 'num',
          value: 60,
        },
        image: 'neve-bandeira',
      },
      {
        type: 'g2d:sceneCommand',
        method: 'putTrackSprite',
        args: [
          {
            type: 'str',
            value: 'pista',
          },
          {
            type: 'var',
            name: 'bandeiraDireita',
          },
          {
            type: 'num',
            value: 70,
          },
          {
            type: 'num',
            value: 1320,
          },
        ],
      },
      {
        type: 'g2d:sceneCommand',
        method: 'repeatTrackSprite',
        args: [
          {
            type: 'str',
            value: 'pista',
          },
          {
            type: 'var',
            name: 'bandeiraDireita',
          },
          {
            type: 'num',
            value: 6,
          },
          {
            type: 'num',
            value: 960,
          },
          {
            type: 'str',
            value: 'line',
          },
        ],
      },
      {
        type: 'g2d:createImageSprite',
        varName: 'gelo',
        x: {
          type: 'num',
          value: 0,
        },
        y: {
          type: 'num',
          value: 0,
        },
        w: {
          type: 'num',
          value: 150,
        },
        h: {
          type: 'num',
          value: 32,
        },
        image: 'neve-gelo',
      },
      {
        type: 'g2d:sceneCommand',
        method: 'putTrackSprite',
        args: [
          {
            type: 'str',
            value: 'pista',
          },
          {
            type: 'var',
            name: 'gelo',
          },
          {
            type: 'num',
            value: -40,
          },
          {
            type: 'num',
            value: 930,
          },
        ],
      },
      {
        type: 'g2d:sceneCommand',
        method: 'repeatTrackSprite',
        args: [
          {
            type: 'str',
            value: 'pista',
          },
          {
            type: 'var',
            name: 'gelo',
          },
          {
            type: 'num',
            value: 12,
          },
          {
            type: 'num',
            value: 480,
          },
          {
            type: 'str',
            value: 'weave',
          },
        ],
      },
      {
        type: 'g2d:createImageSprite',
        varName: 'pinheiroEsquerda',
        x: {
          type: 'num',
          value: 0,
        },
        y: {
          type: 'num',
          value: 0,
        },
        w: {
          type: 'num',
          value: 90,
        },
        h: {
          type: 'num',
          value: 135,
        },
        image: 'neve-pinheiro',
      },
      {
        type: 'g2d:sceneCommand',
        method: 'putTrackSprite',
        args: [
          {
            type: 'str',
            value: 'pista',
          },
          {
            type: 'var',
            name: 'pinheiroEsquerda',
          },
          {
            type: 'num',
            value: -210,
          },
          {
            type: 'num',
            value: 280,
          },
        ],
      },
      {
        type: 'g2d:sceneCommand',
        method: 'repeatTrackSprite',
        args: [
          {
            type: 'str',
            value: 'pista',
          },
          {
            type: 'var',
            name: 'pinheiroEsquerda',
          },
          {
            type: 'num',
            value: 36,
          },
          {
            type: 'num',
            value: 180,
          },
          {
            type: 'str',
            value: 'steps-left',
          },
        ],
      },
      {
        type: 'g2d:createImageSprite',
        varName: 'pinheiroDireita',
        x: {
          type: 'num',
          value: 0,
        },
        y: {
          type: 'num',
          value: 0,
        },
        w: {
          type: 'num',
          value: 90,
        },
        h: {
          type: 'num',
          value: 135,
        },
        image: 'neve-pinheiro',
      },
      {
        type: 'g2d:sceneCommand',
        method: 'putTrackSprite',
        args: [
          {
            type: 'str',
            value: 'pista',
          },
          {
            type: 'var',
            name: 'pinheiroDireita',
          },
          {
            type: 'num',
            value: 210,
          },
          {
            type: 'num',
            value: 340,
          },
        ],
      },
      {
        type: 'g2d:sceneCommand',
        method: 'repeatTrackSprite',
        args: [
          {
            type: 'str',
            value: 'pista',
          },
          {
            type: 'var',
            name: 'pinheiroDireita',
          },
          {
            type: 'num',
            value: 36,
          },
          {
            type: 'num',
            value: 180,
          },
          {
            type: 'str',
            value: 'steps-right',
          },
        ],
      },
      {
        type: 'g2d:sceneCommand',
        method: 'trackHud',
        args: [
          {
            type: 'str',
            value: 'pista',
          },
          {
            type: 'str',
            value: 'Estrelas',
          },
          {
            type: 'num',
            value: 12,
          },
        ],
      },
      {
        type: 'g2d:sceneCommand',
        method: 'sceneGameScreens',
        args: [
          {
            type: 'str',
            value: 'DESCIDA DA NEVE',
          },
          {
            type: 'str',
            value: 'Pegue estrelas. Desvie das bandeiras.',
          },
        ],
      },
    ],
    events: [
      {
        type: 'g2d:sceneEvent',
        method: 'onTrackEncounter',
        args: [
          {
            type: 'str',
            value: 'pista',
          },
          {
            type: 'var',
            name: 'estrela',
          },
        ],
        body: [
          {
            type: 'g2d:sceneCommand',
            method: 'collectTrackItem',
            args: [],
          },
          {
            type: 'g2d:sceneCommand',
            method: 'trackScore',
            args: [
              {
                type: 'str',
                value: 'pista',
              },
              {
                type: 'num',
                value: 1,
              },
            ],
          },
        ],
      },
      {
        type: 'g2d:sceneEvent',
        method: 'onTrackEncounter',
        args: [
          {
            type: 'str',
            value: 'pista',
          },
          {
            type: 'var',
            name: 'bandeira',
          },
        ],
        body: [
          {
            type: 'g2d:sceneCommand',
            method: 'trackHurt',
            args: [
              {
                type: 'str',
                value: 'pista',
              },
              {
                type: 'num',
                value: 1,
              },
            ],
          },
        ],
      },
      {
        type: 'g2d:sceneEvent',
        method: 'onTrackEncounter',
        args: [
          {
            type: 'str',
            value: 'pista',
          },
          {
            type: 'var',
            name: 'bandeiraDireita',
          },
        ],
        body: [
          {
            type: 'g2d:sceneCommand',
            method: 'trackHurt',
            args: [
              {
                type: 'str',
                value: 'pista',
              },
              {
                type: 'num',
                value: 1,
              },
            ],
          },
        ],
      },
    ],
    loops: [],
  },
  extensions: [
    {
      extensionId: 'game-2d',
    },
  ],
} as SZIRV2
