// Generated by scripts/gen-snow-descent.ts. Do not edit.
import type { SZIRV2 } from '../ir'
export const SNOW_IR = {
  version: 2,
  html: [],
  css: [],
  behavior: {
    start: [
      {
        type: 'gk:setup',
        w: {
          type: 'num',
          value: 640,
        },
        h: {
          type: 'num',
          value: 720,
        },
        bg: '#102d46',
        accent: '#f99143',
      },
      {
        type: 'gk:setStageDescription',
        description:
          'Monte a descida com controles, movimento, vidas, placar e telas personalizáveis. Clique em Descer a montanha para começar. Setas/A-D ou arraste na neve para virar. P ou Pausar abre a pausa; Continuar retoma. Chegue com pelo menos seis estrelas e uma vida. O botão da tela final recomeça.',
      },
      {
        type: 'gk:sceneCommand',
        method: 'addSceneBackdrop',
        args: [
          {
            type: 'str',
            value: 'ceu',
          },
          {
            type: 'str',
            value: 'neve-ceu',
          },
          {
            type: 'str',
            value: 'far',
          },
        ],
      },
      {
        type: 'gk:sceneCommand',
        method: 'addSceneBackdrop',
        args: [
          {
            type: 'str',
            value: 'montanhas',
          },
          {
            type: 'str',
            value: 'neve-montanhas',
          },
          {
            type: 'str',
            value: 'back',
          },
        ],
      },
      {
        type: 'gk:sceneCommand',
        method: 'sceneBackdropMotion',
        args: [
          {
            type: 'str',
            value: 'montanhas',
          },
          {
            type: 'num',
            value: 40,
          },
        ],
      },
      {
        type: 'gk:sceneCommand',
        method: 'addSceneBackdrop',
        args: [
          {
            type: 'str',
            value: 'chao',
          },
          {
            type: 'str',
            value: 'neve-pista',
          },
          {
            type: 'str',
            value: 'back',
          },
        ],
      },
      {
        type: 'gk:sceneCommand',
        method: 'addSceneBackdrop',
        args: [
          {
            type: 'str',
            value: 'flocos',
          },
          {
            type: 'str',
            value: 'neve-brilho',
          },
          {
            type: 'str',
            value: 'front',
          },
        ],
      },
      {
        type: 'gk:sceneCommand',
        method: 'createSpriteTrack',
        args: [
          {
            type: 'str',
            value: 'pista',
          },
        ],
      },
      {
        type: 'gk:createCharacter',
        varName: 'jogador',
        image: 'neve-esquiador',
        w: {
          type: 'num',
          value: 26,
        },
        h: {
          type: 'num',
          value: 42,
        },
        speed: {
          type: 'num',
          value: 0,
        },
        color: '#ffffff',
      },
      {
        type: 'gk:sceneCommand',
        method: 'sceneAnimation',
        args: [
          {
            type: 'var',
            name: 'jogador',
          },
          {
            type: 'str',
            value: 'neve-esquiador-animado',
          },
          {
            type: 'str',
            value: 'deslizar',
          },
          {
            type: 'bool',
            value: false,
          },
        ],
      },
      {
        type: 'gk:setHealth',
        charVar: 'jogador',
        lives: {
          type: 'num',
          value: 3,
        },
      },
      {
        type: 'gk:sceneCommand',
        method: 'trackFollow',
        args: [
          {
            type: 'str',
            value: 'pista',
          },
          {
            type: 'var',
            name: 'jogador',
          },
        ],
      },
      {
        type: 'gk:sceneCommand',
        method: 'trackInput',
        args: [
          {
            type: 'str',
            value: 'pista',
          },
          {
            type: 'str',
            value: 'both',
          },
          {
            type: 'num',
            value: 140,
          },
        ],
      },
      {
        type: 'gk:sceneCommand',
        method: 'trackLimit',
        args: [
          {
            type: 'str',
            value: 'pista',
          },
          {
            type: 'num',
            value: 120,
          },
          {
            type: 'num',
            value: 120,
          },
        ],
      },
      {
        type: 'gk:sceneCommand',
        method: 'trackSpeed',
        args: [
          {
            type: 'str',
            value: 'pista',
          },
          {
            type: 'num',
            value: 320,
          },
        ],
      },
      {
        type: 'gk:sceneCommand',
        method: 'trackFinishLine',
        args: [
          {
            type: 'str',
            value: 'pista',
          },
          {
            type: 'num',
            value: 6600,
          },
        ],
      },
      {
        type: 'gk:createCharacter',
        varName: 'estrela',
        image: 'neve-estrela',
        w: {
          type: 'num',
          value: 22,
        },
        h: {
          type: 'num',
          value: 22,
        },
        speed: {
          type: 'num',
          value: 0,
        },
        color: '#ffffff',
      },
      {
        type: 'gk:sceneCommand',
        method: 'putTrackSprite',
        args: [
          {
            type: 'str',
            value: 'pista',
          },
          {
            type: 'var',
            name: 'estrela',
          },
          {
            type: 'num',
            value: -80,
          },
          {
            type: 'num',
            value: 600,
          },
        ],
      },
      {
        type: 'gk:sceneCommand',
        method: 'repeatTrackSprite',
        args: [
          {
            type: 'str',
            value: 'pista',
          },
          {
            type: 'var',
            name: 'estrela',
          },
          {
            type: 'num',
            value: 12,
          },
          {
            type: 'num',
            value: 480,
          },
          {
            type: 'str',
            value: 'weave',
          },
        ],
      },
      {
        type: 'gk:createCharacter',
        varName: 'bandeira',
        image: 'neve-bandeira',
        w: {
          type: 'num',
          value: 28,
        },
        h: {
          type: 'num',
          value: 60,
        },
        speed: {
          type: 'num',
          value: 0,
        },
        color: '#ffffff',
      },
      {
        type: 'gk:sceneCommand',
        method: 'putTrackSprite',
        args: [
          {
            type: 'str',
            value: 'pista',
          },
          {
            type: 'var',
            name: 'bandeira',
          },
          {
            type: 'num',
            value: 80,
          },
          {
            type: 'num',
            value: 840,
          },
        ],
      },
      {
        type: 'gk:sceneCommand',
        method: 'repeatTrackSprite',
        args: [
          {
            type: 'str',
            value: 'pista',
          },
          {
            type: 'var',
            name: 'bandeira',
          },
          {
            type: 'num',
            value: 6,
          },
          {
            type: 'num',
            value: 960,
          },
          {
            type: 'str',
            value: 'alternate',
          },
        ],
      },
      {
        type: 'gk:createCharacter',
        varName: 'bandeiraDireita',
        image: 'neve-bandeira',
        w: {
          type: 'num',
          value: 28,
        },
        h: {
          type: 'num',
          value: 60,
        },
        speed: {
          type: 'num',
          value: 0,
        },
        color: '#ffffff',
      },
      {
        type: 'gk:sceneCommand',
        method: 'putTrackSprite',
        args: [
          {
            type: 'str',
            value: 'pista',
          },
          {
            type: 'var',
            name: 'bandeiraDireita',
          },
          {
            type: 'num',
            value: 70,
          },
          {
            type: 'num',
            value: 1320,
          },
        ],
      },
      {
        type: 'gk:sceneCommand',
        method: 'repeatTrackSprite',
        args: [
          {
            type: 'str',
            value: 'pista',
          },
          {
            type: 'var',
            name: 'bandeiraDireita',
          },
          {
            type: 'num',
            value: 6,
          },
          {
            type: 'num',
            value: 960,
          },
          {
            type: 'str',
            value: 'line',
          },
        ],
      },
      {
        type: 'gk:createCharacter',
        varName: 'gelo',
        image: 'neve-gelo',
        w: {
          type: 'num',
          value: 150,
        },
        h: {
          type: 'num',
          value: 32,
        },
        speed: {
          type: 'num',
          value: 0,
        },
        color: '#ffffff',
      },
      {
        type: 'gk:sceneCommand',
        method: 'putTrackSprite',
        args: [
          {
            type: 'str',
            value: 'pista',
          },
          {
            type: 'var',
            name: 'gelo',
          },
          {
            type: 'num',
            value: -40,
          },
          {
            type: 'num',
            value: 930,
          },
        ],
      },
      {
        type: 'gk:sceneCommand',
        method: 'repeatTrackSprite',
        args: [
          {
            type: 'str',
            value: 'pista',
          },
          {
            type: 'var',
            name: 'gelo',
          },
          {
            type: 'num',
            value: 12,
          },
          {
            type: 'num',
            value: 480,
          },
          {
            type: 'str',
            value: 'weave',
          },
        ],
      },
      {
        type: 'gk:createCharacter',
        varName: 'pinheiroEsquerda',
        image: 'neve-pinheiro',
        w: {
          type: 'num',
          value: 90,
        },
        h: {
          type: 'num',
          value: 135,
        },
        speed: {
          type: 'num',
          value: 0,
        },
        color: '#ffffff',
      },
      {
        type: 'gk:sceneCommand',
        method: 'putTrackSprite',
        args: [
          {
            type: 'str',
            value: 'pista',
          },
          {
            type: 'var',
            name: 'pinheiroEsquerda',
          },
          {
            type: 'num',
            value: -210,
          },
          {
            type: 'num',
            value: 280,
          },
        ],
      },
      {
        type: 'gk:sceneCommand',
        method: 'repeatTrackSprite',
        args: [
          {
            type: 'str',
            value: 'pista',
          },
          {
            type: 'var',
            name: 'pinheiroEsquerda',
          },
          {
            type: 'num',
            value: 36,
          },
          {
            type: 'num',
            value: 180,
          },
          {
            type: 'str',
            value: 'steps-left',
          },
        ],
      },
      {
        type: 'gk:createCharacter',
        varName: 'pinheiroDireita',
        image: 'neve-pinheiro',
        w: {
          type: 'num',
          value: 90,
        },
        h: {
          type: 'num',
          value: 135,
        },
        speed: {
          type: 'num',
          value: 0,
        },
        color: '#ffffff',
      },
      {
        type: 'gk:sceneCommand',
        method: 'putTrackSprite',
        args: [
          {
            type: 'str',
            value: 'pista',
          },
          {
            type: 'var',
            name: 'pinheiroDireita',
          },
          {
            type: 'num',
            value: 210,
          },
          {
            type: 'num',
            value: 340,
          },
        ],
      },
      {
        type: 'gk:sceneCommand',
        method: 'repeatTrackSprite',
        args: [
          {
            type: 'str',
            value: 'pista',
          },
          {
            type: 'var',
            name: 'pinheiroDireita',
          },
          {
            type: 'num',
            value: 36,
          },
          {
            type: 'num',
            value: 180,
          },
          {
            type: 'str',
            value: 'steps-right',
          },
        ],
      },
      {
        type: 'var',
        name: 'estrelas',
        value: {
          type: 'num',
          value: 0,
        },
      },
      {
        type: 'gk:setScreenText',
        screen: 'menu',
        title: {
          type: 'str',
          value: 'DESCIDA DA NEVE',
        },
        text: {
          type: 'str',
          value: 'Pegue seis estrelas e desvie das bandeiras. Use setas ou arraste na pista.',
        },
        button: {
          type: 'str',
          value: 'Descer a montanha',
        },
      },
      {
        type: 'gk:setScreenText',
        screen: 'pausa',
        title: {
          type: 'str',
          value: 'DESCANSO NA MONTANHA',
        },
        text: {
          type: 'str',
          value: 'Vamos continuar a descida?',
        },
        button: {
          type: 'str',
          value: 'Continuar',
        },
      },
      {
        type: 'gk:setScreenText',
        screen: 'vitoria',
        title: {
          type: 'str',
          value: 'VOCÊ CHEGOU!',
        },
        text: {
          type: 'str',
          value: 'Você chegou com pelo menos seis estrelas.',
        },
        button: {
          type: 'str',
          value: 'Descer de novo',
        },
      },
      {
        type: 'gk:setScreenText',
        screen: 'fim',
        title: {
          type: 'str',
          value: 'VAMOS TENTAR DE NOVO?',
        },
        text: {
          type: 'str',
          value: 'Pegue seis estrelas e cuide das três vidas.',
        },
        button: {
          type: 'str',
          value: 'Tentar de novo',
        },
      },
      {
        type: 'gk:setPauseKey',
        key: 'p',
      },
      {
        type: 'gk:sceneCommand',
        method: 'trackCameraView',
        args: [
          {
            type: 'str',
            value: 'pista',
          },
          {
            type: 'str',
            value: 'near',
          },
        ],
      },
    ],
    events: [
      {
        type: 'gk:sceneEvent',
        method: 'onTrackSpriteEncounter',
        args: [
          {
            type: 'str',
            value: 'pista',
          },
          {
            type: 'var',
            name: 'estrela',
          },
        ],
        body: [
          {
            type: 'gk:sceneCommand',
            method: 'collectTrackItem',
            args: [],
          },
          {
            type: 'assign',
            name: 'estrelas',
            value: {
              type: 'binop',
              op: '+',
              left: {
                type: 'var',
                name: 'estrelas',
              },
              right: {
                type: 'num',
                value: 1,
              },
            },
          },
        ],
        parameter: 'encontrado',
      },
      {
        type: 'gk:sceneEvent',
        method: 'onTrackSpriteEncounter',
        args: [
          {
            type: 'str',
            value: 'pista',
          },
          {
            type: 'var',
            name: 'bandeira',
          },
        ],
        body: [
          {
            type: 'gk:hurt',
            charVar: 'jogador',
            amount: {
              type: 'num',
              value: 1,
            },
            iframes: {
              type: 'num',
              value: 0.35,
            },
          },
          {
            type: 'if',
            cond: {
              type: 'gk:isDead',
              charVar: 'jogador',
            },
            then: [
              {
                type: 'gk:setState',
                name: 'fim',
              },
            ],
          },
        ],
        parameter: 'encontrado',
      },
      {
        type: 'gk:sceneEvent',
        method: 'onTrackSpriteEncounter',
        args: [
          {
            type: 'str',
            value: 'pista',
          },
          {
            type: 'var',
            name: 'bandeiraDireita',
          },
        ],
        body: [
          {
            type: 'gk:hurt',
            charVar: 'jogador',
            amount: {
              type: 'num',
              value: 1,
            },
            iframes: {
              type: 'num',
              value: 0.35,
            },
          },
          {
            type: 'if',
            cond: {
              type: 'gk:isDead',
              charVar: 'jogador',
            },
            then: [
              {
                type: 'gk:setState',
                name: 'fim',
              },
            ],
          },
        ],
        parameter: 'encontrado',
      },
      {
        type: 'gk:sceneEvent',
        method: 'onTrackFinish',
        args: [
          {
            type: 'str',
            value: 'pista',
          },
        ],
        body: [
          {
            type: 'if',
            cond: {
              type: 'binop',
              op: '>=',
              left: {
                type: 'var',
                name: 'estrelas',
              },
              right: {
                type: 'num',
                value: 6,
              },
            },
            then: [
              {
                type: 'gk:setState',
                name: 'vitoria',
              },
            ],
            else: [
              {
                type: 'gk:setState',
                name: 'fim',
              },
            ],
          },
        ],
      },
      {
        type: 'gk:onGameClick',
        xName: 'x',
        yName: 'y',
        body: [
          {
            type: 'if',
            cond: {
              type: 'logical',
              op: '&&',
              left: {
                type: 'logical',
                op: '&&',
                left: {
                  type: 'binop',
                  op: '===',
                  left: {
                    type: 'gk:gameState',
                  },
                  right: {
                    type: 'str',
                    value: 'jogando',
                  },
                },
                right: {
                  type: 'binop',
                  op: '>',
                  left: {
                    type: 'var',
                    name: 'x',
                  },
                  right: {
                    type: 'binop',
                    op: '-',
                    left: {
                      type: 'gk:gameWidth',
                    },
                    right: {
                      type: 'num',
                      value: 120,
                    },
                  },
                },
              },
              right: {
                type: 'binop',
                op: '<',
                left: {
                  type: 'var',
                  name: 'y',
                },
                right: {
                  type: 'num',
                  value: 90,
                },
              },
            },
            then: [
              {
                type: 'gk:pause',
              },
            ],
          },
        ],
      },
    ],
    loops: [
      {
        type: 'gk:onDrawHud',
        ctxName: 'ctx',
        body: [
          {
            type: 'gk:drawCounter',
            label: {
              type: 'str',
              value: 'Vidas',
            },
            value: {
              type: 'gk:healthOf',
              charVar: 'jogador',
            },
            x: {
              type: 'num',
              value: 30,
            },
            y: {
              type: 'num',
              value: 28,
            },
          },
          {
            type: 'gk:drawCounter',
            label: {
              type: 'str',
              value: 'Estrelas',
            },
            value: {
              type: 'binop',
              op: '+',
              left: {
                type: 'var',
                name: 'estrelas',
              },
              right: {
                type: 'str',
                value: '/12',
              },
            },
            x: {
              type: 'num',
              value: 180,
            },
            y: {
              type: 'num',
              value: 28,
            },
          },
          {
            type: 'gk:drawCounter',
            label: {
              type: 'str',
              value: 'Pausar',
            },
            value: {
              type: 'str',
              value: '',
            },
            x: {
              type: 'binop',
              op: '-',
              left: {
                type: 'gk:gameWidth',
              },
              right: {
                type: 'num',
                value: 100,
              },
            },
            y: {
              type: 'num',
              value: 28,
            },
          },
          {
            type: 'gk:drawBar',
            current: {
              type: 'gk:sceneValue',
              method: 'trackPosition',
              args: [
                {
                  type: 'str',
                  value: 'pista',
                },
                {
                  type: 'str',
                  value: 'distance',
                },
              ],
            },
            max: {
              type: 'num',
              value: 6600,
            },
            x: {
              type: 'num',
              value: 24,
            },
            y: {
              type: 'num',
              value: 80,
            },
            w: {
              type: 'binop',
              op: '-',
              left: {
                type: 'gk:gameWidth',
              },
              right: {
                type: 'num',
                value: 48,
              },
            },
            h: {
              type: 'num',
              value: 5,
            },
            color: '#82d1dc',
          },
        ],
      },
    ],
  },
  extensions: [
    {
      extensionId: 'game-2d-advanced',
    },
  ],
} as SZIRV2
