import type { ExampleExperience } from '#core'

export type ExampleQAInteraction =
  | 'start'
  | 'arrows'
  | 'wasd'
  | 'space'
  | 'click'
  | 'drag'
  | 'escape'
  | 'action-j'
  | 'action-fight'
  | 'interact-e'
  | 'horn-h'
  | 'digit-1'
  | 'choice-2'
  | 'place-c'
  | 'remove-x'
  | 'auto'

export interface ExampleQAContract {
  /** Chave idêntica à construída pela KitGallery: extensão:nome. */
  key: string
  name: string
  experience: ExampleExperience
  /** Promessa observável do cartão, mantida independente do manifest. */
  promise: string
  /** Caminho de aceite que deve funcionar no harness e/ou Chromium. */
  scenario: string
  interactions: readonly ExampleQAInteraction[]
}

/**
 * Contrato explícito da vitrine privilegiada. Não é derivado do catálogo:
 * adicionar, remover ou renomear um card exige decidir sua classificação e seu
 * cenário de aceite aqui, impedindo cobertura "por acidente".
 */
export const EXAMPLE_QA_CONTRACTS = [
  {
    key: 'game-2d:Pegue a moeda',
    name: 'Pegue a moeda',
    experience: 'game',
    promise: 'Andar com as setas, encostar na moeda e fazer cinco pontos para vencer.',
    scenario: 'Começar, mover o herói, coletar cinco moedas, vencer e reiniciar.',
    interactions: ['start', 'arrows'],
  },
  {
    key: 'game-2d:Pong simples',
    name: 'Pong simples',
    experience: 'game',
    promise: 'Disputar uma partida de Pong contra o computador até cinco pontos.',
    scenario: 'Começar, mover a raquete, marcar/sofrer cinco pontos, concluir e reiniciar.',
    interactions: ['start', 'arrows'],
  },
  {
    key: 'game-2d:Herói que anda',
    name: 'Herói que anda',
    experience: 'demo',
    promise: 'Mostrar sprite, spritesheet e movimento pelas setas.',
    scenario: 'Mover nas quatro direções e observar a animação trocar.',
    interactions: ['arrows'],
  },
  {
    key: 'game-2d:Mini plataforma',
    name: 'Mini plataforma',
    experience: 'demo',
    promise: 'Mostrar movimento, pulo, gravidade e limite de tela.',
    scenario: 'Andar, pular, cair e permanecer dentro da tela.',
    interactions: ['arrows', 'space'],
  },
  {
    key: 'game-2d:Plataforma com inimigos',
    name: 'Plataforma com inimigos',
    experience: 'game',
    promise: 'Combater três comportamentos de inimigo com vida e pontos.',
    scenario: 'Começar, mover, atirar, sofrer dano, pontuar e reiniciar.',
    interactions: ['start', 'arrows', 'space'],
  },
  {
    key: 'game-2d:Jogo desenhado por código',
    name: 'Jogo desenhado por código',
    experience: 'demo',
    promise: 'Desenhar herói e moeda apenas com formas.',
    scenario: 'Mover o herói e coletar uma moeda sem carregar imagem.',
    interactions: ['arrows'],
  },
  {
    key: 'game-2d:Sala com paredes',
    name: 'Sala com paredes',
    experience: 'demo',
    promise: 'Mostrar um tilemap cujas paredes bloqueiam o herói.',
    scenario: 'Andar pelo piso e confirmar colisão em todas as paredes.',
    interactions: ['arrows'],
  },
  {
    key: 'game-2d:Nave contra Asteroides',
    name: 'Nave contra Asteroides',
    experience: 'game',
    promise: 'Atirar, pontuar, sobreviver e chegar a vitória ou derrota.',
    scenario: 'Passar pelo menu, mover, atirar, concluir e jogar novamente.',
    interactions: ['start', 'arrows', 'space'],
  },
  {
    key: 'game-2d:Asteroides clássico',
    name: 'Asteroides clássico',
    experience: 'game',
    promise: 'Girar, impulsionar e atirar como no Asteroids clássico.',
    scenario: 'Começar, pilotar, destruir asteroides e reiniciar.',
    interactions: ['start', 'arrows', 'space'],
  },
  {
    key: 'game-2d:Dino Run',
    name: 'Dino Run',
    experience: 'game',
    promise: 'Correr, pular, abaixar, coletar bônus e manter recorde.',
    scenario: 'Começar, evitar os três obstáculos, pontuar, perder e reiniciar.',
    interactions: ['start', 'arrows', 'space'],
  },
  {
    key: 'game-2d:Dino Corredor',
    name: 'Dino Corredor',
    experience: 'game',
    promise: 'Pular cactos com colisão perdoadora enquanto o placar sobe e o jogo acelera.',
    scenario: 'Enter ou espaço começa; pular cactos, pontuar por segundo, bater e reiniciar.',
    interactions: ['start', 'space'],
  },
  {
    key: 'game-2d:Chuva de Meteoros',
    name: 'Chuva de Meteoros',
    experience: 'game',
    promise:
      'Voar nas quatro direções sob uma chuva vertical de meteoros e atirar para sobreviver.',
    scenario:
      'Enter ou espaço começa; voar com as setas, atirar, destruir meteoros, pontuar por tempo e reiniciar.',
    interactions: ['start', 'arrows', 'space'],
  },
  {
    key: 'game-2d:Batalha de Monstrinhos',
    name: 'Batalha de Monstrinhos',
    experience: 'game',
    promise: 'Batalha por turnos com vantagem de tipo: fogo tira o dobro da planta e a poção cura.',
    scenario:
      'Enter começa; após a abertura os golpes liberam nas teclas 1/2/3, o rival devolve e a vida zerada troca a cena.',
    interactions: ['start', 'digit-1', 'choice-2'],
  },
  {
    key: 'game-2d:Aventura do Herói',
    name: 'Aventura do Herói',
    experience: 'game',
    promise: 'Mundo top-down maior que a tela com mato cortável, espada temporária e guardiões.',
    scenario:
      'Enter começa; setas andam com a câmera seguindo; espaço corta o mato e fere guardiões; derrotar os quatro vence.',
    interactions: ['start', 'arrows', 'space'],
  },
  {
    key: 'game-2d:Guerra de Gorilas',
    name: 'Guerra de Gorilas',
    experience: 'game',
    promise: 'Dois jogadores lançam bananas com vento, gravidade e crateras.',
    scenario: 'Começar, arrastar a mira, alternar turnos, acertar e reiniciar.',
    interactions: ['start', 'drag'],
  },
  {
    key: 'game-2d:Guerra de Gorilas vs Robô',
    name: 'Guerra de Gorilas vs Robô',
    experience: 'game',
    promise: 'Enfrentar um robô que calcula e executa a própria jogada.',
    scenario: 'Começar, lançar, observar a resposta automática e concluir.',
    interactions: ['start', 'drag', 'auto'],
  },
  {
    key: 'game-2d:Equilibrista',
    name: 'Equilibrista',
    experience: 'game',
    promise:
      'Montar a regra do mouse (segurado cresce o bastão, solto derruba) e atravessar somando pontos numa variável.',
    scenario:
      'Enter começa; segurar, soltar, atravessar, pontuar nos eventos, cair e recomeçar limpo.',
    interactions: ['start', 'drag'],
  },
  {
    key: 'game-2d:Balão',
    name: 'Balão',
    experience: 'game',
    promise:
      'Acender o fogo com o mouse segurado, voar com combustível limitado e desviar das árvores do caminho.',
    scenario:
      'Enter começa; sustentar o balão, gastar combustível, bater ou pousar seco e reiniciar.',
    interactions: ['start', 'click'],
  },
  {
    key: 'game-2d:Aventura com câmera',
    name: 'Aventura com câmera',
    experience: 'exploration',
    promise: 'Explorar um caminho grande e visível com câmera, paisagem, moedas, som e música.',
    scenario: 'Percorrer o caminho, acompanhar a câmera e coletar as quatro moedas.',
    interactions: ['arrows'],
  },
  {
    key: 'game-2d-advanced:Meu primeiro jogo',
    name: 'Meu primeiro jogo',
    experience: 'demo',
    promise: 'Apresentar a base mínima de personagem e movimento.',
    scenario: 'Abrir pelo botão Jogar e mover o personagem pelas setas.',
    interactions: ['click', 'arrows'],
  },
  {
    key: 'game-2d-advanced:Caça-moedas profissional',
    name: 'Caça-moedas profissional',
    experience: 'game',
    promise: 'Usar menu, pausa, estados e vitória ao pegar cinco moedas.',
    scenario: 'Começar, pausar, coletar cinco moedas, vencer e jogar novamente.',
    interactions: ['click', 'arrows', 'escape'],
  },
  {
    key: 'game-2d-advanced:Arena dos Goblins',
    name: 'Arena dos Goblins',
    experience: 'game',
    promise: 'Derrotar dez goblins com spawner, combate e invencibilidade.',
    scenario: 'Mover, golpear, sofrer dano, cumprir a missão e reiniciar.',
    interactions: ['wasd', 'action-j'],
  },
  {
    key: 'game-2d-advanced:Vila do Dragão',
    name: 'Vila do Dragão',
    experience: 'game',
    promise: 'Viver um RPG com missão, chave, poção, caverna e dragão.',
    scenario: 'Vila, ferreiro, chave, porta, caverna, batalha, vitória e novo jogo.',
    interactions: ['click', 'arrows', 'space'],
  },
  {
    key: 'game-2d-advanced:Floresta Ninja',
    name: 'Floresta Ninja',
    experience: 'game',
    promise: 'Golpear na direção e derrotar dois ninjas patrulheiros.',
    scenario: 'Mover, atacar os dois inimigos, vencer e reiniciar.',
    interactions: ['wasd', 'space'],
  },
  {
    key: 'game-2d-advanced:Salto na Floresta',
    name: 'Salto na Floresta',
    experience: 'game',
    promise: 'Usar pulo tolerante, plataformas especiais e pisão.',
    scenario: 'Atravessar a fase, derrotar bichos, pegar cinco frutas e reiniciar.',
    interactions: ['wasd', 'space'],
  },
  {
    key: 'game-2d-advanced:Dino Corredor Profissional',
    name: 'Dino Corredor Profissional',
    experience: 'game',
    promise: 'Pular cactos com molde, pool, parallax e recorde salvo de verdade.',
    scenario: 'Correr, saltar obstáculos cada vez mais rápidos, bater e ver o recorde guardado.',
    interactions: ['space', 'arrows', 'click'],
  },
  {
    key: 'game-2d-advanced:Chuva de Meteoros Profissional',
    name: 'Chuva de Meteoros Profissional',
    experience: 'game',
    promise: 'Sobreviver a uma chuva que acelera, com moldes, efeitos de explosão e recorde salvo.',
    scenario:
      'Decolar pelo botão, voar, atirar com recarga, destruir meteoros, bater e ver o recorde guardado.',
    interactions: ['click', 'arrows', 'space'],
  },
  {
    key: 'game-2d-advanced:Batalha de Monstrinhos Profissional',
    name: 'Batalha de Monstrinhos Profissional',
    experience: 'game',
    promise: 'Montar o time, escrever a tabela de vantagem e capturar o lendário.',
    scenario:
      'Andar até a rival, batalhar pelos menus do kit, curar na fonte e capturar no mato fundo.',
    interactions: ['arrows', 'space'],
  },
  {
    key: 'game-2d-advanced:Aventura do Herói Profissional',
    name: 'Aventura do Herói Profissional',
    experience: 'game',
    promise: 'Explorar um mundo maior que a tela e derrotar os sete monstros com a espada.',
    scenario:
      'Cortar o mato, passar atrás das árvores e vencer javalis e lobos até a tela de vitória.',
    interactions: ['arrows', 'space'],
  },
  {
    key: 'game-2d-advanced:Bichinhos do Quintal',
    name: 'Bichinhos do Quintal',
    experience: 'game',
    promise: 'Encontrar, batalhar e capturar três criaturas.',
    scenario: 'Explorar o mapa, vencer turnos, capturar três bichos e reiniciar.',
    interactions: ['arrows', 'space'],
  },
  {
    key: 'game-2d-advanced:Invasão dos Óvnis',
    name: 'Invasão dos Óvnis',
    experience: 'game',
    promise: 'Defender-se de uma formação que marcha, atira e acelera.',
    scenario: 'Mover, atirar, usar power-up, vencer/perder e jogar novamente.',
    interactions: ['arrows', 'space'],
  },
  {
    key: 'game-2d-advanced:Duelo dos Bonecos',
    name: 'Duelo dos Bonecos',
    experience: 'game',
    promise: 'Disputar melhor de três contra o computador com golpes variados.',
    scenario: 'Mover, defender, atacar, agarrar, concluir rounds e reiniciar.',
    interactions: ['action-fight'],
  },
  {
    key: 'game-2d-advanced:Defesa do Reino',
    name: 'Defesa do Reino',
    experience: 'game',
    promise: 'Comprar torres e defender cinco vidas em ondas crescentes.',
    scenario: 'Comprar, negar compra inválida, vencer/perder ondas e reiniciar.',
    interactions: ['click', 'auto'],
  },
  {
    key: 'game-2d-advanced:Reino Aberto',
    name: 'Reino Aberto',
    experience: 'exploration',
    promise: 'Explorar quatro mapas ligados e conversar com personagens.',
    scenario: 'Cruzar cada borda, visitar mapa grande e falar com os dois NPCs.',
    interactions: ['arrows', 'space'],
  },
  {
    key: 'game-2d-advanced:Batalha em Equipe',
    name: 'Batalha em Equipe',
    experience: 'game',
    promise: 'Lutar por turnos com aliado, cura, fichas e dois inimigos.',
    scenario: 'Falar com o capitão, inspecionar, escolher alvos, vencer e reiniciar.',
    interactions: ['arrows', 'space', 'click'],
  },
  {
    key: 'game-2d-advanced:O Chefao',
    name: 'O Chefao',
    experience: 'game',
    promise: 'Enfrentar um chefe que muda de fase e acerta o time.',
    scenario: 'Falar com o guardião, lutar, observar a segunda fase e concluir.',
    interactions: ['arrows', 'space'],
  },
  {
    key: 'game-2d-advanced:O Chefao da Ficha',
    name: 'O Chefao da Ficha',
    experience: 'game',
    promise: 'Criar e enfrentar um chefe definido por ficha.',
    scenario: 'Começar na caverna, falar, abrir a batalha e concluir/reiniciar.',
    interactions: ['arrows', 'space'],
  },
  {
    key: 'game-2d-advanced:Corrida de Tabuleiro',
    name: 'Corrida de Tabuleiro',
    experience: 'game',
    promise: 'Rolar dado, mover peões e alternar dois turnos.',
    scenario: 'Rolar várias vezes, pontuar em casa premiada e concluir a corrida.',
    interactions: ['click'],
  },
  {
    key: 'game-2d-advanced:Jogo da Memoria',
    name: 'Jogo da Memoria',
    experience: 'game',
    promise: 'Virar cartas e encontrar três pares embaralhados.',
    scenario: 'Virar duas, ocultar erro, manter acerto, vencer e reiniciar.',
    interactions: ['click'],
  },
  {
    key: 'game-2d-advanced:Duelo de Cartas',
    name: 'Duelo de Cartas',
    experience: 'game',
    promise: 'Jogar cartas com energia contra uma intenção inimiga.',
    scenario: 'Comprar, atacar, defender, passar turnos, concluir e reiniciar.',
    interactions: ['click', 'space'],
  },
  {
    key: 'game-2d-advanced:Cobrinha',
    name: 'Cobrinha',
    experience: 'game',
    promise: 'Mover uma cobrinha em grade, comer e crescer.',
    scenario: 'Virar, comer, colidir com parede/corpo e recomeçar limpa.',
    interactions: ['arrows'],
  },
  {
    key: 'game-2d-advanced:Quebra-blocos',
    name: 'Quebra-blocos',
    experience: 'game',
    promise: 'Rebater a bola com ângulo e destruir todos os blocos.',
    scenario: 'Mover a raquete, perder bola, limpar blocos e reiniciar.',
    interactions: ['arrows'],
  },
  {
    key: 'game-3d:Boneco de formas',
    name: 'Boneco de formas',
    experience: 'demo',
    promise: 'Montar e girar um modelo feito de formas 3D.',
    scenario: 'Observar formas, materiais, chão e rotação contínua.',
    interactions: ['auto'],
  },
  {
    key: 'game-3d:Noite enevoada',
    name: 'Noite enevoada',
    experience: 'demo',
    promise: 'Mostrar céu noturno, neblina, sombras e luz pontual.',
    scenario: 'Observar o primeiro frame e a rotação sob luz e neblina.',
    interactions: ['auto'],
  },
  {
    key: 'game-3d:Enxame que gira',
    name: 'Enxame que gira',
    experience: 'demo',
    promise: 'Criar cinco cópias de um molde e iterar sobre elas.',
    scenario: 'Contar as cinco cópias e observar a rotação do conjunto.',
    interactions: ['auto'],
  },
  {
    key: 'game-3d:Torre maluca',
    name: 'Torre maluca',
    experience: 'game',
    promise: 'Soltar andares móveis e pontuar pelos encaixes.',
    scenario: 'Soltar peças, pontuar, falhar e recomeçar sem torre antiga.',
    interactions: ['click'],
  },
  {
    key: 'game-3d:Corrida maluca',
    name: 'Corrida maluca',
    experience: 'game',
    promise: 'Completar voltas desviando de rivais.',
    scenario: 'Acelerar, frear, virar, completar volta e reiniciar.',
    interactions: ['arrows'],
  },
  {
    key: 'game-3d:Atravesse a rua',
    name: 'Atravesse a rua',
    experience: 'game',
    promise: 'Cruzar uma grade isométrica desviando do trânsito.',
    scenario: 'Pular casas, pontuar, colidir, ver fim e reiniciar.',
    interactions: ['arrows'],
  },
  {
    key: 'game-3d:Desvie dos blocos',
    name: 'Desvie dos blocos',
    experience: 'game',
    promise: 'Correr e pular de blocos que aceleram.',
    scenario: 'Mover, pular, sobreviver e colidir para encerrar a partida.',
    interactions: ['wasd', 'space'],
  },
  {
    key: 'game-3d:Corrida Infinita 3D',
    name: 'Corrida Infinita 3D',
    experience: 'game',
    promise: 'Trocar de pista, pular e sobreviver a caixas que aceleram.',
    scenario: 'Trocar de pista, pular caixa, marcar tempo, bater e recomeçar.',
    interactions: ['arrows', 'space'],
  },
  {
    key: 'game-3d:Patrulha Espacial',
    name: 'Patrulha Espacial',
    experience: 'game',
    promise:
      'Pilotar a nave vista de trás, inclinar nas curvas e atirar lasers em meteoros que aceleram.',
    scenario:
      'Andar com setas ou A/D, atirar com espaço, destruir meteoro, marcar tempo, bater e recomeçar.',
    interactions: ['wasd', 'arrows', 'space'],
  },
  {
    key: 'game-3d:Labirinto dos Robôs',
    name: 'Labirinto dos Robôs',
    experience: 'game',
    promise: 'Andar em primeira pessoa pelo labirinto e derrotar robôs com a mira central.',
    scenario:
      'Andar com WASD, pular, clicar para travar a mira e atirar, tomar dano e vencer ou reiniciar.',
    interactions: ['wasd', 'space', 'click'],
  },
  {
    key: 'game-3d:Mundo de Blocos',
    name: 'Mundo de Blocos',
    experience: 'game',
    promise: 'Construir com blocos na grade isométrica e empilhar uma torre de cinco.',
    scenario:
      'Mover o cursor com as setas, colocar com espaço, trocar o tipo com 1 e quebrar com o clique.',
    interactions: ['arrows', 'space', 'digit-1', 'click'],
  },
  {
    key: 'game-3d:Cubo girando',
    name: 'Cubo girando',
    experience: 'demo',
    promise: 'Mostrar um cubo Three.js em rotação contínua.',
    scenario: 'Observar frames sucessivos e confirmar a rotação nos três eixos.',
    interactions: ['auto'],
  },
  {
    key: 'game-3d-advanced:Defesa da Torre',
    name: 'Defesa da Torre',
    experience: 'game',
    promise: 'Torres autônomas defendem um cristal com máquina de estados.',
    scenario: 'Observar mira, tiro, recarga, vitória/derrota e reinício.',
    interactions: ['auto'],
  },
  {
    key: 'game-3d-advanced:Salto nas Nuvens',
    name: 'Salto nas Nuvens',
    experience: 'game',
    promise: 'Pular em física 3D, coletar moedas e usar câmera seguidora.',
    scenario: 'Mover, pular, cair, coletar tudo, vencer e reiniciar.',
    interactions: ['wasd', 'space'],
  },
  {
    key: 'game-3d-advanced:Parkour do Vulcão',
    name: 'Parkour do Vulcão',
    experience: 'game',
    promise: 'Percorrer rampa, elevador, trampolim e zonas físicas.',
    scenario: 'Usar cada obstáculo, coletar três gemas, vencer e reiniciar.',
    interactions: ['wasd', 'space'],
  },
  {
    key: 'game-3d-advanced:Quadra Maluca',
    name: 'Quadra Maluca',
    experience: 'game',
    promise: 'Mover relativo à câmera e apanhar bolas de físicas distintas.',
    scenario: 'Girar câmera, andar no gelo, coletar cinco bolas e reiniciar.',
    interactions: ['wasd', 'drag'],
  },
  {
    key: 'game-3d-advanced:Guardião do Portal',
    name: 'Guardião do Portal',
    experience: 'game',
    promise: 'Defender um portal durante trinta segundos determinísticos.',
    scenario: 'Perder parado, defender até vencer e reiniciar a mesma semente.',
    interactions: ['wasd', 'space'],
  },
  {
    key: 'game-3d-advanced:O Chefão das Sombras',
    name: 'O Chefão das Sombras',
    experience: 'game',
    promise: 'Enfrentar um chefão em três fases, atacando com clique e desviando do anel de tiros.',
    scenario: 'Clicar no chefão, sobreviver às três fases, vencer/perder e reiniciar.',
    interactions: ['click', 'wasd'],
  },
  {
    key: 'game-3d-advanced:Tiro ao Alvo',
    name: 'Tiro ao Alvo',
    experience: 'game',
    promise: 'Clicar em alvos móveis e fazer doze pontos em 25 segundos.',
    scenario: 'Fechar dica, acertar alvos comuns/dourado, vencer/perder e reiniciar.',
    interactions: ['click'],
  },
  {
    key: 'game-3d-advanced:Corrida Infinita Profissional',
    name: 'Corrida Infinita Profissional',
    experience: 'game',
    promise:
      'Correr sem fim em três faixas, pulando barreiras e pegando moedas num jogo que acelera.',
    scenario:
      'Começar, trocar de faixa com A/D ou setas, pular com espaço, pegar moeda, bater e reiniciar.',
    interactions: ['wasd', 'arrows', 'space'],
  },
  {
    key: 'game-3d-advanced:Patrulha Espacial Profissional',
    name: 'Patrulha Espacial Profissional',
    experience: 'game',
    promise: 'Destruir vinte meteoros que brilham antes de explodir, numa chuva que acelera.',
    scenario:
      'Patrulhar pelo botão, andar com A/D ou setas, atirar com espaço, ver a morte dramática, encostar três vezes e vencer.',
    interactions: ['click', 'wasd', 'arrows', 'space'],
  },
  {
    key: 'game-3d-advanced:Labirinto dos Robôs Profissional',
    name: 'Labirinto dos Robôs Profissional',
    experience: 'game',
    promise: 'Atirar em primeira pessoa em robôs com cérebro de patrulha, perseguição e ataque.',
    scenario:
      'Travar a mira, andar, derrotar um robô por tiro, morrer encostado, limpar os cinco e vencer.',
    interactions: ['click', 'wasd'],
  },
  {
    key: 'game-3d-advanced:Mundo de Blocos Profissional',
    name: 'Mundo de Blocos Profissional',
    experience: 'game',
    promise: 'Plantar blocos sólidos na grade com o clique e subir até o topo da muralha.',
    scenario:
      'Andar, plantar bloco, subir nele, trocar o tipo com 1/2/3, reciclar com X e vencer no topo.',
    interactions: ['click', 'wasd', 'space', 'digit-1'],
  },
  {
    key: 'world-3d:Meu Mundo',
    name: 'Meu Mundo',
    experience: 'exploration',
    promise: 'Dirigir em floresta com ciclo de dia, turbo e segredo.',
    scenario: 'Dirigir, usar turbo, buzinar, achar o segredo e entrar na área.',
    interactions: ['wasd', 'horn-h'],
  },
  {
    key: 'world-3d:Corrida do Por do Sol',
    name: 'Corrida do Por do Sol',
    experience: 'game',
    promise: 'Completar checkpoints ordenados com cronômetro e recorde.',
    scenario: 'Passar pelos cinco checkpoints, fechar volta e registrar recorde.',
    interactions: ['wasd'],
  },
  {
    key: 'world-3d:Boliche na Praca',
    name: 'Boliche na Praca',
    experience: 'game',
    promise: 'Derrubar dez pinos e pilhas com o jipe.',
    scenario: 'Acelerar, atingir os pinos, obter strike e reiniciar.',
    interactions: ['wasd'],
  },
  {
    key: 'world-3d:Inverno Magico',
    name: 'Inverno Magico',
    experience: 'exploration',
    promise: 'Explorar neve, vento, gelo escorregadio e totens.',
    scenario: 'Dirigir pelo gelo, observar derrapagem, neve e todos os totens.',
    interactions: ['wasd'],
  },
  {
    key: 'world-3d:Ilha dos Criadores',
    name: 'Ilha dos Criadores',
    experience: 'game',
    promise: 'Explorar a pé, de carro e barco e coletar quinze moedas.',
    scenario: 'Alternar veículos, conversar, coletar a missão e obter conquista.',
    interactions: ['wasd', 'interact-e'],
  },
  {
    key: 'world-3d:Parque dos Brinquedos',
    name: 'Parque dos Brinquedos',
    experience: 'exploration',
    promise: 'Oferecer boliche, TNT, tornado, buzina e objetos físicos.',
    scenario: 'Exercitar letras, pinos, TNT em cadeia, botão, buzina e recado.',
    interactions: ['wasd', 'click', 'horn-h'],
  },
  {
    key: 'world-3d:Vila das Vocacoes',
    name: 'Vila das Vocacoes',
    experience: 'exploration',
    promise: 'Explorar cidade com trânsito, portas, diálogo e minimapa.',
    scenario: 'Falar com Guia, escolher opção, abrir dois locais, coletar e teleportar.',
    interactions: ['wasd', 'interact-e', 'choice-2', 'click'],
  },
  {
    key: 'world-3d:Base da Lua',
    name: 'Base da Lua',
    experience: 'game',
    promise: 'Usar baixa gravidade e jetpack para coletar doze moedas.',
    scenario: 'Pular/voar, visitar a cratera, coletar tudo, conquistar e reiniciar.',
    interactions: ['wasd', 'space'],
  },
  {
    key: 'world-3d:Fazendinha',
    name: 'Fazendinha',
    experience: 'exploration',
    promise: 'Explorar uma fazenda viva e responder à Rosa.',
    scenario: 'Visitar plantações e animais, observar moinho e escolher uma colheita.',
    interactions: ['wasd', 'interact-e', 'choice-2'],
  },
  {
    key: 'world-3d:Folio Procedural',
    name: 'Folio Procedural',
    experience: 'exploration',
    promise: 'Recriar uma experiência de portfólio 3D com formas, física e distrito procedural.',
    scenario: 'Explorar a pé e de jipe, empurrar objetos e atravessar o distrito criativo.',
    interactions: ['wasd', 'space', 'interact-e'],
  },
  {
    key: 'world-3d:Coastal World Procedural',
    name: 'Coastal World Procedural',
    experience: 'exploration',
    promise: 'Explorar um arquipélago costeiro completo criado apenas com primitivas.',
    scenario: 'Alternar personagem, barco e jetpack, cruzar pontes e chegar ao farol.',
    interactions: ['wasd', 'space', 'interact-e'],
  },
  {
    key: 'world-3d:Vocation Vista Procedural',
    name: 'Vocation Vista Procedural',
    experience: 'exploration',
    promise: 'Explorar uma cidade educativa procedural com bairros, casas e inventário.',
    scenario: 'Visitar os três distritos, conversar, abrir locais e concluir a missão.',
    interactions: ['wasd', 'interact-e', 'choice-2'],
  },
  {
    key: 'core:Cidade & Moinho (na mão)',
    name: 'Cidade & Moinho (na mão)',
    experience: 'game',
    promise: 'Jogar mini-Gorillas feito somente com blocos genéricos.',
    scenario: 'Arrastar a bomba, observar vento/moinho, acertar e reiniciar.',
    interactions: ['drag'],
  },
  {
    key: 'core:Invasores do Espaço (na mão)',
    name: 'Invasores do Espaço (na mão)',
    experience: 'game',
    promise: 'Jogar Space Invaders feito somente com o núcleo.',
    scenario: 'Mover, atirar, enfrentar ondas, perder/vencer e reiniciar.',
    interactions: ['arrows', 'digit-1'],
  },
  {
    key: 'core:Passeio 3D (na mão)',
    name: 'Passeio 3D (na mão)',
    experience: 'exploration',
    promise: 'Dirigir num mundo Three.js com câmera, clima e áudio posicional.',
    scenario: 'Dirigir pela floresta, buzinar e observar câmera, névoa e ciclo diário.',
    interactions: ['wasd', 'horn-h'],
  },
  {
    key: 'core:Folio 3D procedural (na mão)',
    name: 'Folio 3D procedural (na mão)',
    experience: 'exploration',
    promise: 'Construir terreno, estrada, prédios e física usando somente blocos nativos.',
    scenario: 'Mover o personagem, pular e colidir no cenário Three.js sem extensão ou asset.',
    interactions: ['wasd', 'space'],
  },
  {
    key: 'core:Dino Corredor (na mão)',
    name: 'Dino Corredor (na mão)',
    experience: 'game',
    promise: 'Ver o motor do Dino runner por dentro: classes, deltaTime e timer de spawn.',
    scenario: 'Correr, pular cactos, ver o placar subir, colidir e recomeçar com Enter.',
    interactions: ['space', 'arrows', 'start'],
  },
  {
    key: 'core:Corrida Infinita (na mão)',
    name: 'Corrida Infinita (na mão)',
    experience: 'game',
    promise: 'Correr sem fim em three.js puro com esteira, pool e colisão na mão.',
    scenario: 'Trocar de pista, pular obstáculos, ver a velocidade crescer, bater e reiniciar.',
    interactions: ['arrows', 'space', 'click'],
  },
  {
    key: 'core:Batalha de Monstrinhos (na mão)',
    name: 'Batalha de Monstrinhos (na mão)',
    experience: 'game',
    promise: 'Vencer a batalha por turnos com golpes, vantagem de elemento, cura e troca.',
    scenario:
      'Começar, escolher golpe no menu com cursor, trocar de monstrinho, aguardar o turno do inimigo e vencer ou reiniciar.',
    interactions: ['start', 'arrows', 'escape'],
  },
  {
    key: 'core:Aventura do Herói (na mão)',
    name: 'Aventura do Herói (na mão)',
    experience: 'game',
    promise: 'Explorar o mundo com câmera, cortar mato e derrotar quatro inimigos com a espada.',
    scenario:
      'Começar, andar com deslize na parede, golpear mato e inimigos com knockback e vencer ou perder e reiniciar.',
    interactions: ['start', 'arrows', 'space'],
  },
  {
    key: 'core:Labirinto dos Robôs (na mão)',
    name: 'Labirinto dos Robôs (na mão)',
    experience: 'game',
    promise: 'Andar pelo labirinto em primeira pessoa, mirar pelo centro e derrotar os robôs.',
    scenario:
      'Arrastar para olhar, andar com WASD, atirar com espaço num robô, tomar dano, vencer ou perder e reiniciar.',
    interactions: ['drag', 'wasd', 'space', 'click'],
  },
  {
    key: 'core:Mundo de Blocos (na mão)',
    name: 'Mundo de Blocos (na mão)',
    experience: 'game',
    promise: 'Colocar e remover blocos na face mirada e construir uma torre até a nuvem.',
    scenario:
      'Arrastar para olhar, andar e pular, trocar o tipo com 1/2/3, colocar com C na face mirada e remover com X.',
    interactions: ['drag', 'wasd', 'space', 'digit-1', 'place-c', 'remove-x'],
  },
  {
    key: 'core:Chuva de Meteoros (na mão)',
    name: 'Chuva de Meteoros (na mão)',
    experience: 'game',
    promise:
      'Ver o Space Shooter por dentro: herança de sprites, diagonal normalizada e giro com rotate.',
    scenario:
      'Enter começa; voar na diagonal, atirar num meteoro, ver a explosão animada, colidir e recomeçar.',
    interactions: ['start', 'arrows', 'space'],
  },
  {
    key: 'core:Patrulha Espacial (na mão)',
    name: 'Patrulha Espacial (na mão)',
    experience: 'game',
    promise:
      'Patrulhar em three.js puro com nave que inclina e flutua, flash sem shader e sombras fake.',
    scenario:
      'Começar com Enter ou clique, mover com as setas, atirar e ver o flash, colidir e reiniciar.',
    interactions: ['start', 'arrows', 'space', 'click'],
  },
  {
    key: 'game-2d:Muralha do Reino',
    name: 'Muralha do Reino',
    experience: 'game',
    promise: 'Segurar as ondas de invasores comprando torres que atiram sozinhas.',
    scenario: 'Começar, comprar torres no clique, derrotar as ondas, perder ou vencer e reiniciar.',
    interactions: ['start', 'click'],
  },
  {
    key: 'game-2d:Escalada do Guerreiro',
    name: 'Escalada do Guerreiro',
    experience: 'game',
    promise: 'Subir pulando de plataforma em plataforma até a bandeira do topo.',
    scenario: 'Começar, andar e pular com as setas, subir com a câmera e alcançar a bandeira.',
    interactions: ['start', 'arrows'],
  },
  {
    key: 'game-2d-advanced:Muralha do Reino Profissional',
    name: 'Muralha do Reino Profissional',
    experience: 'game',
    promise: 'Defender o reino com o kit de torres: caminho, ondas crescentes e moedas.',
    scenario:
      'Comprar torres no clique, mirar os invasores, ganhar moedas, perder corações e recomeçar.',
    interactions: ['click'],
  },
  {
    key: 'game-2d-advanced:Escalada do Guerreiro Profissional',
    name: 'Escalada do Guerreiro Profissional',
    experience: 'game',
    promise: 'Subir com o kit de plataforma: pulo gostoso, tábuas e câmera que acompanha.',
    scenario:
      'Andar e pular com as setas, subir pelas tábuas, renascer ao cair e alcançar a bandeira.',
    interactions: ['arrows'],
  },
  {
    key: 'core:Muralha do Reino (na mão)',
    name: 'Muralha do Reino (na mão)',
    experience: 'game',
    promise: 'Defender o reino com a lógica de torre feita só com o núcleo.',
    scenario:
      'Começar, comprar torres no clique, encarar as 5 ondas, perder ou vencer e reiniciar.',
    interactions: ['start', 'click'],
  },
  {
    key: 'core:Escalada do Guerreiro (na mão)',
    name: 'Escalada do Guerreiro (na mão)',
    experience: 'game',
    promise: 'Subir a plataforma vertical feita só com o núcleo, com câmera que acompanha.',
    scenario: 'Andar com A e D, pular com W, atravessar tábuas por baixo e alcançar a bandeira.',
    interactions: ['wasd'],
  },
] as const satisfies readonly ExampleQAContract[]
