// Shim: client do members do @sistemazero/member-shell — a vitrine deste app é `kids` (configurada no shell.ts`; o kids usa `kids`).
import { shell } from './shell'

export const {
  listMyCourses,
  listCatalog,
  checkStudioAccessReadonly,
  checkChallengeAccessReadonly,
  checkPensaAccessReadonly,
  checkPintaAccessReadonly,
  getProfileAllowanceReadonly,
  getMyCourse,
  getLesson,
  resolveAttachment,
  resolveEbook,
  markLessonComplete,
  saveVideoPosition,
  saveCourseRating,
  submitQuizAttempt,
  getGamification,
  getGamificationReadonly,
  getStudioUnlocksReadonly,
  getChallengeReadonly,
  getAiCreditsReadonly,
  getAvatarReadonly,
  listAvatarsByProfileIdsReadonly,
  getPublicProfile,
  getRoomReadonly,
  getMissionsReadonly,
  getLeagueReadonly,
  listTeacherThreadsReadonly,
  getTeacherThreadsUnreadReadonly,
} = shell.members
