/**
 * Contrato pequeno e sem dependências da categoria Canvas 3D. As camadas de IR,
 * geração e validação importam estas listas para que um macro novo não dependa
 * de copiar classificações privadas em vários arquivos.
 */
export const CANVAS3D_SEMANTIC_STATEMENT_TYPES = [
  'rendererConfig',
  'rendererResponsive',
  'environmentLoad',
  'disposeObject',
  'lerpPosition',
  'bloomSetup',
  'particlesSetup',
  'waterSetup',
  'waterTime',
  'grassSetup',
  'grassTime',
  'signSetup',
  'primitiveSetup',
  'terrainSetup',
  'roadSetup',
  'buildingSetup',
  'citySetup',
  'physicsLiteSetup',
  'physicsLiteStaticBox',
  'physicsLiteStaticSphere',
  'physicsLiteStaticObject',
  'physicsLiteStaticCity',
  'physicsLiteBody',
  'physicsLiteMove',
  'physicsLiteJump',
  'physicsLiteTrigger',
  'physicsLiteStep',
  'physicsLiteVelocity',
  'physicsLiteImpulse',
  'physicsLiteTeleport',
  'physicsLiteRemove',
  'physicsLiteClear',
  'physicsLiteCollisionEvent',
  'physicsLiteTriggerEvent',
  'physicsLiteRaycast',
  'physicsLiteBodyState',
  'physicsLiteStats',
] as const

export const CANVAS3D_RESOURCE_CREATOR_TYPES: ReadonlySet<string> = new Set([
  'bloomSetup',
  'particlesSetup',
  'waterSetup',
  'grassSetup',
  'signSetup',
  'primitiveSetup',
  'terrainSetup',
  'roadSetup',
  'buildingSetup',
  'citySetup',
  'environmentLoad',
  'loaderLoad',
])
