type DropdownOption = readonly [label: string, value: string]

/**
 * Catálogo único dos dropdowns do Jogo 3D. Os blocos usam os rótulos e o
 * parser usa os mesmos valores para decidir se o código cabe em um bloco sem
 * perder o que a criança escreveu.
 */
export const GAME3D_DROPDOWN_OPTIONS = {
  key: [
    ['W (frente)', 'KeyW'],
    ['S (trás)', 'KeyS'],
    ['A (esquerda)', 'KeyA'],
    ['D (direita)', 'KeyD'],
    ['espaço (pular)', 'Space'],
    ['↑ seta para cima', 'ArrowUp'],
    ['↓ seta para baixo', 'ArrowDown'],
    ['← seta esquerda', 'ArrowLeft'],
    ['→ seta direita', 'ArrowRight'],
  ],
  gridDirection: [
    ['frente', 'forward'],
    ['trás', 'backward'],
    ['esquerda', 'left'],
    ['direita', 'right'],
  ],
  rowKind: [
    ['grama', 'grass'],
    ['floresta (árvores)', 'forest'],
    ['carros', 'car'],
    ['caminhões', 'truck'],
  ],
  rowDirection: [
    ['→ direita', 'right'],
    ['← esquerda', 'left'],
  ],
  raceMode: [
    ['acelerar', 'accelerate'],
    ['frear', 'decelerate'],
    ['velocidade normal', 'normal'],
  ],
  axis: [
    ['↔ X', 'x'],
    ['↕ Y', 'y'],
    ['↗ Z', 'z'],
  ],
  rotationAxis: [
    ['↕ Y', 'y'],
    ['↔ X', 'x'],
    ['↗ Z', 'z'],
  ],
  propertyAxis: [
    ['x', 'x'],
    ['y', 'y'],
    ['z', 'z'],
  ],
  visibility: [
    ['Mostrar', 'show'],
    ['Esconder', 'hide'],
  ],
  material: [
    ['normal', 'normal'],
    ['metal', 'metal'],
    ['vidro', 'glass'],
    ['brilhante', 'glow'],
    ['só linhas', 'wireframe'],
  ],
  shadows: [
    ['Ligar', 'on'],
    ['Desligar', 'off'],
  ],
  effect: [
    ['moeda', 'coin'],
    ['pulo', 'jump'],
    ['explosão', 'explosion'],
    ['acerto', 'hit'],
  ],
} satisfies Readonly<Record<string, readonly DropdownOption[]>>

type Game3DDropdown = keyof typeof GAME3D_DROPDOWN_OPTIONS

const GAME3D_DROPDOWN_ARGUMENTS: Readonly<
  Record<string, Readonly<Partial<Record<number, Game3DDropdown>>>>
> = {
  keyDown: { 0: 'key' },
  gridMove: { 1: 'gridDirection' },
  crosserMove: { 1: 'gridDirection' },
  addRow: { 2: 'rowKind', 3: 'rowDirection' },
  raceControl: { 1: 'raceMode' },
  slideBetween: { 1: 'axis' },
  spin: { 1: 'rotationAxis' },
  getPos: { 1: 'propertyAxis' },
  getRot: { 1: 'propertyAxis' },
  getVel: { 1: 'propertyAxis' },
  rotateBy: { 1: 'rotationAxis' },
  setVisible: { 1: 'visibility' },
  setMaterial: { 1: 'material' },
  setShadows: { 1: 'shadows' },
  pruneSwarm: { 1: 'axis' },
  playEffect: { 0: 'effect' },
}

export function game3dDropdownArgumentIsValid(
  method: string,
  argumentIndex: number,
  value: string | undefined,
): boolean {
  const dropdown = GAME3D_DROPDOWN_ARGUMENTS[method]?.[argumentIndex]
  if (!dropdown) return true
  if (value === undefined) return false
  return GAME3D_DROPDOWN_OPTIONS[dropdown].some(([, optionValue]) => optionValue === value)
}

/** Assinaturas canônicas geradas pelos blocos e reconhecidas pela Ponte. */
export const GAME3D_CALL_ARITIES: Readonly<Record<string, number | readonly number[]>> = {
  createScene: 1,
  createFullscreenScene: [0, 1],
  setBackground: 2,
  setCameraPosition: 4,
  createBox: 2,
  createSphere: 2,
  createBlock: 2,
  setPosition: 4,
  setRotation: 4,
  setScale: 2,
  setVelocity: 4,
  applyGravity: 2,
  jump: 2,
  controlWithKeys: 2,
  cameraFollow: 2,
  keyDown: 1,
  collides: 2,
  hitAny: 2,
  createGroup: 0,
  runEnemies: 5,
  stop: 1,
  isometricCamera: 2,
  gridPosition: 3,
  gridStep: 1,
  gridMove: 2,
  moveAcross: 4,
  touchesBox: 2,
  createCrossingScene: 1,
  createCrosser: 2,
  crosserMove: 2,
  crosserStep: 2,
  crosserReset: 2,
  addRow: 5,
  generateRows: 2,
  moveTraffic: 1,
  crosserHit: 2,
  crosserRow: 1,
  topCamera: 2,
  moveInCircle: 3,
  distanceTo: 2,
  isNear: 3,
  createRaceScene: 1,
  createRaceTrack: 1,
  createRaceCar: 2,
  raceStep: 2,
  raceControl: 2,
  runRivals: 1,
  raceHit: 2,
  raceLaps: 1,
  raceReset: 2,
  fall: 1,
  slideBetween: 5,
  spin: 3,
  createStackScene: 1,
  createStackTower: 1,
  stackDrop: 1,
  stackStep: 1,
  stackReset: 1,
  stackScore: 1,
  stackGameOver: 1,
  getPos: 2,
  getRot: 2,
  getScale: 1,
  getVel: 2,
  getSpeed: 1,
  isMoving: 1,
  dt: 1,
  moveBy: 4,
  rotateBy: 3,
  moveTowards: 5,
  lookAtObject: 2,
  lookAtPoint: 4,
  moveForward: 2,
  faceVelocity: 1,
  angleTo: 2,
  pickAtMouse: 1,
  pointerOver: 2,
  aimAhead: 3,
  onGround: 2,
  groundHeight: 2,
  body: 2,
  stepBody: 2,
  setSolid: 1,
  platformerControls: 4,
  fpsControls: 3,
  resolveCollision: 2,
  fpsCamera: 2,
  orbitCamera: 2,
  thirdPersonCamera: 4,
  cameraLookAt: 2,
  setFOV: 2,
  createCylinder: 2,
  createCone: 2,
  createPlane: 2,
  createTorus: 2,
  createModel: 1,
  addToModel: 2,
  setColor: 2,
  setOpacity: 2,
  setMaterial: 2,
  setTexture: 2,
  setVisible: 2,
  remove: 2,
  addAmbientLight: 3,
  addSunLight: 3,
  addPointLight: 6,
  setFog: 4,
  setSky: 3,
  setShadows: 2,
  createSwarm: 1,
  spawnInSwarm: 5,
  countSwarm: 1,
  forEachInSwarm: 2,
  removeFromSwarm: 2,
  pruneSwarm: 4,
  playNote: 2,
  playEffect: 1,
  animate: 2,
}

export function game3dCallArityIsValid(method: string, count: number): boolean {
  const arity = GAME3D_CALL_ARITIES[method]
  if (arity === undefined) return false
  return typeof arity === 'number' ? arity === count : arity.includes(count)
}

/**
 * Operações que pertencem diretamente à montagem do jogo. Esta é a fonte
 * compartilhada pelo placement dos blocos e pela validação de IR importada.
 */
export const GAME3D_START_ONLY_STATEMENT_TYPES: ReadonlySet<string> = new Set([
  'g3d:createScene',
  'g3d:createFullscreenScene',
  'g3d:createBox',
  'g3d:createSphere',
  'g3d:createBlock',
  'g3d:createGroup',
  'g3d:isometricCamera',
  'g3d:createCrossingScene',
  'g3d:createCrosser',
  'g3d:addRow',
  'g3d:generateRows',
  'g3d:createRaceScene',
  'g3d:createRaceTrack',
  'g3d:createRaceCar',
  'g3d:topCamera',
  'g3d:createStackScene',
  'g3d:createStackTower',
  'g3d:body',
  'g3d:setSolid',
  'g3d:createCylinder',
  'g3d:createCone',
  'g3d:createPlane',
  'g3d:createTorus',
  'g3d:createModel',
  'g3d:addToModel',
  'g3d:setMaterial',
  'g3d:setTexture',
  'g3d:addAmbientLight',
  'g3d:addSunLight',
  'g3d:addPointLight',
  'g3d:setFog',
  'g3d:setSky',
  'g3d:setShadows',
  'g3d:createSwarm',
])
