type DropdownOption = readonly [label: string, value: string]

export type Game3DSymbolKind = 'world' | 'object' | 'group' | 'swarm'
export type Game3DObjectScope = 'any-three-object' | 'game-world-object'

export interface Game3DReferenceField {
  field: string
  kind: Game3DSymbolKind
  objectScope?: Game3DObjectScope
}

/** Recursos nomeados que cada comando do Jogo 3D introduz no programa. */
export const GAME3D_SEMANTIC_DECLARATION_FIELDS: Readonly<Record<string, Game3DReferenceField>> = {
  'g3d:createScene': { field: 'varName', kind: 'world' },
  'g3d:createFullscreenScene': { field: 'varName', kind: 'world' },
  'g3d:createCrossingScene': { field: 'varName', kind: 'world' },
  'g3d:createRaceScene': { field: 'varName', kind: 'world' },
  'g3d:createStackScene': { field: 'varName', kind: 'world' },
  'g3d:createBox': { field: 'varName', kind: 'object' },
  'g3d:createSphere': { field: 'varName', kind: 'object' },
  'g3d:createBlock': { field: 'varName', kind: 'object' },
  'g3d:createCrosser': { field: 'varName', kind: 'object' },
  'g3d:createRaceCar': { field: 'varName', kind: 'object' },
  'g3d:createCylinder': { field: 'varName', kind: 'object' },
  'g3d:createCone': { field: 'varName', kind: 'object' },
  'g3d:createPlane': { field: 'varName', kind: 'object' },
  'g3d:createTorus': { field: 'varName', kind: 'object' },
  'g3d:createModel': { field: 'varName', kind: 'object' },
  'g3d:createGroup': { field: 'varName', kind: 'group' },
  'g3d:createSwarm': { field: 'varName', kind: 'swarm' },
}

const world = (field = 'worldVar'): Game3DReferenceField => ({ field, kind: 'world' })
const object = (field = 'objVar'): Game3DReferenceField => ({ field, kind: 'object' })
const gameObject = (field = 'objVar'): Game3DReferenceField => ({
  field,
  kind: 'object',
  objectScope: 'game-world-object',
})
const group = (field = 'groupVar'): Game3DReferenceField => ({ field, kind: 'group' })
const swarm = (field = 'swarmVar'): Game3DReferenceField => ({ field, kind: 'swarm' })

/** Expressões que devolvem um objeto pertencente a um mundo do Jogo 3D. */
export const GAME3D_OBJECT_EXPRESSION_TYPES: ReadonlySet<string> = new Set([
  'g3d:pickAtMouse',
  'g3d:aimAhead',
])

/** Referências semânticas emitidas pelos blocos e consumidas pelo validador de IR. */
export const GAME3D_SEMANTIC_REFERENCE_FIELDS: Readonly<
  Record<string, readonly Game3DReferenceField[]>
> = {
  'g3d:setBackground': [world()],
  'g3d:setCameraPosition': [world()],
  'g3d:createBox': [world()],
  'g3d:createSphere': [world()],
  'g3d:setPosition': [object()],
  'g3d:setRotation': [object()],
  'g3d:animate': [world()],
  'g3d:createBlock': [world()],
  'g3d:setVelocity': [object()],
  'g3d:jump': [object()],
  'g3d:applyGravity': [object(), object('groundVar')],
  'g3d:controlWithKeys': [object()],
  'g3d:setScale': [object()],
  'g3d:cameraFollow': [world(), gameObject()],
  'g3d:runEnemies': [world(), group(), gameObject('groundVar')],
  'g3d:stop': [world()],
  'g3d:createCrosser': [world()],
  'g3d:crosserMove': [object()],
  'g3d:crosserStep': [gameObject(), world()],
  'g3d:crosserReset': [gameObject(), world()],
  'g3d:gridPosition': [object()],
  'g3d:addRow': [world()],
  'g3d:generateRows': [world()],
  'g3d:moveTraffic': [world()],
  'g3d:isometricCamera': [world(), gameObject('followVar')],
  'g3d:gridStep': [object()],
  'g3d:gridMove': [object()],
  'g3d:moveAcross': [group()],
  'g3d:touchesBox': [object(), group()],
  'g3d:topCamera': [world(), gameObject('followVar')],
  'g3d:moveInCircle': [object()],
  'g3d:createRaceTrack': [world()],
  'g3d:createRaceCar': [world()],
  'g3d:raceStep': [gameObject(), world()],
  'g3d:raceControl': [object()],
  'g3d:runRivals': [world()],
  'g3d:raceReset': [gameObject(), world()],
  'g3d:fall': [object()],
  'g3d:slideBetween': [object()],
  'g3d:spin': [object()],
  'g3d:createStackTower': [world()],
  'g3d:stackDrop': [world()],
  'g3d:stackStep': [world()],
  'g3d:stackReset': [world()],
  'g3d:moveBy': [object()],
  'g3d:rotateBy': [object()],
  'g3d:moveTowards': [object()],
  'g3d:lookAtObject': [object('aVar'), object('bVar')],
  'g3d:lookAtPoint': [object()],
  'g3d:moveForward': [object()],
  'g3d:faceVelocity': [object()],
  'g3d:body': [object()],
  'g3d:stepBody': [gameObject(), world()],
  'g3d:setSolid': [object()],
  'g3d:platformerControls': [gameObject(), world()],
  'g3d:fpsControls': [gameObject(), world()],
  'g3d:resolveCollision': [object('aVar'), object('bVar')],
  'g3d:fpsCamera': [world(), gameObject()],
  'g3d:orbitCamera': [world(), gameObject()],
  'g3d:thirdPersonCamera': [world(), gameObject()],
  'g3d:cameraLookAt': [world(), gameObject()],
  'g3d:setFOV': [world()],
  'g3d:createCylinder': [world()],
  'g3d:createCone': [world()],
  'g3d:createPlane': [world()],
  'g3d:createTorus': [world()],
  'g3d:createModel': [world()],
  'g3d:setColor': [object()],
  'g3d:setOpacity': [object()],
  'g3d:setMaterial': [object()],
  'g3d:setTexture': [object()],
  'g3d:setVisible': [object()],
  'g3d:removeObject': [world(), object()],
  'g3d:addToModel': [gameObject('modelVar'), gameObject('partVar')],
  'g3d:addAmbientLight': [world()],
  'g3d:addSunLight': [world()],
  'g3d:addPointLight': [world()],
  'g3d:setFog': [world()],
  'g3d:setSky': [world()],
  'g3d:setShadows': [world()],
  'g3d:createSwarm': [world()],
  'g3d:spawnInSwarm': [swarm(), gameObject('originalVar')],
  'g3d:countSwarm': [swarm()],
  'g3d:forEachInSwarm': [swarm()],
  'g3d:removeFromSwarm': [swarm(), gameObject('itemVar')],
  'g3d:pruneSwarm': [swarm()],
  'g3d:collides': [object('aVar'), object('bVar')],
  'g3d:hitAny': [object(), group()],
  'g3d:crosserHit': [gameObject(), world()],
  'g3d:crosserRow': [object()],
  'g3d:distanceTo': [object('aVar'), object('bVar')],
  'g3d:isNear': [object('aVar'), object('bVar')],
  'g3d:raceHit': [gameObject(), world()],
  'g3d:raceLaps': [object()],
  'g3d:stackScore': [world()],
  'g3d:stackGameOver': [world()],
  'g3d:getPos': [object()],
  'g3d:getRot': [object()],
  'g3d:getScale': [object()],
  'g3d:getVel': [object()],
  'g3d:getSpeed': [object()],
  'g3d:isMoving': [object()],
  'g3d:dt': [world()],
  'g3d:angleTo': [object('aVar'), object('bVar')],
  'g3d:pickAtMouse': [world()],
  'g3d:pointerOver': [world(), gameObject()],
  'g3d:aimAhead': [world(), gameObject()],
  'g3d:onGround': [world(), gameObject()],
  'g3d:groundHeight': [world(), gameObject()],
}

/**
 * Catálogo único dos dropdowns do Jogo 3D. Os blocos usam os rótulos e o
 * parser usa os mesmos valores para decidir se o código cabe em um bloco sem
 * perder o que a criança escreveu.
 */
export const GAME3D_DROPDOWN_OPTIONS = {
  key: [
    ['W (frente)', 'KeyW'],
    ['S (trás)', 'KeyS'],
    ['A (esquerda)', 'KeyA'],
    ['D (direita)', 'KeyD'],
    ['espaço (pular)', 'Space'],
    ['↑ seta para cima', 'ArrowUp'],
    ['↓ seta para baixo', 'ArrowDown'],
    ['← seta esquerda', 'ArrowLeft'],
    ['→ seta direita', 'ArrowRight'],
  ],
  gridDirection: [
    ['frente', 'forward'],
    ['trás', 'backward'],
    ['esquerda', 'left'],
    ['direita', 'right'],
  ],
  rowKind: [
    ['grama', 'grass'],
    ['floresta (árvores)', 'forest'],
    ['carros', 'car'],
    ['caminhões', 'truck'],
  ],
  rowDirection: [
    ['→ direita', 'right'],
    ['← esquerda', 'left'],
  ],
  raceMode: [
    ['acelerar', 'accelerate'],
    ['frear', 'decelerate'],
    ['velocidade normal', 'normal'],
  ],
  axis: [
    ['↔ X', 'x'],
    ['↕ Y', 'y'],
    ['↗ Z', 'z'],
  ],
  rotationAxis: [
    ['↕ Y', 'y'],
    ['↔ X', 'x'],
    ['↗ Z', 'z'],
  ],
  propertyAxis: [
    ['x', 'x'],
    ['y', 'y'],
    ['z', 'z'],
  ],
  visibility: [
    ['Mostrar', 'show'],
    ['Esconder', 'hide'],
  ],
  material: [
    ['normal', 'normal'],
    ['metal', 'metal'],
    ['vidro', 'glass'],
    ['brilhante', 'glow'],
    ['só linhas', 'wireframe'],
  ],
  shadows: [
    ['Ligar', 'on'],
    ['Desligar', 'off'],
  ],
  effect: [
    ['moeda', 'coin'],
    ['pulo', 'jump'],
    ['explosão', 'explosion'],
    ['acerto', 'hit'],
  ],
} satisfies Readonly<Record<string, readonly DropdownOption[]>>

type Game3DDropdown = keyof typeof GAME3D_DROPDOWN_OPTIONS

const GAME3D_DROPDOWN_ARGUMENTS: Readonly<
  Record<string, Readonly<Partial<Record<number, Game3DDropdown>>>>
> = {
  keyDown: { 0: 'key' },
  gridMove: { 1: 'gridDirection' },
  crosserMove: { 1: 'gridDirection' },
  addRow: { 2: 'rowKind', 3: 'rowDirection' },
  raceControl: { 1: 'raceMode' },
  slideBetween: { 1: 'axis' },
  spin: { 1: 'rotationAxis' },
  getPos: { 1: 'propertyAxis' },
  getRot: { 1: 'propertyAxis' },
  getVel: { 1: 'propertyAxis' },
  rotateBy: { 1: 'rotationAxis' },
  setVisible: { 1: 'visibility' },
  setMaterial: { 1: 'material' },
  setShadows: { 1: 'shadows' },
  pruneSwarm: { 1: 'axis' },
  playEffect: { 0: 'effect' },
}

export function game3dDropdownArgumentIsValid(
  method: string,
  argumentIndex: number,
  value: string | undefined,
): boolean {
  const dropdown = GAME3D_DROPDOWN_ARGUMENTS[method]?.[argumentIndex]
  if (!dropdown) return true
  if (value === undefined) return false
  return GAME3D_DROPDOWN_OPTIONS[dropdown].some(([, optionValue]) => optionValue === value)
}

/** Assinaturas canônicas geradas pelos blocos e reconhecidas pela Ponte. */
export const GAME3D_CALL_ARITIES: Readonly<Record<string, number | readonly number[]>> = {
  createScene: 1,
  createFullscreenScene: [0, 1],
  setBackground: 2,
  setCameraPosition: 4,
  createBox: 2,
  createSphere: 2,
  createBlock: 2,
  setPosition: 4,
  setRotation: 4,
  setScale: 2,
  setVelocity: 4,
  applyGravity: 2,
  jump: 2,
  controlWithKeys: 2,
  cameraFollow: 2,
  keyDown: 1,
  collides: 2,
  hitAny: 2,
  createGroup: 0,
  runEnemies: 5,
  stop: 1,
  isometricCamera: 2,
  gridPosition: 3,
  gridStep: 1,
  gridMove: 2,
  moveAcross: 4,
  touchesBox: 2,
  createCrossingScene: 1,
  createCrosser: 2,
  crosserMove: 2,
  crosserStep: 2,
  crosserReset: 2,
  addRow: 5,
  generateRows: 2,
  moveTraffic: 1,
  crosserHit: 2,
  crosserRow: 1,
  topCamera: 2,
  moveInCircle: 3,
  distanceTo: 2,
  isNear: 3,
  createRaceScene: 1,
  createRaceTrack: 1,
  createRaceCar: 2,
  raceStep: 2,
  raceControl: 2,
  runRivals: 1,
  raceHit: 2,
  raceLaps: 1,
  raceReset: 2,
  fall: 1,
  slideBetween: 5,
  spin: 3,
  createStackScene: 1,
  createStackTower: 1,
  stackDrop: 1,
  stackStep: 1,
  stackReset: 1,
  stackScore: 1,
  stackGameOver: 1,
  getPos: 2,
  getRot: 2,
  getScale: 1,
  getVel: 2,
  getSpeed: 1,
  isMoving: 1,
  dt: 1,
  moveBy: 4,
  rotateBy: 3,
  moveTowards: 5,
  lookAtObject: 2,
  lookAtPoint: 4,
  moveForward: 2,
  faceVelocity: 1,
  angleTo: 2,
  pickAtMouse: 1,
  pointerOver: 2,
  aimAhead: 3,
  onGround: 2,
  groundHeight: 2,
  body: 2,
  stepBody: 2,
  setSolid: 1,
  platformerControls: 4,
  fpsControls: 3,
  resolveCollision: 2,
  fpsCamera: 2,
  orbitCamera: 2,
  thirdPersonCamera: 4,
  cameraLookAt: 2,
  setFOV: 2,
  createCylinder: 2,
  createCone: 2,
  createPlane: 2,
  createTorus: 2,
  createModel: 1,
  addToModel: 2,
  setColor: 2,
  setOpacity: 2,
  setMaterial: 2,
  setTexture: 2,
  setVisible: 2,
  remove: 2,
  addAmbientLight: 3,
  addSunLight: 3,
  addPointLight: 6,
  setFog: 4,
  setSky: 3,
  setShadows: 2,
  createSwarm: 1,
  spawnInSwarm: 5,
  countSwarm: 1,
  forEachInSwarm: 2,
  removeFromSwarm: 2,
  pruneSwarm: 4,
  playNote: 2,
  playEffect: 1,
  animate: 2,
}

export function game3dCallArityIsValid(method: string, count: number): boolean {
  const arity = GAME3D_CALL_ARITIES[method]
  if (arity === undefined) return false
  return typeof arity === 'number' ? arity === count : arity.includes(count)
}

/**
 * Operações que pertencem diretamente à montagem do jogo. Esta é a fonte
 * compartilhada pelo placement dos blocos e pela validação de IR importada.
 */
export const GAME3D_START_ONLY_STATEMENT_TYPES: ReadonlySet<string> = new Set([
  'g3d:createScene',
  'g3d:createFullscreenScene',
  'g3d:createBox',
  'g3d:createSphere',
  'g3d:createBlock',
  'g3d:createGroup',
  'g3d:isometricCamera',
  'g3d:createCrossingScene',
  'g3d:createCrosser',
  'g3d:addRow',
  'g3d:generateRows',
  'g3d:createRaceScene',
  'g3d:createRaceTrack',
  'g3d:createRaceCar',
  'g3d:topCamera',
  'g3d:createStackScene',
  'g3d:createStackTower',
  'g3d:body',
  'g3d:setSolid',
  'g3d:createCylinder',
  'g3d:createCone',
  'g3d:createPlane',
  'g3d:createTorus',
  'g3d:createModel',
  'g3d:addToModel',
  'g3d:setMaterial',
  'g3d:setTexture',
  'g3d:addAmbientLight',
  'g3d:addSunLight',
  'g3d:addPointLight',
  'g3d:setFog',
  'g3d:setSky',
  'g3d:setShadows',
  'g3d:createSwarm',
])

/** Comandos sem efeito antes de um loop, evento ou função entrar em execução. */
export const GAME3D_RUNNING_CONTEXT_STATEMENT_TYPES: ReadonlySet<string> = new Set(['g3d:stop'])
