import {
  arenaGoblinsExample,
  batalhaEmEquipeExample,
  bichinhosDoQuintalExample,
  cacaMoedasExample,
  cobrinhaExample,
  corridaTabuleiroExample,
  defesaDoReinoExample,
  dinoProfissionalExample,
  dueloDeCartasExample,
  dueloDosBonecosExample,
  florestaNinjaExample,
  invasaoDosOvnisExample,
  jogoDaMemoriaExample,
  meuPrimeiroJogoExample,
  oChefaoExample,
  oChefaoFichaExample,
  quebraBlocosExample,
  reinoAbertoExample,
  saltoNaFlorestaExample,
  vilaDoDragaoExample,
} from './examples'

export const gameKitExamples = [
  meuPrimeiroJogoExample,
  cacaMoedasExample,
  arenaGoblinsExample,
  vilaDoDragaoExample,
  florestaNinjaExample,
  saltoNaFlorestaExample,
  dinoProfissionalExample,
  bichinhosDoQuintalExample,
  invasaoDosOvnisExample,
  dueloDosBonecosExample,
  defesaDoReinoExample,
  reinoAbertoExample,
  batalhaEmEquipeExample,
  oChefaoExample,
  oChefaoFichaExample,
  corridaTabuleiroExample,
  jogoDaMemoriaExample,
  dueloDeCartasExample,
  cobrinhaExample,
  quebraBlocosExample,
] as const
