import {
  aLendaDoHeroiBasicoExample,
  cacaEstelarBasicoExample,
  cercoNaBaseBasicoExample,
  corridaInfinitaExample,
  crossingExample,
  defesaDaTorreBasicoExample,
  dodgeExample,
  labirintoRobosExample,
  minaDeCristaisBasicoExample,
  mundoBlocosExample,
  nightExample,
  patrulhaEspacialExample,
  raceExample,
  reinoCogumeloExample,
  reunirRebanhoBasicoExample,
  rotatingCubeExample,
  shapesExample,
  stackExample,
  swarmExample,
} from './examples'

export const gameThreeDExamples = [
  rotatingCubeExample,
  shapesExample,
  nightExample,
  swarmExample,
  dodgeExample,
  corridaInfinitaExample,
  labirintoRobosExample,
  mundoBlocosExample,
  patrulhaEspacialExample,
  crossingExample,
  raceExample,
  defesaDaTorreBasicoExample,
  reunirRebanhoBasicoExample,
  aLendaDoHeroiBasicoExample,
  cacaEstelarBasicoExample,
  cercoNaBaseBasicoExample,
  minaDeCristaisBasicoExample,
  stackExample,
  reinoCogumeloExample,
] as const
