import { preserve } from 'railway/iac'

// Apenas nomes. Valores e referências permanecem no Railway de cada ambiente.
const common: Record<string, string[]> = {
  hub: [
    'DATABASE_POOL_MAX',
    'DATABASE_URL',
    'GATEWAY_HMAC_SECRET',
    'HOST',
    'INTERNAL_API_TOKEN',
    'KIDS_BFF_BASE_URL',
    'MEMBERS_BASE_URL',
    'MEMBERS_INTERNAL_TOKEN',
    'NODE_ENV',
    'PORT',
  ],
  catalog: ['DATABASE_POOL_MAX', 'DATABASE_URL', 'INTERNAL_API_TOKEN', 'NODE_ENV', 'PORT'],
  referrals: [
    'APP_ENV',
    'BONUS_AMOUNT_CENTS',
    'BONUS_MATURE_HOURS',
    'CATALOG_BASE_URL',
    'CONVERSION_OFFER_SLUGS',
    'DATABASE_URL',
    'FUNNEL_PUBLIC_URL',
    'GATEWAY_URL',
    'HOST',
    'INTERNAL_API_TOKEN',
    'KIDS_COMMUNITY_URL',
    'METRICS_TOKEN',
    'NODE_ENV',
    'PAYMENTS_BASE_URL',
    'PAYMENTS_INTERNAL_TOKEN',
    'PAYMENTS_WEBHOOK_HMAC_SECRET',
    'PORT',
    'REFERRALS_HMAC_SECRET',
    'SENTRY_DSN',
  ],
  payments: [
    'ASYNC_CHARGE_CREATION',
    'DATABASE_POOL_MAX',
    'DATABASE_URL',
    'EFI_BOLETO_NOTIFICATION_URL',
    'EFI_CERTIFICATE_BASE64',
    'EFI_CLIENT_ID',
    'EFI_CLIENT_SECRET',
    'EFI_PIX_KEY',
    'EFI_SANDBOX',
    'EFI_WEBHOOK_SECRET',
    'INTERNAL_API_TOKEN',
    'METRICS_TOKEN',
    'NODE_ENV',
    'TRUST_PROXY',
  ],
  'api-gateway': [
    'AUTH_ALLOWED_CIDRS',
    'AUTH_HMAC_SECRET',
    'AUTH_INTERNAL_TOKEN',
    'AUTH_URL',
    'CATALOG_INTERNAL_TOKEN',
    'CATALOG_URL',
    'FISCAL_ALLOWED_CIDRS',
    'FISCAL_HMAC_SECRET',
    'FISCAL_INTERNAL_TOKEN',
    'FISCAL_URL',
    'FUNNEL_ALLOWED_CIDRS',
    'FUNNEL_HMAC_SECRET',
    'FUNNEL_INTERNAL_TOKEN',
    'FUNNEL_URL',
    'GATEWAY_CONSUMER_ID',
    'GATEWAY_HMAC_SECRET',
    'HELPDESK_ALLOWED_CIDRS',
    'HELPDESK_HMAC_SECRET',
    'HELPDESK_INTERNAL_TOKEN',
    'HELPDESK_URL',
    'HUB_INTERNAL_TOKEN',
    'HUB_URL',
    'JWT_AUDIENCE',
    'JWT_ISSUER',
    'JWT_JWKS_URL',
    'LOG_LEVEL',
    'MARKETING_HMAC_SECRET',
    'MARKETING_INTERNAL_TOKEN',
    'MARKETING_URL',
    'MEMBERS_HMAC_SECRET',
    'MEMBERS_INTERNAL_TOKEN',
    'MEMBERS_URL',
    'MEMBER_SHELL_HMAC_SECRET',
    'MESSAGING_INTERNAL_TOKEN',
    'MESSAGING_URL',
    'METRICS_TOKEN',
    'NODE_ENV',
    'PAYMENTS_INTERNAL_TOKEN',
    'PAYMENTS_URL',
    'PORT',
    'REFERRALS_ALLOWED_CIDRS',
    'REFERRALS_HMAC_SECRET',
    'REFERRALS_INTERNAL_TOKEN',
    'REFERRALS_URL',
    'TRUSTED_PROXY_HOPS',
    'TRUST_PROXY',
  ],
  fiscal: [
    'APP_ENV',
    'CATALOG_BASE_URL',
    'DATABASE_URL',
    'FISCAL_HMAC_SECRET',
    'FISCAL_SELF_URL',
    'GATEWAY_URL',
    'HOST',
    'INTERNAL_API_TOKEN',
    'METRICS_TOKEN',
    'NFSE_AMBIENTE',
    'NFSE_CERT_PASSWORD',
    'NFSE_CERT_PFX_BASE64',
    'NFSE_CTRIB_MUN',
    'NFSE_DPS_SERIE',
    'NFSE_IM',
    'NFSE_PTOTTRIB_SN',
    'NFSE_SERVICE_DESC_PREFIX',
    'NODE_ENV',
    'PAYMENTS_BASE_URL',
    'PAYMENTS_INTERNAL_TOKEN',
    'PAYMENTS_WEBHOOK_HMAC_SECRET',
    'PORT',
  ],
  marketing: [
    'DATABASE_URL',
    'HOST',
    'INTERNAL_API_TOKEN',
    'MARKETING_HMAC_SECRET',
    'NODE_ENV',
    'OPENROUTER_API_KEY',
    'OPENROUTER_MARKETING_MODEL',
    'PORT',
    'R2_ACCESS_KEY_ID',
    'R2_ACCOUNT_ID',
    'R2_MARKETING_BUCKET',
    'R2_SECRET_ACCESS_KEY',
  ],
  auth: [
    'AUTH_HMAC_SECRET',
    'AUTH_INTERNAL_TOKEN',
    'COMMUNITY_URL',
    'DATABASE_POOL_MAX',
    'DATABASE_URL',
    'GATEWAY_URL',
    'INVITE_TOKEN_TTL_MINUTES',
    'JWT_ALG',
    'JWT_KID',
    'JWT_PRIVATE_KEY',
    'KIDS_COMMUNITY_URL',
    'MEMBERS_BASE_URL',
    'MEMBERS_INTERNAL_TOKEN',
    'NODE_ENV',
    'PORT',
    'TRUSTED_PROXY_HOPS',
    'TRUST_PROXY',
  ],
  messaging: [
    'ATTACHMENT_FETCH_ALLOWED_HOSTS',
    'DATABASE_POOL_MAX',
    'DATABASE_URL',
    'EVOLUTION_API_KEY',
    'EVOLUTION_URL',
    'MESSAGING_INTERNAL_TOKEN',
    'MESSAGING_WEBHOOK_TOKEN',
    'METRICS_TOKEN',
    'NODE_ENV',
    'PORT',
    'RAILWAY_DOCKERFILE_PATH',
    'SENDGRID_API_KEY',
    'SENDGRID_WEBHOOK_PUBLIC_KEY',
  ],
  'marketing-app': ['GATEWAY_URL', 'JWT_AUDIENCE', 'JWT_ISSUER', 'JWT_JWKS_URL'],
  helpdesk: [
    'COMMUNITY_URL',
    'DATABASE_URL',
    'GATEWAY_URL',
    'GOOGLE_CLIENT_ID',
    'GOOGLE_CLIENT_SECRET',
    'HELPDESK_APP_URL',
    'HELPDESK_HMAC_SECRET',
    'HELPDESK_MAILBOX_ADDRESS',
    'HELPDESK_TOKEN_ENC_KEY',
    'HOST',
    'INTERNAL_API_TOKEN',
    'KIDS_COMMUNITY_URL',
    'NODE_ENV',
    'OAUTH_PUBLIC_BASE_URL',
    'OPENROUTER_API_KEY',
    'OPENROUTER_HELPDESK_MODEL',
    'PORT',
  ],
  'evolution-api': [
    'AUTHENTICATION_API_KEY',
    'CACHE_LOCAL_ENABLED',
    'CACHE_REDIS_ENABLED',
    'DATABASE_CONNECTION_CLIENT_NAME',
    'DATABASE_CONNECTION_URI',
    'DATABASE_ENABLED',
    'DATABASE_PROVIDER',
    'DATABASE_SAVE_DATA_CHATS',
    'DATABASE_SAVE_DATA_CONTACTS',
    'DATABASE_SAVE_DATA_HISTORIC',
    'DATABASE_SAVE_DATA_INSTANCE',
    'DATABASE_SAVE_DATA_LABELS',
    'DATABASE_SAVE_DATA_NEW_MESSAGE',
    'DATABASE_SAVE_MESSAGE_UPDATE',
    'DEL_INSTANCE',
    'LANGUAGE',
    'SERVER_PORT',
    'SERVER_URL',
  ],
  community: [
    'APP_PUBLIC_URL',
    'FUNNEL_URL',
    'GATEWAY_URL',
    'JWT_AUDIENCE',
    'JWT_ISSUER',
    'JWT_JWKS_URL',
    'MEMBER_SHELL_HMAC_SECRET',
    'NODE_ENV',
    'PORT',
    'R2_ACCESS_KEY_ID',
    'R2_ACCOUNT_ID',
    'R2_BUCKET',
    'R2_PRIVATE_BUCKET',
    'R2_PUBLIC_URL',
    'R2_SECRET_ACCESS_KEY',
    'R2_UGC_BUCKET',
  ],
  funnel: [
    'COMMUNITY_URL',
    'DATABASE_POOL_MAX',
    'DATABASE_URL',
    'FUNNEL_CONSUMER_ID',
    'FUNNEL_HMAC_SECRET',
    'FUNNEL_INTERNAL_TOKEN',
    'FUNNEL_OFFER_KIDS_COMUNIDADE_DOS_CRIADORES',
    'FUNNEL_OFFER_KIDS_DESAFIO_PRIMEIRO_JOGO',
    'FUNNEL_OFFER_PRO_NO_COMANDO_DA_IA',
    'FUNNEL_PUBLIC_URL',
    'GATEWAY_URL',
    'HOST',
    'KIDS_COMMUNITY_URL',
    'NODE_ENV',
    'PORT',
    'PUBLIC_EFI_ACCOUNT_IDENTIFIER',
    'PUBLIC_EFI_SANDBOX',
    'TRUST_PROXY',
  ],
  members: [
    'AUTH_BASE_URL',
    'AUTH_INTERNAL_TOKEN',
    'AVATAR_PHOTO_URL_PREFIXES',
    'CATALOG_BASE_URL',
    'CATALOG_INTERNAL_TOKEN',
    'DATABASE_POOL_MAX',
    'DATABASE_URL',
    'FUNNEL_URL',
    'GATEWAY_HMAC_SECRET',
    'GATEWAY_URL',
    'HUB_BASE_URL',
    'INTERNAL_API_TOKEN',
    'KIDS_COMMUNITY_URL',
    'MEMBERS_HMAC_SECRET',
    'NODE_ENV',
    'PORT',
  ],
  'helpdesk-app': [
    'GATEWAY_URL',
    'HOSTNAME',
    'JWT_AUDIENCE',
    'JWT_ISSUER',
    'JWT_JWKS_URL',
    'NODE_ENV',
    'PORT',
  ],
  admin: [
    'COMMUNITY_URL',
    'ELEVENLABS_API_KEY',
    'ELEVENLABS_VOICE_ID',
    'GATEWAY_URL',
    'JWT_AUDIENCE',
    'JWT_ISSUER',
    'JWT_JWKS_URL',
    'KIDS_COMMUNITY_URL',
    'NODE_ENV',
    'R2_ACCESS_KEY_ID',
    'R2_ACCOUNT_ID',
    'R2_BUCKET',
    'R2_PRIVATE_BUCKET',
    'R2_PUBLIC_URL',
    'R2_SECRET_ACCESS_KEY',
    'STUDIO_PRO_RUNTIME_TOKEN',
    'STUDIO_PRO_RUNTIME_URL',
    'VIMEO_ACCESS_TOKEN',
    'VIMEO_FOLDER_ID',
    'VIMEO_WHITELIST_DOMAINS',
  ],
  'community-kids': [
    'APP_PUBLIC_URL',
    'CREATION_CLEANUP_CRON_SECRET',
    'GATEWAY_HMAC_SECRET',
    'GATEWAY_URL',
    'JWT_AUDIENCE',
    'JWT_ISSUER',
    'JWT_JWKS_URL',
    'MEMBER_SHELL_HMAC_SECRET',
    'NODE_ENV',
    'OPENROUTER_API_KEY',
    'OPENROUTER_PENSA_MODEL',
    'OPENROUTER_ZAPPY_MODEL',
    'PARENT_GATE_HMAC_SECRET',
    'PORT',
    'R2_ACCESS_KEY_ID',
    'R2_ACCOUNT_ID',
    'R2_BUCKET',
    'R2_PRIVATE_BUCKET',
    'R2_PUBLIC_URL',
    'R2_SECRET_ACCESS_KEY',
    'R2_UGC_BUCKET',
    'STUDIO_PRO_RUNTIME_TOKEN',
    'STUDIO_PRO_RUNTIME_URL',
    'ZAPPY_ENABLED',
  ],
}

const extra: Record<string, Record<string, string[]>> = {
  staging: {
    hub: [],
    catalog: [],
    referrals: [],
    payments: [],
    'api-gateway': [],
    fiscal: [],
    marketing: [
      'GATEWAY_URL',
      'MARKETING_APP_URL',
      'MARKETING_TOKEN_ENC_KEY',
      'OAUTH_PUBLIC_BASE_URL',
    ],
    auth: [],
    messaging: [],
    'marketing-app': [],
    helpdesk: [],
    'evolution-api': [],
    community: [],
    funnel: [],
    members: [],
    'helpdesk-app': [],
    admin: [],
    'community-kids': ['NEXT_PUBLIC_KIDS_CHEST_RIVE_URL'],
  },
  production: {
    hub: ['RELEASE_MAINTENANCE_MODE', 'SENTRY_DSN'],
    catalog: ['SENTRY_DSN'],
    referrals: ['SCHOLARSHIP_COURSE_SLUG'],
    payments: ['SENTRY_DSN', 'WEBHOOK_DELIVERY_MAX_ATTEMPTS'],
    'api-gateway': ['SENTRY_DSN'],
    fiscal: ['SENTRY_DSN'],
    marketing: [],
    auth: ['SENTRY_DSN'],
    messaging: ['ALERT_EMAIL', 'SENTRY_DSN'],
    'marketing-app': [],
    helpdesk: [],
    'evolution-api': [],
    community: ['RELEASE_MAINTENANCE_MODE', 'SENTRY_DSN'],
    funnel: ['CATALOG_OFFER_SLUG', 'SENTRY_DSN'],
    members: [
      'FUNNEL_INTERNAL_TOKEN',
      'RELEASE_MAINTENANCE_MODE',
      'RELEASE_SCHEMA_STAGE',
      'SENTRY_DSN',
    ],
    'helpdesk-app': [],
    admin: ['R2_UGC_BUCKET', 'RELEASE_MAINTENANCE_MODE', 'SENTRY_DSN'],
    'community-kids': [
      'KIDS_REFORM_NOTICE_ENABLED',
      'OPENROUTER_MODEL',
      'RELEASE_MAINTENANCE_MODE',
      'SENTRY_DSN',
    ],
  },
}

export function preservedVariables(environment: string, service: string) {
  if (!common[service] || !extra[environment]) throw new Error('Ambiente ou serviço desconhecido')
  return Object.fromEntries(
    [...common[service], ...extra[environment][service]].map((key) => [key, preserve()]),
  )
}
