/**
 * Copy do Pinta, 100% em português e centralizada — sem travessão, sem jargão.
 * Texto de UI vive AQUI (os componentes só referenciam), para revisão de tom
 * num lugar só.
 */
import type { PintaTemplateId } from '../templates/catalog'
import type { PintaAssetKind } from './project'

export const COPY = {
  appName: 'Pinta',
  gallery: {
    title: 'Meus desenhos',
    subtitle: 'Crie os personagens, cenários e peças dos seus jogos.',
    create: 'Criar novo',
    empty: 'Nada por aqui ainda. Toque em "Criar novo" para começar o seu primeiro desenho!',
    emptyCta: 'Começar meu primeiro desenho',
    loading: 'Abrindo a sua galeria...',
    loadError: 'Não consegui abrir a sua galeria. Tente de novo daqui a pouco.',
    /** Veio pelo botão "Editar" do Estúdio, mas o desenho já tinha sido apagado. */
    drawingGone: 'Esse desenho não está mais aqui. Escolha outro na sua galeria.',
    retry: 'Tentar de novo',
    rename: 'Renomear',
    duplicate: 'Duplicar',
    remove: 'Apagar',
    removeConfirmTitle: 'Apagar este desenho?',
    removeConfirmBody: 'Ele vai sumir da galeria. Não dá para desfazer.',
    removeConfirm: 'Apagar',
    cancel: 'Cancelar',
    quotaFull: 'A sua galeria está cheia! Apague um desenho antigo para criar um novo.',
    downloadAll: 'Baixar tudo',
    looseSection: 'Desenhos avulsos',
    restore: 'Trazer de volta',
    restoreError: 'Não consegui ler esse arquivo. Ele é um backup do Pinta (.pinta.json)?',
    zipError: 'Não consegui montar o arquivo agora. Tente de novo.',
    restoredOne: 'Trouxe 1 desenho de volta!',
    restoredMany: (count: number) => `Trouxe ${count} desenhos de volta!`,
    restorePartial: ' Alguns ficaram de fora.',
    importImage: 'Trazer uma foto',
    importDecodeError: 'Não consegui abrir essa imagem. Tente um PNG ou JPG.',
    importDone: 'Sua imagem já está na galeria!',
  },
  importImage: {
    title: 'O que essa imagem vira?',
    asBackground: {
      emoji: '🖼️',
      title: 'Cenário de fundo',
      description: 'A imagem grande que fica atrás do jogo.',
    },
    asTileset: {
      emoji: '🧩',
      title: 'Peças do cenário',
      description: 'Corta a imagem em pecinhas para montar mapas.',
    },
    sizeTitle: 'Escolha o tamanho',
    tileSizeTitle: 'Tamanho de cada peça',
    colorsNote: 'As cores da foto viram as cores do Pinta.',
    newColors: (n: number) => (n === 1 ? '1 cor nova' : `${n} cores novas`),
    uniqueTiles: (n: number) => (n === 1 ? '1 peça' : `${n} peças`),
    tooManyTiles: 'Essa imagem tem peças demais! Tente um tamanho de peça maior.',
    detected: 'Detectei sozinho',
    preview: 'Vai ficar assim:',
    back: 'Voltar',
    next: 'Avançar',
    create: 'Trazer para a galeria',
  },
  newAsset: {
    styleTitle: 'Como você quer desenhar?',
    title: 'O que você quer criar?',
    sizeTitle: 'Qual o tamanho?',
    nameTitle: 'Qual o nome?',
    namePlaceholder: 'meu-heroi',
    nameHelp: 'Use letras minúsculas e traços. Esse nome aparece nos blocos do Estúdio.',
    nameInvalid: 'Esse nome não vai funcionar. Tente algo como "meu-heroi".',
    nameTaken: 'Você já tem um desenho com esse nome. Escolha outro.',
    back: 'Voltar',
    next: 'Avançar',
    createButton: 'Começar a desenhar',
    creating: 'Criando...',
    chooseTilesetTitle: 'Qual conjunto de peças o mapa vai usar?',
    tilesetPieces: (count: number) => (count === 1 ? '1 peça' : `${count} peças`),
    needTileset: 'Antes de criar um mapa, crie as suas "Peças do cenário".',
    forProjectPrefix: 'Desenho para o jogo',
    willLookLike: 'Vai ficar assim:',
  },
  styles: {
    pixel: {
      emoji: '👾',
      title: 'Pixel art',
      description: 'Desenhe quadradinho por quadradinho, no estilo dos jogos clássicos.',
    },
    vector: {
      emoji: '✏️',
      title: 'Vetor',
      description: 'Desenhe com formas e pincel, com linhas sempre lisinhas.',
    },
  },
  styleBadge: {
    pixel: 'Pixel',
    vector: 'Vetor',
  },
  kinds: {
    'pixel-sprite': {
      emoji: '🧍',
      title: 'Personagem',
      description: 'Um herói, bicho ou item, com animações de andar, pular e mais.',
    },
    'pixel-background': {
      emoji: '🖼️',
      title: 'Cenário de fundo',
      description: 'A imagem grande que fica atrás do seu jogo.',
    },
    tileset: {
      emoji: '🧩',
      title: 'Peças do cenário',
      description:
        'Um CONJUNTO de peças (chão, parede, decoração). Desenhe VÁRIAS peças aqui e depois monte o mapa com elas.',
    },
    tilemap: {
      emoji: '🗺️',
      title: 'Mapa',
      description: 'Monte uma fase inteira escolhendo um conjunto de peças e pintando com elas.',
    },
    'vector-sprite': {
      emoji: '🧍',
      title: 'Personagem',
      description: 'Um herói, bicho ou item feito de formas, com animações.',
    },
    'vector-background': {
      emoji: '🖼️',
      title: 'Cenário de fundo',
      description: 'A imagem grande que fica atrás do seu jogo, feita de formas.',
    },
    'vector-tileset': {
      emoji: '🧩',
      title: 'Peças do cenário',
      description:
        'Um CONJUNTO de peças feitas de formas. Desenhe VÁRIAS peças aqui e monte o mapa com elas.',
    },
  } satisfies Record<PintaAssetKind, { emoji: string; title: string; description: string }>,
  templates: {
    styleCard: {
      emoji: '✨',
      title: 'Modelos prontos',
      description: 'Comece de um desenho pronto e mude do seu jeito.',
    },
    stepTitle: 'Escolha um modelo para começar',
    items: {
      heroi: { title: 'Herói corajoso', description: 'Um personagem 16×16 que já anda.' },
      slime: { title: 'Slime saltitante', description: 'Um bichinho verde que pisca.' },
      moeda: { title: 'Moeda girando', description: 'Uma moeda com 4 quadros de giro.' },
      nave: { title: 'Nave espacial', description: 'Para jogos de atirar nas estrelas.' },
      'chao-de-grama': {
        title: 'Chão de grama',
        description: 'Peças de chão, terra, plataforma e espinho.',
      },
      'fase-plataforma': {
        title: 'Fase de plataforma',
        description: 'Um mapa pronto para explorar (já vem com as peças).',
      },
      fantasminha: { title: 'Fantasminha', description: 'Um fantasma de formas que flutua.' },
      'ceu-com-sol': { title: 'Céu com sol', description: 'Um cenário de dia, feito de formas.' },
    } satisfies Record<PintaTemplateId, { title: string; description: string }>,
  },
  sizes: {
    16: 'Pequeno',
    32: 'Médio',
    48: 'Grande',
    64: 'Gigante',
  } as Record<number, string>,
  /** Rótulos por POSIÇÃO nas listas de tamanho de cenário/desenho livre/mapa. */
  sizeScale: ['Pequeno', 'Médio', 'Grande', 'Bem grande', 'Gigante'],
  editor: {
    back: 'Voltar',
    undo: 'Desfazer',
    redo: 'Refazer',
    saved: 'Salvo',
    saving: 'Salvando…',
    saveError: 'Não consegui salvar',
    taskLinkError: 'Não consegui vincular o desenho à tarefa. Confira a internet e tente de novo.',
    taskStudioProgressError:
      'O desenho chegou ao Estúdio, mas não consegui atualizar a tarefa. Confira a internet e tente usar no Estúdio de novo.',
    download: 'Baixar',
    sendToStudio: 'Usar no Estúdio',
    zoomIn: 'Aproximar',
    zoomOut: 'Afastar',
    zoomFit: 'Ajustar',
  },
  tools: {
    pencil: 'Lápis',
    eraser: 'Borracha',
    fill: 'Balde de tinta',
    recolor: 'Trocar uma cor',
    select: 'Selecionar e mover',
    line: 'Linha',
    rect: 'Retângulo',
    ellipse: 'Círculo',
    picker: 'Conta-gotas',
    mirror: 'Espelho lado a lado',
    mirrorV: 'Espelho de cima e de baixo',
    grid: 'Grade',
    filled: 'Preencher formas',
    brushSize: 'Tamanho do traço',
    flipH: 'Espelhar na horizontal',
    flipV: 'Espelhar na vertical',
    rotate: 'Girar',
    /** As duas cores da caixa de ferramentas (esquerda × direita do mouse). */
    primaryColor: 'Cor principal',
    secondaryColor: 'Cor secundária',
    primaryHint: 'Cor principal (pinta com o botão esquerdo)',
    secondaryHint: 'Cor secundária (pinta com o botão direito)',
    swapColors: 'Trocar as duas cores',
    transparentColor: 'Transparente (apaga)',
    clear: 'Limpar tudo',
  },
  /** Barra que aparece quando há um pedaço selecionado no desenho de pixel. */
  selection: {
    bar: 'O que fazer com o pedaço selecionado',
    duplicate: 'Duplicar o pedaço',
    flipH: 'Espelhar para o outro lado',
    flipV: 'Espelhar de cabeça para baixo',
    remove: 'Apagar o pedaço',
  },
  palette: {
    title: 'Cores',
    transparent: 'Apagar (transparente)',
    switchPalette: 'Trocar paleta',
    addColor: 'Nova cor',
    addColorTitle: 'Escolher uma cor',
    add: 'Adicionar',
    colorLimit: 'Você já tem o máximo de cores neste desenho.',
    deleteColor: 'Apagar esta cor',
    deleteColorTitle: 'Apagar esta cor?',
    deleteColorBody:
      'Tudo que você pintou com ela vai ficar transparente. Quer apagar mesmo assim?',
    deleteColorConfirm: 'Apagar cor',
    baseColorLocked:
      'As cores da paleta são fixas! Você só pode apagar as cores que adicionou com o +.',
    pickColorFirst: 'Escolha uma cor primeiro para poder apagar.',
  },
  colorPicker: {
    hex: 'Código da cor',
    recent: 'Cores recentes',
  },
  layers: {
    title: 'Camadas',
    add: 'Nova camada',
    remove: 'Apagar esta camada',
    removeTitle: 'Apagar esta camada?',
    removeBody: 'Tudo o que você desenhou nela vai embora. Quer apagar mesmo assim?',
    removeConfirm: 'Apagar camada',
    lastOne: 'Todo desenho precisa de pelo menos uma camada!',
    limit: 'Este desenho já tem o máximo de camadas.',
    show: 'Mostrar',
    hide: 'Esconder',
    rename: 'Trocar o nome da camada',
    renameTitle: 'Qual vai ser o nome da camada?',
    nameLabel: 'Nome da camada',
    namePlaceholder: 'Ex.: roupa',
    save: 'Salvar o nome',
    reorder: 'Arrastar para mudar a ordem',
    moveUp: 'Subir a camada',
    moveDown: 'Descer a camada',
    /** Nome automático: "Camada 1", "Camada 2"... */
    namePrefix: 'Camada',
    hiddenWarning: 'Esta camada está escondida! Toque no olhinho para ver o que você desenhar.',
    thumbAlt: 'Desenho da camada',
  },
  animation: {
    panel: 'Prévia e animações',
    preview: 'Prévia',
    play: 'Rodar animação',
    reproduce: 'Reproduzir',
    edit: 'Editar',
    settings: 'Configurações da animação',
    pause: 'Pausar',
    speed: 'Velocidade',
    slow: 'Devagar',
    fast: 'Rápido',
    onion: 'Fantasma do quadro anterior',
    loop: 'Repetir animação',
    // Painel "Animação selecionada" (detalhes à direita).
    selected: 'Animação selecionada',
    selectedBadge: 'selecionada',
    duration: 'Duração',
    seconds: (value: string) => `${value} s`,
    speedNames: { slow: 'Devagar', normal: 'Normal', fast: 'Rápido' },
    repeatLabel: 'Repetição',
    repeatOn: 'Ligada',
    repeatOff: 'Desligada',
    smoothing: 'Suavização',
    smoothingLinear: 'Linear',
    smoothingEase: 'Suave',
    // Faixa "Spritesheet" (embaixo).
    spritesheet: 'Spritesheet',
    animationCount: (count: number) => (count === 1 ? '1 animação' : `${count} animações`),
    frameCount: (count: number) => (count === 1 ? '1 quadro' : `${count} quadros`),
    animations: 'Animações',
    addAnimation: 'Nova animação',
    renameAnimation: 'Renomear animação',
    removeAnimation: 'Apagar animação',
    duplicateAnimation: 'Duplicar animação',
    frames: 'Quadros',
    addFrame: 'Novo quadro',
    duplicateFrame: 'Duplicar quadro',
    removeFrame: 'Apagar quadro',
    moveFrameLeft: 'Mover para a esquerda',
    moveFrameRight: 'Mover para a direita',
    animationLimit: 'Você chegou ao limite de animações deste personagem.',
    frameLimit: 'Essa animação já tem o máximo de quadros.',
  },
  tiles: {
    tiles: 'Peças',
    addTile: 'Nova peça',
    duplicateTile: 'Duplicar peça',
    removeTile: 'Apagar peça',
    solid: 'Peça sólida (o personagem não atravessa)',
    // Colisão por peça (ciclo livre → sólido → plataforma)
    cycleCollision: 'Mudar a colisão da peça',
    collisionNone: 'Peça livre (o personagem atravessa)',
    collisionSolid: 'Peça sólida (o personagem não atravessa)',
    collisionPlatform: 'Peça plataforma (pisa por cima, passa por baixo)',
    tileLimit: 'Você chegou ao limite de peças.',
    blankTile:
      'Essa peça ainda está em branco! Desenhe nela em "Peças do cenário" que o mapa se pinta sozinho.',
    layers: 'Camadas',
    addLayer: 'Nova camada',
    removeLayer: 'Apagar camada',
    layerLimit: 'Este mapa já tem o máximo de camadas.',
    show: 'Mostrar',
    hide: 'Esconder',
    pickTile: 'Peças para pintar',
    missingTileset: 'Não achei as peças deste mapa. Elas podem ter sido apagadas.',
    sheetError: 'Não consegui desenhar as peças agora. Tente fechar e abrir o mapa.',
    mapGrid: 'Grade do mapa',
    tileLabel: (index: number) => `Peça ${index}`,
    layerNamePrefix: 'Camada',
    // Ferramentas novas do mapa (MapperMate)
    autoExpand: 'Crescer o mapa pintando na borda',
    autoExpandLimit: 'O mapa chegou ao tamanho máximo!',
    stampBlock: (cols: number, rows: number) => `Bloco de ${cols} × ${rows} peças`,
    stampClear: 'Voltar para uma peça só',
    copyPiece: 'Copiar pedaço',
    clearPiece: 'Apagar pedaço',
    showCollision: 'Ver as colisões do mapa',
    statusSize: (cols: number, rows: number) => `${cols} colunas × ${rows} linhas`,
    statusCell: (col: number, row: number) => `Coluna ${col} · Linha ${row}`,
    frontLayer: 'Camada da frente (aparece por cima do jogador)',
    frontBadge: 'frente',
    playMap: 'Jogar meu mapa',
  },
  vector: {
    select: 'Selecionar',
    reshape: 'Editar os pontos',
    pan: 'Mão (arrastar a tela)',
    brush: 'Pincel',
    polygon: 'Polígono',
    star: 'Estrela',
    text: 'Texto',
    fill: 'Preenchimento',
    stroke: 'Contorno',
    strokeWidth: 'Espessura do contorno',
    appearance: 'Aparência',
    swapFillStroke: 'Trocar preenchimento e contorno',
    /** Disclosure da tela estreita (cores + camadas + aparência). */
    panelsTitle: 'Cores e camadas',
    opacity: 'Quanto aparece',
    none: 'Sem cor',
    customColor: 'Cor personalizada',
    gradient: 'Degradê',
    gradientH: 'Degradê deitado',
    gradientV: 'Degradê em pé',
    gradientRadial: 'Degradê redondo (do meio)',
    gradientFrom: 'Cor do começo',
    gradientTo: 'Cor do fim',
    forward: 'Uma camada para a frente',
    backward: 'Uma camada para trás',
    toFront: 'Trazer bem para a frente',
    toBack: 'Levar bem para o fundo',
    group: 'Agrupar',
    ungroup: 'Desagrupar',
    sides: 'Lados',
    tips: 'Pontas',
    duplicate: 'Duplicar',
    remove: 'Apagar',
    textPrompt: 'O que você quer escrever?',
    textPlaceholder: 'Digite aqui...',
    add: 'Adicionar',
    rotate: 'Girar',
    shapeLimit: 'Este desenho já tem o máximo de formas.',
    svg: 'Desenho (SVG)',
  },
  /** Nomes amigáveis das cores livres do vetorial (aria/title dos swatches). */
  colorNames: {
    '#ffffff': 'branco',
    '#ff2121': 'vermelho',
    '#ff93c4': 'rosa claro',
    '#ff8135': 'laranja',
    '#fff609': 'amarelo',
    '#249ca3': 'verde água',
    '#78dc52': 'verde',
    '#003fad': 'azul escuro',
    '#87f2ff': 'azul claro',
    '#8e2ec4': 'roxo',
    '#a4839f': 'lilás',
    '#5c406c': 'roxo escuro',
    '#e5cdc4': 'bege',
    '#91463d': 'marrom',
    '#000000': 'preto',
  } as Record<string, string>,
  exportDialog: {
    title: 'Baixar',
    currentFrame: 'Quadro atual (PNG)',
    currentFrameSvg: 'Quadro atual (SVG)',
    image: 'Imagem (PNG)',
    spritesheet: 'Folha de animações (PNG)',
    spritesheetSvg: 'Folha de animações (SVG)',
    spritesheetJson: 'Receita das animações (para o Estúdio)',
    tilesetSheet: 'Folha de peças (PNG)',
    tilesetSheetSvg: 'Folha de peças (SVG)',
    tilemapImage: 'Imagem do mapa (PNG)',
    tilemapJson: 'Mapa completo (para o Estúdio)',
    copyGrid: 'Copiar a grade do mapa',
    gridCopied: 'Grade copiada! Cole no bloco de mapa do Estúdio.',
    copyError: 'Não consegui copiar. Tente baixar o arquivo.',
    recipeTitle: 'Para usar no Estúdio:',
    scale: 'Tamanho da imagem',
    scaleVectorHint: 'Pode ampliar sem medo: desenho de formas não perde qualidade.',
    scaleStudioWarning:
      'Para usar no Estúdio, baixe no tamanho ×1 (o tamanho de verdade do desenho).',
    tilemapGridFile: 'Baixar a grade (arquivo de texto)',
    preparing: 'Preparando...',
    close: 'Fechar',
  },
  sendToStudio: {
    success: 'Pronto! Seu desenho já está no Estúdio, em "Meus desenhos".',
    successLocked: 'Salvei! Quando o Estúdio for liberado, seu desenho vai estar lá.',
    error: 'Não consegui enviar agora. Tente de novo daqui a pouco.',
    tooBig: 'Esse desenho ficou grande demais para o Estúdio. Tente um tamanho menor.',
    openStudio: 'Abrir o Estúdio',
    sending: 'Enviando...',
    /** Confirmação do reenvio automático (a criança abriu o desenho pelo jogo). */
    resynced: 'Atualizado no Estúdio',
    // Mapa: viaja como ASSET completo (grade + peças embutidas), não mais só a
    // grade no clipboard — o caminho de texto continua no "Baixar".
    mapSuccess: 'Seu mapa já está no Estúdio! Procure o bloco "Criar mapa do meu desenho".',
    mapSuccessLocked: 'Salvei! Quando o Estúdio for liberado, seu mapa vai estar lá.',
    playSuccess: 'Pronto! Seu mapa virou um jogo no Estúdio. É só apertar Jogar!',
  },
  coach: {
    gotIt: 'Entendi!',
    pixel: {
      title: 'Dicas rápidas',
      tips: [
        'O Lápis desenha e a Borracha apaga.',
        'O Balde de tinta pinta um espaço todo de uma vez.',
        'Com "Selecionar", marque um pedaço e use Duplicar e Espelhar para fazer o outro lado.',
        'Rode a bolinha do mouse para aproximar e afastar.',
        'Teclas rápidas: P lápis, E borracha, G balde, M selecionar.',
        'O foguete leva o seu desenho para o Estúdio.',
      ],
    },
    vector: {
      title: 'Dicas rápidas',
      tips: [
        'Escolha uma forma ou o Pincel e arraste no palco.',
        '"Selecionar" deixa mover, girar e trocar a cor.',
        '"Editar os pontos" muda o contorno; o Degradê mistura duas cores.',
        'Rode a bolinha do mouse para aproximar e afastar.',
        'Teclas rápidas: V selecionar, B pincel, H mão, T texto.',
      ],
    },
    map: {
      title: 'Dicas rápidas',
      tips: [
        'Escolha uma peça no canto e pinte na grade.',
        'Arraste sobre as peças para pegar um bloco inteiro e carimbar.',
        'A Linha e o Retângulo pintam vários tiles de uma vez.',
        'Rode a bolinha do mouse para aproximar e afastar.',
        'Teclas rápidas: P lápis, E borracha, G balde, M selecionar.',
        'O foguete copia a grade para o bloco de mapa do Estúdio.',
      ],
    },
  },
  toast: {
    downloadReady: 'Baixado! Procure na pasta de downloads.',
    downloadError: 'Não consegui gerar a imagem agora. Tente de novo.',
  },
  // Rótulos de acessibilidade (aria-label) + defaults do modelo que aparecem na
  // UI — centralizados aqui p/ i18n e p/ não repetir literais soltos nas telas.
  a11y: {
    drawArea: 'Área de desenho',
    tools: 'Ferramentas',
    close: 'Fechar',
    colorLabel: (index: number) => `Cor ${index}`,
    frameLabel: (number: number) => `Quadro ${number}`,
    sheetFrame: (name: string, number: number) => `${name}: quadro ${number}`,
    step: (current: number, total: number) => `Passo ${current} de ${total}`,
    openAsset: (label: string) => `Abrir ${label}`,
    defaultLayer: 'Chão',
    defaultAnimation: 'animação',
  },
} as const
