/**
 * Copy do Pinta, 100% em português e centralizada — sem travessão, sem jargão.
 * Texto de UI vive AQUI (os componentes só referenciam), para revisão de tom
 * num lugar só.
 */
import type { PintaTemplateId } from '../templates/catalog'
import type { PintaAssetKind } from './project'

export const COPY = {
  appName: 'Pinta',
  gallery: {
    title: 'Meus desenhos',
    subtitle: 'Crie os personagens, cenários e peças dos seus jogos.',
    create: 'Criar novo',
    empty: 'Nada por aqui ainda. Toque em "Criar novo" para começar o seu primeiro desenho!',
    emptyCta: 'Começar meu primeiro desenho',
    loading: 'Abrindo a sua galeria...',
    loadError: 'Não consegui abrir a sua galeria. Tente de novo daqui a pouco.',
    /** Bloco de aula: não há galeria por trás, então a copy fala do DESENHO. */
    lessonLoadError: 'Não consegui abrir o seu desenho. Recarregue a página daqui a pouco.',
    lessonBrokenAsset: 'Esse desenho veio com algum problema. Avise o seu professor.',
    /** Veio pelo botão "Editar" do Estúdio, mas o desenho já tinha sido apagado. */
    drawingGone: 'Esse desenho não está mais aqui. Escolha outro na sua galeria.',
    retry: 'Tentar de novo',
    rename: 'Renomear',
    duplicate: 'Duplicar',
    remove: 'Apagar',
    removeConfirmTitle: 'Apagar este desenho?',
    removeConfirmBody: 'Ele vai sumir da galeria. Não dá para desfazer.',
    removeConfirm: 'Apagar',
    removeTilesetTitle: 'Estas peças estão sendo usadas',
    removeTilesetBody:
      'Antes de apagar este conjunto, apague os mapas abaixo ou crie versões deles com outras peças:',
    tilesetInUse: 'Estas peças ainda são usadas por um ou mais mapas.',
    cancel: 'Cancelar',
    storageBudget:
      'Sua galeria chegou ao limite de 32 MB. Apague um desenho ou uma figura grande para continuar salvando.',
    downloadAll: 'Baixar tudo',
    /** Busca da galeria (sem teto de desenhos, ela é o que mantém a galeria navegável). */
    search: 'Buscar desenho',
    searchPlaceholder: 'Buscar por nome, tipo ou jogo',
    searchClear: 'Limpar busca',
    searchClearAll: 'Limpar busca e filtros',
    syncing: 'Buscando na sua conta os desenhos que ainda não chegaram…',
    searchEmpty: 'Nenhum desenho combina com essa busca.',
    /** Filtros da galeria (chips): estilo e tipo. */
    filterStyle: 'Estilo',
    filterRole: 'Tipo',
    filterAll: 'Todos',
    filterRoles: {
      sprite: 'Personagem',
      background: 'Cenário',
      tileset: 'Peças',
      tilemap: 'Mapa',
    },
    /**
     * Nomes acessíveis dos chips (leitor de tela): distintos dos cartões "Pixel art"/"Vetor" do
     * "Criar novo", que ficam na mesma página atrás do modal.
     */
    filterAria: {
      allStyles: 'Mostrar todos os estilos',
      pixel: 'Mostrar só pixel art',
      vector: 'Mostrar só vetor',
      allRoles: 'Mostrar todos os tipos',
      sprite: 'Mostrar só personagens',
      background: 'Mostrar só cenários',
      tileset: 'Mostrar só peças',
      tilemap: 'Mostrar só mapas',
    },
    searchCount: (shown: number, total: number) =>
      shown === 1 ? `1 desenho de ${total}` : `${shown} desenhos de ${total}`,
    looseSection: 'Desenhos avulsos',
    restore: 'Trazer de volta',
    restoring: 'Trazendo de volta…',
    restoreError: 'Não consegui ler esse arquivo. Ele é um arquivo do Pinta (.zip ou .pinta.json)?',
    restoreTooLarge: 'Esse backup é grande demais. Escolha um arquivo de até 32 MB.',
    restoreZipMissing: 'Esse ZIP não tem a galeria do Pinta.',
    restoreZipDuplicate: 'Esse ZIP tem mais de uma galeria do Pinta e não é seguro restaurá-lo.',
    restoreMissingTileset: 'Não encontrei as peças deste mapa, então ele ficou de fora.',
    zipError: 'Não consegui montar o arquivo agora. Tente de novo.',
    restoredOne: 'Trouxe 1 desenho de volta!',
    restoredMany: (count: number) => `Trouxe ${count} desenhos de volta!`,
    restoredMapBundle: 'Trouxe o mapa e as peças de volta!',
    restorePartial: ' Alguns ficaram de fora.',
    importImage: 'Trazer uma foto',
    importDecodeError: 'Não consegui abrir essa imagem. Tente um PNG ou JPG.',
    importTooLarge: 'Essa imagem é grande demais. Escolha um arquivo de até 20 MB.',
    importDone: 'Sua imagem já está na galeria!',
  },
  importImage: {
    loading: 'Abrindo a foto...',
    title: 'O que essa imagem vira?',
    asSprite: {
      emoji: '🦸',
      title: 'Personagem',
      description: 'A imagem inteira vira um personagem, pronto para animar.',
    },
    asBackground: {
      emoji: '🖼️',
      title: 'Cenário de fundo',
      description: 'A imagem grande que fica atrás do jogo.',
    },
    asTileset: {
      emoji: '🧩',
      title: 'Peças do cenário',
      description: 'Corta a imagem em pecinhas para montar mapas.',
    },
    sizeTitle: 'Escolha o tamanho',
    spriteSizeTitle: 'Tamanho do quadro do personagem',
    spriteFitNote: 'A imagem entra inteira, sem cortar. O que sobrar fica transparente.',
    tileSizeTitle: 'Tamanho de cada peça',
    colorsNote: 'As cores da foto viram as cores do Pinta.',
    newColors: (n: number) => (n === 1 ? '1 cor nova' : `${n} cores novas`),
    uniqueTiles: (n: number) => (n === 1 ? '1 peça' : `${n} peças`),
    tooManyTiles: 'Essa imagem tem peças demais! Tente um tamanho de peça maior.',
    detected: 'Detectei sozinho',
    preview: 'Vai ficar assim:',
    back: 'Voltar',
    next: 'Avançar',
    create: 'Trazer para a galeria',
  },
  newAsset: {
    styleTitle: 'Como você quer desenhar?',
    title: 'O que você quer criar?',
    sizeTitle: 'Qual o tamanho?',
    nameTitle: 'Qual o nome?',
    namePlaceholder: 'meu-heroi',
    nameHelp: 'Use letras minúsculas e traços. Esse nome aparece nos blocos do Estúdio.',
    nameInvalid: 'Esse nome não vai funcionar. Tente algo como "meu-heroi".',
    nameTaken: 'Você já tem um desenho com esse nome. Escolha outro.',
    back: 'Voltar',
    next: 'Avançar',
    createButton: 'Começar a desenhar',
    creating: 'Criando...',
    chooseTilesetTitle: 'Qual conjunto de peças o mapa vai usar?',
    tilesetPieces: (count: number) => (count === 1 ? '1 peça' : `${count} peças`),
    needTileset: 'Antes de criar um mapa, crie as suas "Peças do cenário".',
    forProjectPrefix: 'Desenho para o jogo',
    willLookLike: 'Vai ficar assim:',
    customSize: {
      card: 'Personalizado',
      cardDetail: 'Você escolhe os números',
      width: 'Largura',
      height: 'Altura',
      frame: 'Tamanho do quadro',
      cols: 'Colunas',
      rows: 'Linhas',
      help: (min: number, max: number) => `Escolha números de ${min} até ${max}.`,
      rangeError: (label: string, min: number, max: number) =>
        `${label} precisa ser um número de ${min} até ${max}.`,
    },
  },
  styles: {
    pixel: {
      emoji: '👾',
      title: 'Pixel art',
      description: 'Desenhe quadradinho por quadradinho, no estilo dos jogos clássicos.',
    },
    vector: {
      emoji: '✏️',
      title: 'Vetor',
      description: 'Desenhe com formas e pincel, com linhas sempre lisinhas.',
    },
  },
  styleBadge: {
    pixel: 'Pixel',
    vector: 'Vetor',
  },
  kinds: {
    'pixel-sprite': {
      emoji: '🧍',
      title: 'Personagem',
      description: 'Um herói, bicho ou item, com animações de andar, pular e mais.',
    },
    'pixel-background': {
      emoji: '🖼️',
      title: 'Cenário de fundo',
      description: 'A imagem grande que fica atrás do seu jogo.',
    },
    tileset: {
      emoji: '🧩',
      title: 'Peças do cenário',
      description:
        'Um CONJUNTO de peças (chão, parede, decoração). Desenhe VÁRIAS peças aqui e depois monte o mapa com elas.',
    },
    tilemap: {
      emoji: '🗺️',
      title: 'Mapa',
      description: 'Monte uma fase inteira escolhendo um conjunto de peças e pintando com elas.',
    },
    'vector-sprite': {
      emoji: '🧍',
      title: 'Personagem',
      description: 'Um herói, bicho ou item feito de formas, com animações.',
    },
    'vector-background': {
      emoji: '🖼️',
      title: 'Cenário de fundo',
      description: 'A imagem grande que fica atrás do seu jogo, feita de formas.',
    },
    'vector-tileset': {
      emoji: '🧩',
      title: 'Peças do cenário',
      description:
        'Um CONJUNTO de peças feitas de formas. Desenhe VÁRIAS peças aqui e monte o mapa com elas.',
    },
  } satisfies Record<PintaAssetKind, { emoji: string; title: string; description: string }>,
  templates: {
    styleCard: {
      emoji: '✨',
      title: 'Modelos prontos',
      description: 'Comece de um desenho pronto e mude do seu jeito.',
    },
    stepTitle: 'Escolha um modelo para começar',
    items: {
      heroi: { title: 'Herói corajoso', description: 'Um personagem 16×16 que já anda.' },
      slime: { title: 'Slime saltitante', description: 'Um bichinho verde que pisca.' },
      moeda: { title: 'Moeda girando', description: 'Uma moeda com 4 quadros de giro.' },
      nave: { title: 'Nave espacial', description: 'Para jogos de atirar nas estrelas.' },
      'chao-de-grama': {
        title: 'Chão de grama',
        description: 'Peças de chão, terra, plataforma e espinho.',
      },
      'fase-plataforma': {
        title: 'Fase de plataforma',
        description: 'Um mapa pronto para explorar (já vem com as peças).',
      },
      fantasminha: { title: 'Fantasminha', description: 'Um fantasma de formas que flutua.' },
      'ceu-com-sol': { title: 'Céu com sol', description: 'Um cenário de dia, feito de formas.' },
    } satisfies Record<PintaTemplateId, { title: string; description: string }>,
  },
  sizes: {
    16: 'Pequeno',
    32: 'Médio',
    48: 'Grande',
    64: 'Gigante',
  } as Record<number, string>,
  /** Rótulos por POSIÇÃO nas listas de tamanho de cenário/desenho livre/mapa. */
  sizeScale: ['Pequeno', 'Médio', 'Grande', 'Bem grande', 'Gigante'],
  editor: {
    back: 'Voltar',
    undo: 'Desfazer',
    redo: 'Refazer',
    saved: 'Salvo',
    saving: 'Salvando…',
    saveError: 'Não consegui salvar',
    taskLinkError: 'Não consegui vincular o desenho à tarefa. Confira a internet e tente de novo.',
    taskStudioProgressError:
      'O desenho chegou ao Estúdio, mas não consegui atualizar a tarefa. Confira a internet e tente usar no Estúdio de novo.',
    download: 'Baixar',
    sendToStudio: 'Usar no Estúdio',
    zoomIn: 'Aproximar',
    zoomOut: 'Afastar',
    zoomFit: 'Ajustar',
    resize: {
      /** O botão mostra o tamanho de agora: "Tamanho: 128 x 32". */
      button: (width: number, height: number) => `Tamanho: ${width} x ${height}`,
      title: 'Mudar o tamanho do desenho',
      helpPixels: 'O desenho continua igual e fica no meio do novo tamanho.',
      helpCells: 'O mapa continua igual e fica no meio do novo tamanho.',
      willCut: 'Diminuir corta o que ficar de fora. Dá para desfazer com Ctrl+Z.',
      apply: 'Mudar o tamanho',
      cancel: 'Agora não',
      done: 'Pronto, o tamanho mudou',
    },
  },
  tools: {
    pencil: 'Lápis',
    eraser: 'Borracha',
    fill: 'Balde de tinta',
    recolor: 'Trocar uma cor',
    select: 'Selecionar e mover',
    line: 'Linha',
    rect: 'Retângulo',
    ellipse: 'Círculo',
    picker: 'Conta-gotas',
    mirror: 'Espelho lado a lado',
    mirrorV: 'Espelho de cima e de baixo',
    grid: 'Grade',
    filled: 'Preencher formas',
    brushSize: 'Tamanho do traço',
    flipH: 'Espelhar na horizontal',
    flipV: 'Espelhar na vertical',
    rotate: 'Girar',
    /** As duas cores da caixa de ferramentas (esquerda × direita do mouse). */
    primaryColor: 'Cor principal',
    secondaryColor: 'Cor secundária',
    primaryHint: 'Cor principal (pinta com o botão esquerdo)',
    secondaryHint: 'Cor secundária (pinta com o botão direito)',
    swapColors: 'Trocar as duas cores',
    transparentColor: 'Transparente (apaga)',
    clear: 'Limpar tudo',
  },
  /** Barra que aparece quando há um pedaço selecionado no desenho de pixel. */
  selection: {
    bar: 'O que fazer com o pedaço selecionado',
    duplicate: 'Duplicar o pedaço',
    flipH: 'Espelhar para o outro lado',
    flipV: 'Espelhar de cabeça para baixo',
    remove: 'Apagar o pedaço',
  },
  /** Janela "Atalhos" + rótulos do catálogo (`core/shortcuts.ts`). */
  shortcuts: {
    button: 'Atalhos',
    title: 'Atalhos do teclado',
    intro:
      'Os mesmos atalhos dos programas de desenho de gente grande. No Mac, use Cmd no lugar de Ctrl.',
    toolsSection: 'Ferramentas',
    toolHint: 'Só a letra, sem Ctrl.',
    close: 'Entendi',
    sections: {
      edit: 'Editar',
      select: 'Selecionar',
      arrange: 'Organizar',
      view: 'Ver',
      frames: 'Quadros da animação',
      layers: 'Camadas',
      help: 'Ajuda',
    },
    labels: {
      undo: 'Desfazer',
      redo: 'Refazer',
      copy: 'Copiar o selecionado',
      cut: 'Recortar o pedaço',
      paste: 'Colar',
      duplicate: 'Duplicar o pedaço',
      duplicateShapes: 'Duplicar as formas selecionadas',
      delete: 'Apagar o selecionado',
      swapColors: 'Trocar a cor principal com a secundária',
      swapFillStroke: 'Trocar preenchimento e contorno',
      flipFrameH: 'Espelhar o quadro para o outro lado',
      flipFrameV: 'Espelhar o quadro de cabeça para baixo',
      rotateFrame: 'Girar o quadro',
      flipShapesH: 'Espelhar a seleção para o outro lado',
      flipShapesV: 'Espelhar a seleção de cabeça para baixo',
      selectAll: 'Selecionar tudo',
      deselect: 'Soltar a seleção',
      deselectShapes: 'Soltar a seleção',
      nudge: 'Mover a seleção 1 pixel',
      nudgeFar: 'Mover a seleção 10 pixels',
      group: 'Agrupar',
      ungroup: 'Desagrupar',
      forward: 'Uma camada para a frente',
      backward: 'Uma camada para trás',
      toFront: 'Bem para a frente',
      toBack: 'Bem para o fundo',
      lock: 'Trancar a seleção (sem nada selecionado: destrancar tudo)',
      hide: 'Esconder a seleção (sem nada selecionado: mostrar tudo)',
      zoomIn: 'Aproximar',
      zoomOut: 'Afastar',
      zoomReset: 'Zoom normal',
      zoomFit: 'Ajustar na tela',
      grid: 'Mostrar ou esconder a grade',
      mirrorH: 'Espelho lado a lado (ligar/desligar)',
      mirrorV: 'Espelho de cima e de baixo (ligar/desligar)',
      onion: 'Fantasma do quadro anterior (ligar/desligar)',
      pan: 'Segurar para arrastar a tela (Mão)',
      nextFrame: 'Quadro seguinte',
      prevFrame: 'Quadro anterior',
      addFrame: 'Novo quadro',
      duplicateFrame: 'Duplicar o quadro',
      playPause: 'Reproduzir ou pausar a prévia',
      addLayer: 'Nova camada',
      help: 'Abrir esta janela',
    },
  },
  /** Copiar e colar entre desenhos (área de transferência do aplicativo). */
  clipboard: {
    vectorIntoPixel:
      'Formas de vetor não entram na pixel art. Cole num desenho de vetor, ou desenhe por cima.',
    biggerThanDrawing:
      'O pedaço colado é maior que este desenho. O que passar da borda fica de fora.',
    nothingToSelect: 'Não tem nada pintado nesta camada para selecionar ainda.',
    figureUnavailable:
      'Não consegui transformar essa pixel art em figura aqui. Tente um pedaço menor.',
  },
  palette: {
    title: 'Cores',
    transparent: 'Apagar (transparente)',
    switchPalette: 'Trocar paleta',
    addColor: 'Nova cor',
    addColorTitle: 'Escolher uma cor',
    add: 'Adicionar',
    colorLimit: 'Você já tem o máximo de cores neste desenho.',
    deleteColor: 'Apagar esta cor',
    deleteColorTitle: 'Apagar esta cor?',
    deleteColorBody:
      'Tudo que você pintou com ela vai ficar transparente. Quer apagar mesmo assim?',
    deleteColorConfirm: 'Apagar cor',
    baseColorLocked:
      'As cores da paleta são fixas! Você só pode apagar as cores que adicionou com o +.',
    pickColorFirst: 'Escolha uma cor primeiro para poder apagar.',
  },
  colorPicker: {
    hex: 'Código da cor',
    recent: 'Cores recentes',
    apply: 'Aplicar',
  },
  layers: {
    title: 'Camadas',
    add: 'Nova camada',
    remove: 'Apagar esta camada',
    removeTitle: 'Apagar esta camada?',
    removeBody: 'Tudo o que você desenhou nela vai embora. Quer apagar mesmo assim?',
    removeConfirm: 'Apagar camada',
    lastOne: 'Todo desenho precisa de pelo menos uma camada!',
    limit: 'Este desenho já tem o máximo de camadas.',
    show: 'Mostrar',
    hide: 'Esconder',
    rename: 'Trocar o nome da camada',
    renameTitle: 'Qual vai ser o nome da camada?',
    nameLabel: 'Nome da camada',
    namePlaceholder: 'Ex.: roupa',
    save: 'Salvar o nome',
    reorder: 'Arrastar para mudar a ordem',
    reorderShape: 'Mudar a ordem da forma',
    /** Alça agrupada: movimento fino sobre irmã; grupo inteiro sobre externa. */
    reorderGroup: 'Mudar a ordem da forma ou do grupo',
    moveUp: 'Subir a camada',
    moveDown: 'Descer a camada',
    /** Nome automático: "Camada 1", "Camada 2"... */
    namePrefix: 'Camada',
    hiddenWarning: 'Esta camada está escondida! Toque no olhinho para ver o que você desenhar.',
    /** Cadeado: prefixo + nome da camada/forma, como o show/hide. */
    lock: 'Trancar',
    unlock: 'Destrancar',
    lockedWarning: 'Esta camada está trancada! Toque no cadeado para poder desenhar nela.',
    lockedShapeWarning: 'Essa forma está trancada! Toque no cadeado da camada para mudar ela.',
    lockedDelete: 'Esta camada está trancada! Destranque no cadeado para poder apagar.',
    lockedTransform:
      'Tem camada trancada neste desenho! Destranque os cadeados para virar ou girar o quadro.',
    thumbAlt: 'Desenho da camada',
  },
  animation: {
    panel: 'Prévia e animações',
    preview: 'Prévia',
    reproduce: 'Reproduzir',
    edit: 'Editar',
    settings: 'Configurações da animação',
    speed: 'Velocidade',
    slow: 'Devagar',
    fast: 'Rápido',
    onion: 'Fantasma do quadro anterior',
    // Painel "Animação selecionada" (detalhes à direita).
    selected: 'Animação selecionada',
    selectedBadge: 'selecionada',
    duration: 'Duração',
    seconds: (value: string) => `${value} s`,
    speedNames: { slow: 'Devagar', normal: 'Normal', fast: 'Rápido' },
    repeatLabel: 'Repetição',
    repeatOn: 'Ligada',
    repeatOff: 'Desligada',
    smoothing: 'Suavização',
    smoothingLinear: 'Linear',
    smoothingEase: 'Suave',
    // Faixa "Spritesheet" (embaixo).
    spritesheet: 'Spritesheet',
    animationCount: (count: number) => (count === 1 ? '1 animação' : `${count} animações`),
    frameCount: (count: number) => (count === 1 ? '1 quadro' : `${count} quadros`),
    addAnimation: 'Nova animação',
    renameAnimation: 'Renomear animação',
    removeAnimation: 'Apagar animação',
    duplicateAnimation: 'Duplicar animação',
    addFrame: 'Novo quadro',
    duplicateFrame: 'Duplicar quadro',
    removeFrame: 'Apagar quadro',
    moveFrameLeft: 'Mover para a esquerda',
    moveFrameRight: 'Mover para a direita',
    animationLimit: 'Você chegou ao limite de animações deste personagem.',
    frameLimit: 'Essa animação já tem o máximo de quadros.',
    expandTimeline: 'Expandir timeline',
    compactTimeline: 'Compactar timeline',
  },
  panel: {
    expand: (title: string) => `Mostrar ${title}`,
    collapse: (title: string) => `Recolher ${title}`,
  },
  tiles: {
    tiles: 'Peças',
    addTile: 'Nova peça',
    duplicateTile: 'Duplicar peça',
    removeTile: 'Apagar peça',
    solid: 'Peça sólida (o personagem não atravessa)',
    // Colisão por peça (ciclo livre → sólido → plataforma)
    cycleCollision: 'Mudar a colisão da peça',
    collisionNone: 'Peça livre (o personagem atravessa)',
    collisionSolid: 'Peça sólida (o personagem não atravessa)',
    collisionPlatform: 'Peça plataforma (pisa por cima, passa por baixo)',
    tileLimit: 'Você chegou ao limite de peças.',
    blankTile:
      'Essa peça ainda está em branco! Desenhe nela em "Peças do cenário" que o mapa se pinta sozinho.',
    layers: 'Camadas',
    addLayer: 'Nova camada',
    removeLayer: 'Apagar camada',
    layerLimit: 'Este mapa já tem o máximo de camadas.',
    show: 'Mostrar',
    hide: 'Esconder',
    pickTile: 'Peças para pintar',
    missingTileset: 'Não achei as peças deste mapa. Elas podem ter sido apagadas.',
    sheetError: 'Não consegui desenhar as peças agora. Tente fechar e abrir o mapa.',
    mapGrid: 'Grade do mapa',
    tileLabel: (index: number) => `Peça ${index}`,
    layerNamePrefix: 'Camada',
    // Ferramentas novas do mapa (MapperMate)
    autoExpand: 'Crescer o mapa pintando na borda',
    autoExpandLimit: 'O mapa chegou ao tamanho máximo!',
    stampBlock: (cols: number, rows: number) => `Bloco de ${cols} × ${rows} peças`,
    stampClear: 'Voltar para uma peça só',
    copyPiece: 'Copiar pedaço',
    clearPiece: 'Apagar pedaço',
    showCollision: 'Ver as colisões do mapa',
    statusSize: (cols: number, rows: number) => `${cols} colunas × ${rows} linhas`,
    statusCell: (col: number, row: number) => `Coluna ${col} · Linha ${row}`,
    frontLayer: 'Camada da frente (aparece por cima do jogador)',
    frontBadge: 'frente',
    playMap: 'Jogar meu mapa',
  },
  vector: {
    select: 'Selecionar',
    reshape: 'Editar os pontos',
    pan: 'Mão (arrastar a tela)',
    brush: 'Pincel',
    polygon: 'Polígono',
    star: 'Estrela',
    text: 'Texto',
    fill: 'Preenchimento',
    stroke: 'Contorno',
    strokeWidth: 'Espessura do contorno',
    appearance: 'Aparência',
    swapFillStroke: 'Trocar preenchimento e contorno',
    /** Disclosure da tela estreita (cores + camadas + aparência). */
    panelsTitle: 'Cores e camadas',
    /**
     * Ações da seleção. O MESMO conjunto serve a faixa colada na barra de cima
     * (desktop) e a barra flutuante sobre o palco (toque) — as duas nunca
     * aparecem juntas, então não há rótulo ambíguo.
     */
    selectionBar: 'O que fazer com as formas selecionadas',
    selDuplicate: 'Duplicar a seleção',
    selFlipH: 'Espelhar a seleção para o lado',
    selFlipV: 'Espelhar a seleção de cabeça para baixo',
    selGroup: 'Agrupar a seleção',
    selUngroup: 'Desagrupar a seleção',
    selRemove: 'Apagar a seleção',
    /**
     * MISTURAR formas (o pathfinder do Illustrator). Ficam no bloco `sel*`
     * porque são ações da faixa da seleção.
     *
     * ⭐ Os rótulos são de CRIANÇA, não os termos do ramo (decisão dela): o
     * ícone já é a linguagem universal de quem conhece, e quem não conhece
     * aprende pela frase. O par "ficar só com" / "tirar" o MESMO pedaço é lido
     * junto de propósito.
     *
     * "Virar uma forma só" também vai para a barra flutuante do TOQUE; as
     * outras três não cabem em 375px e pedem enxergar quem está na frente.
     */
    pathfinderTitle: 'Misturar',
    selUnite: 'Virar uma forma só',
    selMinusFront: 'Tirar a forma da frente',
    selIntersect: 'Ficar só com o pedaço em comum',
    selExclude: 'Tirar o pedaço em comum',
    /** Recusas da mistura: cada uma diz o que houve E o que fazer a seguir. */
    pathfinderNeedsTwo: 'Escolha duas formas fechadas, como um quadrado ou um círculo.',
    pathfinderSkips: 'Linhas, textos e figuras não entram na mistura. Escolha só formas fechadas.',
    pathfinderOpenPath: 'Este traço está aberto. Feche ele antes de misturar.',
    pathfinderBadPath:
      'Este traço veio num formato que eu não sei ler, então não dá para misturar.',
    pathfinderApart: 'Estas formas não se encostam. Ponha uma em cima da outra para misturar.',
    pathfinderEmpty: 'Assim não sobra nada. Tente com as formas mais em cima uma da outra.',
    pathfinderTooBig: 'Este desenho ficou grande demais para misturar.',
    pathfinderFailed: 'Não consegui misturar essas formas. Tente mexer um pouquinho nelas.',
    /**
     * Ações do modo "Editar os pontos". Moram no MESMO lugar das de cima (a
     * faixa troca de conteúdo com a ferramenta), então valem a mesma regra: um
     * rótulo só, servindo desktop e toque.
     */
    nodeBar: 'O que fazer com os pontos',
    nodeRemove: 'Apagar os pontos escolhidos',
    nodeClose: 'Fechar o caminho',
    nodeOpen: 'Abrir o caminho',
    /** Com UM ponto escolhido a tesoura age ALI. Rótulos separados de propósito:
     *  "abrir o caminho" tira o trecho que fechava, "abrir neste ponto" preserva
     *  o desenho inteiro e só corta a emenda. */
    nodeOpenHere: 'Abrir o caminho neste ponto',
    nodeCut: 'Cortar em dois neste ponto',
    nodeCutOneOnly: 'Escolha um ponto só para cortar aqui.',
    nodeCutEndpoint: 'Este ponto é uma ponta do traço. Escolha um ponto do meio para cortar.',
    nodeCutDone: 'Virou dois traços.',
    nodeCutTooBig: 'Este desenho está grande demais para cortar aqui.',
    nodeHint: 'Toque no traço para acrescentar um ponto',
    /**
     * Forma sem pontos editáveis: retângulo, círculo, texto, figura, ou uma
     * mistura que virou mais de um pedaço. A faixa DIZ isso em vez de sumir.
     */
    nodeUneditable: 'Esta forma não se edita por pontos. Dá para mudar a cor, o tamanho e o lugar.',
    nodeToCurve: 'Transformar em curva',
    nodeToLine: 'Transformar em reta',
    nodeSmooth: 'Ponto suave',
    nodeCorner: 'Ponto de canto',
    nodeSimplify: 'Suavizar o traço',
    nodeSimplifyDone: 'Este traço já está o mais liso que dá.',
    /** Com pontos escolhidos o botão alcança SÓ eles, e o rótulo diz isso
     *  antes do toque — o idioma da tesoura, que também troca de rótulo. */
    nodeSimplifyPart: 'Suavizar os pontos escolhidos',
    nodeSimplifyPartDone: 'Esses pontos já estão o mais lisos que dá.',
    nodeSimplifyTooBig: 'Este desenho está grande demais para suavizar o traço.',
    nodeSimplifyPartTooBig: 'Este desenho está grande demais para suavizar os pontos escolhidos.',
    /** O número vem da forma (3 num polígono, 2 num traço): dizer "alguns"
     *  não ajuda quem está tentando entender por que não apagou. */
    nodeFloor: (min: number) =>
      `Este desenho precisa de pelo menos ${min} pontos para continuar existindo.`,
    nodeCloseNeedsThree: 'Um caminho precisa de pelo menos 3 pontos para virar uma forma fechada.',
    nodeCeiling: 'Esta forma já tem o máximo de pontos.',
    alignTitle: 'Alinhar',
    alignLeft: 'Alinhar na esquerda',
    alignCenterH: 'Centralizar na largura',
    alignRight: 'Alinhar na direita',
    alignTop: 'Alinhar em cima',
    alignMiddleV: 'Centralizar na altura',
    alignBottom: 'Alinhar embaixo',
    pen: 'Caneta (clique para marcar os pontos)',
    cornerRadius: 'Cantos arredondados',
    fontSize: 'Tamanho da letra',
    fontFamily: 'Fonte',
    /** Alinhamento das LINHAS do texto. Rótulos distintos dos `align*` da faixa
     *  da seleção, que alinham FORMAS (os testes casam por nome acessível). */
    textAlignTitle: 'Alinhamento do texto',
    textAlignLeft: 'Texto na esquerda',
    textAlignCenter: 'Texto no meio',
    textAlignRight: 'Texto na direita',
    textMultilineHint: 'Enter pula de linha. Ctrl + Enter salva.',
    editText: 'Mudar o texto',
    saveText: 'Salvar',
    /** Rótulo por tipo de forma no painel Camadas (texto mostra o próprio conteúdo). */
    shapeNames: {
      rect: 'Retângulo',
      ellipse: 'Círculo',
      line: 'Linha',
      polygon: 'Forma',
      path: 'Traço',
      text: 'Texto',
      image: 'Figura',
    } as Record<string, string>,
    opacity: 'Quanto aparece',
    none: 'Sem cor',
    customColor: 'Cor personalizada',
    gradient: 'Degradê',
    gradientH: 'Degradê deitado',
    gradientV: 'Degradê em pé',
    gradientRadial: 'Degradê redondo (do meio)',
    gradientFrom: 'Cor do começo',
    gradientTo: 'Cor do fim',
    gradientOff: 'Tirar o degradê',
    forward: 'Uma camada para a frente',
    backward: 'Uma camada para trás',
    toFront: 'Trazer bem para a frente',
    toBack: 'Levar bem para o fundo',
    sides: 'Lados',
    tips: 'Pontas',
    textPrompt: 'O que você quer escrever?',
    textPlaceholder: 'Digite aqui...',
    add: 'Adicionar',
    rotate: 'Girar',
    shapeLimit: 'Este desenho já tem o máximo de formas.',
    /** Trazer um desenho da galeria para dentro deste. */
    insertAsset: 'Trazer um desenho',
    insertTitle: 'Qual desenho você quer trazer?',
    insertSearch: 'Procurar pelo nome',
    insertAsShapes: 'vira formas',
    insertAsImage: 'vira figura',
    insertEmpty: 'Este desenho está em branco.',
    insertNothing: 'Você ainda não tem outro desenho para trazer para cá.',
    insertNoMatch: 'Nenhum desenho com esse nome.',
    insertFailed: 'Não deu para trazer este desenho.',
    insertTooManyShapes: 'Este desenho não cabe: passaria do máximo de formas.',
    svg: 'Desenho (SVG)',
  },
  /** Nomes amigáveis das cores livres do vetorial (aria/title dos swatches). */
  colorNames: {
    '#ffffff': 'branco',
    '#ff2121': 'vermelho',
    '#ff93c4': 'rosa claro',
    '#ff8135': 'laranja',
    '#fff609': 'amarelo',
    '#249ca3': 'verde água',
    '#78dc52': 'verde',
    '#003fad': 'azul escuro',
    '#87f2ff': 'azul claro',
    '#8e2ec4': 'roxo',
    '#a4839f': 'lilás',
    '#5c406c': 'roxo escuro',
    '#e5cdc4': 'bege',
    '#91463d': 'marrom',
    '#000000': 'preto',
  } as Record<string, string>,
  exportDialog: {
    title: 'Baixar',
    editableFile: 'Desenho editável (.pinta.json)',
    editableMissingTileset:
      'Não encontrei as peças usadas por este mapa. Sem elas, o arquivo não funcionaria.',
    currentFrame: 'Quadro atual (PNG)',
    currentFrameSvg: 'Quadro atual (SVG)',
    image: 'Imagem (PNG)',
    spritesheet: 'Folha de animações (PNG)',
    spritesheetSvg: 'Folha de animações (SVG)',
    spritesheetJson: 'Receita das animações (para o Estúdio)',
    gif: (name: string) => `Animação "${name}" em GIF`,
    gifHint:
      'O GIF leva todos os quadros da animação e roda sozinho: dá para mandar para alguém, anexar numa publicação da comunidade ou usar onde quiser.',
    gifEmpty: 'Esta animação ainda não tem quadros. Desenhe um quadro para poder baixar o GIF.',
    tilesetSheet: 'Folha de peças (PNG)',
    tilesetSheetSvg: 'Folha de peças (SVG)',
    tilemapImage: 'Imagem do mapa (PNG)',
    tilemapJson: 'Mapa completo (para o Estúdio)',
    copyGrid: 'Copiar a grade do mapa',
    gridCopied: 'Grade copiada! Cole no bloco de mapa do Estúdio.',
    copyError: 'Não consegui copiar. Tente baixar o arquivo.',
    recipeTitle: 'Para usar no Estúdio:',
    scale: 'Tamanho da imagem',
    scaleVectorHint: 'Pode ampliar sem medo: desenho de formas não perde qualidade.',
    scaleStudioWarning:
      'Para usar no Estúdio, baixe no tamanho ×1 (o tamanho de verdade do desenho).',
    tilemapGridFile: 'Baixar a grade (arquivo de texto)',
    preparing: 'Preparando...',
    close: 'Fechar',
  },
  sendToStudio: {
    success: 'Pronto! Seu desenho já está no Estúdio, em "Meus desenhos".',
    successLocked: 'Salvei! Quando o Estúdio for liberado, seu desenho vai estar lá.',
    error: 'Não consegui enviar agora. Tente de novo daqui a pouco.',
    tooBig: 'Esse desenho ficou grande demais para o Estúdio. Tente um tamanho menor.',
    openStudio: 'Abrir o Estúdio',
    sending: 'Enviando...',
    /** Confirmação do reenvio automático (a criança abriu o desenho pelo jogo). */
    resynced: 'Atualizado no Estúdio',
    // Mapa: viaja como ASSET completo (grade + peças embutidas), não mais só a
    // grade no clipboard — o caminho de texto continua no "Baixar".
    mapSuccess: 'Seu mapa já está no Estúdio! Procure o bloco "Criar mapa do meu desenho".',
    mapSuccessLocked: 'Salvei! Quando o Estúdio for liberado, seu mapa vai estar lá.',
    playSuccess: 'Pronto! Seu mapa virou um jogo no Estúdio. É só apertar Jogar!',
  },
  coach: {
    gotIt: 'Entendi!',
    pixel: {
      title: 'Dicas rápidas',
      tips: [
        'O Lápis desenha e a Borracha apaga.',
        'O Balde de tinta pinta um espaço todo de uma vez.',
        'Com "Selecionar", marque um pedaço e use Duplicar e Espelhar para fazer o outro lado.',
        'Rode a bolinha do mouse para aproximar e afastar.',
        'Teclas rápidas: P lápis, E borracha, G balde, M selecionar.',
        'O foguete leva o seu desenho para o Estúdio.',
      ],
    },
    vector: {
      title: 'Dicas rápidas',
      tips: [
        'Escolha uma forma ou o Pincel e arraste no palco.',
        '"Selecionar" deixa mover, girar e trocar a cor.',
        '"Editar os pontos" muda o contorno; o Degradê mistura duas cores.',
        'A Caneta marca pontos; aperte Enter para fechar a forma.',
        'A Grade ajuda a desenhar tudo alinhado.',
        'Rode a bolinha do mouse para aproximar e afastar.',
        'Teclas rápidas: V selecionar, B pincel, H mão, T texto.',
      ],
    },
    map: {
      title: 'Dicas rápidas',
      tips: [
        'Escolha uma peça no canto e pinte na grade.',
        'Arraste sobre as peças para pegar um bloco inteiro e carimbar.',
        'A Linha e o Retângulo pintam vários tiles de uma vez.',
        'Rode a bolinha do mouse para aproximar e afastar.',
        'Teclas rápidas: P lápis, E borracha, G balde, M selecionar.',
        'O foguete copia a grade para o bloco de mapa do Estúdio.',
      ],
    },
  },
  toast: {
    downloadReady: 'Baixado! Procure na pasta de downloads.',
    downloadError: 'Não consegui gerar a imagem agora. Tente de novo.',
  },
  // Rótulos de acessibilidade (aria-label) + defaults do modelo que aparecem na
  // UI — centralizados aqui p/ i18n e p/ não repetir literais soltos nas telas.
  a11y: {
    drawArea: 'Área de desenho',
    tools: 'Ferramentas',
    close: 'Fechar',
    colorLabel: (index: number) => `Cor ${index}`,
    frameLabel: (number: number) => `Quadro ${number}`,
    sheetFrame: (name: string, number: number) => `${name}: quadro ${number}`,
    step: (current: number, total: number) => `Passo ${current} de ${total}`,
    openAsset: (label: string) => `Abrir ${label}`,
    defaultLayer: 'Chão',
    defaultAnimation: 'animação',
  },
} as const
