/**
 * Copy do Pinta, 100% em português e centralizada — sem travessão, sem jargão.
 * Texto de UI vive AQUI (os componentes só referenciam), para revisão de tom
 * num lugar só.
 */
import type { PintaAssetKind } from './project'

export const COPY = {
  appName: 'Pinta',
  gallery: {
    title: 'Meus desenhos',
    subtitle: 'Crie os personagens, cenários e peças dos seus jogos.',
    create: 'Criar novo',
    empty: 'Nada por aqui ainda. Toque em "Criar novo" para começar o seu primeiro desenho!',
    loading: 'Abrindo a sua galeria...',
    loadError: 'Não consegui abrir a sua galeria. Tente de novo daqui a pouco.',
    rename: 'Renomear',
    duplicate: 'Duplicar',
    remove: 'Apagar',
    removeConfirmTitle: 'Apagar este desenho?',
    removeConfirmBody: 'Ele vai sumir da galeria. Não dá para desfazer.',
    removeConfirm: 'Apagar',
    cancel: 'Cancelar',
    quotaFull: 'A sua galeria está cheia! Apague um desenho antigo para criar um novo.',
    downloadAll: 'Baixar tudo',
    restore: 'Trazer de volta',
    restoreError: 'Não consegui ler esse arquivo. Ele é um backup do Pinta (.pinta.json)?',
    zipError: 'Não consegui montar o arquivo agora. Tente de novo.',
  },
  newAsset: {
    styleTitle: 'Como você quer desenhar?',
    title: 'O que você quer criar?',
    sizeTitle: 'Qual o tamanho?',
    nameTitle: 'Qual o nome?',
    namePlaceholder: 'meu-heroi',
    nameHelp: 'Use letras minúsculas e traços. Esse nome aparece nos blocos do Estúdio.',
    nameInvalid: 'Esse nome não vai funcionar. Tente algo como "meu-heroi".',
    nameTaken: 'Você já tem um desenho com esse nome. Escolha outro.',
    back: 'Voltar',
    next: 'Avançar',
    createButton: 'Começar a desenhar',
    creating: 'Criando...',
    chooseTilesetTitle: 'Quais peças o mapa vai usar?',
    needTileset: 'Antes de criar um mapa, crie as suas "Peças do cenário".',
  },
  styles: {
    pixel: {
      emoji: '👾',
      title: 'Pixel art',
      description: 'Desenhe quadradinho por quadradinho, no estilo dos jogos clássicos.',
    },
    vector: {
      emoji: '✏️',
      title: 'Vetor',
      description: 'Desenhe com formas e pincel, com linhas sempre lisinhas.',
    },
  },
  styleBadge: {
    pixel: 'Pixel',
    vector: 'Vetor',
  },
  kinds: {
    'pixel-sprite': {
      emoji: '🧍',
      title: 'Personagem',
      description: 'Um herói, bicho ou item, com animações de andar, pular e mais.',
    },
    'pixel-background': {
      emoji: '🖼️',
      title: 'Cenário de fundo',
      description: 'A imagem grande que fica atrás do seu jogo.',
    },
    tileset: {
      emoji: '🧩',
      title: 'Peças do cenário',
      description: 'Blocos de chão, parede e decoração para montar mapas.',
    },
    tilemap: {
      emoji: '🗺️',
      title: 'Mapa',
      description: 'Monte uma fase inteira usando as suas peças.',
    },
    'vector-sprite': {
      emoji: '🧍',
      title: 'Personagem',
      description: 'Um herói, bicho ou item feito de formas, com animações.',
    },
    'vector-background': {
      emoji: '🖼️',
      title: 'Cenário de fundo',
      description: 'A imagem grande que fica atrás do seu jogo, feita de formas.',
    },
    'vector-tileset': {
      emoji: '🧩',
      title: 'Peças do cenário',
      description: 'Blocos de chão e parede desenhados com formas.',
    },
  } satisfies Record<PintaAssetKind, { emoji: string; title: string; description: string }>,
  sizes: {
    16: 'Pequeno',
    32: 'Médio',
    48: 'Grande',
    64: 'Gigante',
  } as Record<number, string>,
  /** Rótulos por POSIÇÃO nas listas de tamanho de cenário/desenho livre/mapa. */
  sizeScale: ['Pequeno', 'Médio', 'Grande'],
  editor: {
    back: 'Voltar',
    undo: 'Desfazer',
    redo: 'Refazer',
    saved: 'Salvo',
    saving: 'Salvando...',
    saveError: 'Não consegui salvar',
    download: 'Baixar',
    sendToStudio: 'Usar no Estúdio',
    zoomIn: 'Aproximar',
    zoomOut: 'Afastar',
    zoomFit: 'Ajustar',
  },
  tools: {
    pencil: 'Lápis',
    eraser: 'Borracha',
    fill: 'Balde de tinta',
    line: 'Linha',
    rect: 'Retângulo',
    ellipse: 'Círculo',
    picker: 'Conta-gotas',
    mirror: 'Espelho',
    filled: 'Preencher formas',
    brushSize: 'Tamanho do traço',
    flipH: 'Espelhar na horizontal',
    flipV: 'Espelhar na vertical',
    rotate: 'Girar',
  },
  palette: {
    title: 'Cores',
    transparent: 'Apagar (transparente)',
    switchPalette: 'Trocar paleta',
  },
  animation: {
    preview: 'Prévia',
    play: 'Rodar animação',
    pause: 'Pausar',
    speed: 'Velocidade',
    slow: 'Devagar',
    fast: 'Rápido',
    onion: 'Fantasma do quadro anterior',
    loop: 'Repetir animação',
    animations: 'Animações',
    addAnimation: 'Nova animação',
    renameAnimation: 'Renomear animação',
    removeAnimation: 'Apagar animação',
    duplicateAnimation: 'Duplicar animação',
    frames: 'Quadros',
    addFrame: 'Novo quadro',
    duplicateFrame: 'Duplicar quadro',
    removeFrame: 'Apagar quadro',
    moveFrameLeft: 'Mover para a esquerda',
    moveFrameRight: 'Mover para a direita',
    animationLimit: 'Você chegou ao limite de animações deste personagem.',
    frameLimit: 'Essa animação já tem o máximo de quadros.',
  },
  tiles: {
    tiles: 'Peças',
    addTile: 'Nova peça',
    duplicateTile: 'Duplicar peça',
    removeTile: 'Apagar peça',
    solid: 'Peça sólida (o personagem não atravessa)',
    tileLimit: 'Você chegou ao limite de peças.',
    layers: 'Camadas',
    addLayer: 'Nova camada',
    removeLayer: 'Apagar camada',
    layerLimit: 'Este mapa já tem o máximo de camadas.',
    show: 'Mostrar',
    hide: 'Esconder',
    pickTile: 'Peças para pintar',
    missingTileset: 'Não achei as peças deste mapa. Elas podem ter sido apagadas.',
    sheetError: 'Não consegui desenhar as peças agora. Tente fechar e abrir o mapa.',
  },
  vector: {
    select: 'Selecionar',
    pan: 'Mão (arrastar a tela)',
    brush: 'Pincel',
    polygon: 'Polígono',
    star: 'Estrela',
    text: 'Texto',
    fill: 'Preenchimento',
    stroke: 'Contorno',
    strokeWidth: 'Espessura do contorno',
    opacity: 'Quanto aparece',
    none: 'Sem cor',
    forward: 'Trazer para a frente',
    backward: 'Levar para trás',
    duplicate: 'Duplicar',
    remove: 'Apagar',
    textPrompt: 'O que você quer escrever?',
    textPlaceholder: 'Digite aqui...',
    add: 'Adicionar',
    rotate: 'Girar',
    shapeLimit: 'Este desenho já tem o máximo de formas.',
    svg: 'Desenho (SVG)',
  },
  /** Nomes amigáveis das cores livres do vetorial (aria/title dos swatches). */
  colorNames: {
    '#ffffff': 'branco',
    '#ff2121': 'vermelho',
    '#ff93c4': 'rosa claro',
    '#ff8135': 'laranja',
    '#fff609': 'amarelo',
    '#249ca3': 'verde água',
    '#78dc52': 'verde',
    '#003fad': 'azul escuro',
    '#87f2ff': 'azul claro',
    '#8e2ec4': 'roxo',
    '#a4839f': 'lilás',
    '#5c406c': 'roxo escuro',
    '#e5cdc4': 'bege',
    '#91463d': 'marrom',
    '#000000': 'preto',
  } as Record<string, string>,
  exportDialog: {
    title: 'Baixar',
    currentFrame: 'Quadro atual (PNG)',
    currentFrameSvg: 'Quadro atual (SVG)',
    image: 'Imagem (PNG)',
    spritesheet: 'Folha de animações (PNG)',
    spritesheetSvg: 'Folha de animações (SVG)',
    spritesheetJson: 'Receita das animações (arquivo de números)',
    tilesetSheet: 'Folha de peças (PNG)',
    tilesetSheetSvg: 'Folha de peças (SVG)',
    tilemapImage: 'Imagem do mapa (PNG)',
    tilemapJson: 'Mapa completo (arquivo de números)',
    copyGrid: 'Copiar a grade do mapa',
    gridCopied: 'Grade copiada! Cole no bloco de mapa do Estúdio.',
    copyError: 'Não consegui copiar. Tente baixar o arquivo.',
    recipeTitle: 'Para usar no Estúdio:',
    scale: 'Tamanho da imagem',
    scaleVectorHint: 'Pode ampliar sem medo: desenho de formas não perde qualidade.',
    scaleStudioWarning: 'Para usar no Estúdio, baixe no tamanho ×1.',
    tilemapGridFile: 'Baixar a grade (arquivo de texto)',
    preparing: 'Preparando...',
    close: 'Fechar',
  },
  sendToStudio: {
    success: 'Pronto! Seu desenho já está no Estúdio, em "Meus desenhos".',
    successLocked: 'Salvei! Quando o Estúdio for liberado, seu desenho vai estar lá.',
    error: 'Não consegui enviar agora. Tente de novo daqui a pouco.',
    tooBig: 'Esse desenho ficou grande demais para o Estúdio. Tente um tamanho menor.',
    openStudio: 'Abrir o Estúdio',
    sending: 'Enviando...',
  },
  toast: {
    downloadReady: 'Baixado! Procure na pasta de downloads.',
    downloadError: 'Não consegui gerar a imagem agora. Tente de novo.',
  },
} as const
