import type { ExtensionExample } from '#extensions'
import { withIndependentPeriodicLoops } from './withIndependentPeriodicLoops'

/**
 * Exemplo bundlado: "Batalha de Monstrinhos Profissional" — o nível 2 da
 * família de batalha de monstrinhos (o Pokemon do Clear Code recriado com o
 * 👾 Kit Monstrinhos COMPLETO), SEM nenhum bloco do Kit RPG: o pátio é
 * movimento livre (moveWithKeys + regiões). Mostra as FICHAS data-driven
 * (pkmCreature/pkmMove com tipo e força), a TABELA DE VANTAGEM real que a
 * criança escreve (pkmTypeChart: fogo>planta, água>fogo, planta>água, 2x e
 * 0.5x), o TIME com memória de vida entre trocas e batalhas (pkmGive +
 * pkmDrawTeam no HUD), a batalha de TREINADOR com menus navegáveis do kit
 * (pkmBattleTrainer + pkmTrainerCreature), o Centro de Cura num bloco
 * (pkmHealTeam na fonte) e o encontro selvagem manual no mato fundo
 * (overlapPercent + chance + pkmBattleWild) com CAPTURA como vitória:
 * pkmCaught lido no TOPO do onUpdate (fechar batalha é RETOMADA e não roda
 * onEnterState de "jogando"), sem rpgOnBattleEnd.
 *
 * ⚠️ A IR foi GERADA pelo parser real a partir do script achatado (o fonte
 * vive em `__gen_batalhaProfissional.ts` — se o parser mudar a saída, o drift
 * test `batalhaProfissionalExample.test.ts` manda re-embutir aqui).
 */
export const batalhaProfissionalExample: ExtensionExample = withIndependentPeriodicLoops({
  name: 'Batalha de Monstrinhos Profissional',
  experience: 'game',
  description:
    'Monte o time, escreva a tabela de vantagem e desafie a rival! Fichas de monstrinho, golpes por tipo, menus de batalha do kit, fonte que cura e captura do lendário no mato fundo.',
  ir: {
    html: [],
    css: [],
    extensions: [{ extensionId: 'game-2d-advanced' }],
    version: 2,
    behavior: {
      start: [
        {
          type: 'gk:setup',
          w: { type: 'num', value: 960 },
          h: { type: 'num', value: 540 },
          bg: '#8fce77',
          accent: '#2b8a3e',
        },
        {
          type: 'gk:setScreenText',
          screen: 'menu',
          title: { type: 'str', value: 'Batalha de Monstrinhos Profissional' },
          text: {
            type: 'str',
            value:
              'Setas: andar. ESPAÇO perto da rival Alice: batalhar! Fogo vence planta, planta vence água e água vence fogo. Cure o time na fonte e capture o Faiscolosso no mato fundo.',
          },
          button: { type: 'str', value: 'Começar' },
        },
        {
          type: 'gk:setScreenText',
          screen: 'vitoria',
          title: { type: 'str', value: 'Capturou!' },
          text: {
            type: 'str',
            value: 'O Faiscolosso entrou para o seu time. Você é a nova lenda do quintal!',
          },
          button: { type: 'str', value: 'Jogar de novo' },
        },
        {
          type: 'gk:defineLook',
          name: 'treinadora',
          ctxName: 'ctx',
          body: [
            {
              type: 'canvasFillStyle',
              ctxVar: 'ctx',
              color: { type: 'color', value: '#e8590c' },
            },
            {
              type: 'canvasFillRect',
              ctxVar: 'ctx',
              x: { type: 'num', value: 10 },
              y: { type: 'num', value: 0 },
              w: { type: 'num', value: 24 },
              h: { type: 'num', value: 10 },
            },
            {
              type: 'canvasFillStyle',
              ctxVar: 'ctx',
              color: { type: 'color', value: '#ffd8a8' },
            },
            {
              type: 'canvasFillRect',
              ctxVar: 'ctx',
              x: { type: 'num', value: 12 },
              y: { type: 'num', value: 10 },
              w: { type: 'num', value: 20 },
              h: { type: 'num', value: 12 },
            },
            {
              type: 'canvasFillStyle',
              ctxVar: 'ctx',
              color: { type: 'color', value: '#1971c2' },
            },
            {
              type: 'canvasFillRect',
              ctxVar: 'ctx',
              x: { type: 'num', value: 8 },
              y: { type: 'num', value: 22 },
              w: { type: 'num', value: 28 },
              h: { type: 'num', value: 18 },
            },
            {
              type: 'canvasFillStyle',
              ctxVar: 'ctx',
              color: { type: 'color', value: '#343a40' },
            },
            {
              type: 'canvasFillRect',
              ctxVar: 'ctx',
              x: { type: 'num', value: 12 },
              y: { type: 'num', value: 40 },
              w: { type: 'num', value: 20 },
              h: { type: 'num', value: 16 },
            },
          ],
          baseW: { type: 'num', value: 44 },
          baseH: { type: 'num', value: 56 },
        },
        {
          type: 'gk:defineLook',
          name: 'rival',
          ctxName: 'ctx',
          body: [
            {
              type: 'canvasFillStyle',
              ctxVar: 'ctx',
              color: { type: 'color', value: '#2f9e44' },
            },
            {
              type: 'canvasFillRect',
              ctxVar: 'ctx',
              x: { type: 'num', value: 10 },
              y: { type: 'num', value: 0 },
              w: { type: 'num', value: 24 },
              h: { type: 'num', value: 10 },
            },
            {
              type: 'canvasFillStyle',
              ctxVar: 'ctx',
              color: { type: 'color', value: '#ffe8cc' },
            },
            {
              type: 'canvasFillRect',
              ctxVar: 'ctx',
              x: { type: 'num', value: 12 },
              y: { type: 'num', value: 10 },
              w: { type: 'num', value: 20 },
              h: { type: 'num', value: 12 },
            },
            {
              type: 'canvasFillStyle',
              ctxVar: 'ctx',
              color: { type: 'color', value: '#e03131' },
            },
            {
              type: 'canvasFillRect',
              ctxVar: 'ctx',
              x: { type: 'num', value: 8 },
              y: { type: 'num', value: 22 },
              w: { type: 'num', value: 28 },
              h: { type: 'num', value: 18 },
            },
            {
              type: 'canvasFillStyle',
              ctxVar: 'ctx',
              color: { type: 'color', value: '#212529' },
            },
            {
              type: 'canvasFillRect',
              ctxVar: 'ctx',
              x: { type: 'num', value: 12 },
              y: { type: 'num', value: 40 },
              w: { type: 'num', value: 20 },
              h: { type: 'num', value: 16 },
            },
          ],
          baseW: { type: 'num', value: 44 },
          baseH: { type: 'num', value: 56 },
        },
        {
          type: 'gk:defineLook',
          name: 'fonte',
          ctxName: 'ctx',
          body: [
            {
              type: 'canvasFillStyle',
              ctxVar: 'ctx',
              color: { type: 'color', value: '#adb5bd' },
            },
            {
              type: 'canvasFillRect',
              ctxVar: 'ctx',
              x: { type: 'num', value: 5 },
              y: { type: 'num', value: 70 },
              w: { type: 'num', value: 120 },
              h: { type: 'num', value: 30 },
            },
            {
              type: 'canvasFillStyle',
              ctxVar: 'ctx',
              color: { type: 'color', value: '#74c0fc' },
            },
            {
              type: 'canvasFillRect',
              ctxVar: 'ctx',
              x: { type: 'num', value: 15 },
              y: { type: 'num', value: 76 },
              w: { type: 'num', value: 100 },
              h: { type: 'num', value: 18 },
            },
            {
              type: 'canvasFillStyle',
              ctxVar: 'ctx',
              color: { type: 'color', value: '#ced4da' },
            },
            {
              type: 'canvasFillRect',
              ctxVar: 'ctx',
              x: { type: 'num', value: 52 },
              y: { type: 'num', value: 30 },
              w: { type: 'num', value: 26 },
              h: { type: 'num', value: 44 },
            },
            {
              type: 'canvasFillStyle',
              ctxVar: 'ctx',
              color: { type: 'color', value: '#a5d8ff' },
            },
            {
              type: 'canvasArc',
              ctxVar: 'ctx',
              x: { type: 'num', value: 65 },
              y: { type: 'num', value: 22 },
              r: { type: 'num', value: 14 },
            },
          ],
          baseW: { type: 'num', value: 130 },
          baseH: { type: 'num', value: 110 },
        },
        {
          type: 'gk:defineLook',
          name: 'grama',
          ctxName: 'ctx',
          body: [
            {
              type: 'canvasFillStyle',
              ctxVar: 'ctx',
              color: { type: 'color', value: '#2f9e44' },
            },
            {
              type: 'canvasFillRect',
              ctxVar: 'ctx',
              x: { type: 'num', value: 6 },
              y: { type: 'num', value: 24 },
              w: { type: 'num', value: 10 },
              h: { type: 'num', value: 32 },
            },
            {
              type: 'canvasFillRect',
              ctxVar: 'ctx',
              x: { type: 'num', value: 24 },
              y: { type: 'num', value: 12 },
              w: { type: 'num', value: 10 },
              h: { type: 'num', value: 44 },
            },
            {
              type: 'canvasFillRect',
              ctxVar: 'ctx',
              x: { type: 'num', value: 42 },
              y: { type: 'num', value: 26 },
              w: { type: 'num', value: 10 },
              h: { type: 'num', value: 30 },
            },
            {
              type: 'canvasFillStyle',
              ctxVar: 'ctx',
              color: { type: 'color', value: '#51cf66' },
            },
            {
              type: 'canvasFillRect',
              ctxVar: 'ctx',
              x: { type: 'num', value: 15 },
              y: { type: 'num', value: 34 },
              w: { type: 'num', value: 8 },
              h: { type: 'num', value: 22 },
            },
          ],
          baseW: { type: 'num', value: 56 },
          baseH: { type: 'num', value: 56 },
        },
        {
          type: 'gk:defineLook',
          name: 'faisco',
          ctxName: 'ctx',
          body: [
            {
              type: 'canvasFillStyle',
              ctxVar: 'ctx',
              color: { type: 'color', value: '#ff922b' },
            },
            {
              type: 'canvasFillRect',
              ctxVar: 'ctx',
              x: { type: 'num', value: 14 },
              y: { type: 'num', value: 26 },
              w: { type: 'num', value: 46 },
              h: { type: 'num', value: 30 },
            },
            {
              type: 'canvasFillRect',
              ctxVar: 'ctx',
              x: { type: 'num', value: 18 },
              y: { type: 'num', value: 10 },
              w: { type: 'num', value: 12 },
              h: { type: 'num', value: 18 },
            },
            {
              type: 'canvasFillStyle',
              ctxVar: 'ctx',
              color: { type: 'color', value: '#ffd43b' },
            },
            {
              type: 'canvasFillRect',
              ctxVar: 'ctx',
              x: { type: 'num', value: 54 },
              y: { type: 'num', value: 6 },
              w: { type: 'num', value: 14 },
              h: { type: 'num', value: 24 },
            },
            {
              type: 'canvasFillStyle',
              ctxVar: 'ctx',
              color: { type: 'color', value: '#212529' },
            },
            {
              type: 'canvasFillRect',
              ctxVar: 'ctx',
              x: { type: 'num', value: 46 },
              y: { type: 'num', value: 34 },
              w: { type: 'num', value: 6 },
              h: { type: 'num', value: 6 },
            },
          ],
          baseW: { type: 'num', value: 80 },
          baseH: { type: 'num', value: 64 },
        },
        {
          type: 'gk:defineLook',
          name: 'gotinha',
          ctxName: 'ctx',
          body: [
            {
              type: 'canvasFillStyle',
              ctxVar: 'ctx',
              color: { type: 'color', value: '#4dabf7' },
            },
            {
              type: 'canvasArc',
              ctxVar: 'ctx',
              x: { type: 'num', value: 36 },
              y: { type: 'num', value: 38 },
              r: { type: 'num', value: 24 },
            },
            {
              type: 'canvasFillRect',
              ctxVar: 'ctx',
              x: { type: 'num', value: 30 },
              y: { type: 'num', value: 4 },
              w: { type: 'num', value: 12 },
              h: { type: 'num', value: 16 },
            },
            {
              type: 'canvasFillStyle',
              ctxVar: 'ctx',
              color: { type: 'color', value: '#ffffff' },
            },
            {
              type: 'canvasFillRect',
              ctxVar: 'ctx',
              x: { type: 'num', value: 26 },
              y: { type: 'num', value: 32 },
              w: { type: 'num', value: 6 },
              h: { type: 'num', value: 8 },
            },
          ],
          baseW: { type: 'num', value: 72 },
          baseH: { type: 'num', value: 64 },
        },
        {
          type: 'gk:defineLook',
          name: 'brotinho',
          ctxName: 'ctx',
          body: [
            {
              type: 'canvasFillStyle',
              ctxVar: 'ctx',
              color: { type: 'color', value: '#69db7c' },
            },
            {
              type: 'canvasFillRect',
              ctxVar: 'ctx',
              x: { type: 'num', value: 16 },
              y: { type: 'num', value: 28 },
              w: { type: 'num', value: 40 },
              h: { type: 'num', value: 32 },
            },
            {
              type: 'canvasFillStyle',
              ctxVar: 'ctx',
              color: { type: 'color', value: '#2f9e44' },
            },
            {
              type: 'canvasFillRect',
              ctxVar: 'ctx',
              x: { type: 'num', value: 31 },
              y: { type: 'num', value: 6 },
              w: { type: 'num', value: 10 },
              h: { type: 'num', value: 24 },
            },
            {
              type: 'canvasFillRect',
              ctxVar: 'ctx',
              x: { type: 'num', value: 39 },
              y: { type: 'num', value: 10 },
              w: { type: 'num', value: 16 },
              h: { type: 'num', value: 8 },
            },
            {
              type: 'canvasFillStyle',
              ctxVar: 'ctx',
              color: { type: 'color', value: '#212529' },
            },
            {
              type: 'canvasFillRect',
              ctxVar: 'ctx',
              x: { type: 'num', value: 44 },
              y: { type: 'num', value: 38 },
              w: { type: 'num', value: 6 },
              h: { type: 'num', value: 6 },
            },
          ],
          baseW: { type: 'num', value: 72 },
          baseH: { type: 'num', value: 68 },
        },
        {
          type: 'gk:defineLook',
          name: 'folhito',
          ctxName: 'ctx',
          body: [
            {
              type: 'canvasFillStyle',
              ctxVar: 'ctx',
              color: { type: 'color', value: '#8ce99a' },
            },
            {
              type: 'canvasFillRect',
              ctxVar: 'ctx',
              x: { type: 'num', value: 12 },
              y: { type: 'num', value: 20 },
              w: { type: 'num', value: 40 },
              h: { type: 'num', value: 28 },
            },
            {
              type: 'canvasFillStyle',
              ctxVar: 'ctx',
              color: { type: 'color', value: '#2b8a3e' },
            },
            {
              type: 'canvasFillRect',
              ctxVar: 'ctx',
              x: { type: 'num', value: 16 },
              y: { type: 'num', value: 6 },
              w: { type: 'num', value: 8 },
              h: { type: 'num', value: 16 },
            },
            {
              type: 'canvasFillStyle',
              ctxVar: 'ctx',
              color: { type: 'color', value: '#212529' },
            },
            {
              type: 'canvasFillRect',
              ctxVar: 'ctx',
              x: { type: 'num', value: 40 },
              y: { type: 'num', value: 28 },
              w: { type: 'num', value: 5 },
              h: { type: 'num', value: 5 },
            },
          ],
          baseW: { type: 'num', value: 64 },
          baseH: { type: 'num', value: 56 },
        },
        {
          type: 'gk:defineLook',
          name: 'pingo',
          ctxName: 'ctx',
          body: [
            {
              type: 'canvasFillStyle',
              ctxVar: 'ctx',
              color: { type: 'color', value: '#74c0fc' },
            },
            {
              type: 'canvasArc',
              ctxVar: 'ctx',
              x: { type: 'num', value: 28 },
              y: { type: 'num', value: 30 },
              r: { type: 'num', value: 20 },
            },
            {
              type: 'canvasFillRect',
              ctxVar: 'ctx',
              x: { type: 'num', value: 24 },
              y: { type: 'num', value: 2 },
              w: { type: 'num', value: 8 },
              h: { type: 'num', value: 14 },
            },
            {
              type: 'canvasFillStyle',
              ctxVar: 'ctx',
              color: { type: 'color', value: '#ffffff' },
            },
            {
              type: 'canvasFillRect',
              ctxVar: 'ctx',
              x: { type: 'num', value: 22 },
              y: { type: 'num', value: 24 },
              w: { type: 'num', value: 5 },
              h: { type: 'num', value: 7 },
            },
          ],
          baseW: { type: 'num', value: 56 },
          baseH: { type: 'num', value: 52 },
        },
        {
          type: 'gk:defineLook',
          name: 'braseiro',
          ctxName: 'ctx',
          body: [
            {
              type: 'canvasFillStyle',
              ctxVar: 'ctx',
              color: { type: 'color', value: '#fa5252' },
            },
            {
              type: 'canvasFillRect',
              ctxVar: 'ctx',
              x: { type: 'num', value: 14 },
              y: { type: 'num', value: 24 },
              w: { type: 'num', value: 44 },
              h: { type: 'num', value: 30 },
            },
            {
              type: 'canvasFillStyle',
              ctxVar: 'ctx',
              color: { type: 'color', value: '#ffa94d' },
            },
            {
              type: 'canvasFillRect',
              ctxVar: 'ctx',
              x: { type: 'num', value: 26 },
              y: { type: 'num', value: 4 },
              w: { type: 'num', value: 10 },
              h: { type: 'num', value: 22 },
            },
            {
              type: 'canvasFillStyle',
              ctxVar: 'ctx',
              color: { type: 'color', value: '#ffe066' },
            },
            {
              type: 'canvasFillRect',
              ctxVar: 'ctx',
              x: { type: 'num', value: 28 },
              y: { type: 'num', value: 0 },
              w: { type: 'num', value: 6 },
              h: { type: 'num', value: 8 },
            },
            {
              type: 'canvasFillStyle',
              ctxVar: 'ctx',
              color: { type: 'color', value: '#212529' },
            },
            {
              type: 'canvasFillRect',
              ctxVar: 'ctx',
              x: { type: 'num', value: 48 },
              y: { type: 'num', value: 32 },
              w: { type: 'num', value: 6 },
              h: { type: 'num', value: 6 },
            },
          ],
          baseW: { type: 'num', value: 72 },
          baseH: { type: 'num', value: 60 },
        },
        {
          type: 'gk:defineLook',
          name: 'faiscolosso',
          ctxName: 'ctx',
          body: [
            {
              type: 'canvasFillStyle',
              ctxVar: 'ctx',
              color: { type: 'color', value: '#f59f00' },
            },
            {
              type: 'canvasFillRect',
              ctxVar: 'ctx',
              x: { type: 'num', value: 12 },
              y: { type: 'num', value: 30 },
              w: { type: 'num', value: 72 },
              h: { type: 'num', value: 44 },
            },
            {
              type: 'canvasFillStyle',
              ctxVar: 'ctx',
              color: { type: 'color', value: '#ffd43b' },
            },
            {
              type: 'canvasFillRect',
              ctxVar: 'ctx',
              x: { type: 'num', value: 28 },
              y: { type: 'num', value: 4 },
              w: { type: 'num', value: 16 },
              h: { type: 'num', value: 28 },
            },
            {
              type: 'canvasFillRect',
              ctxVar: 'ctx',
              x: { type: 'num', value: 52 },
              y: { type: 'num', value: 10 },
              w: { type: 'num', value: 14 },
              h: { type: 'num', value: 22 },
            },
            {
              type: 'canvasFillStyle',
              ctxVar: 'ctx',
              color: { type: 'color', value: '#e8590c' },
            },
            {
              type: 'canvasFillRect',
              ctxVar: 'ctx',
              x: { type: 'num', value: 12 },
              y: { type: 'num', value: 14 },
              w: { type: 'num', value: 10 },
              h: { type: 'num', value: 18 },
            },
            {
              type: 'canvasFillStyle',
              ctxVar: 'ctx',
              color: { type: 'color', value: '#ffffff' },
            },
            {
              type: 'canvasFillRect',
              ctxVar: 'ctx',
              x: { type: 'num', value: 62 },
              y: { type: 'num', value: 42 },
              w: { type: 'num', value: 10 },
              h: { type: 'num', value: 8 },
            },
          ],
          baseW: { type: 'num', value: 96 },
          baseH: { type: 'num', value: 80 },
        },
        {
          type: 'gk:pkmCreature',
          name: 'Faisco',
          creatureType: 'fogo',
          hp: { type: 'num', value: 34 },
          str: { type: 'num', value: 9 },
          def: { type: 'num', value: 5 },
          spd: { type: 'num', value: 8 },
          image: '',
          look: 'faisco',
        },
        {
          type: 'gk:pkmCreature',
          name: 'Gotinha',
          creatureType: 'água',
          hp: { type: 'num', value: 36 },
          str: { type: 'num', value: 8 },
          def: { type: 'num', value: 6 },
          spd: { type: 'num', value: 6 },
          image: '',
          look: 'gotinha',
        },
        {
          type: 'gk:pkmCreature',
          name: 'Brotinho',
          creatureType: 'planta',
          hp: { type: 'num', value: 38 },
          str: { type: 'num', value: 8 },
          def: { type: 'num', value: 7 },
          spd: { type: 'num', value: 5 },
          image: '',
          look: 'brotinho',
        },
        {
          type: 'gk:pkmCreature',
          name: 'Folhito',
          creatureType: 'planta',
          hp: { type: 'num', value: 30 },
          str: { type: 'num', value: 7 },
          def: { type: 'num', value: 5 },
          spd: { type: 'num', value: 6 },
          image: '',
          look: 'folhito',
        },
        {
          type: 'gk:pkmCreature',
          name: 'Pingo',
          creatureType: 'água',
          hp: { type: 'num', value: 32 },
          str: { type: 'num', value: 8 },
          def: { type: 'num', value: 5 },
          spd: { type: 'num', value: 7 },
          image: '',
          look: 'pingo',
        },
        {
          type: 'gk:pkmCreature',
          name: 'Braseiro',
          creatureType: 'fogo',
          hp: { type: 'num', value: 34 },
          str: { type: 'num', value: 10 },
          def: { type: 'num', value: 6 },
          spd: { type: 'num', value: 8 },
          image: '',
          look: 'braseiro',
        },
        {
          type: 'gk:pkmCreature',
          name: 'Faiscolosso',
          creatureType: 'fogo',
          hp: { type: 'num', value: 60 },
          str: { type: 'num', value: 12 },
          def: { type: 'num', value: 8 },
          spd: { type: 'num', value: 10 },
          image: '',
          look: 'faiscolosso',
        },
        {
          type: 'gk:pkmMove',
          move: 'Brasa',
          creature: 'Faisco',
          moveType: 'fogo',
          dmg: { type: 'num', value: 14 },
          acc: { type: 'num', value: 95 },
          fx: 'bola',
          color: '#ff922b',
        },
        {
          type: 'gk:pkmMove',
          move: 'Rasteira',
          creature: 'Faisco',
          moveType: 'normal',
          dmg: { type: 'num', value: 9 },
          acc: { type: 'num', value: 100 },
          fx: 'investida',
          color: '#ced4da',
        },
        {
          type: 'gk:pkmMove',
          move: 'Esguicho',
          creature: 'Gotinha',
          moveType: 'água',
          dmg: { type: 'num', value: 14 },
          acc: { type: 'num', value: 95 },
          fx: 'onda',
          color: '#339af0',
        },
        {
          type: 'gk:pkmMove',
          move: 'Chicote de Folha',
          creature: 'Brotinho',
          moveType: 'planta',
          dmg: { type: 'num', value: 14 },
          acc: { type: 'num', value: 95 },
          fx: 'raio',
          color: '#51cf66',
        },
        {
          type: 'gk:pkmMove',
          move: 'Folha Afiada',
          creature: 'Folhito',
          moveType: 'planta',
          dmg: { type: 'num', value: 12 },
          acc: { type: 'num', value: 95 },
          fx: 'raio',
          color: '#40c057',
        },
        {
          type: 'gk:pkmMove',
          move: 'Bolha',
          creature: 'Pingo',
          moveType: 'água',
          dmg: { type: 'num', value: 12 },
          acc: { type: 'num', value: 95 },
          fx: 'bola',
          color: '#4dabf7',
        },
        {
          type: 'gk:pkmMove',
          move: 'Labareda',
          creature: 'Braseiro',
          moveType: 'fogo',
          dmg: { type: 'num', value: 16 },
          acc: { type: 'num', value: 90 },
          fx: 'bola',
          color: '#fa5252',
        },
        {
          type: 'gk:pkmMove',
          move: 'Trovão de Fogo',
          creature: 'Faiscolosso',
          moveType: 'fogo',
          dmg: { type: 'num', value: 22 },
          acc: { type: 'num', value: 90 },
          fx: 'raio',
          color: '#ffd43b',
        },
        { type: 'gk:pkmTypeChart', atk: 'fogo', def: 'planta', mult: { type: 'num', value: 2 } },
        {
          type: 'gk:pkmTypeChart',
          atk: 'planta',
          def: 'fogo',
          mult: { type: 'num', value: 0.5 },
        },
        { type: 'gk:pkmTypeChart', atk: 'água', def: 'fogo', mult: { type: 'num', value: 2 } },
        { type: 'gk:pkmTypeChart', atk: 'fogo', def: 'água', mult: { type: 'num', value: 0.5 } },
        { type: 'gk:pkmTypeChart', atk: 'planta', def: 'água', mult: { type: 'num', value: 2 } },
        {
          type: 'gk:pkmTypeChart',
          atk: 'água',
          def: 'planta',
          mult: { type: 'num', value: 0.5 },
        },
        { type: 'gk:pkmCatchDifficulty', creature: 'Faiscolosso', level: 'difícil' },
        { type: 'gk:pkmGive', creature: 'Faisco', level: { type: 'num', value: 5 } },
        { type: 'gk:pkmGive', creature: 'Gotinha', level: { type: 'num', value: 5 } },
        { type: 'gk:pkmGive', creature: 'Brotinho', level: { type: 'num', value: 5 } },
        {
          type: 'gk:pkmGiveBall',
          count: { type: 'num', value: 5 },
          power: { type: 'num', value: 65 },
        },
        {
          type: 'gk:defineRegion',
          name: 'fonte',
          x: { type: 'num', value: 50 },
          y: { type: 'num', value: 40 },
          w: { type: 'num', value: 130 },
          h: { type: 'num', value: 110 },
        },
        {
          type: 'gk:defineRegion',
          name: 'grama',
          x: { type: 'num', value: 660 },
          y: { type: 'num', value: 360 },
          w: { type: 'num', value: 240 },
          h: { type: 'num', value: 150 },
        },
        {
          type: 'gk:defineMold',
          name: 'rival',
          w: { type: 'num', value: 44 },
          h: { type: 'num', value: 56 },
          health: { type: 'num', value: 1 },
          speed: { type: 'num', value: 0 },
          damage: { type: 'num', value: 0 },
          color: '#e03131',
          image: '',
          look: 'rival',
        },
        {
          type: 'gk:spawnNamed',
          varName: 'rival',
          mold: 'rival',
          x: { type: 'num', value: 760 },
          y: { type: 'num', value: 230 },
        },
        {
          type: 'gk:createCharacter',
          varName: 'heroi',
          image: '',
          w: { type: 'num', value: 44 },
          h: { type: 'num', value: 56 },
          speed: { type: 'num', value: 240 },
          color: '#1971c2',
        },
        {
          type: 'gk:placeCharacter',
          charVar: 'heroi',
          x: { type: 'num', value: 140 },
          y: { type: 'num', value: 420 },
        },
        {
          type: 'gk:setHitbox',
          charVar: 'heroi',
          ox: { type: 'num', value: 8 },
          oy: { type: 'num', value: 8 },
          w: { type: 'num', value: 28 },
          h: { type: 'num', value: 44 },
        },
        { type: 'gk:stateLook', charVar: 'heroi', state: 'parado', look: 'treinadora' },
        { type: 'gk:stateLook', charVar: 'heroi', state: 'andando', look: 'treinadora' },
      ],
      events: [
        {
          type: 'gk:onEvent',
          event: 'monstrinho:pegou',
          body: [{ type: 'gk:playEffect', fx: 'win' }],
        },
      ],
      loops: [
        {
          type: 'gk:onUpdate',
          dtName: 'dt',
          body: [
            {
              type: 'if',
              cond: { type: 'gk:pkmCaught' },
              then: [{ type: 'gk:setState', name: 'vitoria' }],
            },
            { type: 'gk:moveWithKeys', charVar: 'heroi', dtVar: 'dt' },
            { type: 'gk:keepOnScreen', charVar: 'heroi' },
            { type: 'gk:autoAnimate', charVar: 'heroi' },
            {
              type: 'if',
              cond: {
                type: 'logical',
                op: '&&',
                left: { type: 'gk:charactersTouch', aVar: 'heroi', bVar: 'rival' },
                right: { type: 'gk:keyPressed', key: ' ' },
              },
              then: [
                { type: 'gk:playEffect', fx: 'click' },
                {
                  type: 'gk:pkmBattleTrainer',
                  name: 'Alice',
                  body: [
                    {
                      type: 'gk:pkmTrainerCreature',
                      creature: 'Folhito',
                      level: { type: 'num', value: 5 },
                    },
                    {
                      type: 'gk:pkmTrainerCreature',
                      creature: 'Pingo',
                      level: { type: 'num', value: 6 },
                    },
                    {
                      type: 'gk:pkmTrainerCreature',
                      creature: 'Braseiro',
                      level: { type: 'num', value: 7 },
                    },
                  ],
                },
              ],
            },
            {
              type: 'gk:everySeconds',
              seconds: { type: 'num', value: 1.5 },
              body: [
                {
                  type: 'if',
                  cond: {
                    type: 'binop',
                    op: '>',
                    left: { type: 'gk:overlapPercent', charVar: 'heroi', region: 'fonte' },
                    right: { type: 'num', value: 50 },
                  },
                  then: [
                    { type: 'gk:pkmHealTeam' },
                    { type: 'gk:playEffect', fx: 'powerup' },
                    {
                      type: 'gk:floatText',
                      text: { type: 'str', value: 'Time curado!' },
                      x: { type: 'gk:charX', charVar: 'heroi' },
                      y: {
                        type: 'binop',
                        op: '-',
                        left: { type: 'gk:charY', charVar: 'heroi' },
                        right: { type: 'num', value: 20 },
                      },
                      color: '#e7f5ff',
                      size: { type: 'num', value: 18 },
                    },
                  ],
                },
              ],
            },
            {
              type: 'gk:everySeconds',
              seconds: { type: 'num', value: 1 },
              body: [
                {
                  type: 'if',
                  cond: {
                    type: 'logical',
                    op: '&&',
                    left: {
                      type: 'binop',
                      op: '>',
                      left: { type: 'gk:overlapPercent', charVar: 'heroi', region: 'grama' },
                      right: { type: 'num', value: 50 },
                    },
                    right: { type: 'gk:chance', percent: { type: 'num', value: 35 } },
                  },
                  then: [
                    {
                      type: 'gk:pkmBattleWild',
                      creature: 'Faiscolosso',
                      level: { type: 'num', value: 9 },
                    },
                  ],
                },
              ],
            },
          ],
        },
        {
          type: 'gk:onDraw',
          ctxName: 'ctx',
          body: [
            { type: 'gk:drawBackground', color: '#8fce77', grid: false },
            {
              type: 'gk:drawLook',
              look: 'fonte',
              x: { type: 'num', value: 50 },
              y: { type: 'num', value: 40 },
              w: { type: 'num', value: 130 },
              h: { type: 'num', value: 110 },
            },
            {
              type: 'forRange',
              varName: 'i',
              from: { type: 'num', value: 0 },
              to: { type: 'num', value: 4 },
              step: { type: 'num', value: 1 },
              body: [
                {
                  type: 'gk:drawLook',
                  look: 'grama',
                  x: {
                    type: 'binop',
                    op: '+',
                    left: { type: 'num', value: 660 },
                    right: {
                      type: 'binop',
                      op: '*',
                      left: { type: 'var', name: 'i' },
                      right: { type: 'num', value: 60 },
                    },
                  },
                  y: { type: 'num', value: 366 },
                  w: { type: 'num', value: 56 },
                  h: { type: 'num', value: 56 },
                },
                {
                  type: 'gk:drawLook',
                  look: 'grama',
                  x: {
                    type: 'binop',
                    op: '+',
                    left: { type: 'num', value: 690 },
                    right: {
                      type: 'binop',
                      op: '*',
                      left: { type: 'var', name: 'i' },
                      right: { type: 'num', value: 60 },
                    },
                  },
                  y: { type: 'num', value: 440 },
                  w: { type: 'num', value: 56 },
                  h: { type: 'num', value: 56 },
                },
              ],
            },
            { type: 'gk:drawActive', mold: 'rival' },
            { type: 'gk:drawCharacter', charVar: 'heroi' },
          ],
        },
        {
          type: 'gk:onDrawHud',
          ctxName: 'ctx',
          body: [
            {
              type: 'gk:pkmDrawTeam',
              x: { type: 'num', value: 16 },
              y: { type: 'num', value: 14 },
            },
            {
              type: 'canvasFillStyle',
              ctxVar: 'ctx',
              color: { type: 'color', value: '#14331a' },
            },
            { type: 'canvasFont', ctxVar: 'ctx', size: 16, family: 'sans-serif' },
            {
              type: 'canvasFillText',
              ctxVar: 'ctx',
              text: {
                type: 'binop',
                op: '+',
                left: { type: 'str', value: 'Bolas de captura: ' },
                right: { type: 'gk:pkmBallCount' },
              },
              x: { type: 'num', value: 20 },
              y: { type: 'num', value: 128 },
            },
            {
              type: 'canvasFillText',
              ctxVar: 'ctx',
              text: { type: 'str', value: 'Fonte: cura o time. Mato fundo: monstrinho raro!' },
              x: { type: 'num', value: 20 },
              y: { type: 'num', value: 528 },
            },
          ],
        },
      ],
    },
  },
})
