import type { ExtensionExample } from '#extensions'

/**
 * Exemplo bundlado: "Duelo de Heróis Profissional" — o fighting-game do Chris
 * Courses (samurai contra kenji) recriado com o 🥊 Kit Luta do motor avançado (o
 * mesmo kit do "Duelo dos Bonecos"), SEM assets: os dois heróis, o chão e o
 * cenário são desenhados por código (defineLook + drawBackground). Mostra a
 * arquitetura do kit num duelo de DOIS jogadores humanos: cada herói anda, pula,
 * agacha e defende (lutaFighter), tem soco rápido, chute pesado e um especial de
 * barra cheia (lutaMove + lutaAttack), a vida cai por golpe e as duas barras e o
 * relógio saem no lutaDrawHud. Vence a melhor de 3 rounds; o luta:acabou escreve
 * o vencedor na tela de fim.
 *
 * ⚠️ A IR foi GERADA pelo parser real a partir do script achatado (o fonte vive
 * em __gen_dueloDeHeroisProfissional.ts — se o parser mudar a saída, o drift test
 * dueloDeHeroisProfissionalExample.test.ts manda re-embutir aqui).
 */
export const dueloDeHeroisProfissionalExample: ExtensionExample = {
  name: 'Duelo de Heróis Profissional',
  experience: 'game',
  description:
    'A luta um contra um do motor avançado para dois jogadores: cada herói anda, pula, defende e tem soco, chute e um especial de barra cheia. A vida cai a cada golpe e vence a melhor de 3 rounds.',
  ir: {
    html: [],
    css: [],
    extensions: [{ extensionId: 'game-2d-advanced' }],
    version: 2,
    behavior: {
      molds: [
        {
          type: 'gk:defineLook',
          name: 'samurai',
          ctxName: 'ctx',
          body: [
            {
              type: 'canvasFillStyle',
              ctxVar: 'ctx',
              color: { type: 'color', value: '#e8d9b5' },
            },
            {
              type: 'canvasFillRect',
              ctxVar: 'ctx',
              x: { type: 'num', value: 14 },
              y: { type: 'num', value: 4 },
              w: { type: 'num', value: 22 },
              h: { type: 'num', value: 20 },
            },
            {
              type: 'canvasFillStyle',
              ctxVar: 'ctx',
              color: { type: 'color', value: '#b03a2e' },
            },
            {
              type: 'canvasFillRect',
              ctxVar: 'ctx',
              x: { type: 'num', value: 10 },
              y: { type: 'num', value: 0 },
              w: { type: 'num', value: 30 },
              h: { type: 'num', value: 8 },
            },
            {
              type: 'canvasFillStyle',
              ctxVar: 'ctx',
              color: { type: 'color', value: '#2b2d42' },
            },
            {
              type: 'canvasFillRect',
              ctxVar: 'ctx',
              x: { type: 'num', value: 20 },
              y: { type: 'num', value: 12 },
              w: { type: 'num', value: 5 },
              h: { type: 'num', value: 5 },
            },
            {
              type: 'canvasFillStyle',
              ctxVar: 'ctx',
              color: { type: 'color', value: '#3a6ea5' },
            },
            {
              type: 'canvasFillRect',
              ctxVar: 'ctx',
              x: { type: 'num', value: 10 },
              y: { type: 'num', value: 24 },
              w: { type: 'num', value: 30 },
              h: { type: 'num', value: 46 },
            },
            {
              type: 'canvasFillStyle',
              ctxVar: 'ctx',
              color: { type: 'color', value: '#284b73' },
            },
            {
              type: 'canvasFillRect',
              ctxVar: 'ctx',
              x: { type: 'num', value: 10 },
              y: { type: 'num', value: 24 },
              w: { type: 'num', value: 30 },
              h: { type: 'num', value: 8 },
            },
            {
              type: 'canvasFillStyle',
              ctxVar: 'ctx',
              color: { type: 'color', value: '#c0c8d0' },
            },
            {
              type: 'canvasFillRect',
              ctxVar: 'ctx',
              x: { type: 'num', value: 40 },
              y: { type: 'num', value: 18 },
              w: { type: 'num', value: 6 },
              h: { type: 'num', value: 54 },
            },
            {
              type: 'canvasFillStyle',
              ctxVar: 'ctx',
              color: { type: 'color', value: '#2a2f45' },
            },
            {
              type: 'canvasFillRect',
              ctxVar: 'ctx',
              x: { type: 'num', value: 14 },
              y: { type: 'num', value: 70 },
              w: { type: 'num', value: 9 },
              h: { type: 'num', value: 40 },
            },
            {
              type: 'canvasFillRect',
              ctxVar: 'ctx',
              x: { type: 'num', value: 28 },
              y: { type: 'num', value: 70 },
              w: { type: 'num', value: 9 },
              h: { type: 'num', value: 40 },
            },
          ],
          baseW: { type: 'num', value: 50 },
          baseH: { type: 'num', value: 110 },
        },
        {
          type: 'gk:defineLook',
          name: 'ninja',
          ctxName: 'ctx',
          body: [
            {
              type: 'canvasFillStyle',
              ctxVar: 'ctx',
              color: { type: 'color', value: '#2a2f45' },
            },
            {
              type: 'canvasFillRect',
              ctxVar: 'ctx',
              x: { type: 'num', value: 14 },
              y: { type: 'num', value: 4 },
              w: { type: 'num', value: 22 },
              h: { type: 'num', value: 20 },
            },
            {
              type: 'canvasFillStyle',
              ctxVar: 'ctx',
              color: { type: 'color', value: '#7b2d8e' },
            },
            {
              type: 'canvasFillRect',
              ctxVar: 'ctx',
              x: { type: 'num', value: 10 },
              y: { type: 'num', value: 0 },
              w: { type: 'num', value: 30 },
              h: { type: 'num', value: 8 },
            },
            {
              type: 'canvasFillStyle',
              ctxVar: 'ctx',
              color: { type: 'color', value: '#ff5e5e' },
            },
            {
              type: 'canvasFillRect',
              ctxVar: 'ctx',
              x: { type: 'num', value: 20 },
              y: { type: 'num', value: 12 },
              w: { type: 'num', value: 6 },
              h: { type: 'num', value: 4 },
            },
            {
              type: 'canvasFillStyle',
              ctxVar: 'ctx',
              color: { type: 'color', value: '#8e44ad' },
            },
            {
              type: 'canvasFillRect',
              ctxVar: 'ctx',
              x: { type: 'num', value: 10 },
              y: { type: 'num', value: 24 },
              w: { type: 'num', value: 30 },
              h: { type: 'num', value: 46 },
            },
            {
              type: 'canvasFillStyle',
              ctxVar: 'ctx',
              color: { type: 'color', value: '#6c3483' },
            },
            {
              type: 'canvasFillRect',
              ctxVar: 'ctx',
              x: { type: 'num', value: 10 },
              y: { type: 'num', value: 24 },
              w: { type: 'num', value: 30 },
              h: { type: 'num', value: 8 },
            },
            {
              type: 'canvasFillStyle',
              ctxVar: 'ctx',
              color: { type: 'color', value: '#c0c8d0' },
            },
            {
              type: 'canvasFillRect',
              ctxVar: 'ctx',
              x: { type: 'num', value: 4 },
              y: { type: 'num', value: 18 },
              w: { type: 'num', value: 6 },
              h: { type: 'num', value: 54 },
            },
            {
              type: 'canvasFillStyle',
              ctxVar: 'ctx',
              color: { type: 'color', value: '#22283a' },
            },
            {
              type: 'canvasFillRect',
              ctxVar: 'ctx',
              x: { type: 'num', value: 14 },
              y: { type: 'num', value: 70 },
              w: { type: 'num', value: 9 },
              h: { type: 'num', value: 40 },
            },
            {
              type: 'canvasFillRect',
              ctxVar: 'ctx',
              x: { type: 'num', value: 28 },
              y: { type: 'num', value: 70 },
              w: { type: 'num', value: 9 },
              h: { type: 'num', value: 40 },
            },
          ],
          baseW: { type: 'num', value: 50 },
          baseH: { type: 'num', value: 110 },
        },
        {
          type: 'gk:defineLook',
          name: 'loja',
          ctxName: 'ctx',
          body: [
            {
              type: 'canvasFillStyle',
              ctxVar: 'ctx',
              color: { type: 'color', value: '#5a4a7a' },
            },
            {
              type: 'canvasFillRect',
              ctxVar: 'ctx',
              x: { type: 'num', value: 0 },
              y: { type: 'num', value: 40 },
              w: { type: 'num', value: 160 },
              h: { type: 'num', value: 100 },
            },
            {
              type: 'canvasFillStyle',
              ctxVar: 'ctx',
              color: { type: 'color', value: '#3d3357' },
            },
            {
              type: 'canvasFillRect',
              ctxVar: 'ctx',
              x: { type: 'num', value: 0 },
              y: { type: 'num', value: 40 },
              w: { type: 'num', value: 160 },
              h: { type: 'num', value: 14 },
            },
            {
              type: 'canvasFillStyle',
              ctxVar: 'ctx',
              color: { type: 'color', value: '#2a2340' },
            },
            {
              type: 'canvasFillRect',
              ctxVar: 'ctx',
              x: { type: 'num', value: 60 },
              y: { type: 'num', value: 80 },
              w: { type: 'num', value: 40 },
              h: { type: 'num', value: 60 },
            },
            {
              type: 'canvasFillStyle',
              ctxVar: 'ctx',
              color: { type: 'color', value: '#ffd166' },
            },
            {
              type: 'canvasFillRect',
              ctxVar: 'ctx',
              x: { type: 'num', value: 20 },
              y: { type: 'num', value: 64 },
              w: { type: 'num', value: 26 },
              h: { type: 'num', value: 20 },
            },
            {
              type: 'canvasFillRect',
              ctxVar: 'ctx',
              x: { type: 'num', value: 114 },
              y: { type: 'num', value: 64 },
              w: { type: 'num', value: 26 },
              h: { type: 'num', value: 20 },
            },
          ],
          baseW: { type: 'num', value: 160 },
          baseH: { type: 'num', value: 140 },
        },
        {
          type: 'gk:defineMold',
          name: 'chao',
          w: { type: 'num', value: 960 },
          h: { type: 'num', value: 60 },
          health: { type: 'num', value: 1 },
          speed: { type: 'num', value: 0 },
          damage: { type: 'num', value: 0 },
          color: '#3d2b52',
          image: '',
          look: '',
        },
      ],
      start: [
        {
          type: 'gk:setup',
          w: { type: 'num', value: 960 },
          h: { type: 'num', value: 540 },
          bg: '#241733',
          accent: '#ffd166',
        },
        {
          type: 'gk:setScreenText',
          screen: 'menu',
          title: { type: 'str', value: 'Duelo de Heróis Profissional' },
          text: {
            type: 'str',
            value:
              'Jogador 1: A/D anda, W pula, S agacha, F defende, G soco, H chute, J especial. Jogador 2: setas anda e pula, 0 defende, teclas 1 soco, 2 chute, 3 especial. Melhor de 3 rounds!',
          },
          button: { type: 'str', value: 'Lutar' },
        },
        {
          type: 'gk:createCharacter',
          varName: 'heroi1',
          image: '',
          w: { type: 'num', value: 50 },
          h: { type: 'num', value: 110 },
          speed: { type: 'num', value: 260 },
          color: '#4a9eff',
        },
        {
          type: 'gk:createCharacter',
          varName: 'heroi2',
          image: '',
          w: { type: 'num', value: 50 },
          h: { type: 'num', value: 110 },
          speed: { type: 'num', value: 260 },
          color: '#e0526a',
        },
        { type: 'gk:stateLook', charVar: 'heroi1', state: 'parado', look: 'samurai' },
        { type: 'gk:stateLook', charVar: 'heroi2', state: 'parado', look: 'ninja' },
        {
          type: 'gk:lutaMove',
          name: 'soco',
          charVar: 'heroi1',
          speed: 'rápido',
          damage: { type: 'num', value: 8 },
          range: { type: 'num', value: 80 },
          pierce: false,
          special: false,
        },
        {
          type: 'gk:lutaMove',
          name: 'chute',
          charVar: 'heroi1',
          speed: 'pesado',
          damage: { type: 'num', value: 16 },
          range: { type: 'num', value: 100 },
          pierce: false,
          special: false,
        },
        {
          type: 'gk:lutaMove',
          name: 'especial',
          charVar: 'heroi1',
          speed: 'médio',
          damage: { type: 'num', value: 26 },
          range: { type: 'num', value: 120 },
          pierce: true,
          special: true,
        },
        {
          type: 'gk:lutaMove',
          name: 'soco',
          charVar: 'heroi2',
          speed: 'rápido',
          damage: { type: 'num', value: 8 },
          range: { type: 'num', value: 80 },
          pierce: false,
          special: false,
        },
        {
          type: 'gk:lutaMove',
          name: 'chute',
          charVar: 'heroi2',
          speed: 'pesado',
          damage: { type: 'num', value: 16 },
          range: { type: 'num', value: 100 },
          pierce: false,
          special: false,
        },
        {
          type: 'gk:lutaMove',
          name: 'especial',
          charVar: 'heroi2',
          speed: 'médio',
          damage: { type: 'num', value: 26 },
          range: { type: 'num', value: 120 },
          pierce: true,
          special: true,
        },
        {
          type: 'gk:spawnFromMold',
          mold: 'chao',
          x: { type: 'num', value: 0 },
          y: { type: 'num', value: 480 },
        },
        {
          type: 'gk:placeCharacter',
          charVar: 'heroi1',
          x: { type: 'num', value: 230 },
          y: { type: 'num', value: 370 },
        },
        {
          type: 'gk:placeCharacter',
          charVar: 'heroi2',
          x: { type: 'num', value: 680 },
          y: { type: 'num', value: 370 },
        },
        {
          type: 'gk:lutaMatch',
          p1Var: 'heroi1',
          p2Var: 'heroi2',
          rounds: { type: 'num', value: 3 },
          seconds: { type: 'num', value: 40 },
        },
      ],
      events: [
        {
          type: 'gk:onEvent',
          event: 'luta:acabou',
          body: [
            {
              type: 'gk:setScreenText',
              screen: 'fim',
              title: { type: 'str', value: 'Fim da luta!' },
              text: {
                type: 'binop',
                op: '+',
                left: {
                  type: 'binop',
                  op: '+',
                  left: { type: 'str', value: 'Venceu o ' },
                  right: { type: 'gk:lutaWinner' },
                },
                right: { type: 'str', value: '. Bora de revanche?' },
              },
              button: { type: 'str', value: 'Revanche' },
            },
            { type: 'gk:playEffect', fx: 'win' },
          ],
        },
      ],
      loops: [
        {
          type: 'gk:onUpdate',
          dtName: 'dt',
          body: [
            {
              type: 'gk:lutaFighter',
              charVar: 'heroi1',
              left: 'a',
              right: 'd',
              jump: 'w',
              crouch: 's',
              guard: 'f',
              dtVar: 'dt',
            },
            {
              type: 'gk:lutaFighter',
              charVar: 'heroi2',
              left: 'seta esquerda',
              right: 'seta direita',
              jump: 'seta para cima',
              crouch: 'seta para baixo',
              guard: '0',
              dtVar: 'dt',
            },
            {
              type: 'if',
              cond: { type: 'gk:keyPressed', key: 'g' },
              then: [{ type: 'gk:lutaAttack', charVar: 'heroi1', move: 'soco' }],
            },
            {
              type: 'if',
              cond: { type: 'gk:keyPressed', key: 'h' },
              then: [{ type: 'gk:lutaAttack', charVar: 'heroi1', move: 'chute' }],
            },
            {
              type: 'if',
              cond: { type: 'gk:keyPressed', key: 'j' },
              then: [{ type: 'gk:lutaAttack', charVar: 'heroi1', move: 'especial' }],
            },
            {
              type: 'if',
              cond: { type: 'gk:keyPressed', key: '1' },
              then: [{ type: 'gk:lutaAttack', charVar: 'heroi2', move: 'soco' }],
            },
            {
              type: 'if',
              cond: { type: 'gk:keyPressed', key: '2' },
              then: [{ type: 'gk:lutaAttack', charVar: 'heroi2', move: 'chute' }],
            },
            {
              type: 'if',
              cond: { type: 'gk:keyPressed', key: '3' },
              then: [{ type: 'gk:lutaAttack', charVar: 'heroi2', move: 'especial' }],
            },
            { type: 'gk:collideGroup', charVar: 'heroi1', mold: 'chao' },
            { type: 'gk:collideGroup', charVar: 'heroi2', mold: 'chao' },
          ],
        },
        {
          type: 'gk:onDraw',
          ctxName: 'ctx',
          body: [
            { type: 'gk:drawBackground', color: '#241733', grid: false },
            {
              type: 'gk:drawLook',
              look: 'loja',
              x: { type: 'num', value: 640 },
              y: { type: 'num', value: 300 },
              w: { type: 'num', value: 160 },
              h: { type: 'num', value: 140 },
            },
            { type: 'gk:drawActive', mold: 'chao' },
            { type: 'gk:drawCharacter', charVar: 'heroi1' },
            { type: 'gk:drawCharacter', charVar: 'heroi2' },
          ],
        },
        {
          type: 'gk:onDrawHud',
          ctxName: 'ctx',
          body: [{ type: 'gk:lutaDrawHud' }],
        },
      ],
    },
  },
}
