import type { ExtensionExample } from '#extensions'

/**
 * Exemplo bundlado: "Portas do Castelo Profissional" — o kings-and-pigs do Chris
 * Courses (o rei que percorre o castelo e entra na porta para trocar de fase)
 * recriado com o 🏃 Kit Plataforma do motor avançado (o mesmo kit do "Salto na
 * Floresta"), SEM assets: o rei, o chão de pedra e as portas são desenhados por
 * código (defineLook + drawBackground). Mostra a arquitetura do kit num jogo de
 * fases: andar e pular com colisão (platformerHero + collideGroup), TRÊS salas
 * em regiões lado a lado (defineRegion) num mundo largo com a câmera seguindo
 * (cameraFollow), e a porta de cada sala que troca de fase (isInside + setState /
 * setCheckpoint + respawn). A porta da terceira sala é a saída: a vitória.
 *
 * ⚠️ A IR foi GERADA pelo parser real a partir do script achatado (o fonte vive
 * em __gen_portasDoCasteloProfissional.ts — se o parser mudar a saída, o drift
 * test portasDoCasteloProfissionalExample.test.ts manda re-embutir aqui).
 */
export const portasDoCasteloProfissionalExample: ExtensionExample = {
  name: 'Portas do Castelo Profissional',
  experience: 'game',
  description:
    'A plataforma de fases do motor avançado: o rei anda e pula com colisão por 3 salas de um castelo. Encoste na porta de cada sala para passar de fase. A porta da terceira sala é a saída e a vitória.',
  ir: {
    html: [],
    css: [],
    extensions: [{ extensionId: 'game-2d-advanced' }],
    version: 2,
    behavior: {
      start: [
        {
          type: 'gk:setup',
          w: { type: 'num', value: 960 },
          h: { type: 'num', value: 540 },
          bg: '#2b2136',
          accent: '#ffd166',
        },
        {
          type: 'gk:setScreenText',
          screen: 'menu',
          title: { type: 'str', value: 'Portas do Castelo Profissional' },
          text: {
            type: 'str',
            value:
              'Use as setas para andar e pular. Chegue na porta de cada sala para passar de fase. São 3 salas até a saída!',
          },
          button: { type: 'str', value: 'Entrar' },
        },
        {
          type: 'gk:setScreenText',
          screen: 'vitoria',
          title: { type: 'str', value: 'Você escapou do castelo!' },
          text: {
            type: 'str',
            value: 'Passou pelas 3 salas e achou a porta de saída. O rei está livre!',
          },
          button: { type: 'str', value: 'Jogar de novo' },
        },
        {
          type: 'gk:defineLook',
          name: 'rei',
          ctxName: 'ctx',
          body: [
            {
              type: 'canvasFillStyle',
              ctxVar: 'ctx',
              color: { type: 'color', value: '#f2d16b' },
            },
            {
              type: 'canvasFillRect',
              ctxVar: 'ctx',
              x: { type: 'num', value: 4 },
              y: { type: 'num', value: 0 },
              w: { type: 'num', value: 24 },
              h: { type: 'num', value: 8 },
            },
            {
              type: 'canvasFillStyle',
              ctxVar: 'ctx',
              color: { type: 'color', value: '#e8c48a' },
            },
            {
              type: 'canvasFillRect',
              ctxVar: 'ctx',
              x: { type: 'num', value: 6 },
              y: { type: 'num', value: 8 },
              w: { type: 'num', value: 20 },
              h: { type: 'num', value: 14 },
            },
            {
              type: 'canvasFillStyle',
              ctxVar: 'ctx',
              color: { type: 'color', value: '#2b2d42' },
            },
            {
              type: 'canvasFillRect',
              ctxVar: 'ctx',
              x: { type: 'num', value: 11 },
              y: { type: 'num', value: 13 },
              w: { type: 'num', value: 4 },
              h: { type: 'num', value: 4 },
            },
            {
              type: 'canvasFillRect',
              ctxVar: 'ctx',
              x: { type: 'num', value: 18 },
              y: { type: 'num', value: 13 },
              w: { type: 'num', value: 4 },
              h: { type: 'num', value: 4 },
            },
            {
              type: 'canvasFillStyle',
              ctxVar: 'ctx',
              color: { type: 'color', value: '#3a6ea5' },
            },
            {
              type: 'canvasFillRect',
              ctxVar: 'ctx',
              x: { type: 'num', value: 4 },
              y: { type: 'num', value: 22 },
              w: { type: 'num', value: 24 },
              h: { type: 'num', value: 20 },
            },
            {
              type: 'canvasFillStyle',
              ctxVar: 'ctx',
              color: { type: 'color', value: '#284b73' },
            },
            {
              type: 'canvasFillRect',
              ctxVar: 'ctx',
              x: { type: 'num', value: 4 },
              y: { type: 'num', value: 22 },
              w: { type: 'num', value: 24 },
              h: { type: 'num', value: 6 },
            },
            {
              type: 'canvasFillStyle',
              ctxVar: 'ctx',
              color: { type: 'color', value: '#2a2f45' },
            },
            {
              type: 'canvasFillRect',
              ctxVar: 'ctx',
              x: { type: 'num', value: 7 },
              y: { type: 'num', value: 42 },
              w: { type: 'num', value: 7 },
              h: { type: 'num', value: 12 },
            },
            {
              type: 'canvasFillRect',
              ctxVar: 'ctx',
              x: { type: 'num', value: 18 },
              y: { type: 'num', value: 42 },
              w: { type: 'num', value: 7 },
              h: { type: 'num', value: 12 },
            },
          ],
          baseW: { type: 'num', value: 32 },
          baseH: { type: 'num', value: 54 },
        },
        {
          type: 'gk:defineLook',
          name: 'pedra',
          ctxName: 'ctx',
          body: [
            {
              type: 'canvasFillStyle',
              ctxVar: 'ctx',
              color: { type: 'color', value: '#4a4258' },
            },
            {
              type: 'canvasFillRect',
              ctxVar: 'ctx',
              x: { type: 'num', value: 0 },
              y: { type: 'num', value: 0 },
              w: { type: 'num', value: 120 },
              h: { type: 'num', value: 40 },
            },
            {
              type: 'canvasFillStyle',
              ctxVar: 'ctx',
              color: { type: 'color', value: '#3a3446' },
            },
            {
              type: 'canvasFillRect',
              ctxVar: 'ctx',
              x: { type: 'num', value: 0 },
              y: { type: 'num', value: 0 },
              w: { type: 'num', value: 120 },
              h: { type: 'num', value: 5 },
            },
            {
              type: 'canvasFillRect',
              ctxVar: 'ctx',
              x: { type: 'num', value: 0 },
              y: { type: 'num', value: 20 },
              w: { type: 'num', value: 120 },
              h: { type: 'num', value: 2 },
            },
            {
              type: 'canvasFillRect',
              ctxVar: 'ctx',
              x: { type: 'num', value: 40 },
              y: { type: 'num', value: 0 },
              w: { type: 'num', value: 3 },
              h: { type: 'num', value: 20 },
            },
            {
              type: 'canvasFillRect',
              ctxVar: 'ctx',
              x: { type: 'num', value: 84 },
              y: { type: 'num', value: 20 },
              w: { type: 'num', value: 3 },
              h: { type: 'num', value: 20 },
            },
          ],
          baseW: { type: 'num', value: 120 },
          baseH: { type: 'num', value: 40 },
        },
        {
          type: 'gk:defineLook',
          name: 'porta',
          ctxName: 'ctx',
          body: [
            {
              type: 'canvasFillStyle',
              ctxVar: 'ctx',
              color: { type: 'color', value: '#5a3d2b' },
            },
            {
              type: 'canvasFillRect',
              ctxVar: 'ctx',
              x: { type: 'num', value: 0 },
              y: { type: 'num', value: 0 },
              w: { type: 'num', value: 48 },
              h: { type: 'num', value: 72 },
            },
            {
              type: 'canvasFillStyle',
              ctxVar: 'ctx',
              color: { type: 'color', value: '#3a2718' },
            },
            {
              type: 'canvasFillRect',
              ctxVar: 'ctx',
              x: { type: 'num', value: 6 },
              y: { type: 'num', value: 6 },
              w: { type: 'num', value: 36 },
              h: { type: 'num', value: 66 },
            },
            {
              type: 'canvasFillStyle',
              ctxVar: 'ctx',
              color: { type: 'color', value: '#ffd166' },
            },
            {
              type: 'canvasFillRect',
              ctxVar: 'ctx',
              x: { type: 'num', value: 34 },
              y: { type: 'num', value: 36 },
              w: { type: 'num', value: 6 },
              h: { type: 'num', value: 6 },
            },
          ],
          baseW: { type: 'num', value: 48 },
          baseH: { type: 'num', value: 72 },
        },
        {
          type: 'gk:setJumpFeel',
          coyote: { type: 'num', value: 0.1 },
          buffer: { type: 'num', value: 0.1 },
          hold: { type: 'num', value: 0.3 },
          gravity: { type: 'num', value: 2200 },
        },
        {
          type: 'gk:defineMold',
          name: 'chao',
          w: { type: 'num', value: 120 },
          h: { type: 'num', value: 40 },
          health: { type: 'num', value: 1 },
          speed: { type: 'num', value: 0 },
          damage: { type: 'num', value: 0 },
          color: '#4a4258',
          image: '',
          look: 'pedra',
        },
        {
          type: 'gk:defineEffect',
          name: 'poeira',
          count: { type: 'num', value: 8 },
          color: '#c9b8e0',
          size: { type: 'num', value: 3 },
          life: { type: 'num', value: 0.4 },
          speed: { type: 'num', value: 100 },
          gravity: { type: 'num', value: 300 },
        },
        {
          type: 'gk:createCharacter',
          varName: 'rei',
          image: '',
          w: { type: 'num', value: 32 },
          h: { type: 'num', value: 54 },
          speed: { type: 'num', value: 210 },
          color: '#f2d16b',
        },
        { type: 'gk:stateLook', charVar: 'rei', state: 'parado', look: 'rei' },
        { type: 'var', name: 'fase', value: { type: 'num', value: 1 } },
        {
          type: 'gk:setCheckpoint',
          x: { type: 'num', value: 80 },
          y: { type: 'num', value: 440 },
        },
        { type: 'gk:respawn', charVar: 'rei' },
        {
          type: 'gk:spawnFromMold',
          mold: 'chao',
          x: { type: 'num', value: 0 },
          y: { type: 'num', value: 500 },
        },
        {
          type: 'gk:spawnFromMold',
          mold: 'chao',
          x: { type: 'num', value: 120 },
          y: { type: 'num', value: 500 },
        },
        {
          type: 'gk:spawnFromMold',
          mold: 'chao',
          x: { type: 'num', value: 240 },
          y: { type: 'num', value: 500 },
        },
        {
          type: 'gk:spawnFromMold',
          mold: 'chao',
          x: { type: 'num', value: 360 },
          y: { type: 'num', value: 500 },
        },
        {
          type: 'gk:spawnFromMold',
          mold: 'chao',
          x: { type: 'num', value: 480 },
          y: { type: 'num', value: 500 },
        },
        {
          type: 'gk:spawnFromMold',
          mold: 'chao',
          x: { type: 'num', value: 600 },
          y: { type: 'num', value: 500 },
        },
        {
          type: 'gk:spawnFromMold',
          mold: 'chao',
          x: { type: 'num', value: 720 },
          y: { type: 'num', value: 500 },
        },
        {
          type: 'gk:spawnFromMold',
          mold: 'chao',
          x: { type: 'num', value: 840 },
          y: { type: 'num', value: 500 },
        },
        {
          type: 'gk:spawnFromMold',
          mold: 'chao',
          x: { type: 'num', value: 960 },
          y: { type: 'num', value: 500 },
        },
        {
          type: 'gk:spawnFromMold',
          mold: 'chao',
          x: { type: 'num', value: 1080 },
          y: { type: 'num', value: 500 },
        },
        {
          type: 'gk:spawnFromMold',
          mold: 'chao',
          x: { type: 'num', value: 1200 },
          y: { type: 'num', value: 500 },
        },
        {
          type: 'gk:spawnFromMold',
          mold: 'chao',
          x: { type: 'num', value: 1320 },
          y: { type: 'num', value: 500 },
        },
        {
          type: 'gk:spawnFromMold',
          mold: 'chao',
          x: { type: 'num', value: 1440 },
          y: { type: 'num', value: 500 },
        },
        {
          type: 'gk:spawnFromMold',
          mold: 'chao',
          x: { type: 'num', value: 1560 },
          y: { type: 'num', value: 500 },
        },
        {
          type: 'gk:spawnFromMold',
          mold: 'chao',
          x: { type: 'num', value: 1680 },
          y: { type: 'num', value: 500 },
        },
        {
          type: 'gk:spawnFromMold',
          mold: 'chao',
          x: { type: 'num', value: 1800 },
          y: { type: 'num', value: 500 },
        },
        {
          type: 'gk:spawnFromMold',
          mold: 'chao',
          x: { type: 'num', value: 1920 },
          y: { type: 'num', value: 500 },
        },
        {
          type: 'gk:spawnFromMold',
          mold: 'chao',
          x: { type: 'num', value: 2040 },
          y: { type: 'num', value: 500 },
        },
        {
          type: 'gk:spawnFromMold',
          mold: 'chao',
          x: { type: 'num', value: 2160 },
          y: { type: 'num', value: 500 },
        },
        {
          type: 'gk:spawnFromMold',
          mold: 'chao',
          x: { type: 'num', value: 2280 },
          y: { type: 'num', value: 500 },
        },
        {
          type: 'gk:spawnFromMold',
          mold: 'chao',
          x: { type: 'num', value: 2400 },
          y: { type: 'num', value: 500 },
        },
        {
          type: 'gk:spawnFromMold',
          mold: 'chao',
          x: { type: 'num', value: 2520 },
          y: { type: 'num', value: 500 },
        },
        {
          type: 'gk:spawnFromMold',
          mold: 'chao',
          x: { type: 'num', value: 2640 },
          y: { type: 'num', value: 500 },
        },
        {
          type: 'gk:spawnFromMold',
          mold: 'chao',
          x: { type: 'num', value: 2760 },
          y: { type: 'num', value: 500 },
        },
        {
          type: 'gk:spawnFromMold',
          mold: 'chao',
          x: { type: 'num', value: 520 },
          y: { type: 'num', value: 380 },
        },
        {
          type: 'gk:spawnFromMold',
          mold: 'chao',
          x: { type: 'num', value: 1300 },
          y: { type: 'num', value: 360 },
        },
        {
          type: 'gk:spawnFromMold',
          mold: 'chao',
          x: { type: 'num', value: 2280 },
          y: { type: 'num', value: 380 },
        },
        {
          type: 'gk:defineRegion',
          name: 'porta1',
          x: { type: 'num', value: 860 },
          y: { type: 'num', value: 428 },
          w: { type: 'num', value: 48 },
          h: { type: 'num', value: 72 },
        },
        {
          type: 'gk:defineRegion',
          name: 'porta2',
          x: { type: 'num', value: 1820 },
          y: { type: 'num', value: 428 },
          w: { type: 'num', value: 48 },
          h: { type: 'num', value: 72 },
        },
        {
          type: 'gk:defineRegion',
          name: 'saida',
          x: { type: 'num', value: 2820 },
          y: { type: 'num', value: 428 },
          w: { type: 'num', value: 48 },
          h: { type: 'num', value: 72 },
        },
        {
          type: 'gk:cameraFollow',
          charVar: 'rei',
          w: { type: 'num', value: 2900 },
          h: { type: 'num', value: 540 },
        },
      ],
      events: [
        {
          type: 'gk:onEvent',
          event: 'plataforma:pisou',
          body: [
            {
              type: 'gk:burst',
              effect: 'poeira',
              x: {
                type: 'binop',
                op: '+',
                left: { type: 'gk:charX', charVar: 'rei' },
                right: { type: 'num', value: 16 },
              },
              y: {
                type: 'binop',
                op: '+',
                left: { type: 'gk:charY', charVar: 'rei' },
                right: { type: 'num', value: 54 },
              },
            },
          ],
        },
      ],
      loops: [
        {
          type: 'gk:onUpdate',
          dtName: 'dt',
          body: [
            {
              type: 'gk:platformerHero',
              charVar: 'rei',
              speed: { type: 'num', value: 210 },
              force: { type: 'num', value: 700 },
              dtVar: 'dt',
            },
            { type: 'gk:collideGroup', charVar: 'rei', mold: 'chao' },
            { type: 'gk:platformerAnim', charVar: 'rei' },
            {
              type: 'if',
              cond: {
                type: 'logical',
                op: '&&',
                left: {
                  type: 'binop',
                  op: '===',
                  left: { type: 'var', name: 'fase' },
                  right: { type: 'num', value: 1 },
                },
                right: { type: 'gk:isInside', charVar: 'rei', region: 'porta1' },
              },
              then: [
                { type: 'assign', name: 'fase', value: { type: 'num', value: 2 } },
                {
                  type: 'gk:setCheckpoint',
                  x: { type: 'num', value: 1040 },
                  y: { type: 'num', value: 440 },
                },
                { type: 'gk:respawn', charVar: 'rei' },
                { type: 'gk:playEffect', fx: 'click' },
              ],
            },
            {
              type: 'if',
              cond: {
                type: 'logical',
                op: '&&',
                left: {
                  type: 'binop',
                  op: '===',
                  left: { type: 'var', name: 'fase' },
                  right: { type: 'num', value: 2 },
                },
                right: { type: 'gk:isInside', charVar: 'rei', region: 'porta2' },
              },
              then: [
                { type: 'assign', name: 'fase', value: { type: 'num', value: 3 } },
                {
                  type: 'gk:setCheckpoint',
                  x: { type: 'num', value: 2000 },
                  y: { type: 'num', value: 440 },
                },
                { type: 'gk:respawn', charVar: 'rei' },
                { type: 'gk:playEffect', fx: 'click' },
              ],
            },
            {
              type: 'if',
              cond: {
                type: 'logical',
                op: '&&',
                left: {
                  type: 'binop',
                  op: '===',
                  left: { type: 'var', name: 'fase' },
                  right: { type: 'num', value: 3 },
                },
                right: { type: 'gk:isInside', charVar: 'rei', region: 'saida' },
              },
              then: [{ type: 'gk:setState', name: 'vitoria' }],
            },
            {
              type: 'if',
              cond: {
                type: 'binop',
                op: '>',
                left: { type: 'gk:charY', charVar: 'rei' },
                right: { type: 'num', value: 620 },
              },
              then: [{ type: 'gk:respawn', charVar: 'rei' }],
            },
          ],
        },
        {
          type: 'gk:onDraw',
          ctxName: 'ctx',
          body: [
            { type: 'gk:drawBackground', color: '#2b2136', grid: false },
            { type: 'gk:drawActive', mold: 'chao' },
            {
              type: 'gk:drawLook',
              look: 'porta',
              x: { type: 'num', value: 860 },
              y: { type: 'num', value: 428 },
              w: { type: 'num', value: 48 },
              h: { type: 'num', value: 72 },
            },
            {
              type: 'gk:drawLook',
              look: 'porta',
              x: { type: 'num', value: 1820 },
              y: { type: 'num', value: 428 },
              w: { type: 'num', value: 48 },
              h: { type: 'num', value: 72 },
            },
            {
              type: 'gk:drawLook',
              look: 'porta',
              x: { type: 'num', value: 2820 },
              y: { type: 'num', value: 428 },
              w: { type: 'num', value: 48 },
              h: { type: 'num', value: 72 },
            },
            { type: 'gk:drawShadow', charVar: 'rei' },
            { type: 'gk:drawCharacter', charVar: 'rei' },
            { type: 'gk:drawEffects' },
          ],
        },
        {
          type: 'gk:onDrawHud',
          ctxName: 'ctx',
          body: [
            {
              type: 'canvasFillStyle',
              ctxVar: 'ctx',
              color: { type: 'color', value: '#ffffff' },
            },
            { type: 'canvasFont', ctxVar: 'ctx', size: 24, family: 'sans-serif' },
            {
              type: 'canvasFillText',
              ctxVar: 'ctx',
              text: {
                type: 'binop',
                op: '+',
                left: {
                  type: 'binop',
                  op: '+',
                  left: { type: 'str', value: 'Sala ' },
                  right: { type: 'var', name: 'fase' },
                },
                right: { type: 'str', value: ' de 3' },
              },
              x: { type: 'num', value: 20 },
              y: { type: 'num', value: 36 },
            },
          ],
        },
      ],
    },
  },
}
