import type { ExtensionExample } from '#extensions'

/**
 * Exemplo bundlado: "Safári de Monstros Profissional" — o Monster Hunter
 * (Python-Monsters do Clear Code) recriado com o 🧙 Kit RPG, SEM nenhum asset.
 * DIFERENCIAL vs "Treinador de Criaturas Profissional" (que usa o Kit
 * Monstrinhos e para numa batalha por turnos): aqui a captura acontece NO
 * OVERWORLD (cada monstro selvagem é um NPC que você captura apertando ESPAÇO de
 * frente), o parceiro EVOLUI ao juntar 3, e há DOIS biomas ligados pela borda
 * (rpgConnectEdge): Floresta e Caverna.
 *
 * ⚠️ A IR foi GERADA pelo parser real a partir do script achatado (o mesmo
 * código vive no drift test e no __gen_safariDeMonstrosProfissional.ts).
 */
export const safariDeMonstrosProfissionalExample: ExtensionExample = {
  name: 'Safári de Monstros Profissional',
  experience: 'game',
  description:
    'Explore dois biomas de um mundo aberto: capture os monstros selvagens NA HORA, sem tela de batalha, apertando Espaço de frente para eles. Junte 3 e o parceiro evolui; junte os 5 da Floresta e da Caverna para completar o safári.',
  ir: {
    html: [],
    css: [],
    extensions: [{ extensionId: 'game-2d-advanced' }],
    version: 2,
    behavior: {
      molds: [
        {
          type: 'gk:defineLook',
          name: 'explorador',
          ctxName: 'ctx',
          body: [
            {
              type: 'canvasFillStyle',
              ctxVar: 'ctx',
              color: { type: 'color', value: '#b8860b' },
            },
            {
              type: 'canvasFillRect',
              ctxVar: 'ctx',
              x: { type: 'num', value: 8 },
              y: { type: 'num', value: 0 },
              w: { type: 'num', value: 28 },
              h: { type: 'num', value: 8 },
            },
            {
              type: 'canvasFillStyle',
              ctxVar: 'ctx',
              color: { type: 'color', value: '#ffd8a8' },
            },
            {
              type: 'canvasFillRect',
              ctxVar: 'ctx',
              x: { type: 'num', value: 13 },
              y: { type: 'num', value: 8 },
              w: { type: 'num', value: 18 },
              h: { type: 'num', value: 14 },
            },
            {
              type: 'canvasFillStyle',
              ctxVar: 'ctx',
              color: { type: 'color', value: '#2e8b57' },
            },
            {
              type: 'canvasFillRect',
              ctxVar: 'ctx',
              x: { type: 'num', value: 8 },
              y: { type: 'num', value: 22 },
              w: { type: 'num', value: 28 },
              h: { type: 'num', value: 22 },
            },
            {
              type: 'canvasFillStyle',
              ctxVar: 'ctx',
              color: { type: 'color', value: '#2d3436' },
            },
            {
              type: 'canvasFillRect',
              ctxVar: 'ctx',
              x: { type: 'num', value: 12 },
              y: { type: 'num', value: 44 },
              w: { type: 'num', value: 8 },
              h: { type: 'num', value: 12 },
            },
            {
              type: 'canvasFillRect',
              ctxVar: 'ctx',
              x: { type: 'num', value: 24 },
              y: { type: 'num', value: 44 },
              w: { type: 'num', value: 8 },
              h: { type: 'num', value: 12 },
            },
          ],
          baseW: { type: 'num', value: 44 },
          baseH: { type: 'num', value: 56 },
        },
        {
          type: 'gk:defineLook',
          name: 'sabio',
          ctxName: 'ctx',
          body: [
            {
              type: 'canvasFillStyle',
              ctxVar: 'ctx',
              color: { type: 'color', value: '#6a5acd' },
            },
            {
              type: 'canvasFillRect',
              ctxVar: 'ctx',
              x: { type: 'num', value: 8 },
              y: { type: 'num', value: 22 },
              w: { type: 'num', value: 28 },
              h: { type: 'num', value: 24 },
            },
            {
              type: 'canvasFillStyle',
              ctxVar: 'ctx',
              color: { type: 'color', value: '#ffe8cc' },
            },
            {
              type: 'canvasFillRect',
              ctxVar: 'ctx',
              x: { type: 'num', value: 13 },
              y: { type: 'num', value: 10 },
              w: { type: 'num', value: 18 },
              h: { type: 'num', value: 14 },
            },
            {
              type: 'canvasFillStyle',
              ctxVar: 'ctx',
              color: { type: 'color', value: '#ecf0f1' },
            },
            {
              type: 'canvasFillRect',
              ctxVar: 'ctx',
              x: { type: 'num', value: 11 },
              y: { type: 'num', value: 4 },
              w: { type: 'num', value: 22 },
              h: { type: 'num', value: 8 },
            },
          ],
          baseW: { type: 'num', value: 44 },
          baseH: { type: 'num', value: 56 },
        },
        {
          type: 'gk:defineLook',
          name: 'guarda',
          ctxName: 'ctx',
          body: [
            {
              type: 'canvasFillStyle',
              ctxVar: 'ctx',
              color: { type: 'color', value: '#34495e' },
            },
            {
              type: 'canvasFillRect',
              ctxVar: 'ctx',
              x: { type: 'num', value: 8 },
              y: { type: 'num', value: 20 },
              w: { type: 'num', value: 28 },
              h: { type: 'num', value: 26 },
            },
            {
              type: 'canvasFillStyle',
              ctxVar: 'ctx',
              color: { type: 'color', value: '#ffd8a8' },
            },
            {
              type: 'canvasFillRect',
              ctxVar: 'ctx',
              x: { type: 'num', value: 13 },
              y: { type: 'num', value: 8 },
              w: { type: 'num', value: 18 },
              h: { type: 'num', value: 14 },
            },
            {
              type: 'canvasFillStyle',
              ctxVar: 'ctx',
              color: { type: 'color', value: '#95a5a6' },
            },
            {
              type: 'canvasFillRect',
              ctxVar: 'ctx',
              x: { type: 'num', value: 11 },
              y: { type: 'num', value: 2 },
              w: { type: 'num', value: 22 },
              h: { type: 'num', value: 8 },
            },
          ],
          baseW: { type: 'num', value: 44 },
          baseH: { type: 'num', value: 56 },
        },
        {
          type: 'gk:defineLook',
          name: 'verdinho',
          ctxName: 'ctx',
          body: [
            {
              type: 'canvasFillStyle',
              ctxVar: 'ctx',
              color: { type: 'color', value: '#2f9e44' },
            },
            {
              type: 'canvasArc',
              ctxVar: 'ctx',
              x: { type: 'num', value: 22 },
              y: { type: 'num', value: 24 },
              r: { type: 'num', value: 18 },
            },
            {
              type: 'canvasFillStyle',
              ctxVar: 'ctx',
              color: { type: 'color', value: '#69db7c' },
            },
            {
              type: 'canvasFillRect',
              ctxVar: 'ctx',
              x: { type: 'num', value: 18 },
              y: { type: 'num', value: 2 },
              w: { type: 'num', value: 8 },
              h: { type: 'num', value: 14 },
            },
            {
              type: 'canvasFillStyle',
              ctxVar: 'ctx',
              color: { type: 'color', value: '#ffffff' },
            },
            {
              type: 'canvasFillRect',
              ctxVar: 'ctx',
              x: { type: 'num', value: 15 },
              y: { type: 'num', value: 20 },
              w: { type: 'num', value: 6 },
              h: { type: 'num', value: 6 },
            },
            {
              type: 'canvasFillRect',
              ctxVar: 'ctx',
              x: { type: 'num', value: 26 },
              y: { type: 'num', value: 20 },
              w: { type: 'num', value: 6 },
              h: { type: 'num', value: 6 },
            },
          ],
          baseW: { type: 'num', value: 44 },
          baseH: { type: 'num', value: 44 },
        },
        {
          type: 'gk:defineLook',
          name: 'azulao',
          ctxName: 'ctx',
          body: [
            {
              type: 'canvasFillStyle',
              ctxVar: 'ctx',
              color: { type: 'color', value: '#2b7de0' },
            },
            {
              type: 'canvasArc',
              ctxVar: 'ctx',
              x: { type: 'num', value: 22 },
              y: { type: 'num', value: 24 },
              r: { type: 'num', value: 18 },
            },
            {
              type: 'canvasFillStyle',
              ctxVar: 'ctx',
              color: { type: 'color', value: '#a5d8ff' },
            },
            {
              type: 'canvasFillRect',
              ctxVar: 'ctx',
              x: { type: 'num', value: 14 },
              y: { type: 'num', value: 4 },
              w: { type: 'num', value: 16 },
              h: { type: 'num', value: 8 },
            },
            {
              type: 'canvasFillStyle',
              ctxVar: 'ctx',
              color: { type: 'color', value: '#ffffff' },
            },
            {
              type: 'canvasFillRect',
              ctxVar: 'ctx',
              x: { type: 'num', value: 15 },
              y: { type: 'num', value: 20 },
              w: { type: 'num', value: 6 },
              h: { type: 'num', value: 6 },
            },
            {
              type: 'canvasFillRect',
              ctxVar: 'ctx',
              x: { type: 'num', value: 26 },
              y: { type: 'num', value: 20 },
              w: { type: 'num', value: 6 },
              h: { type: 'num', value: 6 },
            },
          ],
          baseW: { type: 'num', value: 44 },
          baseH: { type: 'num', value: 44 },
        },
        {
          type: 'gk:defineLook',
          name: 'flamil',
          ctxName: 'ctx',
          body: [
            {
              type: 'canvasFillStyle',
              ctxVar: 'ctx',
              color: { type: 'color', value: '#e05a2b' },
            },
            {
              type: 'canvasArc',
              ctxVar: 'ctx',
              x: { type: 'num', value: 22 },
              y: { type: 'num', value: 24 },
              r: { type: 'num', value: 18 },
            },
            {
              type: 'canvasFillStyle',
              ctxVar: 'ctx',
              color: { type: 'color', value: '#ffd43b' },
            },
            {
              type: 'canvasFillRect',
              ctxVar: 'ctx',
              x: { type: 'num', value: 14 },
              y: { type: 'num', value: 2 },
              w: { type: 'num', value: 8 },
              h: { type: 'num', value: 12 },
            },
            {
              type: 'canvasFillStyle',
              ctxVar: 'ctx',
              color: { type: 'color', value: '#ffffff' },
            },
            {
              type: 'canvasFillRect',
              ctxVar: 'ctx',
              x: { type: 'num', value: 15 },
              y: { type: 'num', value: 20 },
              w: { type: 'num', value: 6 },
              h: { type: 'num', value: 6 },
            },
            {
              type: 'canvasFillRect',
              ctxVar: 'ctx',
              x: { type: 'num', value: 26 },
              y: { type: 'num', value: 20 },
              w: { type: 'num', value: 6 },
              h: { type: 'num', value: 6 },
            },
          ],
          baseW: { type: 'num', value: 44 },
          baseH: { type: 'num', value: 44 },
        },
        {
          type: 'gk:defineLook',
          name: 'rochoso',
          ctxName: 'ctx',
          body: [
            {
              type: 'canvasFillStyle',
              ctxVar: 'ctx',
              color: { type: 'color', value: '#7f8c8d' },
            },
            {
              type: 'canvasFillRect',
              ctxVar: 'ctx',
              x: { type: 'num', value: 6 },
              y: { type: 'num', value: 10 },
              w: { type: 'num', value: 32 },
              h: { type: 'num', value: 30 },
            },
            {
              type: 'canvasFillStyle',
              ctxVar: 'ctx',
              color: { type: 'color', value: '#b2bec3' },
            },
            {
              type: 'canvasFillRect',
              ctxVar: 'ctx',
              x: { type: 'num', value: 12 },
              y: { type: 'num', value: 16 },
              w: { type: 'num', value: 8 },
              h: { type: 'num', value: 8 },
            },
            {
              type: 'canvasFillRect',
              ctxVar: 'ctx',
              x: { type: 'num', value: 24 },
              y: { type: 'num', value: 16 },
              w: { type: 'num', value: 8 },
              h: { type: 'num', value: 8 },
            },
            {
              type: 'canvasFillStyle',
              ctxVar: 'ctx',
              color: { type: 'color', value: '#2d3436' },
            },
            {
              type: 'canvasFillRect',
              ctxVar: 'ctx',
              x: { type: 'num', value: 14 },
              y: { type: 'num', value: 18 },
              w: { type: 'num', value: 4 },
              h: { type: 'num', value: 4 },
            },
            {
              type: 'canvasFillRect',
              ctxVar: 'ctx',
              x: { type: 'num', value: 26 },
              y: { type: 'num', value: 18 },
              w: { type: 'num', value: 4 },
              h: { type: 'num', value: 4 },
            },
          ],
          baseW: { type: 'num', value: 44 },
          baseH: { type: 'num', value: 44 },
        },
        {
          type: 'gk:defineLook',
          name: 'sombrio',
          ctxName: 'ctx',
          body: [
            {
              type: 'canvasFillStyle',
              ctxVar: 'ctx',
              color: { type: 'color', value: '#5a3a92' },
            },
            {
              type: 'canvasArc',
              ctxVar: 'ctx',
              x: { type: 'num', value: 22 },
              y: { type: 'num', value: 24 },
              r: { type: 'num', value: 18 },
            },
            {
              type: 'canvasFillStyle',
              ctxVar: 'ctx',
              color: { type: 'color', value: '#d0bfff' },
            },
            {
              type: 'canvasFillRect',
              ctxVar: 'ctx',
              x: { type: 'num', value: 12 },
              y: { type: 'num', value: 6 },
              w: { type: 'num', value: 6 },
              h: { type: 'num', value: 12 },
            },
            {
              type: 'canvasFillRect',
              ctxVar: 'ctx',
              x: { type: 'num', value: 26 },
              y: { type: 'num', value: 6 },
              w: { type: 'num', value: 6 },
              h: { type: 'num', value: 12 },
            },
            {
              type: 'canvasFillStyle',
              ctxVar: 'ctx',
              color: { type: 'color', value: '#ff5e5e' },
            },
            {
              type: 'canvasFillRect',
              ctxVar: 'ctx',
              x: { type: 'num', value: 15 },
              y: { type: 'num', value: 22 },
              w: { type: 'num', value: 6 },
              h: { type: 'num', value: 6 },
            },
            {
              type: 'canvasFillRect',
              ctxVar: 'ctx',
              x: { type: 'num', value: 26 },
              y: { type: 'num', value: 22 },
              w: { type: 'num', value: 6 },
              h: { type: 'num', value: 6 },
            },
          ],
          baseW: { type: 'num', value: 44 },
          baseH: { type: 'num', value: 44 },
        },
        {
          type: 'gk:defineLook',
          name: 'filhote',
          ctxName: 'ctx',
          body: [
            {
              type: 'canvasFillStyle',
              ctxVar: 'ctx',
              color: { type: 'color', value: '#4fa3d1' },
            },
            {
              type: 'canvasArc',
              ctxVar: 'ctx',
              x: { type: 'num', value: 20 },
              y: { type: 'num', value: 22 },
              r: { type: 'num', value: 16 },
            },
            {
              type: 'canvasFillStyle',
              ctxVar: 'ctx',
              color: { type: 'color', value: '#ffffff' },
            },
            {
              type: 'canvasFillRect',
              ctxVar: 'ctx',
              x: { type: 'num', value: 13 },
              y: { type: 'num', value: 18 },
              w: { type: 'num', value: 6 },
              h: { type: 'num', value: 6 },
            },
            {
              type: 'canvasFillRect',
              ctxVar: 'ctx',
              x: { type: 'num', value: 24 },
              y: { type: 'num', value: 18 },
              w: { type: 'num', value: 6 },
              h: { type: 'num', value: 6 },
            },
          ],
          baseW: { type: 'num', value: 40 },
          baseH: { type: 'num', value: 40 },
        },
        {
          type: 'gk:defineLook',
          name: 'adulto',
          ctxName: 'ctx',
          body: [
            {
              type: 'canvasFillStyle',
              ctxVar: 'ctx',
              color: { type: 'color', value: '#2c78a8' },
            },
            { type: 'canvasBeginPath', ctxVar: 'ctx' },
            {
              type: 'canvasMoveTo',
              ctxVar: 'ctx',
              x: { type: 'num', value: 4 },
              y: { type: 'num', value: 22 },
            },
            {
              type: 'canvasLineTo',
              ctxVar: 'ctx',
              x: { type: 'num', value: 20 },
              y: { type: 'num', value: 4 },
            },
            {
              type: 'canvasLineTo',
              ctxVar: 'ctx',
              x: { type: 'num', value: 20 },
              y: { type: 'num', value: 22 },
            },
            { type: 'canvasFill', ctxVar: 'ctx' },
            { type: 'canvasBeginPath', ctxVar: 'ctx' },
            {
              type: 'canvasMoveTo',
              ctxVar: 'ctx',
              x: { type: 'num', value: 40 },
              y: { type: 'num', value: 22 },
            },
            {
              type: 'canvasLineTo',
              ctxVar: 'ctx',
              x: { type: 'num', value: 24 },
              y: { type: 'num', value: 4 },
            },
            {
              type: 'canvasLineTo',
              ctxVar: 'ctx',
              x: { type: 'num', value: 24 },
              y: { type: 'num', value: 22 },
            },
            { type: 'canvasFill', ctxVar: 'ctx' },
            {
              type: 'canvasFillStyle',
              ctxVar: 'ctx',
              color: { type: 'color', value: '#4fa3d1' },
            },
            {
              type: 'canvasArc',
              ctxVar: 'ctx',
              x: { type: 'num', value: 22 },
              y: { type: 'num', value: 24 },
              r: { type: 'num', value: 17 },
            },
            {
              type: 'canvasFillStyle',
              ctxVar: 'ctx',
              color: { type: 'color', value: '#ffe066' },
            },
            {
              type: 'canvasFillRect',
              ctxVar: 'ctx',
              x: { type: 'num', value: 14 },
              y: { type: 'num', value: 18 },
              w: { type: 'num', value: 6 },
              h: { type: 'num', value: 6 },
            },
            {
              type: 'canvasFillRect',
              ctxVar: 'ctx',
              x: { type: 'num', value: 26 },
              y: { type: 'num', value: 18 },
              w: { type: 'num', value: 6 },
              h: { type: 'num', value: 6 },
            },
          ],
          baseW: { type: 'num', value: 44 },
          baseH: { type: 'num', value: 44 },
        },
        {
          type: 'gk:defineLook',
          name: 'arvore',
          ctxName: 'ctx',
          body: [
            {
              type: 'canvasFillStyle',
              ctxVar: 'ctx',
              color: { type: 'color', value: '#6b4226' },
            },
            {
              type: 'canvasFillRect',
              ctxVar: 'ctx',
              x: { type: 'num', value: 26 },
              y: { type: 'num', value: 40 },
              w: { type: 'num', value: 12 },
              h: { type: 'num', value: 24 },
            },
            {
              type: 'canvasFillStyle',
              ctxVar: 'ctx',
              color: { type: 'color', value: '#2f7d32' },
            },
            {
              type: 'canvasFillRect',
              ctxVar: 'ctx',
              x: { type: 'num', value: 6 },
              y: { type: 'num', value: 4 },
              w: { type: 'num', value: 52 },
              h: { type: 'num', value: 40 },
            },
          ],
          baseW: { type: 'num', value: 64 },
          baseH: { type: 'num', value: 64 },
        },
        {
          type: 'gk:defineLook',
          name: 'mato',
          ctxName: 'ctx',
          body: [
            {
              type: 'canvasFillStyle',
              ctxVar: 'ctx',
              color: { type: 'color', value: '#2f9e44' },
            },
            {
              type: 'canvasFillRect',
              ctxVar: 'ctx',
              x: { type: 'num', value: 6 },
              y: { type: 'num', value: 22 },
              w: { type: 'num', value: 10 },
              h: { type: 'num', value: 34 },
            },
            {
              type: 'canvasFillRect',
              ctxVar: 'ctx',
              x: { type: 'num', value: 24 },
              y: { type: 'num', value: 10 },
              w: { type: 'num', value: 10 },
              h: { type: 'num', value: 46 },
            },
            {
              type: 'canvasFillRect',
              ctxVar: 'ctx',
              x: { type: 'num', value: 42 },
              y: { type: 'num', value: 24 },
              w: { type: 'num', value: 10 },
              h: { type: 'num', value: 32 },
            },
            {
              type: 'canvasFillStyle',
              ctxVar: 'ctx',
              color: { type: 'color', value: '#51cf66' },
            },
            {
              type: 'canvasFillRect',
              ctxVar: 'ctx',
              x: { type: 'num', value: 15 },
              y: { type: 'num', value: 32 },
              w: { type: 'num', value: 8 },
              h: { type: 'num', value: 24 },
            },
          ],
          baseW: { type: 'num', value: 64 },
          baseH: { type: 'num', value: 64 },
        },
        {
          type: 'gk:defineLook',
          name: 'pedra',
          ctxName: 'ctx',
          body: [
            {
              type: 'canvasFillStyle',
              ctxVar: 'ctx',
              color: { type: 'color', value: '#616a6b' },
            },
            {
              type: 'canvasFillRect',
              ctxVar: 'ctx',
              x: { type: 'num', value: 8 },
              y: { type: 'num', value: 20 },
              w: { type: 'num', value: 48 },
              h: { type: 'num', value: 40 },
            },
            {
              type: 'canvasFillStyle',
              ctxVar: 'ctx',
              color: { type: 'color', value: '#808b8d' },
            },
            {
              type: 'canvasFillRect',
              ctxVar: 'ctx',
              x: { type: 'num', value: 16 },
              y: { type: 'num', value: 28 },
              w: { type: 'num', value: 14 },
              h: { type: 'num', value: 12 },
            },
          ],
          baseW: { type: 'num', value: 64 },
          baseH: { type: 'num', value: 64 },
        },
      ],
      start: [
        {
          type: 'gk:setup',
          w: { type: 'num', value: 960 },
          h: { type: 'num', value: 540 },
          bg: '#3a7d44',
          accent: '#e6398b',
        },
        {
          type: 'gk:setScreenText',
          screen: 'menu',
          title: { type: 'str', value: 'Safári de Monstros Profissional' },
          text: {
            type: 'str',
            value:
              'Setas: explorar os dois biomas. ESPAÇO de frente para um monstro selvagem: jogar a rede e capturar na hora. Ande para a borda leste e entre na Caverna. Junte 5 monstros e veja seu parceiro evoluir!',
          },
          button: { type: 'str', value: 'Começar o safári' },
        },
        {
          type: 'gk:setScreenText',
          screen: 'vitoria',
          title: { type: 'str', value: 'Safári completo!' },
          text: {
            type: 'str',
            value:
              'Você capturou os 5 monstros da Floresta e da Caverna, e seu parceiro evoluiu. Um verdadeiro caçador de monstros!',
          },
          button: { type: 'str', value: 'Explorar de novo' },
        },
        {
          type: 'gk:createCharacter',
          varName: 'heroi',
          image: '',
          w: { type: 'num', value: 44 },
          h: { type: 'num', value: 56 },
          speed: { type: 'num', value: 220 },
          color: '#2e8b57',
        },
        {
          type: 'gk:setHitbox',
          charVar: 'heroi',
          ox: { type: 'num', value: 8 },
          oy: { type: 'num', value: 20 },
          w: { type: 'num', value: 28 },
          h: { type: 'num', value: 34 },
        },
        { type: 'gk:stateLook', charVar: 'heroi', state: 'parado', look: 'explorador' },
        { type: 'gk:stateLook', charVar: 'heroi', state: 'andando', look: 'explorador' },
        {
          type: 'gk:cameraFollow',
          charVar: 'heroi',
          w: { type: 'num', value: 1280 },
          h: { type: 'num', value: 1024 },
        },
        { type: 'var', name: 'capturados', value: { type: 'num', value: 0 } },
        { type: 'var', name: 'evoluido', value: { type: 'bool', value: false } },
        { type: 'gk:rpgSetStartMap', map: 'floresta' },
        {
          type: 'gk:rpgCreateMap',
          map: 'floresta',
          cols: { type: 'num', value: 20 },
          rows: { type: 'num', value: 16 },
          ctxName: 'ctx',
          body: [{ type: 'gk:drawBackground', color: '#3a7d44', grid: false }],
        },
        {
          type: 'gk:rpgCreateMap',
          map: 'caverna',
          cols: { type: 'num', value: 20 },
          rows: { type: 'num', value: 16 },
          ctxName: 'ctx',
          body: [{ type: 'gk:drawBackground', color: '#3b3550', grid: false }],
        },
      ],
      events: [
        {
          type: 'gk:rpgOnEnterMap',
          map: 'floresta',
          body: [
            { type: 'gk:rpgConnectEdge', side: 'leste', map: 'caverna' },
            {
              type: 'gk:rpgCreateNpc',
              name: 'Sabio',
              cx: { type: 'num', value: 4 },
              cy: { type: 'num', value: 3 },
              image: '',
              look: 'sabio',
            },
            {
              type: 'gk:rpgCreateNpc',
              name: 'Verdinho',
              cx: { type: 'num', value: 9 },
              cy: { type: 'num', value: 8 },
              image: '',
              look: 'verdinho',
            },
            {
              type: 'gk:rpgCreateNpc',
              name: 'Azulao',
              cx: { type: 'num', value: 14 },
              cy: { type: 'num', value: 11 },
              image: '',
              look: 'azulao',
            },
            {
              type: 'gk:rpgCreateNpc',
              name: 'Flamil',
              cx: { type: 'num', value: 6 },
              cy: { type: 'num', value: 12 },
              image: '',
              look: 'flamil',
            },
            {
              type: 'gk:rpgBlockCell',
              cx: { type: 'num', value: 2 },
              cy: { type: 'num', value: 8 },
            },
            {
              type: 'gk:rpgBlockCell',
              cx: { type: 'num', value: 17 },
              cy: { type: 'num', value: 4 },
            },
            {
              type: 'gk:rpgBlockCell',
              cx: { type: 'num', value: 11 },
              cy: { type: 'num', value: 6 },
            },
            {
              type: 'if',
              cond: {
                type: 'binop',
                op: '==',
                left: { type: 'gk:rpgHasFlag', flag: 'spawnou' },
                right: { type: 'bool', value: false },
              },
              then: [
                {
                  type: 'gk:placeCharacter',
                  charVar: 'heroi',
                  x: { type: 'num', value: 448 },
                  y: { type: 'num', value: 384 },
                },
                { type: 'gk:rpgAddFlag', flag: 'spawnou' },
              ],
            },
          ],
        },
        {
          type: 'gk:rpgOnEnterMap',
          map: 'caverna',
          body: [
            { type: 'gk:rpgConnectEdge', side: 'oeste', map: 'floresta' },
            {
              type: 'gk:rpgCreateNpc',
              name: 'Guarda',
              cx: { type: 'num', value: 3 },
              cy: { type: 'num', value: 3 },
              image: '',
              look: 'guarda',
            },
            {
              type: 'gk:rpgCreateNpc',
              name: 'Rochoso',
              cx: { type: 'num', value: 8 },
              cy: { type: 'num', value: 6 },
              image: '',
              look: 'rochoso',
            },
            {
              type: 'gk:rpgCreateNpc',
              name: 'Sombrio',
              cx: { type: 'num', value: 14 },
              cy: { type: 'num', value: 9 },
              image: '',
              look: 'sombrio',
            },
            {
              type: 'gk:rpgBlockCell',
              cx: { type: 'num', value: 10 },
              cy: { type: 'num', value: 4 },
            },
            {
              type: 'gk:rpgBlockCell',
              cx: { type: 'num', value: 6 },
              cy: { type: 'num', value: 11 },
            },
          ],
        },
        {
          type: 'gk:rpgOnTalk',
          npc: 'Sabio',
          body: [
            {
              type: 'if',
              cond: { type: 'gk:rpgHasFlag', flag: 'dica' },
              then: [
                {
                  type: 'gk:rpgSay',
                  text: {
                    type: 'str',
                    value: 'A Caverna fica na borda leste. Lá vivem os monstros raros!',
                  },
                  speaker: { type: 'str', value: 'Sabio' },
                },
              ],
              else: [
                {
                  type: 'gk:rpgSay',
                  text: {
                    type: 'str',
                    value:
                      'Bem-vindo ao safari! Chegue de frente num monstro e aperte Espaco para jogar a rede.',
                  },
                  speaker: { type: 'str', value: 'Sabio' },
                },
                { type: 'gk:rpgAddFlag', flag: 'dica' },
              ],
            },
          ],
        },
        {
          type: 'gk:rpgOnTalk',
          npc: 'Guarda',
          body: [
            {
              type: 'gk:rpgSay',
              text: {
                type: 'str',
                value: 'A Caverna e mais dificil. O Rochoso e o Sombrio so aparecem aqui!',
              },
              speaker: { type: 'str', value: 'Guarda' },
            },
          ],
        },
        {
          type: 'gk:rpgOnTalk',
          npc: 'Verdinho',
          body: [
            {
              type: 'if',
              cond: { type: 'gk:rpgHasFlag', flag: 'pego_verdinho' },
              then: [
                {
                  type: 'gk:rpgSay',
                  text: { type: 'str', value: 'O Verdinho ja esta no seu caderno!' },
                  speaker: { type: 'str', value: 'Safari' },
                },
              ],
              else: [
                { type: 'gk:rpgAddFlag', flag: 'pego_verdinho' },
                {
                  type: 'assign',
                  name: 'capturados',
                  value: {
                    type: 'binop',
                    op: '+',
                    left: { type: 'var', name: 'capturados' },
                    right: { type: 'num', value: 1 },
                  },
                },
                {
                  type: 'gk:rpgSay',
                  text: { type: 'str', value: 'Voce jogou a rede e capturou o Verdinho!' },
                  speaker: { type: 'str', value: 'Safari' },
                },
                { type: 'gk:playEffect', fx: 'win' },
              ],
            },
          ],
        },
        {
          type: 'gk:rpgOnTalk',
          npc: 'Azulao',
          body: [
            {
              type: 'if',
              cond: { type: 'gk:rpgHasFlag', flag: 'pego_azulao' },
              then: [
                {
                  type: 'gk:rpgSay',
                  text: { type: 'str', value: 'O Azulao ja esta no seu caderno!' },
                  speaker: { type: 'str', value: 'Safari' },
                },
              ],
              else: [
                { type: 'gk:rpgAddFlag', flag: 'pego_azulao' },
                {
                  type: 'assign',
                  name: 'capturados',
                  value: {
                    type: 'binop',
                    op: '+',
                    left: { type: 'var', name: 'capturados' },
                    right: { type: 'num', value: 1 },
                  },
                },
                {
                  type: 'gk:rpgSay',
                  text: { type: 'str', value: 'Voce jogou a rede e capturou o Azulao!' },
                  speaker: { type: 'str', value: 'Safari' },
                },
                { type: 'gk:playEffect', fx: 'win' },
              ],
            },
          ],
        },
        {
          type: 'gk:rpgOnTalk',
          npc: 'Flamil',
          body: [
            {
              type: 'if',
              cond: { type: 'gk:rpgHasFlag', flag: 'pego_flamil' },
              then: [
                {
                  type: 'gk:rpgSay',
                  text: { type: 'str', value: 'O Flamil ja esta no seu caderno!' },
                  speaker: { type: 'str', value: 'Safari' },
                },
              ],
              else: [
                { type: 'gk:rpgAddFlag', flag: 'pego_flamil' },
                {
                  type: 'assign',
                  name: 'capturados',
                  value: {
                    type: 'binop',
                    op: '+',
                    left: { type: 'var', name: 'capturados' },
                    right: { type: 'num', value: 1 },
                  },
                },
                {
                  type: 'gk:rpgSay',
                  text: { type: 'str', value: 'Voce jogou a rede e capturou o Flamil!' },
                  speaker: { type: 'str', value: 'Safari' },
                },
                { type: 'gk:playEffect', fx: 'win' },
              ],
            },
          ],
        },
        {
          type: 'gk:rpgOnTalk',
          npc: 'Rochoso',
          body: [
            {
              type: 'if',
              cond: { type: 'gk:rpgHasFlag', flag: 'pego_rochoso' },
              then: [
                {
                  type: 'gk:rpgSay',
                  text: { type: 'str', value: 'O Rochoso ja esta no seu caderno!' },
                  speaker: { type: 'str', value: 'Safari' },
                },
              ],
              else: [
                { type: 'gk:rpgAddFlag', flag: 'pego_rochoso' },
                {
                  type: 'assign',
                  name: 'capturados',
                  value: {
                    type: 'binop',
                    op: '+',
                    left: { type: 'var', name: 'capturados' },
                    right: { type: 'num', value: 1 },
                  },
                },
                {
                  type: 'gk:rpgSay',
                  text: { type: 'str', value: 'Que forca! Voce capturou o Rochoso da caverna!' },
                  speaker: { type: 'str', value: 'Safari' },
                },
                { type: 'gk:playEffect', fx: 'win' },
              ],
            },
          ],
        },
        {
          type: 'gk:rpgOnTalk',
          npc: 'Sombrio',
          body: [
            {
              type: 'if',
              cond: { type: 'gk:rpgHasFlag', flag: 'pego_sombrio' },
              then: [
                {
                  type: 'gk:rpgSay',
                  text: { type: 'str', value: 'O Sombrio ja esta no seu caderno!' },
                  speaker: { type: 'str', value: 'Safari' },
                },
              ],
              else: [
                { type: 'gk:rpgAddFlag', flag: 'pego_sombrio' },
                {
                  type: 'assign',
                  name: 'capturados',
                  value: {
                    type: 'binop',
                    op: '+',
                    left: { type: 'var', name: 'capturados' },
                    right: { type: 'num', value: 1 },
                  },
                },
                {
                  type: 'gk:rpgSay',
                  text: { type: 'str', value: 'O raro Sombrio caiu na rede! Que caçada!' },
                  speaker: { type: 'str', value: 'Safari' },
                },
                { type: 'gk:playEffect', fx: 'win' },
              ],
            },
          ],
        },
      ],
      loops: [
        {
          type: 'gk:onUpdate',
          dtName: 'dt',
          body: [
            {
              type: 'gk:rpgMoveGrid',
              charVar: 'heroi',
              cell: { type: 'num', value: 64 },
              dtVar: 'dt',
            },
            { type: 'gk:autoAnimate', charVar: 'heroi' },
            {
              type: 'if',
              cond: {
                type: 'binop',
                op: '>=',
                left: { type: 'var', name: 'capturados' },
                right: { type: 'num', value: 3 },
              },
              then: [
                {
                  type: 'if',
                  cond: {
                    type: 'binop',
                    op: '==',
                    left: { type: 'var', name: 'evoluido' },
                    right: { type: 'bool', value: false },
                  },
                  then: [
                    { type: 'assign', name: 'evoluido', value: { type: 'bool', value: true } },
                    { type: 'gk:playEffect', fx: 'powerup' },
                  ],
                },
              ],
            },
            {
              type: 'if',
              cond: {
                type: 'binop',
                op: '>=',
                left: { type: 'var', name: 'capturados' },
                right: { type: 'num', value: 5 },
              },
              then: [{ type: 'gk:setState', name: 'vitoria' }],
            },
          ],
        },
        {
          type: 'gk:onDraw',
          ctxName: 'ctx',
          body: [
            {
              type: 'forRange',
              varName: 'i',
              from: { type: 'num', value: 0 },
              to: { type: 'num', value: 5 },
              step: { type: 'num', value: 1 },
              body: [
                {
                  type: 'gk:drawLook',
                  look: 'mato',
                  x: {
                    type: 'binop',
                    op: '+',
                    left: { type: 'num', value: 320 },
                    right: {
                      type: 'binop',
                      op: '*',
                      left: { type: 'var', name: 'i' },
                      right: { type: 'num', value: 64 },
                    },
                  },
                  y: { type: 'num', value: 448 },
                  w: { type: 'num', value: 64 },
                  h: { type: 'num', value: 64 },
                },
                {
                  type: 'gk:drawLook',
                  look: 'mato',
                  x: {
                    type: 'binop',
                    op: '+',
                    left: { type: 'num', value: 320 },
                    right: {
                      type: 'binop',
                      op: '*',
                      left: { type: 'var', name: 'i' },
                      right: { type: 'num', value: 64 },
                    },
                  },
                  y: { type: 'num', value: 640 },
                  w: { type: 'num', value: 64 },
                  h: { type: 'num', value: 64 },
                },
              ],
            },
            {
              type: 'gk:drawLook',
              look: 'arvore',
              x: { type: 'num', value: 128 },
              y: { type: 'num', value: 128 },
              w: { type: 'num', value: 64 },
              h: { type: 'num', value: 64 },
            },
            {
              type: 'gk:drawLook',
              look: 'arvore',
              x: { type: 'num', value: 1088 },
              y: { type: 'num', value: 192 },
              w: { type: 'num', value: 64 },
              h: { type: 'num', value: 64 },
            },
            {
              type: 'gk:drawLook',
              look: 'pedra',
              x: { type: 'num', value: 640 },
              y: { type: 'num', value: 256 },
              w: { type: 'num', value: 64 },
              h: { type: 'num', value: 64 },
            },
            {
              type: 'if',
              cond: {
                type: 'binop',
                op: '==',
                left: { type: 'var', name: 'evoluido' },
                right: { type: 'bool', value: true },
              },
              then: [
                {
                  type: 'gk:drawLook',
                  look: 'adulto',
                  x: {
                    type: 'binop',
                    op: '-',
                    left: { type: 'gk:charX', charVar: 'heroi' },
                    right: { type: 'num', value: 46 },
                  },
                  y: {
                    type: 'binop',
                    op: '+',
                    left: { type: 'gk:charY', charVar: 'heroi' },
                    right: { type: 'num', value: 8 },
                  },
                  w: { type: 'num', value: 44 },
                  h: { type: 'num', value: 44 },
                },
              ],
              else: [
                {
                  type: 'gk:drawLook',
                  look: 'filhote',
                  x: {
                    type: 'binop',
                    op: '-',
                    left: { type: 'gk:charX', charVar: 'heroi' },
                    right: { type: 'num', value: 42 },
                  },
                  y: {
                    type: 'binop',
                    op: '+',
                    left: { type: 'gk:charY', charVar: 'heroi' },
                    right: { type: 'num', value: 12 },
                  },
                  w: { type: 'num', value: 40 },
                  h: { type: 'num', value: 40 },
                },
              ],
            },
            { type: 'gk:rpgDrawNpcs' },
            { type: 'gk:drawByDepth', charVar: 'heroi' },
          ],
        },
        {
          type: 'gk:onDrawHud',
          ctxName: 'ctx',
          body: [
            {
              type: 'canvasFillStyle',
              ctxVar: 'ctx',
              color: { type: 'color', value: '#0e2a1c' },
            },
            {
              type: 'canvasFillRect',
              ctxVar: 'ctx',
              x: { type: 'num', value: 12 },
              y: { type: 'num', value: 12 },
              w: { type: 'num', value: 232 },
              h: { type: 'num', value: 40 },
            },
            {
              type: 'canvasFillStyle',
              ctxVar: 'ctx',
              color: { type: 'color', value: '#ffffff' },
            },
            { type: 'canvasFont', ctxVar: 'ctx', size: 18, family: 'sans-serif' },
            {
              type: 'canvasFillText',
              ctxVar: 'ctx',
              text: {
                type: 'binop',
                op: '+',
                left: {
                  type: 'binop',
                  op: '+',
                  left: { type: 'str', value: 'Caderno de monstros: ' },
                  right: { type: 'var', name: 'capturados' },
                },
                right: { type: 'str', value: ' de 5' },
              },
              x: { type: 'num', value: 24 },
              y: { type: 'num', value: 38 },
            },
          ],
        },
      ],
    },
  },
}
