import type { ExtensionExample } from '#extensions'

/**
 * Exemplo bundlado: "Treinador de Criaturas Profissional" — o pokemon-style-game
 * (Pellet Town do Chris Courses) recriado com o 👾 Kit Monstrinhos + o 🧙 Kit RPG,
 * SEM um único asset (o treinador, os aldeões, as casas, a grama e as criaturas
 * são `defineLook` vetorial). O MUNDO é o Kit RPG (mapa 20x16 maior que a tela +
 * câmera que segue + grade com paredes + NPCs que conversam) e só a BATALHA é do
 * Kit Monstrinhos (por turnos, tipo/vantagem fogo>planta>água>fogo, captura). O
 * objetivo: pegar 3 criaturas na grama alta (o time chega a 4 com a inicial) liga
 * a tela de vitória pronta.
 *
 * ⚠️ A IR foi GERADA pelo parser real a partir do script achatado (o mesmo código
 * vive no drift test e no __gen_treinadorDeCriaturas.ts — se o parser mudar a
 * saída, o teste manda re-embutir aqui).
 */
export const treinadorDeCriaturasExample: ExtensionExample = {
  name: 'Treinador de Criaturas Profissional',
  experience: 'game',
  description:
    'Ande pela cidade, converse com os aldeões e pise na grama alta para achar criaturas! Batalhe por turnos com tipo e vantagem, jogue a bola e capture 3 criaturas para virar Mestre.',
  ir: {
    html: [],
    css: [],
    extensions: [{ extensionId: 'game-2d-advanced' }],
    version: 2,
    behavior: {
      molds: [
        {
          type: 'gk:defineLook',
          name: 'treinador',
          ctxName: 'ctx',
          body: [
            {
              type: 'canvasFillStyle',
              ctxVar: 'ctx',
              color: { type: 'color', value: '#c0392b' },
            },
            {
              type: 'canvasFillRect',
              ctxVar: 'ctx',
              x: { type: 'num', value: 10 },
              y: { type: 'num', value: 0 },
              w: { type: 'num', value: 24 },
              h: { type: 'num', value: 12 },
            },
            {
              type: 'canvasFillStyle',
              ctxVar: 'ctx',
              color: { type: 'color', value: '#ffd8a8' },
            },
            {
              type: 'canvasFillRect',
              ctxVar: 'ctx',
              x: { type: 'num', value: 13 },
              y: { type: 'num', value: 12 },
              w: { type: 'num', value: 18 },
              h: { type: 'num', value: 12 },
            },
            {
              type: 'canvasFillStyle',
              ctxVar: 'ctx',
              color: { type: 'color', value: '#2b6cb0' },
            },
            {
              type: 'canvasFillRect',
              ctxVar: 'ctx',
              x: { type: 'num', value: 8 },
              y: { type: 'num', value: 24 },
              w: { type: 'num', value: 28 },
              h: { type: 'num', value: 20 },
            },
            {
              type: 'canvasFillStyle',
              ctxVar: 'ctx',
              color: { type: 'color', value: '#2d3436' },
            },
            {
              type: 'canvasFillRect',
              ctxVar: 'ctx',
              x: { type: 'num', value: 12 },
              y: { type: 'num', value: 44 },
              w: { type: 'num', value: 8 },
              h: { type: 'num', value: 12 },
            },
            {
              type: 'canvasFillRect',
              ctxVar: 'ctx',
              x: { type: 'num', value: 24 },
              y: { type: 'num', value: 44 },
              w: { type: 'num', value: 8 },
              h: { type: 'num', value: 12 },
            },
          ],
          baseW: { type: 'num', value: 44 },
          baseH: { type: 'num', value: 56 },
        },
        {
          type: 'gk:defineLook',
          name: 'professor',
          ctxName: 'ctx',
          body: [
            {
              type: 'canvasFillStyle',
              ctxVar: 'ctx',
              color: { type: 'color', value: '#ecf0f1' },
            },
            {
              type: 'canvasFillRect',
              ctxVar: 'ctx',
              x: { type: 'num', value: 8 },
              y: { type: 'num', value: 22 },
              w: { type: 'num', value: 28 },
              h: { type: 'num', value: 24 },
            },
            {
              type: 'canvasFillStyle',
              ctxVar: 'ctx',
              color: { type: 'color', value: '#ffd8a8' },
            },
            {
              type: 'canvasFillRect',
              ctxVar: 'ctx',
              x: { type: 'num', value: 13 },
              y: { type: 'num', value: 10 },
              w: { type: 'num', value: 18 },
              h: { type: 'num', value: 14 },
            },
            {
              type: 'canvasFillStyle',
              ctxVar: 'ctx',
              color: { type: 'color', value: '#bdc3c7' },
            },
            {
              type: 'canvasFillRect',
              ctxVar: 'ctx',
              x: { type: 'num', value: 11 },
              y: { type: 'num', value: 4 },
              w: { type: 'num', value: 22 },
              h: { type: 'num', value: 8 },
            },
          ],
          baseW: { type: 'num', value: 44 },
          baseH: { type: 'num', value: 56 },
        },
        {
          type: 'gk:defineLook',
          name: 'aldea',
          ctxName: 'ctx',
          body: [
            {
              type: 'canvasFillStyle',
              ctxVar: 'ctx',
              color: { type: 'color', value: '#8e44ad' },
            },
            {
              type: 'canvasFillRect',
              ctxVar: 'ctx',
              x: { type: 'num', value: 8 },
              y: { type: 'num', value: 20 },
              w: { type: 'num', value: 28 },
              h: { type: 'num', value: 26 },
            },
            {
              type: 'canvasFillStyle',
              ctxVar: 'ctx',
              color: { type: 'color', value: '#ffe8cc' },
            },
            {
              type: 'canvasFillRect',
              ctxVar: 'ctx',
              x: { type: 'num', value: 13 },
              y: { type: 'num', value: 8 },
              w: { type: 'num', value: 18 },
              h: { type: 'num', value: 14 },
            },
            {
              type: 'canvasFillStyle',
              ctxVar: 'ctx',
              color: { type: 'color', value: '#f1c40f' },
            },
            {
              type: 'canvasFillRect',
              ctxVar: 'ctx',
              x: { type: 'num', value: 11 },
              y: { type: 'num', value: 2 },
              w: { type: 'num', value: 22 },
              h: { type: 'num', value: 8 },
            },
          ],
          baseW: { type: 'num', value: 44 },
          baseH: { type: 'num', value: 56 },
        },
        {
          type: 'gk:defineLook',
          name: 'idoso',
          ctxName: 'ctx',
          body: [
            {
              type: 'canvasFillStyle',
              ctxVar: 'ctx',
              color: { type: 'color', value: '#7f8c8d' },
            },
            {
              type: 'canvasFillRect',
              ctxVar: 'ctx',
              x: { type: 'num', value: 8 },
              y: { type: 'num', value: 22 },
              w: { type: 'num', value: 28 },
              h: { type: 'num', value: 24 },
            },
            {
              type: 'canvasFillStyle',
              ctxVar: 'ctx',
              color: { type: 'color', value: '#ffe8cc' },
            },
            {
              type: 'canvasFillRect',
              ctxVar: 'ctx',
              x: { type: 'num', value: 13 },
              y: { type: 'num', value: 10 },
              w: { type: 'num', value: 18 },
              h: { type: 'num', value: 14 },
            },
            {
              type: 'canvasFillStyle',
              ctxVar: 'ctx',
              color: { type: 'color', value: '#ecf0f1' },
            },
            {
              type: 'canvasFillRect',
              ctxVar: 'ctx',
              x: { type: 'num', value: 12 },
              y: { type: 'num', value: 6 },
              w: { type: 'num', value: 20 },
              h: { type: 'num', value: 6 },
            },
          ],
          baseW: { type: 'num', value: 44 },
          baseH: { type: 'num', value: 56 },
        },
        {
          type: 'gk:defineLook',
          name: 'enfermeira',
          ctxName: 'ctx',
          body: [
            {
              type: 'canvasFillStyle',
              ctxVar: 'ctx',
              color: { type: 'color', value: '#e74c3c' },
            },
            {
              type: 'canvasFillRect',
              ctxVar: 'ctx',
              x: { type: 'num', value: 8 },
              y: { type: 'num', value: 22 },
              w: { type: 'num', value: 28 },
              h: { type: 'num', value: 24 },
            },
            {
              type: 'canvasFillStyle',
              ctxVar: 'ctx',
              color: { type: 'color', value: '#ffd8a8' },
            },
            {
              type: 'canvasFillRect',
              ctxVar: 'ctx',
              x: { type: 'num', value: 13 },
              y: { type: 'num', value: 10 },
              w: { type: 'num', value: 18 },
              h: { type: 'num', value: 14 },
            },
            {
              type: 'canvasFillStyle',
              ctxVar: 'ctx',
              color: { type: 'color', value: '#ffffff' },
            },
            {
              type: 'canvasFillRect',
              ctxVar: 'ctx',
              x: { type: 'num', value: 11 },
              y: { type: 'num', value: 4 },
              w: { type: 'num', value: 22 },
              h: { type: 'num', value: 8 },
            },
            {
              type: 'canvasFillStyle',
              ctxVar: 'ctx',
              color: { type: 'color', value: '#e74c3c' },
            },
            {
              type: 'canvasFillRect',
              ctxVar: 'ctx',
              x: { type: 'num', value: 19 },
              y: { type: 'num', value: 5 },
              w: { type: 'num', value: 6 },
              h: { type: 'num', value: 6 },
            },
          ],
          baseW: { type: 'num', value: 44 },
          baseH: { type: 'num', value: 56 },
        },
        {
          type: 'gk:defineLook',
          name: 'chaminho',
          ctxName: 'ctx',
          body: [
            {
              type: 'canvasFillStyle',
              ctxVar: 'ctx',
              color: { type: 'color', value: '#e05a2b' },
            },
            {
              type: 'canvasArc',
              ctxVar: 'ctx',
              x: { type: 'num', value: 22 },
              y: { type: 'num', value: 24 },
              r: { type: 'num', value: 18 },
            },
            {
              type: 'canvasFillStyle',
              ctxVar: 'ctx',
              color: { type: 'color', value: '#ffd43b' },
            },
            {
              type: 'canvasFillRect',
              ctxVar: 'ctx',
              x: { type: 'num', value: 14 },
              y: { type: 'num', value: 2 },
              w: { type: 'num', value: 8 },
              h: { type: 'num', value: 12 },
            },
            {
              type: 'canvasFillStyle',
              ctxVar: 'ctx',
              color: { type: 'color', value: '#ffffff' },
            },
            {
              type: 'canvasFillRect',
              ctxVar: 'ctx',
              x: { type: 'num', value: 15 },
              y: { type: 'num', value: 20 },
              w: { type: 'num', value: 6 },
              h: { type: 'num', value: 6 },
            },
            {
              type: 'canvasFillRect',
              ctxVar: 'ctx',
              x: { type: 'num', value: 26 },
              y: { type: 'num', value: 20 },
              w: { type: 'num', value: 6 },
              h: { type: 'num', value: 6 },
            },
          ],
          baseW: { type: 'num', value: 44 },
          baseH: { type: 'num', value: 44 },
        },
        {
          type: 'gk:defineLook',
          name: 'gotoso',
          ctxName: 'ctx',
          body: [
            {
              type: 'canvasFillStyle',
              ctxVar: 'ctx',
              color: { type: 'color', value: '#2b7de0' },
            },
            {
              type: 'canvasArc',
              ctxVar: 'ctx',
              x: { type: 'num', value: 22 },
              y: { type: 'num', value: 24 },
              r: { type: 'num', value: 18 },
            },
            {
              type: 'canvasFillStyle',
              ctxVar: 'ctx',
              color: { type: 'color', value: '#a5d8ff' },
            },
            {
              type: 'canvasFillRect',
              ctxVar: 'ctx',
              x: { type: 'num', value: 18 },
              y: { type: 'num', value: 4 },
              w: { type: 'num', value: 8 },
              h: { type: 'num', value: 12 },
            },
            {
              type: 'canvasFillStyle',
              ctxVar: 'ctx',
              color: { type: 'color', value: '#ffffff' },
            },
            {
              type: 'canvasFillRect',
              ctxVar: 'ctx',
              x: { type: 'num', value: 15 },
              y: { type: 'num', value: 20 },
              w: { type: 'num', value: 6 },
              h: { type: 'num', value: 6 },
            },
            {
              type: 'canvasFillRect',
              ctxVar: 'ctx',
              x: { type: 'num', value: 26 },
              y: { type: 'num', value: 20 },
              w: { type: 'num', value: 6 },
              h: { type: 'num', value: 6 },
            },
          ],
          baseW: { type: 'num', value: 44 },
          baseH: { type: 'num', value: 44 },
        },
        {
          type: 'gk:defineLook',
          name: 'brotim',
          ctxName: 'ctx',
          body: [
            {
              type: 'canvasFillStyle',
              ctxVar: 'ctx',
              color: { type: 'color', value: '#3f9d3f' },
            },
            {
              type: 'canvasArc',
              ctxVar: 'ctx',
              x: { type: 'num', value: 22 },
              y: { type: 'num', value: 24 },
              r: { type: 'num', value: 18 },
            },
            {
              type: 'canvasFillStyle',
              ctxVar: 'ctx',
              color: { type: 'color', value: '#69db7c' },
            },
            {
              type: 'canvasFillRect',
              ctxVar: 'ctx',
              x: { type: 'num', value: 18 },
              y: { type: 'num', value: 2 },
              w: { type: 'num', value: 8 },
              h: { type: 'num', value: 14 },
            },
            {
              type: 'canvasFillStyle',
              ctxVar: 'ctx',
              color: { type: 'color', value: '#ffffff' },
            },
            {
              type: 'canvasFillRect',
              ctxVar: 'ctx',
              x: { type: 'num', value: 15 },
              y: { type: 'num', value: 20 },
              w: { type: 'num', value: 6 },
              h: { type: 'num', value: 6 },
            },
            {
              type: 'canvasFillRect',
              ctxVar: 'ctx',
              x: { type: 'num', value: 26 },
              y: { type: 'num', value: 20 },
              w: { type: 'num', value: 6 },
              h: { type: 'num', value: 6 },
            },
          ],
          baseW: { type: 'num', value: 44 },
          baseH: { type: 'num', value: 44 },
        },
        {
          type: 'gk:defineLook',
          name: 'casa',
          ctxName: 'ctx',
          body: [
            {
              type: 'canvasFillStyle',
              ctxVar: 'ctx',
              color: { type: 'color', value: '#c9a76b' },
            },
            {
              type: 'canvasFillRect',
              ctxVar: 'ctx',
              x: { type: 'num', value: 0 },
              y: { type: 'num', value: 24 },
              w: { type: 'num', value: 64 },
              h: { type: 'num', value: 40 },
            },
            {
              type: 'canvasFillStyle',
              ctxVar: 'ctx',
              color: { type: 'color', value: '#8e3b2a' },
            },
            {
              type: 'canvasFillRect',
              ctxVar: 'ctx',
              x: { type: 'num', value: 0 },
              y: { type: 'num', value: 4 },
              w: { type: 'num', value: 64 },
              h: { type: 'num', value: 22 },
            },
            {
              type: 'canvasFillStyle',
              ctxVar: 'ctx',
              color: { type: 'color', value: '#3a271a' },
            },
            {
              type: 'canvasFillRect',
              ctxVar: 'ctx',
              x: { type: 'num', value: 24 },
              y: { type: 'num', value: 42 },
              w: { type: 'num', value: 16 },
              h: { type: 'num', value: 22 },
            },
          ],
          baseW: { type: 'num', value: 64 },
          baseH: { type: 'num', value: 64 },
        },
        {
          type: 'gk:defineLook',
          name: 'arvore',
          ctxName: 'ctx',
          body: [
            {
              type: 'canvasFillStyle',
              ctxVar: 'ctx',
              color: { type: 'color', value: '#6b4226' },
            },
            {
              type: 'canvasFillRect',
              ctxVar: 'ctx',
              x: { type: 'num', value: 26 },
              y: { type: 'num', value: 40 },
              w: { type: 'num', value: 12 },
              h: { type: 'num', value: 24 },
            },
            {
              type: 'canvasFillStyle',
              ctxVar: 'ctx',
              color: { type: 'color', value: '#2f7d32' },
            },
            {
              type: 'canvasFillRect',
              ctxVar: 'ctx',
              x: { type: 'num', value: 6 },
              y: { type: 'num', value: 4 },
              w: { type: 'num', value: 52 },
              h: { type: 'num', value: 40 },
            },
          ],
          baseW: { type: 'num', value: 64 },
          baseH: { type: 'num', value: 64 },
        },
        {
          type: 'gk:defineLook',
          name: 'mato',
          ctxName: 'ctx',
          body: [
            {
              type: 'canvasFillStyle',
              ctxVar: 'ctx',
              color: { type: 'color', value: '#2f9e44' },
            },
            {
              type: 'canvasFillRect',
              ctxVar: 'ctx',
              x: { type: 'num', value: 6 },
              y: { type: 'num', value: 22 },
              w: { type: 'num', value: 10 },
              h: { type: 'num', value: 34 },
            },
            {
              type: 'canvasFillRect',
              ctxVar: 'ctx',
              x: { type: 'num', value: 24 },
              y: { type: 'num', value: 10 },
              w: { type: 'num', value: 10 },
              h: { type: 'num', value: 46 },
            },
            {
              type: 'canvasFillRect',
              ctxVar: 'ctx',
              x: { type: 'num', value: 42 },
              y: { type: 'num', value: 24 },
              w: { type: 'num', value: 10 },
              h: { type: 'num', value: 32 },
            },
            {
              type: 'canvasFillStyle',
              ctxVar: 'ctx',
              color: { type: 'color', value: '#51cf66' },
            },
            {
              type: 'canvasFillRect',
              ctxVar: 'ctx',
              x: { type: 'num', value: 15 },
              y: { type: 'num', value: 32 },
              w: { type: 'num', value: 8 },
              h: { type: 'num', value: 24 },
            },
          ],
          baseW: { type: 'num', value: 64 },
          baseH: { type: 'num', value: 64 },
        },
        {
          type: 'gk:pkmCreature',
          name: 'Chaminho',
          creatureType: 'fogo',
          hp: { type: 'num', value: 30 },
          str: { type: 'num', value: 9 },
          def: { type: 'num', value: 4 },
          spd: { type: 'num', value: 7 },
          image: '',
          look: 'chaminho',
        },
        {
          type: 'gk:pkmCreature',
          name: 'Gotoso',
          creatureType: 'água',
          hp: { type: 'num', value: 32 },
          str: { type: 'num', value: 8 },
          def: { type: 'num', value: 5 },
          spd: { type: 'num', value: 6 },
          image: '',
          look: 'gotoso',
        },
        {
          type: 'gk:pkmCreature',
          name: 'Brotim',
          creatureType: 'planta',
          hp: { type: 'num', value: 34 },
          str: { type: 'num', value: 7 },
          def: { type: 'num', value: 6 },
          spd: { type: 'num', value: 5 },
          image: '',
          look: 'brotim',
        },
        {
          type: 'gk:pkmMove',
          move: 'Brasa',
          creature: 'Chaminho',
          moveType: 'fogo',
          dmg: { type: 'num', value: 16 },
          acc: { type: 'num', value: 95 },
          fx: 'bola',
          color: '#ff8800',
        },
        {
          type: 'gk:pkmMove',
          move: 'Investida',
          creature: 'Chaminho',
          moveType: 'normal',
          dmg: { type: 'num', value: 10 },
          acc: { type: 'num', value: 100 },
          fx: 'investida',
          color: '#999999',
        },
        {
          type: 'gk:pkmMove',
          move: 'Jato',
          creature: 'Gotoso',
          moveType: 'água',
          dmg: { type: 'num', value: 16 },
          acc: { type: 'num', value: 95 },
          fx: 'onda',
          color: '#2b7de0',
        },
        {
          type: 'gk:pkmMove',
          move: 'Chicote',
          creature: 'Brotim',
          moveType: 'planta',
          dmg: { type: 'num', value: 16 },
          acc: { type: 'num', value: 95 },
          fx: 'raio',
          color: '#3f9d3f',
        },
        { type: 'gk:pkmTypeChart', atk: 'fogo', def: 'planta', mult: { type: 'num', value: 2 } },
        { type: 'gk:pkmTypeChart', atk: 'planta', def: 'água', mult: { type: 'num', value: 2 } },
        { type: 'gk:pkmTypeChart', atk: 'água', def: 'fogo', mult: { type: 'num', value: 2 } },
      ],
      start: [
        {
          type: 'gk:setup',
          w: { type: 'num', value: 960 },
          h: { type: 'num', value: 540 },
          bg: '#5c9e4a',
          accent: '#e6398b',
        },
        {
          type: 'gk:setScreenText',
          screen: 'menu',
          title: { type: 'str', value: 'Treinador de Criaturas Profissional' },
          text: {
            type: 'str',
            value:
              'Setas: andar pela cidade. ESPAÇO de frente para um aldeão: conversar. Pise na grama alta para achar criaturas selvagens, batalhe por turnos e jogue a bola para capturar. Pegue 3 criaturas!',
          },
          button: { type: 'str', value: 'Começar a jornada' },
        },
        {
          type: 'gk:setScreenText',
          screen: 'vitoria',
          title: { type: 'str', value: 'Você é um Mestre!' },
          text: {
            type: 'str',
            value: 'Capturou 3 criaturas da cidade e virou a nova lenda dos treinadores!',
          },
          button: { type: 'str', value: 'Jogar de novo' },
        },
        { type: 'gk:pkmCatchDifficulty', creature: 'Brotim', level: 'normal' },
        { type: 'gk:rpgSetStartMap', map: 'cidade' },
        {
          type: 'gk:rpgCreateMap',
          map: 'cidade',
          cols: { type: 'num', value: 20 },
          rows: { type: 'num', value: 16 },
          ctxName: 'ctx',
          body: [{ type: 'gk:drawBackground', color: '#5c9e4a', grid: false }],
        },
        {
          type: 'gk:createCharacter',
          varName: 'heroi',
          image: '',
          w: { type: 'num', value: 44 },
          h: { type: 'num', value: 56 },
          speed: { type: 'num', value: 220 },
          color: '#c0392b',
        },
        {
          type: 'gk:setHitbox',
          charVar: 'heroi',
          ox: { type: 'num', value: 8 },
          oy: { type: 'num', value: 20 },
          w: { type: 'num', value: 28 },
          h: { type: 'num', value: 34 },
        },
        { type: 'gk:stateLook', charVar: 'heroi', state: 'parado', look: 'treinador' },
        { type: 'gk:stateLook', charVar: 'heroi', state: 'andando', look: 'treinador' },
        {
          type: 'gk:cameraFollow',
          charVar: 'heroi',
          w: { type: 'num', value: 1280 },
          h: { type: 'num', value: 1024 },
        },
      ],
      events: [
        {
          type: 'gk:onEvent',
          event: 'monstrinho:pegou',
          body: [{ type: 'gk:playEffect', fx: 'win' }],
        },
        {
          type: 'gk:rpgOnEnterMap',
          map: 'cidade',
          body: [
            {
              type: 'gk:rpgCreateNpc',
              name: 'Professor',
              cx: { type: 'num', value: 4 },
              cy: { type: 'num', value: 3 },
              image: '',
              look: 'professor',
            },
            {
              type: 'gk:rpgCreateNpc',
              name: 'Idoso',
              cx: { type: 'num', value: 14 },
              cy: { type: 'num', value: 4 },
              image: '',
              look: 'idoso',
            },
            {
              type: 'gk:rpgCreateNpc',
              name: 'Aldeã',
              cx: { type: 'num', value: 8 },
              cy: { type: 'num', value: 5 },
              image: '',
              look: 'aldea',
            },
            {
              type: 'gk:rpgCreateNpc',
              name: 'Enfermeira',
              cx: { type: 'num', value: 3 },
              cy: { type: 'num', value: 12 },
              image: '',
              look: 'enfermeira',
            },
            {
              type: 'gk:rpgBlockCell',
              cx: { type: 'num', value: 4 },
              cy: { type: 'num', value: 2 },
            },
            {
              type: 'gk:rpgBlockCell',
              cx: { type: 'num', value: 14 },
              cy: { type: 'num', value: 3 },
            },
            {
              type: 'gk:rpgBlockCell',
              cx: { type: 'num', value: 3 },
              cy: { type: 'num', value: 11 },
            },
            {
              type: 'gk:rpgBlockCell',
              cx: { type: 'num', value: 17 },
              cy: { type: 'num', value: 13 },
            },
            {
              type: 'gk:pkmGrassCells',
              x1: { type: 'num', value: 6 },
              y1: { type: 'num', value: 8 },
              x2: { type: 'num', value: 18 },
              y2: { type: 'num', value: 14 },
            },
            {
              type: 'gk:pkmWild',
              creature: 'Gotoso',
              min: { type: 'num', value: 3 },
              max: { type: 'num', value: 6 },
            },
            {
              type: 'gk:pkmWild',
              creature: 'Brotim',
              min: { type: 'num', value: 3 },
              max: { type: 'num', value: 6 },
            },
            {
              type: 'gk:pkmWild',
              creature: 'Chaminho',
              min: { type: 'num', value: 4 },
              max: { type: 'num', value: 7 },
            },
            {
              type: 'gk:placeCharacter',
              charVar: 'heroi',
              x: { type: 'num', value: 448 },
              y: { type: 'num', value: 384 },
            },
          ],
        },
        {
          type: 'gk:rpgOnTalk',
          npc: 'Professor',
          body: [
            {
              type: 'if',
              cond: { type: 'gk:rpgHasFlag', flag: 'comecou' },
              then: [
                {
                  type: 'gk:rpgSay',
                  text: {
                    type: 'str',
                    value: 'Vá para a grama alta lá embaixo e capture 3 criaturas!',
                  },
                  speaker: { type: 'str', value: 'Professor' },
                },
              ],
              else: [
                {
                  type: 'gk:rpgSay',
                  text: {
                    type: 'str',
                    value:
                      'Bem-vindo, treinador! Leve o Chaminho e 6 bolas. Pegue 3 criaturas na grama!',
                  },
                  speaker: { type: 'str', value: 'Professor' },
                },
                { type: 'gk:pkmGive', creature: 'Chaminho', level: { type: 'num', value: 5 } },
                {
                  type: 'gk:pkmGiveBall',
                  count: { type: 'num', value: 6 },
                  power: { type: 'num', value: 60 },
                },
                { type: 'gk:rpgAddFlag', flag: 'comecou' },
              ],
            },
          ],
        },
        {
          type: 'gk:rpgOnTalk',
          npc: 'Idoso',
          body: [
            {
              type: 'gk:rpgSay',
              text: {
                type: 'str',
                value: 'Meus ossos doem. No meu tempo, fogo vencia planta e água apagava o fogo!',
              },
              speaker: { type: 'str', value: 'Idoso' },
            },
          ],
        },
        {
          type: 'gk:rpgOnTalk',
          npc: 'Aldeã',
          body: [
            {
              type: 'gk:rpgSay',
              text: {
                type: 'str',
                value: 'Ei, treinador! Você viu a minha criatura? Ela fugiu para a grama alta.',
              },
              speaker: { type: 'str', value: 'Aldeã' },
            },
          ],
        },
        {
          type: 'gk:rpgOnTalk',
          npc: 'Enfermeira',
          body: [
            {
              type: 'gk:rpgSay',
              text: { type: 'str', value: 'Deixe suas criaturas descansarem. Prontas de novo!' },
              speaker: { type: 'str', value: 'Enfermeira' },
            },
            { type: 'gk:pkmHealTeam' },
          ],
        },
        {
          type: 'gk:rpgOnBattleEnd',
          body: [
            {
              type: 'if',
              cond: { type: 'gk:pkmCaught' },
              then: [
                {
                  type: 'if',
                  cond: {
                    type: 'binop',
                    op: '>=',
                    left: { type: 'gk:pkmTeamSize' },
                    right: { type: 'num', value: 4 },
                  },
                  then: [{ type: 'gk:setState', name: 'vitoria' }],
                },
              ],
            },
          ],
        },
      ],
      loops: [
        {
          type: 'gk:onUpdate',
          dtName: 'dt',
          body: [
            {
              type: 'gk:rpgMoveGrid',
              charVar: 'heroi',
              cell: { type: 'num', value: 64 },
              dtVar: 'dt',
            },
            { type: 'gk:autoAnimate', charVar: 'heroi' },
          ],
        },
        {
          type: 'gk:onDraw',
          ctxName: 'ctx',
          body: [
            {
              type: 'forRange',
              varName: 'i',
              from: { type: 'num', value: 0 },
              to: { type: 'num', value: 6 },
              step: { type: 'num', value: 1 },
              body: [
                {
                  type: 'gk:drawLook',
                  look: 'mato',
                  x: {
                    type: 'binop',
                    op: '+',
                    left: { type: 'num', value: 384 },
                    right: {
                      type: 'binop',
                      op: '*',
                      left: { type: 'var', name: 'i' },
                      right: { type: 'num', value: 64 },
                    },
                  },
                  y: { type: 'num', value: 512 },
                  w: { type: 'num', value: 64 },
                  h: { type: 'num', value: 64 },
                },
                {
                  type: 'gk:drawLook',
                  look: 'mato',
                  x: {
                    type: 'binop',
                    op: '+',
                    left: { type: 'num', value: 384 },
                    right: {
                      type: 'binop',
                      op: '*',
                      left: { type: 'var', name: 'i' },
                      right: { type: 'num', value: 64 },
                    },
                  },
                  y: { type: 'num', value: 704 },
                  w: { type: 'num', value: 64 },
                  h: { type: 'num', value: 64 },
                },
              ],
            },
            {
              type: 'gk:drawLook',
              look: 'casa',
              x: { type: 'num', value: 256 },
              y: { type: 'num', value: 128 },
              w: { type: 'num', value: 64 },
              h: { type: 'num', value: 64 },
            },
            {
              type: 'gk:drawLook',
              look: 'casa',
              x: { type: 'num', value: 896 },
              y: { type: 'num', value: 192 },
              w: { type: 'num', value: 64 },
              h: { type: 'num', value: 64 },
            },
            {
              type: 'gk:drawLook',
              look: 'arvore',
              x: { type: 'num', value: 192 },
              y: { type: 'num', value: 704 },
              w: { type: 'num', value: 64 },
              h: { type: 'num', value: 64 },
            },
            {
              type: 'gk:drawLook',
              look: 'arvore',
              x: { type: 'num', value: 1088 },
              y: { type: 'num', value: 832 },
              w: { type: 'num', value: 64 },
              h: { type: 'num', value: 64 },
            },
            { type: 'gk:rpgDrawNpcs' },
            { type: 'gk:drawByDepth', charVar: 'heroi' },
          ],
        },
        {
          type: 'gk:onDrawHud',
          ctxName: 'ctx',
          body: [
            {
              type: 'gk:pkmDrawTeam',
              x: { type: 'num', value: 16 },
              y: { type: 'num', value: 14 },
            },
            {
              type: 'canvasFillStyle',
              ctxVar: 'ctx',
              color: { type: 'color', value: '#123018' },
            },
            { type: 'canvasFont', ctxVar: 'ctx', size: 16, family: 'sans-serif' },
            {
              type: 'canvasFillText',
              ctxVar: 'ctx',
              text: {
                type: 'binop',
                op: '+',
                left: {
                  type: 'binop',
                  op: '+',
                  left: { type: 'str', value: 'Criaturas capturadas: ' },
                  right: {
                    type: 'binop',
                    op: '-',
                    left: { type: 'gk:pkmTeamSize' },
                    right: { type: 'num', value: 1 },
                  },
                },
                right: { type: 'str', value: ' de 3' },
              },
              x: { type: 'num', value: 20 },
              y: { type: 'num', value: 128 },
            },
            {
              type: 'canvasFillText',
              ctxVar: 'ctx',
              text: {
                type: 'binop',
                op: '+',
                left: { type: 'str', value: 'Bolas: ' },
                right: { type: 'gk:pkmBallCount' },
              },
              x: { type: 'num', value: 20 },
              y: { type: 'num', value: 150 },
            },
          ],
        },
      ],
    },
  },
}
