import type { ExtensionExample } from '#extensions'

/**
 * Exemplo bundlado: "Vale Ensolarado Profissional" — o sunnyland-platformer
 * recriado com o 🏃 Kit Plataforma do motor avançado (o mesmo kit do "Salto na
 * Floresta"/"Escalada do Guerreiro Profissional"), SEM assets: a raposinha, o
 * chão de gramado, as tábuas, as gemas, o gambá, o gavião e o fundo são
 * desenhados por código (defineLook + drawBackground). Mostra a arquitetura do
 * kit: pulo gostoso (platformerHero, com coyote/buffer/pulo variável), chão
 * sólido (collideGroup) e tábuas finas que se atravessa por baixo
 * (oneWayPlatform), câmera que segue o herói num vale mais largo que a tela
 * (cameraFollow), gambá que patrulha e vira na beirada e gavião que voa
 * patrulhando (patrolTurnAtWall/patrolAround), os dois derrotados PISANDO
 * (stompKill), gemas coletadas por toque (touching + recycle), corações que
 * caem ao encostar de lado (drawHearts) e renascer no checkpoint ao cair
 * (setCheckpoint + respawn). Juntar as 6 gemas é a vitória.
 *
 * ⚠️ A IR foi GERADA pelo parser real a partir do script achatado (o fonte vive
 * em __gen_valeEnsolarado.ts — se o parser mudar a saída, o drift test
 * valeEnsolaradoExample.test.ts manda re-embutir aqui).
 */
export const valeEnsolaradoExample: ExtensionExample = {
  name: 'Vale Ensolarado Profissional',
  experience: 'game',
  description:
    'A plataforma de coleta do motor avançado: pulo gostoso, pise nos bichos, junte as gemas e não caia no buraco. A câmera segue você por um vale bem largo!',
  ir: {
    html: [],
    css: [],
    extensions: [{ extensionId: 'game-2d-advanced' }],
    version: 2,
    behavior: {
      molds: [
        {
          type: 'gk:defineLook',
          name: 'raposinha',
          ctxName: 'ctx',
          body: [
            {
              type: 'canvasFillStyle',
              ctxVar: 'ctx',
              color: { type: 'color', value: '#e8a33d' },
            },
            {
              type: 'canvasFillRect',
              ctxVar: 'ctx',
              x: { type: 'num', value: 6 },
              y: { type: 'num', value: 12 },
              w: { type: 'num', value: 24 },
              h: { type: 'num', value: 20 },
            },
            {
              type: 'canvasFillStyle',
              ctxVar: 'ctx',
              color: { type: 'color', value: '#fff3d6' },
            },
            {
              type: 'canvasFillRect',
              ctxVar: 'ctx',
              x: { type: 'num', value: 10 },
              y: { type: 'num', value: 20 },
              w: { type: 'num', value: 16 },
              h: { type: 'num', value: 12 },
            },
            {
              type: 'canvasFillStyle',
              ctxVar: 'ctx',
              color: { type: 'color', value: '#e8a33d' },
            },
            {
              type: 'canvasFillRect',
              ctxVar: 'ctx',
              x: { type: 'num', value: 4 },
              y: { type: 'num', value: 6 },
              w: { type: 'num', value: 8 },
              h: { type: 'num', value: 10 },
            },
            {
              type: 'canvasFillRect',
              ctxVar: 'ctx',
              x: { type: 'num', value: 24 },
              y: { type: 'num', value: 6 },
              w: { type: 'num', value: 8 },
              h: { type: 'num', value: 10 },
            },
            {
              type: 'canvasFillStyle',
              ctxVar: 'ctx',
              color: { type: 'color', value: '#3a2a1a' },
            },
            {
              type: 'canvasFillRect',
              ctxVar: 'ctx',
              x: { type: 'num', value: 12 },
              y: { type: 'num', value: 16 },
              w: { type: 'num', value: 4 },
              h: { type: 'num', value: 4 },
            },
            {
              type: 'canvasFillRect',
              ctxVar: 'ctx',
              x: { type: 'num', value: 22 },
              y: { type: 'num', value: 16 },
              w: { type: 'num', value: 4 },
              h: { type: 'num', value: 4 },
            },
            {
              type: 'canvasFillStyle',
              ctxVar: 'ctx',
              color: { type: 'color', value: '#c67d2a' },
            },
            {
              type: 'canvasFillRect',
              ctxVar: 'ctx',
              x: { type: 'num', value: 8 },
              y: { type: 'num', value: 32 },
              w: { type: 'num', value: 8 },
              h: { type: 'num', value: 12 },
            },
            {
              type: 'canvasFillRect',
              ctxVar: 'ctx',
              x: { type: 'num', value: 20 },
              y: { type: 'num', value: 32 },
              w: { type: 'num', value: 8 },
              h: { type: 'num', value: 12 },
            },
          ],
          baseW: { type: 'num', value: 36 },
          baseH: { type: 'num', value: 44 },
        },
        {
          type: 'gk:defineLook',
          name: 'gramado',
          ctxName: 'ctx',
          body: [
            {
              type: 'canvasFillStyle',
              ctxVar: 'ctx',
              color: { type: 'color', value: '#6b4f2a' },
            },
            {
              type: 'canvasFillRect',
              ctxVar: 'ctx',
              x: { type: 'num', value: 0 },
              y: { type: 'num', value: 0 },
              w: { type: 'num', value: 96 },
              h: { type: 'num', value: 32 },
            },
            {
              type: 'canvasFillStyle',
              ctxVar: 'ctx',
              color: { type: 'color', value: '#4caf50' },
            },
            {
              type: 'canvasFillRect',
              ctxVar: 'ctx',
              x: { type: 'num', value: 0 },
              y: { type: 'num', value: 0 },
              w: { type: 'num', value: 96 },
              h: { type: 'num', value: 8 },
            },
            {
              type: 'canvasFillStyle',
              ctxVar: 'ctx',
              color: { type: 'color', value: '#8bc34a' },
            },
            {
              type: 'canvasFillRect',
              ctxVar: 'ctx',
              x: { type: 'num', value: 0 },
              y: { type: 'num', value: 0 },
              w: { type: 'num', value: 96 },
              h: { type: 'num', value: 3 },
            },
          ],
          baseW: { type: 'num', value: 96 },
          baseH: { type: 'num', value: 32 },
        },
        {
          type: 'gk:defineLook',
          name: 'tabua',
          ctxName: 'ctx',
          body: [
            {
              type: 'canvasFillStyle',
              ctxVar: 'ctx',
              color: { type: 'color', value: '#a97c50' },
            },
            {
              type: 'canvasFillRect',
              ctxVar: 'ctx',
              x: { type: 'num', value: 0 },
              y: { type: 'num', value: 0 },
              w: { type: 'num', value: 96 },
              h: { type: 'num', value: 12 },
            },
            {
              type: 'canvasFillStyle',
              ctxVar: 'ctx',
              color: { type: 'color', value: '#7a5a34' },
            },
            {
              type: 'canvasFillRect',
              ctxVar: 'ctx',
              x: { type: 'num', value: 0 },
              y: { type: 'num', value: 9 },
              w: { type: 'num', value: 96 },
              h: { type: 'num', value: 3 },
            },
          ],
          baseW: { type: 'num', value: 96 },
          baseH: { type: 'num', value: 12 },
        },
        {
          type: 'gk:defineLook',
          name: 'gema',
          ctxName: 'ctx',
          body: [
            {
              type: 'canvasFillStyle',
              ctxVar: 'ctx',
              color: { type: 'color', value: '#26c6da' },
            },
            {
              type: 'canvasFillRect',
              ctxVar: 'ctx',
              x: { type: 'num', value: 4 },
              y: { type: 'num', value: 2 },
              w: { type: 'num', value: 16 },
              h: { type: 'num', value: 8 },
            },
            {
              type: 'canvasFillRect',
              ctxVar: 'ctx',
              x: { type: 'num', value: 6 },
              y: { type: 'num', value: 10 },
              w: { type: 'num', value: 12 },
              h: { type: 'num', value: 10 },
            },
            {
              type: 'canvasFillStyle',
              ctxVar: 'ctx',
              color: { type: 'color', value: '#b2ebf2' },
            },
            {
              type: 'canvasFillRect',
              ctxVar: 'ctx',
              x: { type: 'num', value: 7 },
              y: { type: 'num', value: 4 },
              w: { type: 'num', value: 5 },
              h: { type: 'num', value: 5 },
            },
          ],
          baseW: { type: 'num', value: 24 },
          baseH: { type: 'num', value: 24 },
        },
        {
          type: 'gk:defineLook',
          name: 'gambá',
          ctxName: 'ctx',
          body: [
            {
              type: 'canvasFillStyle',
              ctxVar: 'ctx',
              color: { type: 'color', value: '#7e6a99' },
            },
            {
              type: 'canvasFillRect',
              ctxVar: 'ctx',
              x: { type: 'num', value: 2 },
              y: { type: 'num', value: 10 },
              w: { type: 'num', value: 36 },
              h: { type: 'num', value: 18 },
            },
            {
              type: 'canvasFillStyle',
              ctxVar: 'ctx',
              color: { type: 'color', value: '#efe6ff' },
            },
            {
              type: 'canvasFillRect',
              ctxVar: 'ctx',
              x: { type: 'num', value: 28 },
              y: { type: 'num', value: 4 },
              w: { type: 'num', value: 12 },
              h: { type: 'num', value: 14 },
            },
            {
              type: 'canvasFillStyle',
              ctxVar: 'ctx',
              color: { type: 'color', value: '#2a2135' },
            },
            {
              type: 'canvasFillRect',
              ctxVar: 'ctx',
              x: { type: 'num', value: 33 },
              y: { type: 'num', value: 8 },
              w: { type: 'num', value: 4 },
              h: { type: 'num', value: 4 },
            },
          ],
          baseW: { type: 'num', value: 40 },
          baseH: { type: 'num', value: 30 },
        },
        {
          type: 'gk:defineLook',
          name: 'gavião',
          ctxName: 'ctx',
          body: [
            {
              type: 'canvasFillStyle',
              ctxVar: 'ctx',
              color: { type: 'color', value: '#8d6e63' },
            },
            {
              type: 'canvasFillRect',
              ctxVar: 'ctx',
              x: { type: 'num', value: 10 },
              y: { type: 'num', value: 6 },
              w: { type: 'num', value: 20 },
              h: { type: 'num', value: 16 },
            },
            {
              type: 'canvasFillStyle',
              ctxVar: 'ctx',
              color: { type: 'color', value: '#5d4037' },
            },
            {
              type: 'canvasFillRect',
              ctxVar: 'ctx',
              x: { type: 'num', value: 0 },
              y: { type: 'num', value: 8 },
              w: { type: 'num', value: 12 },
              h: { type: 'num', value: 6 },
            },
            {
              type: 'canvasFillRect',
              ctxVar: 'ctx',
              x: { type: 'num', value: 28 },
              y: { type: 'num', value: 8 },
              w: { type: 'num', value: 12 },
              h: { type: 'num', value: 6 },
            },
            {
              type: 'canvasFillStyle',
              ctxVar: 'ctx',
              color: { type: 'color', value: '#ffca28' },
            },
            {
              type: 'canvasFillRect',
              ctxVar: 'ctx',
              x: { type: 'num', value: 18 },
              y: { type: 'num', value: 20 },
              w: { type: 'num', value: 6 },
              h: { type: 'num', value: 6 },
            },
          ],
          baseW: { type: 'num', value: 40 },
          baseH: { type: 'num', value: 28 },
        },
        {
          type: 'gk:defineMold',
          name: 'chao',
          w: { type: 'num', value: 96 },
          h: { type: 'num', value: 32 },
          health: { type: 'num', value: 1 },
          speed: { type: 'num', value: 0 },
          damage: { type: 'num', value: 0 },
          color: '#6b4f2a',
          image: '',
          look: 'gramado',
        },
        {
          type: 'gk:defineMold',
          name: 'tabua',
          w: { type: 'num', value: 96 },
          h: { type: 'num', value: 12 },
          health: { type: 'num', value: 1 },
          speed: { type: 'num', value: 0 },
          damage: { type: 'num', value: 0 },
          color: '#a97c50',
          image: '',
          look: 'tabua',
        },
        {
          type: 'gk:defineMold',
          name: 'gema',
          w: { type: 'num', value: 24 },
          h: { type: 'num', value: 24 },
          health: { type: 'num', value: 1 },
          speed: { type: 'num', value: 0 },
          damage: { type: 'num', value: 0 },
          color: '#26c6da',
          image: '',
          look: 'gema',
        },
        {
          type: 'gk:defineMold',
          name: 'gambá',
          w: { type: 'num', value: 40 },
          h: { type: 'num', value: 30 },
          health: { type: 'num', value: 1 },
          speed: { type: 'num', value: 40 },
          damage: { type: 'num', value: 1 },
          color: '#7e6a99',
          image: '',
          look: 'gambá',
        },
        {
          type: 'gk:defineMold',
          name: 'gavião',
          w: { type: 'num', value: 40 },
          h: { type: 'num', value: 28 },
          health: { type: 'num', value: 1 },
          speed: { type: 'num', value: 60 },
          damage: { type: 'num', value: 1 },
          color: '#8d6e63',
          image: '',
          look: 'gavião',
        },
        {
          type: 'gk:defineEffect',
          name: 'poeira',
          count: { type: 'num', value: 8 },
          color: '#ffffff',
          size: { type: 'num', value: 3 },
          life: { type: 'num', value: 0.4 },
          speed: { type: 'num', value: 100 },
          gravity: { type: 'num', value: 300 },
        },
        {
          type: 'gk:defineEffect',
          name: 'brilho',
          count: { type: 'num', value: 12 },
          color: '#b2ebf2',
          size: { type: 'num', value: 4 },
          life: { type: 'num', value: 0.5 },
          speed: { type: 'num', value: 160 },
          gravity: { type: 'num', value: 0 },
        },
      ],
      start: [
        {
          type: 'gk:setup',
          w: { type: 'num', value: 960 },
          h: { type: 'num', value: 540 },
          bg: '#8ecde6',
          accent: '#e9c46a',
        },
        {
          type: 'gk:setScreenText',
          screen: 'menu',
          title: { type: 'str', value: 'Vale Ensolarado Profissional' },
          text: {
            type: 'str',
            value:
              'Use as setas para andar e pular. Pise nos bichos, junte as 6 gemas e não caia no buraco!',
          },
          button: { type: 'str', value: 'Explorar o vale' },
        },
        {
          type: 'gk:setScreenText',
          screen: 'vitoria',
          title: { type: 'str', value: 'Vale limpo!' },
          text: {
            type: 'str',
            value: 'Você juntou todas as gemas do vale ensolarado. Que aventura!',
          },
          button: { type: 'str', value: 'Explorar de novo' },
        },
        {
          type: 'gk:setScreenText',
          screen: 'fim',
          title: { type: 'str', value: 'Ai!' },
          text: { type: 'str', value: 'Um bicho tirou todos os seus corações. Tente de novo!' },
          button: { type: 'str', value: 'Tentar de novo' },
        },
        {
          type: 'gk:setJumpFeel',
          coyote: { type: 'num', value: 0.1 },
          buffer: { type: 'num', value: 0.1 },
          hold: { type: 'num', value: 0.3 },
          gravity: { type: 'num', value: 2000 },
        },
        {
          type: 'gk:createCharacter',
          varName: 'heroi',
          image: '',
          w: { type: 'num', value: 36 },
          h: { type: 'num', value: 44 },
          speed: { type: 'num', value: 220 },
          color: '#e8a33d',
        },
        { type: 'gk:stateLook', charVar: 'heroi', state: 'parado', look: 'raposinha' },
        { type: 'var', name: 'gemas', value: { type: 'num', value: 0 } },
        { type: 'var', name: 'vidas', value: { type: 'num', value: 3 } },
        {
          type: 'gk:setCheckpoint',
          x: { type: 'num', value: 80 },
          y: { type: 'num', value: 380 },
        },
        { type: 'gk:respawn', charVar: 'heroi' },
        {
          type: 'gk:spawnFromMold',
          mold: 'chao',
          x: { type: 'num', value: 0 },
          y: { type: 'num', value: 460 },
        },
        {
          type: 'gk:spawnFromMold',
          mold: 'chao',
          x: { type: 'num', value: 96 },
          y: { type: 'num', value: 460 },
        },
        {
          type: 'gk:spawnFromMold',
          mold: 'chao',
          x: { type: 'num', value: 192 },
          y: { type: 'num', value: 460 },
        },
        {
          type: 'gk:spawnFromMold',
          mold: 'chao',
          x: { type: 'num', value: 480 },
          y: { type: 'num', value: 460 },
        },
        {
          type: 'gk:spawnFromMold',
          mold: 'chao',
          x: { type: 'num', value: 576 },
          y: { type: 'num', value: 460 },
        },
        {
          type: 'gk:spawnFromMold',
          mold: 'chao',
          x: { type: 'num', value: 960 },
          y: { type: 'num', value: 460 },
        },
        {
          type: 'gk:spawnFromMold',
          mold: 'chao',
          x: { type: 'num', value: 1056 },
          y: { type: 'num', value: 460 },
        },
        {
          type: 'gk:spawnFromMold',
          mold: 'chao',
          x: { type: 'num', value: 1152 },
          y: { type: 'num', value: 460 },
        },
        {
          type: 'gk:spawnFromMold',
          mold: 'chao',
          x: { type: 'num', value: 1440 },
          y: { type: 'num', value: 460 },
        },
        {
          type: 'gk:spawnFromMold',
          mold: 'chao',
          x: { type: 'num', value: 1536 },
          y: { type: 'num', value: 460 },
        },
        {
          type: 'gk:spawnFromMold',
          mold: 'tabua',
          x: { type: 'num', value: 300 },
          y: { type: 'num', value: 360 },
        },
        {
          type: 'gk:spawnFromMold',
          mold: 'tabua',
          x: { type: 'num', value: 700 },
          y: { type: 'num', value: 320 },
        },
        {
          type: 'gk:spawnFromMold',
          mold: 'tabua',
          x: { type: 'num', value: 1080 },
          y: { type: 'num', value: 340 },
        },
        {
          type: 'gk:spawnFromMold',
          mold: 'tabua',
          x: { type: 'num', value: 1260 },
          y: { type: 'num', value: 260 },
        },
        {
          type: 'gk:spawnFromMold',
          mold: 'gema',
          x: { type: 'num', value: 120 },
          y: { type: 'num', value: 400 },
        },
        {
          type: 'gk:spawnFromMold',
          mold: 'gema',
          x: { type: 'num', value: 316 },
          y: { type: 'num', value: 320 },
        },
        {
          type: 'gk:spawnFromMold',
          mold: 'gema',
          x: { type: 'num', value: 540 },
          y: { type: 'num', value: 400 },
        },
        {
          type: 'gk:spawnFromMold',
          mold: 'gema',
          x: { type: 'num', value: 716 },
          y: { type: 'num', value: 280 },
        },
        {
          type: 'gk:spawnFromMold',
          mold: 'gema',
          x: { type: 'num', value: 1096 },
          y: { type: 'num', value: 300 },
        },
        {
          type: 'gk:spawnFromMold',
          mold: 'gema',
          x: { type: 'num', value: 1480 },
          y: { type: 'num', value: 400 },
        },
        {
          type: 'gk:spawnFromMold',
          mold: 'gambá',
          x: { type: 'num', value: 520 },
          y: { type: 'num', value: 430 },
        },
        {
          type: 'gk:spawnFromMold',
          mold: 'gambá',
          x: { type: 'num', value: 1000 },
          y: { type: 'num', value: 430 },
        },
        {
          type: 'gk:spawnFromMold',
          mold: 'gavião',
          x: { type: 'num', value: 780 },
          y: { type: 'num', value: 260 },
        },
        {
          type: 'gk:spawnFromMold',
          mold: 'gavião',
          x: { type: 'num', value: 1300 },
          y: { type: 'num', value: 220 },
        },
        {
          type: 'gk:cameraFollow',
          charVar: 'heroi',
          w: { type: 'num', value: 1632 },
          h: { type: 'num', value: 540 },
        },
      ],
      events: [
        {
          type: 'gk:onEvent',
          event: 'plataforma:pisou',
          body: [
            {
              type: 'gk:burst',
              effect: 'poeira',
              x: {
                type: 'binop',
                op: '+',
                left: { type: 'gk:charX', charVar: 'heroi' },
                right: { type: 'num', value: 18 },
              },
              y: {
                type: 'binop',
                op: '+',
                left: { type: 'gk:charY', charVar: 'heroi' },
                right: { type: 'num', value: 44 },
              },
            },
          ],
        },
      ],
      loops: [
        {
          type: 'gk:onUpdate',
          dtName: 'dt',
          body: [
            {
              type: 'gk:platformerHero',
              charVar: 'heroi',
              speed: { type: 'num', value: 220 },
              force: { type: 'num', value: 640 },
              dtVar: 'dt',
            },
            { type: 'gk:dropThrough', charVar: 'heroi' },
            { type: 'gk:collideGroup', charVar: 'heroi', mold: 'chao' },
            { type: 'gk:oneWayPlatform', charVar: 'heroi', mold: 'tabua', dtVar: 'dt' },
            {
              type: 'gk:forEachActive',
              mold: 'gambá',
              itemName: 'item',
              body: [
                {
                  type: 'gk:patrolTurnAtWall',
                  charVar: 'item',
                  speed: { type: 'num', value: 40 },
                },
                {
                  type: 'gk:applyGravity',
                  charVar: 'item',
                  g: { type: 'num', value: 2160 },
                  dtVar: 'dt',
                },
                { type: 'gk:moveByVelocity', charVar: 'item', dtVar: 'dt' },
                { type: 'gk:collideGroup', charVar: 'item', mold: 'chao' },
              ],
            },
            {
              type: 'gk:forEachActive',
              mold: 'gavião',
              itemName: 'item',
              body: [
                {
                  type: 'gk:patrolAround',
                  charVar: 'item',
                  ox: { type: 'gk:charX', charVar: 'item' },
                  oy: { type: 'gk:charY', charVar: 'item' },
                  radius: { type: 'num', value: 120 },
                },
              ],
            },
            {
              type: 'gk:stompKill',
              charVar: 'heroi',
              mold: 'gambá',
              bounce: { type: 'num', value: 420 },
            },
            {
              type: 'gk:stompKill',
              charVar: 'heroi',
              mold: 'gavião',
              bounce: { type: 'num', value: 420 },
            },
            { type: 'gk:platformerAnim', charVar: 'heroi' },
            {
              type: 'gk:forEachActive',
              mold: 'gema',
              itemName: 'item',
              body: [
                {
                  type: 'if',
                  cond: { type: 'gk:charactersTouch', aVar: 'heroi', bVar: 'item' },
                  then: [
                    {
                      type: 'assign',
                      name: 'gemas',
                      value: {
                        type: 'binop',
                        op: '+',
                        left: { type: 'var', name: 'gemas' },
                        right: { type: 'num', value: 1 },
                      },
                    },
                    {
                      type: 'gk:burst',
                      effect: 'brilho',
                      x: {
                        type: 'binop',
                        op: '+',
                        left: { type: 'gk:charX', charVar: 'item' },
                        right: { type: 'num', value: 12 },
                      },
                      y: {
                        type: 'binop',
                        op: '+',
                        left: { type: 'gk:charY', charVar: 'item' },
                        right: { type: 'num', value: 12 },
                      },
                    },
                    { type: 'gk:recycle', charVar: 'item' },
                  ],
                },
              ],
            },
            {
              type: 'gk:forEachActive',
              mold: 'gambá',
              itemName: 'item',
              body: [
                {
                  type: 'if',
                  cond: {
                    type: 'logical',
                    op: '&&',
                    left: { type: 'gk:charactersTouch', aVar: 'heroi', bVar: 'item' },
                    right: {
                      type: 'logicalNot',
                      value: { type: 'gk:isInvincible', charVar: 'heroi' },
                    },
                  },
                  then: [
                    {
                      type: 'assign',
                      name: 'vidas',
                      value: {
                        type: 'binop',
                        op: '-',
                        left: { type: 'var', name: 'vidas' },
                        right: { type: 'num', value: 1 },
                      },
                    },
                    {
                      type: 'gk:hurt',
                      charVar: 'heroi',
                      amount: { type: 'num', value: 0 },
                      iframes: { type: 'num', value: 1 },
                    },
                    {
                      type: 'gk:knockback',
                      charVar: 'heroi',
                      fromVar: 'item',
                      force: { type: 'num', value: 320 },
                    },
                    {
                      type: 'gk:cameraShake',
                      intensity: { type: 'num', value: 6 },
                      seconds: { type: 'num', value: 0.2 },
                    },
                  ],
                },
              ],
            },
            {
              type: 'gk:forEachActive',
              mold: 'gavião',
              itemName: 'item',
              body: [
                {
                  type: 'if',
                  cond: {
                    type: 'logical',
                    op: '&&',
                    left: { type: 'gk:charactersTouch', aVar: 'heroi', bVar: 'item' },
                    right: {
                      type: 'logicalNot',
                      value: { type: 'gk:isInvincible', charVar: 'heroi' },
                    },
                  },
                  then: [
                    {
                      type: 'assign',
                      name: 'vidas',
                      value: {
                        type: 'binop',
                        op: '-',
                        left: { type: 'var', name: 'vidas' },
                        right: { type: 'num', value: 1 },
                      },
                    },
                    {
                      type: 'gk:hurt',
                      charVar: 'heroi',
                      amount: { type: 'num', value: 0 },
                      iframes: { type: 'num', value: 1 },
                    },
                    {
                      type: 'gk:knockback',
                      charVar: 'heroi',
                      fromVar: 'item',
                      force: { type: 'num', value: 320 },
                    },
                    {
                      type: 'gk:cameraShake',
                      intensity: { type: 'num', value: 6 },
                      seconds: { type: 'num', value: 0.2 },
                    },
                  ],
                },
              ],
            },
            {
              type: 'if',
              cond: {
                type: 'binop',
                op: '>',
                left: { type: 'gk:charY', charVar: 'heroi' },
                right: { type: 'num', value: 620 },
              },
              then: [
                {
                  type: 'assign',
                  name: 'vidas',
                  value: {
                    type: 'binop',
                    op: '-',
                    left: { type: 'var', name: 'vidas' },
                    right: { type: 'num', value: 1 },
                  },
                },
                { type: 'gk:respawn', charVar: 'heroi' },
              ],
            },
            {
              type: 'if',
              cond: {
                type: 'binop',
                op: '<=',
                left: { type: 'var', name: 'vidas' },
                right: { type: 'num', value: 0 },
              },
              then: [{ type: 'gk:endGame' }],
            },
            {
              type: 'if',
              cond: {
                type: 'binop',
                op: '>=',
                left: { type: 'var', name: 'gemas' },
                right: { type: 'num', value: 6 },
              },
              then: [{ type: 'gk:setState', name: 'vitoria' }],
            },
          ],
        },
        {
          type: 'gk:onDraw',
          ctxName: 'ctx',
          body: [
            { type: 'gk:drawBackground', color: '#8ecde6', grid: false },
            { type: 'gk:drawActive', mold: 'chao' },
            { type: 'gk:drawActive', mold: 'tabua' },
            { type: 'gk:drawActive', mold: 'gema' },
            { type: 'gk:drawActive', mold: 'gambá' },
            { type: 'gk:drawActive', mold: 'gavião' },
            { type: 'gk:drawShadow', charVar: 'heroi' },
            { type: 'gk:drawCharacter', charVar: 'heroi' },
            { type: 'gk:drawEffects' },
          ],
        },
        {
          type: 'gk:onDrawHud',
          ctxName: 'ctx',
          body: [
            {
              type: 'gk:drawHearts',
              current: {
                type: 'binop',
                op: '/',
                left: { type: 'var', name: 'vidas' },
                right: { type: 'num', value: 3 },
              },
              max: { type: 'num', value: 3 },
              x: { type: 'num', value: 20 },
              y: { type: 'num', value: 20 },
            },
            {
              type: 'canvasFillStyle',
              ctxVar: 'ctx',
              color: { type: 'color', value: '#123018' },
            },
            { type: 'canvasFont', ctxVar: 'ctx', size: 24, family: 'sans-serif' },
            {
              type: 'canvasFillText',
              ctxVar: 'ctx',
              text: {
                type: 'binop',
                op: '+',
                left: {
                  type: 'binop',
                  op: '+',
                  left: { type: 'str', value: 'Gemas: ' },
                  right: { type: 'var', name: 'gemas' },
                },
                right: { type: 'str', value: '/6' },
              },
              x: { type: 'num', value: 20 },
              y: { type: 'num', value: 72 },
            },
          ],
        },
      ],
    },
  },
}
