import type { ExtensionExample } from '#extensions'

/**
 * Exemplo bundlado: "Vila Ninja Profissional" — o ninja-adventure (aventura
 * top-down) recriado com as peças do 🧙 Kit RPG do motor avançado (o mesmo
 * caminho de "Aventura do Herói"/"Vila do Dragão"), SEM assets: o ninja, os
 * monstros de bambu e dragão, as casas, as árvores e o chão são desenhados por
 * código (defineLook + drawBackground). Mostra a arquitetura: mundo top-down
 * MAIOR que a tela com câmera presa no mapa (createEmptyTilemap +
 * cameraFollowMap), andar nas 4 direções com colisão (moveWithKeys +
 * collideGroup), a lançada NA DIREÇÃO que olha com janela e i-frames
 * (attackFacing + setSwingWindow + didHit), FSM por entidade dirigida por
 * distância (parado -> perseguir -> golpe, via entityState + distanceBetween),
 * monstros que VAGUEIAM em anel no posto (patrolAround), vida em corações
 * (drawHearts) com empurrão nos dois sentidos (knockback), e a missão de
 * derrotar TODOS os 6 monstros que liga a tela de vitória (setMission +
 * missionKill).
 *
 * ⚠️ A IR foi GERADA pelo parser real a partir do script achatado (o fonte vive
 * em __gen_vilaNinja.ts — se o parser mudar a saída, o drift test
 * vilaNinjaExample.test.ts manda re-embutir aqui).
 */
export const vilaNinjaExample: ExtensionExample = {
  name: 'Vila Ninja Profissional',
  experience: 'game',
  description:
    'A aventura top-down do motor avançado: ande nas 4 direções, lance a espada na direção que olha e derrote todos os monstros. A câmera segue você pela vila ninja!',
  ir: {
    html: [],
    css: [],
    extensions: [{ extensionId: 'game-2d-advanced' }],
    version: 2,
    behavior: {
      start: [
        {
          type: 'gk:setup',
          w: { type: 'num', value: 960 },
          h: { type: 'num', value: 540 },
          bg: '#3f7d4e',
          accent: '#e63946',
        },
        {
          type: 'gk:setScreenText',
          screen: 'menu',
          title: { type: 'str', value: 'Vila Ninja Profissional' },
          text: {
            type: 'str',
            value:
              'Setas: andar nas 4 direções. ESPAÇO: lançada na direção que olha. Derrote os 6 monstros da vila ninja!',
          },
          button: { type: 'str', value: 'Começar a missão' },
        },
        {
          type: 'gk:setScreenText',
          screen: 'vitoria',
          title: { type: 'str', value: 'Vila em paz!' },
          text: {
            type: 'str',
            value: 'Você derrotou todos os monstros. A vila ninja está a salvo!',
          },
          button: { type: 'str', value: 'Jogar de novo' },
        },
        {
          type: 'gk:setScreenText',
          screen: 'fim',
          title: { type: 'str', value: 'O ninja caiu!' },
          text: { type: 'str', value: 'Os monstros venceram desta vez. Tente de novo!' },
          button: { type: 'str', value: 'Tentar de novo' },
        },
        {
          type: 'gk:defineLook',
          name: 'ninja parado',
          ctxName: 'ctx',
          body: [
            {
              type: 'canvasFillStyle',
              ctxVar: 'ctx',
              color: { type: 'color', value: '#2b3a67' },
            },
            {
              type: 'canvasFillRect',
              ctxVar: 'ctx',
              x: { type: 'num', value: 10 },
              y: { type: 'num', value: 2 },
              w: { type: 'num', value: 20 },
              h: { type: 'num', value: 12 },
            },
            {
              type: 'canvasFillStyle',
              ctxVar: 'ctx',
              color: { type: 'color', value: '#f2c6a0' },
            },
            {
              type: 'canvasFillRect',
              ctxVar: 'ctx',
              x: { type: 'num', value: 13 },
              y: { type: 'num', value: 12 },
              w: { type: 'num', value: 14 },
              h: { type: 'num', value: 8 },
            },
            {
              type: 'canvasFillStyle',
              ctxVar: 'ctx',
              color: { type: 'color', value: '#26314f' },
            },
            {
              type: 'canvasFillRect',
              ctxVar: 'ctx',
              x: { type: 'num', value: 8 },
              y: { type: 'num', value: 20 },
              w: { type: 'num', value: 24 },
              h: { type: 'num', value: 20 },
            },
            {
              type: 'canvasFillStyle',
              ctxVar: 'ctx',
              color: { type: 'color', value: '#1a2238' },
            },
            {
              type: 'canvasFillRect',
              ctxVar: 'ctx',
              x: { type: 'num', value: 12 },
              y: { type: 'num', value: 40 },
              w: { type: 'num', value: 7 },
              h: { type: 'num', value: 14 },
            },
            {
              type: 'canvasFillRect',
              ctxVar: 'ctx',
              x: { type: 'num', value: 21 },
              y: { type: 'num', value: 40 },
              w: { type: 'num', value: 7 },
              h: { type: 'num', value: 14 },
            },
          ],
          baseW: { type: 'num', value: 40 },
          baseH: { type: 'num', value: 54 },
        },
        {
          type: 'gk:defineLook',
          name: 'ninja andando',
          ctxName: 'ctx',
          body: [
            {
              type: 'canvasFillStyle',
              ctxVar: 'ctx',
              color: { type: 'color', value: '#2b3a67' },
            },
            {
              type: 'canvasFillRect',
              ctxVar: 'ctx',
              x: { type: 'num', value: 10 },
              y: { type: 'num', value: 2 },
              w: { type: 'num', value: 20 },
              h: { type: 'num', value: 12 },
            },
            {
              type: 'canvasFillStyle',
              ctxVar: 'ctx',
              color: { type: 'color', value: '#f2c6a0' },
            },
            {
              type: 'canvasFillRect',
              ctxVar: 'ctx',
              x: { type: 'num', value: 13 },
              y: { type: 'num', value: 12 },
              w: { type: 'num', value: 14 },
              h: { type: 'num', value: 8 },
            },
            {
              type: 'canvasFillStyle',
              ctxVar: 'ctx',
              color: { type: 'color', value: '#26314f' },
            },
            {
              type: 'canvasFillRect',
              ctxVar: 'ctx',
              x: { type: 'num', value: 8 },
              y: { type: 'num', value: 20 },
              w: { type: 'num', value: 24 },
              h: { type: 'num', value: 20 },
            },
            {
              type: 'canvasFillStyle',
              ctxVar: 'ctx',
              color: { type: 'color', value: '#1a2238' },
            },
            {
              type: 'canvasFillRect',
              ctxVar: 'ctx',
              x: { type: 'num', value: 10 },
              y: { type: 'num', value: 40 },
              w: { type: 'num', value: 7 },
              h: { type: 'num', value: 14 },
            },
            {
              type: 'canvasFillRect',
              ctxVar: 'ctx',
              x: { type: 'num', value: 23 },
              y: { type: 'num', value: 40 },
              w: { type: 'num', value: 7 },
              h: { type: 'num', value: 14 },
            },
          ],
          baseW: { type: 'num', value: 40 },
          baseH: { type: 'num', value: 54 },
        },
        {
          type: 'gk:defineLook',
          name: 'ninja golpe',
          ctxName: 'ctx',
          body: [
            {
              type: 'canvasFillStyle',
              ctxVar: 'ctx',
              color: { type: 'color', value: '#2b3a67' },
            },
            {
              type: 'canvasFillRect',
              ctxVar: 'ctx',
              x: { type: 'num', value: 6 },
              y: { type: 'num', value: 2 },
              w: { type: 'num', value: 20 },
              h: { type: 'num', value: 12 },
            },
            {
              type: 'canvasFillStyle',
              ctxVar: 'ctx',
              color: { type: 'color', value: '#f2c6a0' },
            },
            {
              type: 'canvasFillRect',
              ctxVar: 'ctx',
              x: { type: 'num', value: 9 },
              y: { type: 'num', value: 12 },
              w: { type: 'num', value: 14 },
              h: { type: 'num', value: 8 },
            },
            {
              type: 'canvasFillStyle',
              ctxVar: 'ctx',
              color: { type: 'color', value: '#26314f' },
            },
            {
              type: 'canvasFillRect',
              ctxVar: 'ctx',
              x: { type: 'num', value: 4 },
              y: { type: 'num', value: 20 },
              w: { type: 'num', value: 24 },
              h: { type: 'num', value: 20 },
            },
            {
              type: 'canvasFillStyle',
              ctxVar: 'ctx',
              color: { type: 'color', value: '#d0d7de' },
            },
            {
              type: 'canvasFillRect',
              ctxVar: 'ctx',
              x: { type: 'num', value: 28 },
              y: { type: 'num', value: 24 },
              w: { type: 'num', value: 12 },
              h: { type: 'num', value: 5 },
            },
          ],
          baseW: { type: 'num', value: 40 },
          baseH: { type: 'num', value: 54 },
        },
        {
          type: 'gk:defineLook',
          name: 'bambu',
          ctxName: 'ctx',
          body: [
            {
              type: 'canvasFillStyle',
              ctxVar: 'ctx',
              color: { type: 'color', value: '#6ab04c' },
            },
            {
              type: 'canvasFillRect',
              ctxVar: 'ctx',
              x: { type: 'num', value: 6 },
              y: { type: 'num', value: 8 },
              w: { type: 'num', value: 32 },
              h: { type: 'num', value: 30 },
            },
            {
              type: 'canvasFillStyle',
              ctxVar: 'ctx',
              color: { type: 'color', value: '#3d7a2a' },
            },
            {
              type: 'canvasFillRect',
              ctxVar: 'ctx',
              x: { type: 'num', value: 6 },
              y: { type: 'num', value: 8 },
              w: { type: 'num', value: 32 },
              h: { type: 'num', value: 6 },
            },
            {
              type: 'canvasFillStyle',
              ctxVar: 'ctx',
              color: { type: 'color', value: '#1b3a12' },
            },
            {
              type: 'canvasFillRect',
              ctxVar: 'ctx',
              x: { type: 'num', value: 12 },
              y: { type: 'num', value: 20 },
              w: { type: 'num', value: 6 },
              h: { type: 'num', value: 6 },
            },
            {
              type: 'canvasFillRect',
              ctxVar: 'ctx',
              x: { type: 'num', value: 26 },
              y: { type: 'num', value: 20 },
              w: { type: 'num', value: 6 },
              h: { type: 'num', value: 6 },
            },
          ],
          baseW: { type: 'num', value: 44 },
          baseH: { type: 'num', value: 40 },
        },
        {
          type: 'gk:defineLook',
          name: 'dragao',
          ctxName: 'ctx',
          body: [
            {
              type: 'canvasFillStyle',
              ctxVar: 'ctx',
              color: { type: 'color', value: '#b33939' },
            },
            {
              type: 'canvasFillRect',
              ctxVar: 'ctx',
              x: { type: 'num', value: 4 },
              y: { type: 'num', value: 10 },
              w: { type: 'num', value: 36 },
              h: { type: 'num', value: 26 },
            },
            {
              type: 'canvasFillStyle',
              ctxVar: 'ctx',
              color: { type: 'color', value: '#e55039' },
            },
            {
              type: 'canvasFillRect',
              ctxVar: 'ctx',
              x: { type: 'num', value: 36 },
              y: { type: 'num', value: 4 },
              w: { type: 'num', value: 12 },
              h: { type: 'num', value: 16 },
            },
            {
              type: 'canvasFillStyle',
              ctxVar: 'ctx',
              color: { type: 'color', value: '#f6e58d' },
            },
            {
              type: 'canvasFillRect',
              ctxVar: 'ctx',
              x: { type: 'num', value: 10 },
              y: { type: 'num', value: 20 },
              w: { type: 'num', value: 8 },
              h: { type: 'num', value: 8 },
            },
            {
              type: 'canvasFillRect',
              ctxVar: 'ctx',
              x: { type: 'num', value: 24 },
              y: { type: 'num', value: 20 },
              w: { type: 'num', value: 8 },
              h: { type: 'num', value: 8 },
            },
          ],
          baseW: { type: 'num', value: 50 },
          baseH: { type: 'num', value: 38 },
        },
        {
          type: 'gk:defineLook',
          name: 'casa',
          ctxName: 'ctx',
          body: [
            {
              type: 'canvasFillStyle',
              ctxVar: 'ctx',
              color: { type: 'color', value: '#c9a76b' },
            },
            {
              type: 'canvasFillRect',
              ctxVar: 'ctx',
              x: { type: 'num', value: 0 },
              y: { type: 'num', value: 26 },
              w: { type: 'num', value: 72 },
              h: { type: 'num', value: 46 },
            },
            {
              type: 'canvasFillStyle',
              ctxVar: 'ctx',
              color: { type: 'color', value: '#7d4f2a' },
            },
            {
              type: 'canvasFillRect',
              ctxVar: 'ctx',
              x: { type: 'num', value: 0 },
              y: { type: 'num', value: 6 },
              w: { type: 'num', value: 72 },
              h: { type: 'num', value: 24 },
            },
            {
              type: 'canvasFillStyle',
              ctxVar: 'ctx',
              color: { type: 'color', value: '#3a271a' },
            },
            {
              type: 'canvasFillRect',
              ctxVar: 'ctx',
              x: { type: 'num', value: 28 },
              y: { type: 'num', value: 44 },
              w: { type: 'num', value: 18 },
              h: { type: 'num', value: 28 },
            },
          ],
          baseW: { type: 'num', value: 72 },
          baseH: { type: 'num', value: 72 },
        },
        {
          type: 'gk:defineLook',
          name: 'arvore',
          ctxName: 'ctx',
          body: [
            {
              type: 'canvasFillStyle',
              ctxVar: 'ctx',
              color: { type: 'color', value: '#6b4226' },
            },
            {
              type: 'canvasFillRect',
              ctxVar: 'ctx',
              x: { type: 'num', value: 22 },
              y: { type: 'num', value: 52 },
              w: { type: 'num', value: 12 },
              h: { type: 'num', value: 32 },
            },
            {
              type: 'canvasFillStyle',
              ctxVar: 'ctx',
              color: { type: 'color', value: '#2f7d32' },
            },
            {
              type: 'canvasFillRect',
              ctxVar: 'ctx',
              x: { type: 'num', value: 4 },
              y: { type: 'num', value: 4 },
              w: { type: 'num', value: 48 },
              h: { type: 'num', value: 52 },
            },
            {
              type: 'canvasFillStyle',
              ctxVar: 'ctx',
              color: { type: 'color', value: '#43a047' },
            },
            {
              type: 'canvasFillRect',
              ctxVar: 'ctx',
              x: { type: 'num', value: 12 },
              y: { type: 'num', value: 12 },
              w: { type: 'num', value: 20 },
              h: { type: 'num', value: 20 },
            },
          ],
          baseW: { type: 'num', value: 56 },
          baseH: { type: 'num', value: 84 },
        },
        {
          type: 'gk:defineEffect',
          name: 'faisca',
          count: { type: 'num', value: 10 },
          color: '#ffe066',
          size: { type: 'num', value: 4 },
          life: { type: 'num', value: 0.35 },
          speed: { type: 'num', value: 180 },
          gravity: { type: 'num', value: 0 },
        },
        {
          type: 'gk:defineEffect',
          name: 'fumaca',
          count: { type: 'num', value: 12 },
          color: '#dfe6e9',
          size: { type: 'num', value: 5 },
          life: { type: 'num', value: 0.45 },
          speed: { type: 'num', value: 130 },
          gravity: { type: 'num', value: 0 },
        },
        {
          type: 'gk:createEmptyTilemap',
          name: 'vila',
          cols: { type: 'num', value: 30 },
          rows: { type: 'num', value: 17 },
          fill: { type: 'num', value: -1 },
          asset: '',
        },
        {
          type: 'gk:defineMold',
          name: 'casa',
          w: { type: 'num', value: 72 },
          h: { type: 'num', value: 72 },
          health: { type: 'num', value: 1 },
          speed: { type: 'num', value: 0 },
          damage: { type: 'num', value: 0 },
          color: '#c9a76b',
          image: '',
          look: 'casa',
        },
        {
          type: 'gk:defineMold',
          name: 'arvore',
          w: { type: 'num', value: 56 },
          h: { type: 'num', value: 84 },
          health: { type: 'num', value: 1 },
          speed: { type: 'num', value: 0 },
          damage: { type: 'num', value: 0 },
          color: '#2f7d32',
          image: '',
          look: 'arvore',
        },
        {
          type: 'gk:defineMold',
          name: 'bambu',
          w: { type: 'num', value: 44 },
          h: { type: 'num', value: 40 },
          health: { type: 'num', value: 30 },
          speed: { type: 'num', value: 90 },
          damage: { type: 'num', value: 8 },
          color: '#6ab04c',
          image: '',
          look: 'bambu',
        },
        {
          type: 'gk:defineMold',
          name: 'dragao',
          w: { type: 'num', value: 50 },
          h: { type: 'num', value: 38 },
          health: { type: 'num', value: 30 },
          speed: { type: 'num', value: 110 },
          damage: { type: 'num', value: 12 },
          color: '#b33939',
          image: '',
          look: 'dragao',
        },
        {
          type: 'gk:spawnFromMold',
          mold: 'casa',
          x: { type: 'num', value: 260 },
          y: { type: 'num', value: 180 },
        },
        {
          type: 'gk:spawnFromMold',
          mold: 'casa',
          x: { type: 'num', value: 1180 },
          y: { type: 'num', value: 320 },
        },
        {
          type: 'gk:spawnFromMold',
          mold: 'arvore',
          x: { type: 'num', value: 520 },
          y: { type: 'num', value: 500 },
        },
        {
          type: 'gk:spawnFromMold',
          mold: 'arvore',
          x: { type: 'num', value: 900 },
          y: { type: 'num', value: 160 },
        },
        {
          type: 'gk:spawnFromMold',
          mold: 'arvore',
          x: { type: 'num', value: 1400 },
          y: { type: 'num', value: 640 },
        },
        {
          type: 'gk:spawnFromMold',
          mold: 'arvore',
          x: { type: 'num', value: 700 },
          y: { type: 'num', value: 780 },
        },
        {
          type: 'gk:spawnFromMold',
          mold: 'bambu',
          x: { type: 'num', value: 1000 },
          y: { type: 'num', value: 420 },
        },
        {
          type: 'gk:spawnFromMold',
          mold: 'bambu',
          x: { type: 'num', value: 1250 },
          y: { type: 'num', value: 560 },
        },
        {
          type: 'gk:spawnFromMold',
          mold: 'bambu',
          x: { type: 'num', value: 820 },
          y: { type: 'num', value: 640 },
        },
        {
          type: 'gk:spawnFromMold',
          mold: 'dragao',
          x: { type: 'num', value: 1450 },
          y: { type: 'num', value: 300 },
        },
        {
          type: 'gk:spawnFromMold',
          mold: 'dragao',
          x: { type: 'num', value: 1550 },
          y: { type: 'num', value: 500 },
        },
        {
          type: 'gk:spawnFromMold',
          mold: 'dragao',
          x: { type: 'num', value: 1350 },
          y: { type: 'num', value: 720 },
        },
        {
          type: 'gk:createCharacter',
          varName: 'ninja',
          image: '',
          w: { type: 'num', value: 40 },
          h: { type: 'num', value: 54 },
          speed: { type: 'num', value: 240 },
          color: '#2b3a67',
        },
        {
          type: 'gk:placeCharacter',
          charVar: 'ninja',
          x: { type: 'num', value: 180 },
          y: { type: 'num', value: 440 },
        },
        {
          type: 'gk:setHitbox',
          charVar: 'ninja',
          ox: { type: 'num', value: 6 },
          oy: { type: 'num', value: 22 },
          w: { type: 'num', value: 28 },
          h: { type: 'num', value: 30 },
        },
        {
          type: 'gk:setSwingWindow',
          charVar: 'ninja',
          start: { type: 'num', value: 0.08 },
          active: { type: 'num', value: 0.14 },
        },
        { type: 'gk:stateLook', charVar: 'ninja', state: 'parado', look: 'ninja parado' },
        { type: 'gk:stateLook', charVar: 'ninja', state: 'andando', look: 'ninja andando' },
        { type: 'gk:stateLook', charVar: 'ninja', state: 'golpe', look: 'ninja golpe' },
        { type: 'gk:stateLook', charVar: 'ninja', state: 'dano', look: 'ninja parado' },
        { type: 'gk:cameraFollowMap', charVar: 'ninja', map: 'vila' },
        {
          type: 'gk:setMission',
          seconds: { type: 'num', value: 0 },
          killCount: { type: 'num', value: 6 },
        },
      ],
      events: [
        {
          type: 'gk:onEvent',
          event: 'inimigo:caiu',
          body: [{ type: 'gk:playEffect', fx: 'explosion' }],
        },
        {
          type: 'gk:onEnterState',
          name: 'vitoria',
          body: [{ type: 'gk:playEffect', fx: 'win' }],
        },
        {
          type: 'gk:onEnterState',
          name: 'fim',
          body: [{ type: 'gk:playEffect', fx: 'gameover' }],
        },
      ],
      loops: [
        {
          type: 'gk:onUpdate',
          dtName: 'dt',
          body: [
            { type: 'gk:moveWithKeys', charVar: 'ninja', dtVar: 'dt' },
            { type: 'gk:collideGroup', charVar: 'ninja', mold: 'casa' },
            { type: 'gk:collideGroup', charVar: 'ninja', mold: 'arvore' },
            { type: 'gk:keepOnScreen', charVar: 'ninja' },
            {
              type: 'if',
              cond: { type: 'gk:keyPressed', key: ' ' },
              then: [
                { type: 'gk:playEffect', fx: 'click' },
                {
                  type: 'gk:attackFacing',
                  charVar: 'ninja',
                  range: { type: 'num', value: 52 },
                  duration: { type: 'num', value: 0.3 },
                },
              ],
            },
            {
              type: 'gk:forEachActive',
              mold: 'bambu',
              itemName: 'item',
              body: [
                {
                  type: 'if',
                  cond: {
                    type: 'binop',
                    op: '===',
                    left: { type: 'gk:entityState', charVar: 'item' },
                    right: { type: 'str', value: 'golpe' },
                  },
                  then: [{ type: 'gk:seek', charVar: 'item', targetVar: 'ninja', dtVar: 'dt' }],
                  elseif: [
                    {
                      cond: {
                        type: 'binop',
                        op: '<',
                        left: { type: 'gk:distanceBetween', a: 'item', b: 'ninja' },
                        right: { type: 'num', value: 70 },
                      },
                      then: [
                        {
                          type: 'gk:setEntityState',
                          charVar: 'item',
                          state: 'golpe',
                          seconds: { type: 'num', value: 0.5 },
                        },
                      ],
                    },
                    {
                      cond: {
                        type: 'binop',
                        op: '<',
                        left: { type: 'gk:distanceBetween', a: 'item', b: 'ninja' },
                        right: { type: 'num', value: 260 },
                      },
                      then: [
                        {
                          type: 'gk:setEntityState',
                          charVar: 'item',
                          state: 'andando',
                          seconds: { type: 'num', value: 0.1 },
                        },
                        { type: 'gk:seek', charVar: 'item', targetVar: 'ninja', dtVar: 'dt' },
                      ],
                    },
                  ],
                  else: [
                    {
                      type: 'gk:setEntityState',
                      charVar: 'item',
                      state: 'parado',
                      seconds: { type: 'num', value: 0.1 },
                    },
                    {
                      type: 'gk:patrolAround',
                      charVar: 'item',
                      ox: { type: 'num', value: 1000 },
                      oy: { type: 'num', value: 500 },
                      radius: { type: 'num', value: 150 },
                    },
                  ],
                },
                {
                  type: 'if',
                  cond: { type: 'gk:didHit', aVar: 'ninja', bVar: 'item' },
                  then: [
                    {
                      type: 'gk:hurt',
                      charVar: 'item',
                      amount: { type: 'num', value: 12 },
                      iframes: { type: 'num', value: 0.25 },
                    },
                    {
                      type: 'gk:knockback',
                      charVar: 'item',
                      fromVar: 'ninja',
                      force: { type: 'num', value: 380 },
                    },
                    { type: 'gk:playEffect', fx: 'hit' },
                    {
                      type: 'if',
                      cond: { type: 'gk:isDead', charVar: 'item' },
                      then: [
                        {
                          type: 'gk:burst',
                          effect: 'faisca',
                          x: { type: 'gk:charX', charVar: 'item' },
                          y: { type: 'gk:charY', charVar: 'item' },
                        },
                        { type: 'gk:missionKill' },
                        { type: 'gk:emit', event: 'inimigo:caiu' },
                        { type: 'gk:recycle', charVar: 'item' },
                      ],
                    },
                  ],
                },
                {
                  type: 'if',
                  cond: {
                    type: 'logical',
                    op: '&&',
                    left: {
                      type: 'logical',
                      op: '&&',
                      left: {
                        type: 'binop',
                        op: '===',
                        left: { type: 'gk:entityState', charVar: 'item' },
                        right: { type: 'str', value: 'golpe' },
                      },
                      right: { type: 'gk:charactersTouch', aVar: 'item', bVar: 'ninja' },
                    },
                    right: {
                      type: 'logicalNot',
                      value: { type: 'gk:isInvincible', charVar: 'ninja' },
                    },
                  },
                  then: [
                    {
                      type: 'gk:hurt',
                      charVar: 'ninja',
                      amount: { type: 'gk:propertyOf', charVar: 'item', prop: 'damage' },
                      iframes: { type: 'num', value: 1 },
                    },
                    {
                      type: 'gk:knockback',
                      charVar: 'ninja',
                      fromVar: 'item',
                      force: { type: 'num', value: 340 },
                    },
                    { type: 'gk:playEffect', fx: 'hurt' },
                    {
                      type: 'gk:cameraShake',
                      intensity: { type: 'num', value: 6 },
                      seconds: { type: 'num', value: 0.25 },
                    },
                  ],
                },
              ],
            },
            {
              type: 'gk:forEachActive',
              mold: 'dragao',
              itemName: 'item',
              body: [
                {
                  type: 'if',
                  cond: {
                    type: 'binop',
                    op: '===',
                    left: { type: 'gk:entityState', charVar: 'item' },
                    right: { type: 'str', value: 'golpe' },
                  },
                  then: [{ type: 'gk:seek', charVar: 'item', targetVar: 'ninja', dtVar: 'dt' }],
                  elseif: [
                    {
                      cond: {
                        type: 'binop',
                        op: '<',
                        left: { type: 'gk:distanceBetween', a: 'item', b: 'ninja' },
                        right: { type: 'num', value: 60 },
                      },
                      then: [
                        {
                          type: 'gk:setEntityState',
                          charVar: 'item',
                          state: 'golpe',
                          seconds: { type: 'num', value: 0.4 },
                        },
                      ],
                    },
                    {
                      cond: {
                        type: 'binop',
                        op: '<',
                        left: { type: 'gk:distanceBetween', a: 'item', b: 'ninja' },
                        right: { type: 'num', value: 320 },
                      },
                      then: [
                        {
                          type: 'gk:setEntityState',
                          charVar: 'item',
                          state: 'andando',
                          seconds: { type: 'num', value: 0.1 },
                        },
                        { type: 'gk:seek', charVar: 'item', targetVar: 'ninja', dtVar: 'dt' },
                      ],
                    },
                  ],
                  else: [
                    {
                      type: 'gk:setEntityState',
                      charVar: 'item',
                      state: 'parado',
                      seconds: { type: 'num', value: 0.1 },
                    },
                    {
                      type: 'gk:patrolAround',
                      charVar: 'item',
                      ox: { type: 'num', value: 1450 },
                      oy: { type: 'num', value: 500 },
                      radius: { type: 'num', value: 160 },
                    },
                  ],
                },
                {
                  type: 'if',
                  cond: { type: 'gk:didHit', aVar: 'ninja', bVar: 'item' },
                  then: [
                    {
                      type: 'gk:hurt',
                      charVar: 'item',
                      amount: { type: 'num', value: 12 },
                      iframes: { type: 'num', value: 0.25 },
                    },
                    {
                      type: 'gk:knockback',
                      charVar: 'item',
                      fromVar: 'ninja',
                      force: { type: 'num', value: 420 },
                    },
                    { type: 'gk:playEffect', fx: 'hit' },
                    {
                      type: 'if',
                      cond: { type: 'gk:isDead', charVar: 'item' },
                      then: [
                        {
                          type: 'gk:burst',
                          effect: 'faisca',
                          x: { type: 'gk:charX', charVar: 'item' },
                          y: { type: 'gk:charY', charVar: 'item' },
                        },
                        { type: 'gk:missionKill' },
                        { type: 'gk:emit', event: 'inimigo:caiu' },
                        { type: 'gk:recycle', charVar: 'item' },
                      ],
                    },
                  ],
                },
                {
                  type: 'if',
                  cond: {
                    type: 'logical',
                    op: '&&',
                    left: {
                      type: 'logical',
                      op: '&&',
                      left: {
                        type: 'binop',
                        op: '===',
                        left: { type: 'gk:entityState', charVar: 'item' },
                        right: { type: 'str', value: 'golpe' },
                      },
                      right: { type: 'gk:charactersTouch', aVar: 'item', bVar: 'ninja' },
                    },
                    right: {
                      type: 'logicalNot',
                      value: { type: 'gk:isInvincible', charVar: 'ninja' },
                    },
                  },
                  then: [
                    {
                      type: 'gk:hurt',
                      charVar: 'ninja',
                      amount: { type: 'gk:propertyOf', charVar: 'item', prop: 'damage' },
                      iframes: { type: 'num', value: 1 },
                    },
                    {
                      type: 'gk:knockback',
                      charVar: 'ninja',
                      fromVar: 'item',
                      force: { type: 'num', value: 300 },
                    },
                    { type: 'gk:playEffect', fx: 'hurt' },
                  ],
                },
              ],
            },
            { type: 'gk:autoAnimate', charVar: 'ninja' },
            {
              type: 'if',
              cond: { type: 'gk:isDead', charVar: 'ninja' },
              then: [{ type: 'gk:endGame' }],
            },
          ],
        },
        {
          type: 'gk:onDraw',
          ctxName: 'ctx',
          body: [
            { type: 'gk:drawBackground', color: '#3f7d4e', grid: false },
            { type: 'gk:drawShadow', charVar: 'ninja' },
            { type: 'gk:drawByDepth', charVar: 'ninja' },
            { type: 'gk:drawEffects' },
          ],
        },
        {
          type: 'gk:onDrawHud',
          ctxName: 'ctx',
          body: [
            {
              type: 'gk:drawHearts',
              current: {
                type: 'binop',
                op: '/',
                left: { type: 'gk:healthOf', charVar: 'ninja' },
                right: { type: 'num', value: 30 },
              },
              max: { type: 'num', value: 3 },
              x: { type: 'num', value: 20 },
              y: { type: 'num', value: 20 },
            },
            {
              type: 'canvasFillStyle',
              ctxVar: 'ctx',
              color: { type: 'color', value: '#0f2417' },
            },
            { type: 'canvasFont', ctxVar: 'ctx', size: 18, family: 'sans-serif' },
            {
              type: 'canvasFillText',
              ctxVar: 'ctx',
              text: {
                type: 'binop',
                op: '+',
                left: { type: 'str', value: 'Bambus: ' },
                right: { type: 'gk:countActive', mold: 'bambu' },
              },
              x: { type: 'num', value: 20 },
              y: { type: 'num', value: 72 },
            },
            {
              type: 'canvasFillText',
              ctxVar: 'ctx',
              text: {
                type: 'binop',
                op: '+',
                left: { type: 'str', value: 'Dragões: ' },
                right: { type: 'gk:countActive', mold: 'dragao' },
              },
              x: { type: 'num', value: 20 },
              y: { type: 'num', value: 96 },
            },
          ],
        },
      ],
    },
  },
}
