import { CATEGORY_COLORS } from '../theme'
import type { BlockDefinition } from './types'

const C = CATEGORY_COLORS.canvas

export const CANVAS_BLOCKS: BlockDefinition[] = [
  {
    type: 'sz_canvas_setup',
    message0: 'Pegar canvas id %1 e guardar contexto em %2',
    args0: [
      { type: 'field_input', name: 'CANVAS_ID', text: 'tela' },
      { type: 'field_input', name: 'CTX', text: 'ctx' },
    ],
    previousStatement: 'JSStmt',
    nextStatement: 'JSStmt',
    colour: C,
  },
  {
    type: 'sz_canvas_set_size',
    message0: 'Definir tamanho do canvas %1 largura %2 altura %3',
    args0: [
      { type: 'field_input', name: 'CTX', text: 'ctx' },
      { type: 'input_value', name: 'W', check: 'JSValue' },
      { type: 'input_value', name: 'H', check: 'JSValue' },
    ],
    inputsInline: true,
    previousStatement: 'JSStmt',
    nextStatement: 'JSStmt',
    colour: C,
    tooltip:
      'Muda a largura e a altura do canvas dinamicamente (ex.: tela cheia com a largura/altura da janela).',
  },
  {
    type: 'sz_canvas_clear',
    message0: 'Limpar tela %1',
    args0: [{ type: 'field_input', name: 'CTX', text: 'ctx' }],
    previousStatement: 'JSStmt',
    nextStatement: 'JSStmt',
    colour: C,
  },
  {
    type: 'sz_canvas_fill_style',
    message0: 'Definir cor do pincel %1 como %2',
    args0: [
      { type: 'field_input', name: 'CTX', text: 'ctx' },
      { type: 'input_value', name: 'COLOR', check: 'JSValue' },
    ],
    inputsInline: true,
    previousStatement: 'JSStmt',
    nextStatement: 'JSStmt',
    colour: C,
  },
  {
    type: 'sz_canvas_fill_rect',
    message0: 'Desenhar retângulo %1 em x %2 y %3 largura %4 altura %5',
    args0: [
      { type: 'field_input', name: 'CTX', text: 'ctx' },
      { type: 'input_value', name: 'X', check: 'JSValue' },
      { type: 'input_value', name: 'Y', check: 'JSValue' },
      { type: 'input_value', name: 'W', check: 'JSValue' },
      { type: 'input_value', name: 'H', check: 'JSValue' },
    ],
    inputsInline: true,
    previousStatement: 'JSStmt',
    nextStatement: 'JSStmt',
    colour: C,
  },
  {
    type: 'sz_canvas_arc',
    message0: 'Desenhar círculo %1 em x %2 y %3 raio %4',
    args0: [
      { type: 'field_input', name: 'CTX', text: 'ctx' },
      { type: 'input_value', name: 'X', check: 'JSValue' },
      { type: 'input_value', name: 'Y', check: 'JSValue' },
      { type: 'input_value', name: 'R', check: 'JSValue' },
    ],
    inputsInline: true,
    previousStatement: 'JSStmt',
    nextStatement: 'JSStmt',
    colour: C,
  },
  {
    type: 'sz_canvas_fill_text',
    message0: 'Desenhar texto %1 com pincel %2 em x %3 y %4',
    args0: [
      { type: 'field_input', name: 'TEXT', text: 'Olá' },
      { type: 'field_input', name: 'CTX', text: 'ctx' },
      { type: 'input_value', name: 'X', check: 'JSValue' },
      { type: 'input_value', name: 'Y', check: 'JSValue' },
    ],
    inputsInline: true,
    previousStatement: 'JSStmt',
    nextStatement: 'JSStmt',
    colour: C,
  },
  {
    type: 'sz_canvas_anim_loop',
    // O rótulo "A cada frame fazer" e os controles +/− são montados pelo mutator
    // (sz_anim_loop_mutator); aqui ficamos só com o corpo.
    message0: '%1',
    args0: [{ type: 'input_statement', name: 'BODY' }],
    previousStatement: 'JSStmt',
    nextStatement: 'JSStmt',
    colour: C,
    mutator: 'sz_anim_loop_mutator',
    tooltip:
      'Repete o corpo a cada quadro. Clique no + para guardar o id da animação numa variável e poder pará-la depois com "parar animação". Deixe o bloco no nível principal para a variável ficar acessível.',
  },
  {
    type: 'sz_canvas_cancel_anim',
    message0: 'parar animação %1',
    args0: [{ type: 'input_value', name: 'HANDLE', check: 'JSValue' }],
    inputsInline: true,
    previousStatement: 'JSStmt',
    nextStatement: 'JSStmt',
    colour: C,
    tooltip: 'Para a animação, cancelando o id guardado por "A cada frame fazer".',
  },
  {
    type: 'sz_canvas_keyboard',
    message0: 'Ler teclado simples em variável %1',
    args0: [{ type: 'field_input', name: 'NAME', text: 'teclas' }],
    previousStatement: 'JSStmt',
    nextStatement: 'JSStmt',
    colour: C,
  },
  // ---- Canvas extras (Fase 2.3) ----
  {
    type: 'sz_canvas_draw_image',
    message0: 'Desenhar imagem %1 no pincel %2 em x %3 y %4 largura %5 altura %6',
    args0: [
      { type: 'field_input', name: 'SRC', text: 'https://exemplo.com/img.png' },
      { type: 'field_input', name: 'CTX', text: 'ctx' },
      { type: 'input_value', name: 'X', check: 'JSValue' },
      { type: 'input_value', name: 'Y', check: 'JSValue' },
      { type: 'input_value', name: 'W', check: 'JSValue' },
      { type: 'input_value', name: 'H', check: 'JSValue' },
    ],
    inputsInline: true,
    previousStatement: 'JSStmt',
    nextStatement: 'JSStmt',
    colour: C,
  },
  {
    type: 'sz_canvas_save',
    message0: 'Salvar estado do pincel %1',
    args0: [{ type: 'field_input', name: 'CTX', text: 'ctx' }],
    previousStatement: 'JSStmt',
    nextStatement: 'JSStmt',
    colour: C,
  },
  {
    type: 'sz_canvas_restore',
    message0: 'Restaurar estado do pincel %1',
    args0: [{ type: 'field_input', name: 'CTX', text: 'ctx' }],
    previousStatement: 'JSStmt',
    nextStatement: 'JSStmt',
    colour: C,
  },
  {
    type: 'sz_canvas_translate',
    message0: 'Mover pincel %1 em x %2 y %3',
    args0: [
      { type: 'field_input', name: 'CTX', text: 'ctx' },
      { type: 'input_value', name: 'X', check: 'JSValue' },
      { type: 'input_value', name: 'Y', check: 'JSValue' },
    ],
    inputsInline: true,
    previousStatement: 'JSStmt',
    nextStatement: 'JSStmt',
    colour: C,
  },
  {
    type: 'sz_canvas_rotate',
    message0: 'Girar pincel %1 em %2 radianos',
    args0: [
      { type: 'field_input', name: 'CTX', text: 'ctx' },
      { type: 'field_number', name: 'ANGLE', value: 0, precision: 0.01 },
    ],
    previousStatement: 'JSStmt',
    nextStatement: 'JSStmt',
    colour: C,
  },
  {
    type: 'sz_canvas_scale',
    message0: 'Escalar pincel %1 em x %2 y %3',
    args0: [
      { type: 'field_input', name: 'CTX', text: 'ctx' },
      { type: 'field_number', name: 'SX', value: 1, precision: 0.1 },
      { type: 'field_number', name: 'SY', value: 1, precision: 0.1 },
    ],
    previousStatement: 'JSStmt',
    nextStatement: 'JSStmt',
    colour: C,
  },
  {
    type: 'sz_canvas_gradient',
    message0: 'Gradiente linear pincel %1 em variável %2 de (%3,%4) a (%5,%6) com cor %7 → %8',
    args0: [
      { type: 'field_input', name: 'CTX', text: 'ctx' },
      { type: 'field_input', name: 'NAME', text: 'g' },
      { type: 'field_number', name: 'X0', value: 0 },
      { type: 'field_number', name: 'Y0', value: 0 },
      { type: 'field_number', name: 'X1', value: 200 },
      { type: 'field_number', name: 'Y1', value: 0 },
      { type: 'field_colour_sz', name: 'C0', colour: '#22d3ee' },
      { type: 'field_colour_sz', name: 'C1', colour: '#a78bfa' },
    ],
    previousStatement: 'JSStmt',
    nextStatement: 'JSStmt',
    colour: C,
  },

  // ---- Traçado / contorno / fonte / transparência (caminho "na mão", Fase 6) ----
  {
    type: 'sz_canvas_begin_path',
    message0: 'Começar um traçado no pincel %1',
    args0: [{ type: 'field_input', name: 'CTX', text: 'ctx' }],
    previousStatement: 'JSStmt',
    nextStatement: 'JSStmt',
    colour: C,
    tooltip:
      'Inicia um desenho com linhas (ex.: a nave ou um asteroide). Depois use "ir para" e "traçar linha" e termine com "preencher" ou "contorno".',
  },
  {
    type: 'sz_canvas_move_to',
    message0: 'Levar a caneta do pincel %1 para x %2 y %3',
    args0: [
      { type: 'field_input', name: 'CTX', text: 'ctx' },
      { type: 'input_value', name: 'X', check: 'JSValue' },
      { type: 'input_value', name: 'Y', check: 'JSValue' },
    ],
    inputsInline: true,
    previousStatement: 'JSStmt',
    nextStatement: 'JSStmt',
    colour: C,
    tooltip: 'Move a caneta (sem desenhar) para o ponto de início do traçado.',
  },
  {
    type: 'sz_canvas_line_to',
    message0: 'Traçar linha no pincel %1 até x %2 y %3',
    args0: [
      { type: 'field_input', name: 'CTX', text: 'ctx' },
      { type: 'input_value', name: 'X', check: 'JSValue' },
      { type: 'input_value', name: 'Y', check: 'JSValue' },
    ],
    inputsInline: true,
    previousStatement: 'JSStmt',
    nextStatement: 'JSStmt',
    colour: C,
    tooltip:
      'Liga o ponto atual ao ponto x/y com uma linha reta (use vários para fazer um polígono).',
  },
  {
    type: 'sz_canvas_close_path',
    message0: 'Fechar o traçado do pincel %1',
    args0: [{ type: 'field_input', name: 'CTX', text: 'ctx' }],
    previousStatement: 'JSStmt',
    nextStatement: 'JSStmt',
    colour: C,
    tooltip: 'Liga o último ponto de volta ao primeiro (fecha o polígono).',
  },
  {
    type: 'sz_canvas_stroke',
    message0: 'Desenhar o contorno do traçado (pincel %1)',
    args0: [{ type: 'field_input', name: 'CTX', text: 'ctx' }],
    previousStatement: 'JSStmt',
    nextStatement: 'JSStmt',
    colour: C,
    tooltip: 'Desenha só as linhas do traçado (a borda), com a cor e a espessura definidas.',
  },
  {
    type: 'sz_canvas_fill',
    message0: 'Preencher o traçado (pincel %1)',
    args0: [{ type: 'field_input', name: 'CTX', text: 'ctx' }],
    previousStatement: 'JSStmt',
    nextStatement: 'JSStmt',
    colour: C,
    tooltip: 'Pinta o interior do traçado com a cor do pincel (a nave, um asteroide…).',
  },
  {
    type: 'sz_canvas_stroke_style',
    message0: 'Definir cor do contorno do pincel %1 como %2',
    args0: [
      { type: 'field_input', name: 'CTX', text: 'ctx' },
      { type: 'input_value', name: 'COLOR', check: 'JSValue' },
    ],
    inputsInline: true,
    previousStatement: 'JSStmt',
    nextStatement: 'JSStmt',
    colour: C,
    tooltip: 'Escolhe a cor das linhas (contorno) do traçado.',
  },
  {
    type: 'sz_canvas_line_width',
    message0: 'Definir espessura da linha do pincel %1 como %2',
    args0: [
      { type: 'field_input', name: 'CTX', text: 'ctx' },
      { type: 'input_value', name: 'WIDTH', check: 'JSValue' },
    ],
    inputsInline: true,
    previousStatement: 'JSStmt',
    nextStatement: 'JSStmt',
    colour: C,
    tooltip: 'Define a grossura das linhas do contorno (em pixels).',
  },
  {
    type: 'sz_canvas_global_alpha',
    message0: 'Definir transparência do pincel %1 como %2',
    args0: [
      { type: 'field_input', name: 'CTX', text: 'ctx' },
      { type: 'input_value', name: 'ALPHA', check: 'JSValue' },
    ],
    inputsInline: true,
    previousStatement: 'JSStmt',
    nextStatement: 'JSStmt',
    colour: C,
    tooltip: 'Transparência de tudo que for desenhado depois: 1 = opaco, 0 = invisível.',
  },
  {
    type: 'sz_canvas_font',
    message0: 'Definir fonte do pincel %1 tamanho %2 px família %3',
    args0: [
      { type: 'field_input', name: 'CTX', text: 'ctx' },
      { type: 'field_number', name: 'SIZE', value: 20, min: 1 },
      { type: 'field_input', name: 'FAMILY', text: 'sans-serif' },
    ],
    previousStatement: 'JSStmt',
    nextStatement: 'JSStmt',
    colour: C,
    tooltip: 'Tamanho e tipo da letra do texto desenhado (ex.: 24 px, sans-serif).',
  },
  {
    type: 'sz_canvas_text_align',
    message0: 'Alinhar texto do pincel %1 %2',
    args0: [
      { type: 'field_input', name: 'CTX', text: 'ctx' },
      {
        type: 'field_dropdown',
        name: 'ALIGN',
        options: [
          ['à esquerda', 'left'],
          ['no centro', 'center'],
          ['à direita', 'right'],
        ],
      },
    ],
    previousStatement: 'JSStmt',
    nextStatement: 'JSStmt',
    colour: C,
    tooltip: 'De que lado o texto fica em relação ao ponto x (esquerda, centro ou direita).',
  },

  // ---- Entrada na mão: tecla apertada? e posição do mouse/dedo ----
  {
    type: 'sz_input_key_pressed',
    message0: 'a tecla %1 está apertada?',
    args0: [
      {
        type: 'field_dropdown',
        name: 'KEY',
        options: [
          ['→ seta direita', 'ArrowRight'],
          ['← seta esquerda', 'ArrowLeft'],
          ['↑ seta para cima', 'ArrowUp'],
          ['↓ seta para baixo', 'ArrowDown'],
          ['barra de espaço', 'Space'],
          ['Enter', 'Enter'],
        ],
      },
    ],
    output: 'JSValue',
    colour: C,
    tooltip: 'Verdadeiro enquanto a tecla está sendo segurada. Use dentro de um "se".',
  },
  {
    type: 'sz_input_pointer_x',
    message0: 'x do mouse/dedo',
    args0: [],
    output: 'JSValue',
    colour: C,
    tooltip: 'Posição horizontal do mouse/dedo dentro do canvas.',
  },
  {
    type: 'sz_input_pointer_y',
    message0: 'y do mouse/dedo',
    args0: [],
    output: 'JSValue',
    colour: C,
    tooltip: 'Posição vertical do mouse/dedo dentro do canvas.',
  },
]
