import { CATEGORY_COLORS, categoryShades } from '../theme'
import type { BlockDefinition } from './types'

const C = CATEGORY_COLORS.canvas

export const CANVAS_BLOCKS: BlockDefinition[] = [
  {
    type: 'sz_html_canvas',
    message0: 'Criar tela de desenho chamada %1',
    args0: [{ type: 'field_input', name: 'ID', text: 'tela' }],
    message1: 'classe (opcional) %1',
    args1: [{ type: 'field_input', name: 'CLASS', text: '' }],
    previousStatement: 'HTMLNode',
    nextStatement: 'HTMLNode',
    colour: C,
    tooltip:
      'Cria a área onde seus desenhos vão aparecer. Encaixe em Estrutura; depois use “Preparar tela de desenho” em Ao iniciar.',
  },
  {
    type: 'sz_canvas_setup',
    message0: 'Preparar tela de desenho %1 e chamar o pincel de %2',
    args0: [
      // CANVAS_ID referencia a tela criada (seletor); CTX DECLARA a variável do
      // contexto → segue texto (a criança nomeia uma vez; os consumidores é que pegam menu).
      { type: 'field_name_picker', name: 'CANVAS_ID', text: 'tela', kind: 'canvas' },
      { type: 'field_input', name: 'CTX', text: 'ctx' },
    ],
    previousStatement: 'JSStmt',
    nextStatement: 'JSStmt',
    colour: C,
    tooltip: 'Liga o pincel à tela escolhida. Encaixe em Ao iniciar antes dos blocos que desenham.',
  },
  {
    type: 'sz_canvas_set_size',
    message0: 'Definir tamanho da tela %1 largura %2 altura %3',
    args0: [
      { type: 'field_name_picker', name: 'CTX', text: 'ctx', kind: 'variable' },
      { type: 'input_value', name: 'W', check: 'JSValue' },
      { type: 'input_value', name: 'H', check: 'JSValue' },
    ],
    inputsInline: true,
    previousStatement: 'JSStmt',
    nextStatement: 'JSStmt',
    colour: C,
    tooltip:
      'Muda a largura e a altura da tela de desenho, inclusive para acompanhar o tamanho da janela.',
  },
  {
    type: 'sz_canvas_clear',
    message0: 'Limpar tela %1',
    args0: [{ type: 'field_name_picker', name: 'CTX', text: 'ctx', kind: 'variable' }],
    previousStatement: 'JSStmt',
    nextStatement: 'JSStmt',
    colour: C,
    tooltip: 'Apaga todo o desenho para a tela ficar pronta para o próximo desenho.',
  },
  {
    type: 'sz_canvas_fill_style',
    message0: 'Definir cor do pincel %1 como %2',
    args0: [
      { type: 'field_name_picker', name: 'CTX', text: 'ctx', kind: 'variable' },
      { type: 'input_value', name: 'COLOR', check: 'JSValue' },
    ],
    inputsInline: true,
    previousStatement: 'JSStmt',
    nextStatement: 'JSStmt',
    colour: C,
    tooltip: 'Escolhe a cor usada para preencher as próximas formas e letras.',
  },
  {
    type: 'sz_canvas_fill_rect',
    message0: 'Desenhar retângulo com pincel %1',
    args0: [{ type: 'field_name_picker', name: 'CTX', text: 'ctx', kind: 'variable' }],
    message1: 'em x %1 y %2',
    args1: [
      { type: 'input_value', name: 'X', check: 'JSValue' },
      { type: 'input_value', name: 'Y', check: 'JSValue' },
    ],
    message2: 'largura %1 altura %2',
    args2: [
      { type: 'input_value', name: 'W', check: 'JSValue' },
      { type: 'input_value', name: 'H', check: 'JSValue' },
    ],
    previousStatement: 'JSStmt',
    nextStatement: 'JSStmt',
    colour: C,
    tooltip: 'Desenha um retângulo preenchido com a cor atual do pincel.',
  },
  {
    type: 'sz_canvas_arc',
    message0: 'Desenhar círculo %1 em x %2 y %3 raio %4',
    args0: [
      { type: 'field_name_picker', name: 'CTX', text: 'ctx', kind: 'variable' },
      { type: 'input_value', name: 'X', check: 'JSValue' },
      { type: 'input_value', name: 'Y', check: 'JSValue' },
      { type: 'input_value', name: 'R', check: 'JSValue' },
    ],
    inputsInline: true,
    previousStatement: 'JSStmt',
    nextStatement: 'JSStmt',
    colour: C,
    tooltip: 'Desenha um círculo preenchido com a cor atual do pincel.',
  },
  {
    type: 'sz_canvas_fill_text',
    message0: 'Desenhar texto %1 com pincel %2 em x %3 y %4',
    args0: [
      { type: 'input_value', name: 'TEXT', check: 'JSValue' },
      { type: 'field_name_picker', name: 'CTX', text: 'ctx', kind: 'variable' },
      { type: 'input_value', name: 'X', check: 'JSValue' },
      { type: 'input_value', name: 'Y', check: 'JSValue' },
    ],
    inputsInline: true,
    previousStatement: 'JSStmt',
    nextStatement: 'JSStmt',
    colour: C,
    tooltip: 'Escreve a mensagem na posição escolhida usando a fonte e a cor atuais.',
  },
  {
    type: 'sz_canvas_anim_loop',
    // O rótulo "A cada quadro fazer" e os controles +/− são montados pelo mutator
    // (sz_anim_loop_mutator); aqui ficamos só com o corpo.
    message0: '%1',
    args0: [{ type: 'input_statement', name: 'BODY' }],
    previousStatement: 'JSStmt',
    nextStatement: 'JSStmt',
    colour: C,
    mutator: 'sz_anim_loop_mutator',
    tooltip:
      'Repete os blocos de dentro em cada quadro da animação. Use o + para guardar um controle e poder parar depois.',
  },
  {
    type: 'sz_canvas_cancel_anim',
    message0: 'parar animação %1',
    args0: [{ type: 'input_value', name: 'HANDLE', check: 'JSValue' }],
    inputsInline: true,
    previousStatement: 'JSStmt',
    nextStatement: 'JSStmt',
    colour: C,
    tooltip: 'Para a animação indicada pelo controle guardado em “A cada quadro fazer”.',
  },
  {
    type: 'sz_canvas_request_frame',
    message0: 'pedir o próximo quadro chamando %1',
    args0: [{ type: 'field_name_picker', name: 'FN', text: 'animar', kind: 'function' }],
    inputsInline: true,
    previousStatement: 'JSStmt',
    nextStatement: 'JSStmt',
    colour: C,
    tooltip:
      'Chama a função escolhida no próximo quadro. É uma peça avançada para montar a animação à mão.',
  },
  {
    type: 'sz_canvas_request_frame_do',
    message0: 'pedir o próximo quadro, com o tempo em %1 %2 fazer %3',
    args0: [
      { type: 'field_input', name: 'PARAM', text: 't' },
      { type: 'input_dummy' },
      { type: 'input_statement', name: 'DO', check: 'JSStmt' },
    ],
    previousStatement: 'JSStmt',
    nextStatement: 'JSStmt',
    colour: C,
    tooltip: 'Roda os blocos de dentro no próximo quadro e guarda o tempo na variável escolhida.',
  },
  {
    type: 'sz_canvas_keyboard',
    message0: 'Ler teclado simples em variável %1',
    args0: [{ type: 'field_input', name: 'NAME', text: 'teclas' }],
    previousStatement: 'JSStmt',
    nextStatement: 'JSStmt',
    colour: C,
    hidden: true,
    tooltip:
      'Bloco antigo mantido para abrir projetos já salvos. Use “a tecla está apertada?” nos projetos novos.',
  },
  // ---- Canvas extras (Fase 2.3) ----
  {
    type: 'sz_canvas_draw_image',
    message0: 'Desenhar imagem %1 com pincel %2',
    args0: [
      { type: 'field_asset_picker', name: 'SRC', text: 'foto' },
      { type: 'field_name_picker', name: 'CTX', text: 'ctx', kind: 'variable' },
    ],
    message1: 'em x %1 y %2',
    args1: [
      { type: 'input_value', name: 'X', check: 'JSValue' },
      { type: 'input_value', name: 'Y', check: 'JSValue' },
    ],
    message2: 'largura %1 altura %2',
    args2: [
      { type: 'input_value', name: 'W', check: 'JSValue' },
      { type: 'input_value', name: 'H', check: 'JSValue' },
    ],
    previousStatement: 'JSStmt',
    nextStatement: 'JSStmt',
    colour: C,
    tooltip:
      'Desenha a imagem escolhida na posição e no tamanho indicados. Ela é preparada uma vez antes do projeto começar.',
  },
  {
    // Bloco-VALOR: a imagem do projeto que a criança escolhe pelo picker. Gera a
    // FONTE resolvida (dataURL do projeto, com fallback pro nome) — encaixa em
    // qualquer tomada de valor: `img.src`, um objeto `{ sky: [imagem] }`, etc.
    type: 'sz_val_image',
    message0: 'imagem %1',
    args0: [{ type: 'field_asset_picker', name: 'ASSET', text: 'foto' }],
    output: 'JSValue',
    colour: C,
    tooltip: 'Entrega a imagem escolhida do acervo para encaixar em outro bloco.',
  },
  {
    // Cria um objeto de imagem já com a fonte (`const v = new Image(); v.src = …`).
    type: 'sz_js_new_image',
    message0: 'criar imagem %1 com fonte %2',
    args0: [
      { type: 'field_input', name: 'VAR', text: 'img' },
      { type: 'input_value', name: 'SRC', check: 'JSValue' },
    ],
    inputsInline: true,
    previousStatement: 'JSStmt',
    nextStatement: 'JSStmt',
    colour: C,
    tooltip: 'Prepara uma imagem e guarda o resultado na variável escolhida.',
  },
  {
    // Roda o corpo quando a imagem termina de carregar (`img.onload = () => {…}`).
    type: 'sz_js_image_onload',
    message0: 'quando a imagem %1 carregar %2 fazer %3',
    args0: [
      { type: 'input_value', name: 'TARGET', check: 'JSValue' },
      { type: 'input_dummy' },
      { type: 'input_statement', name: 'DO', check: 'JSStmt' },
    ],
    previousStatement: 'JSStmt',
    nextStatement: 'JSStmt',
    colour: C,
    tooltip: 'Roda os blocos de dentro quando a imagem termina de carregar.',
  },
  {
    // Roda o corpo se a imagem FALHAR ao carregar (`img.onerror = () => {…}`).
    type: 'sz_js_image_onerror',
    message0: 'se a imagem %1 falhar %2 fazer %3',
    args0: [
      { type: 'input_value', name: 'TARGET', check: 'JSValue' },
      { type: 'input_dummy' },
      { type: 'input_statement', name: 'DO', check: 'JSStmt' },
    ],
    previousStatement: 'JSStmt',
    nextStatement: 'JSStmt',
    colour: C,
    tooltip: 'Roda os blocos de dentro se a imagem não conseguir carregar.',
  },
  {
    type: 'sz_canvas_save',
    message0: 'Salvar estado do pincel %1',
    args0: [{ type: 'field_name_picker', name: 'CTX', text: 'ctx', kind: 'variable' }],
    previousStatement: 'JSStmt',
    nextStatement: 'JSStmt',
    colour: C,
    tooltip: 'Guarda as cores, o recorte e os movimentos atuais do pincel para recuperar depois.',
  },
  {
    type: 'sz_canvas_restore',
    message0: 'Restaurar estado do pincel %1',
    args0: [{ type: 'field_name_picker', name: 'CTX', text: 'ctx', kind: 'variable' }],
    previousStatement: 'JSStmt',
    nextStatement: 'JSStmt',
    colour: C,
    tooltip: 'Recupera a última configuração guardada do pincel.',
  },
  {
    type: 'sz_canvas_translate',
    message0: 'Mover pincel %1 em x %2 y %3',
    args0: [
      { type: 'field_name_picker', name: 'CTX', text: 'ctx', kind: 'variable' },
      { type: 'input_value', name: 'X', check: 'JSValue' },
      { type: 'input_value', name: 'Y', check: 'JSValue' },
    ],
    inputsInline: true,
    previousStatement: 'JSStmt',
    nextStatement: 'JSStmt',
    colour: C,
    tooltip: 'Move o ponto de origem dos próximos desenhos pela distância indicada.',
  },
  {
    type: 'sz_canvas_rotate',
    message0: 'Girar pincel %1 em %2 radianos',
    args0: [
      { type: 'field_name_picker', name: 'CTX', text: 'ctx', kind: 'variable' },
      { type: 'input_value', name: 'ANGLE', check: 'JSValue' },
    ],
    inputsInline: true,
    previousStatement: 'JSStmt',
    nextStatement: 'JSStmt',
    colour: C,
    tooltip: 'Gira os próximos desenhos ao redor do ponto de origem atual.',
  },
  {
    type: 'sz_canvas_scale',
    message0: 'Escalar pincel %1 em x %2 y %3',
    args0: [
      { type: 'field_name_picker', name: 'CTX', text: 'ctx', kind: 'variable' },
      { type: 'input_value', name: 'SX', check: 'JSValue' },
      { type: 'input_value', name: 'SY', check: 'JSValue' },
    ],
    inputsInline: true,
    previousStatement: 'JSStmt',
    nextStatement: 'JSStmt',
    colour: C,
    tooltip: 'Aumenta ou diminui os próximos desenhos nos sentidos horizontal e vertical.',
  },
  {
    type: 'sz_canvas_gradient',
    message0: 'Criar degradê com pincel %1 e chamar de %2',
    args0: [
      { type: 'field_name_picker', name: 'CTX', text: 'ctx', kind: 'variable' },
      { type: 'field_input', name: 'NAME', text: 'g' },
    ],
    message1: 'de x %1 y %2 até x %3 y %4',
    args1: [
      { type: 'input_value', name: 'X0', check: 'JSValue' },
      { type: 'input_value', name: 'Y0', check: 'JSValue' },
      { type: 'input_value', name: 'X1', check: 'JSValue' },
      { type: 'input_value', name: 'Y1', check: 'JSValue' },
    ],
    message2: 'começando em %1 e terminando em %2',
    args2: [
      { type: 'field_colour_sz', name: 'C0', colour: '#22d3ee' },
      { type: 'field_colour_sz', name: 'C1', colour: '#a78bfa' },
    ],
    previousStatement: 'JSStmt',
    nextStatement: 'JSStmt',
    colour: C,
    tooltip: 'Cria uma passagem suave entre duas cores para usar nos próximos desenhos.',
  },

  // ---- Traçado / contorno / fonte / transparência (caminho "na mão", Fase 6) ----
  {
    type: 'sz_canvas_begin_path',
    message0: 'Começar um traçado no pincel %1',
    args0: [{ type: 'field_name_picker', name: 'CTX', text: 'ctx', kind: 'variable' }],
    previousStatement: 'JSStmt',
    nextStatement: 'JSStmt',
    colour: C,
    tooltip:
      'Inicia um desenho com linhas (ex.: a nave ou um asteroide). Depois use "ir para" e "traçar linha" e termine com "preencher" ou "contorno".',
  },
  {
    type: 'sz_canvas_move_to',
    message0: 'Levar a caneta do pincel %1 para x %2 y %3',
    args0: [
      { type: 'field_name_picker', name: 'CTX', text: 'ctx', kind: 'variable' },
      { type: 'input_value', name: 'X', check: 'JSValue' },
      { type: 'input_value', name: 'Y', check: 'JSValue' },
    ],
    inputsInline: true,
    previousStatement: 'JSStmt',
    nextStatement: 'JSStmt',
    colour: C,
    tooltip: 'Move a caneta (sem desenhar) para o ponto de início do traçado.',
  },
  {
    type: 'sz_canvas_line_to',
    message0: 'Traçar linha no pincel %1 até x %2 y %3',
    args0: [
      { type: 'field_name_picker', name: 'CTX', text: 'ctx', kind: 'variable' },
      { type: 'input_value', name: 'X', check: 'JSValue' },
      { type: 'input_value', name: 'Y', check: 'JSValue' },
    ],
    inputsInline: true,
    previousStatement: 'JSStmt',
    nextStatement: 'JSStmt',
    colour: C,
    tooltip:
      'Liga o ponto atual ao ponto x/y com uma linha reta (use vários para fazer um polígono).',
  },
  {
    type: 'sz_canvas_close_path',
    message0: 'Fechar o traçado do pincel %1',
    args0: [{ type: 'field_name_picker', name: 'CTX', text: 'ctx', kind: 'variable' }],
    previousStatement: 'JSStmt',
    nextStatement: 'JSStmt',
    colour: C,
    tooltip: 'Liga o último ponto de volta ao primeiro (fecha o polígono).',
  },
  {
    type: 'sz_canvas_stroke',
    message0: 'Desenhar o contorno do traçado (pincel %1)',
    args0: [{ type: 'field_name_picker', name: 'CTX', text: 'ctx', kind: 'variable' }],
    previousStatement: 'JSStmt',
    nextStatement: 'JSStmt',
    colour: C,
    tooltip: 'Desenha só as linhas do traçado (a borda), com a cor e a espessura definidas.',
  },
  {
    type: 'sz_canvas_fill',
    message0: 'Preencher o traçado (pincel %1)',
    args0: [{ type: 'field_name_picker', name: 'CTX', text: 'ctx', kind: 'variable' }],
    previousStatement: 'JSStmt',
    nextStatement: 'JSStmt',
    colour: C,
    tooltip: 'Pinta o interior do traçado com a cor do pincel (a nave, um asteroide…).',
  },
  {
    type: 'sz_canvas_rect',
    message0: 'Adicionar retângulo ao traçado do pincel %1',
    args0: [{ type: 'field_name_picker', name: 'CTX', text: 'ctx', kind: 'variable' }],
    message1: 'em x %1 y %2',
    args1: [
      { type: 'input_value', name: 'X', check: 'JSValue' },
      { type: 'input_value', name: 'Y', check: 'JSValue' },
    ],
    message2: 'largura %1 altura %2',
    args2: [
      { type: 'input_value', name: 'W', check: 'JSValue' },
      { type: 'input_value', name: 'H', check: 'JSValue' },
    ],
    previousStatement: 'JSStmt',
    nextStatement: 'JSStmt',
    colour: C,
    tooltip:
      'Adiciona um retângulo ao traçado atual (não desenha sozinho). Útil junto com "recortar" para fazer buracos: traçado da tela inteira + um círculo.',
  },
  {
    type: 'sz_canvas_clip',
    message0: 'Recortar o desenho pelo traçado (pincel %1)',
    args0: [{ type: 'field_name_picker', name: 'CTX', text: 'ctx', kind: 'variable' }],
    previousStatement: 'JSStmt',
    nextStatement: 'JSStmt',
    colour: C,
    tooltip:
      'Daqui pra frente, só desenha DENTRO do traçado atual (o resto fica escondido). Combine com "salvar"/"restaurar" para soltar o recorte depois. Ótimo para crateras/máscaras.',
  },
  {
    type: 'sz_canvas_stroke_style',
    message0: 'Definir cor do contorno do pincel %1 como %2',
    args0: [
      { type: 'field_name_picker', name: 'CTX', text: 'ctx', kind: 'variable' },
      { type: 'input_value', name: 'COLOR', check: 'JSValue' },
    ],
    inputsInline: true,
    previousStatement: 'JSStmt',
    nextStatement: 'JSStmt',
    colour: C,
    tooltip: 'Escolhe a cor das linhas (contorno) do traçado.',
  },
  {
    type: 'sz_canvas_line_width',
    message0: 'Definir espessura da linha do pincel %1 como %2',
    args0: [
      { type: 'field_name_picker', name: 'CTX', text: 'ctx', kind: 'variable' },
      { type: 'input_value', name: 'WIDTH', check: 'JSValue' },
    ],
    inputsInline: true,
    previousStatement: 'JSStmt',
    nextStatement: 'JSStmt',
    colour: C,
    tooltip: 'Define a grossura das linhas do contorno (em pixels).',
  },
  {
    type: 'sz_canvas_global_alpha',
    message0: 'Definir transparência do pincel %1 como %2',
    args0: [
      { type: 'field_name_picker', name: 'CTX', text: 'ctx', kind: 'variable' },
      { type: 'input_value', name: 'ALPHA', check: 'JSValue' },
    ],
    inputsInline: true,
    previousStatement: 'JSStmt',
    nextStatement: 'JSStmt',
    colour: C,
    tooltip: 'Transparência de tudo que for desenhado depois: 1 = opaco, 0 = invisível.',
  },
  {
    type: 'sz_canvas_font',
    message0: 'Definir fonte do pincel %1 tamanho %2 px família %3 estilo %4',
    args0: [
      { type: 'field_name_picker', name: 'CTX', text: 'ctx', kind: 'variable' },
      { type: 'field_number', name: 'SIZE', value: 20, min: 1 },
      { type: 'field_input', name: 'FAMILY', text: 'sans-serif' },
      {
        type: 'field_dropdown',
        name: 'WEIGHT',
        options: [
          ['normal', ''],
          ['negrito', 'bold'],
          ['itálico', 'italic'],
          ['negrito itálico', 'italic bold'],
        ],
      },
    ],
    previousStatement: 'JSStmt',
    nextStatement: 'JSStmt',
    colour: C,
    tooltip: 'Tamanho e tipo da letra do texto desenhado (ex.: 24 px, sans-serif).',
  },
  {
    type: 'sz_canvas_text_align',
    message0: 'Alinhar texto do pincel %1 %2',
    args0: [
      { type: 'field_name_picker', name: 'CTX', text: 'ctx', kind: 'variable' },
      {
        type: 'field_dropdown',
        name: 'ALIGN',
        options: [
          ['à esquerda', 'left'],
          ['no centro', 'center'],
          ['à direita', 'right'],
        ],
      },
    ],
    previousStatement: 'JSStmt',
    nextStatement: 'JSStmt',
    colour: C,
    tooltip: 'De que lado o texto fica em relação ao ponto x (esquerda, centro ou direita).',
  },
  {
    type: 'sz_canvas_text_baseline',
    message0: 'Alinhar texto na vertical do pincel %1 %2',
    args0: [
      { type: 'field_name_picker', name: 'CTX', text: 'ctx', kind: 'variable' },
      {
        type: 'field_dropdown',
        name: 'BASELINE',
        options: [
          ['no topo', 'top'],
          ['no meio', 'middle'],
          ['embaixo', 'bottom'],
          ['na linha de base (padrão)', 'alphabetic'],
        ],
      },
    ],
    previousStatement: 'JSStmt',
    nextStatement: 'JSStmt',
    colour: C,
    tooltip:
      'Onde o texto fica em relação ao ponto y (topo, meio, base ou linha de base). Use "no topo" para o texto começar exatamente na altura y.',
  },
  {
    type: 'sz_canvas_arc_to',
    message0: 'Curva no traçado dobrando em x %1 y %2',
    args0: [
      { type: 'input_value', name: 'X1', check: 'JSValue' },
      { type: 'input_value', name: 'Y1', check: 'JSValue' },
    ],
    message1: 'seguindo até x %1 y %2 com raio %3',
    args1: [
      { type: 'input_value', name: 'X2', check: 'JSValue' },
      { type: 'input_value', name: 'Y2', check: 'JSValue' },
      { type: 'input_value', name: 'R', check: 'JSValue' },
    ],
    message2: 'usando pincel %1',
    args2: [{ type: 'field_name_picker', name: 'CTX', text: 'ctx', kind: 'variable' }],
    previousStatement: 'JSStmt',
    nextStatement: 'JSStmt',
    colour: C,
    tooltip:
      'Liga o ponto atual do traçado ao ponto final com um cantinho arredondado. Ótimo para cantos suaves.',
  },

  // ---- Formas e traçado extras (subcategorias) ----
  {
    type: 'sz_canvas_stroke_rect',
    message0: 'Desenhar contorno de retângulo com pincel %1',
    args0: [{ type: 'field_name_picker', name: 'CTX', text: 'ctx', kind: 'variable' }],
    message1: 'em x %1 y %2',
    args1: [
      { type: 'input_value', name: 'X', check: 'JSValue' },
      { type: 'input_value', name: 'Y', check: 'JSValue' },
    ],
    message2: 'largura %1 altura %2',
    args2: [
      { type: 'input_value', name: 'W', check: 'JSValue' },
      { type: 'input_value', name: 'H', check: 'JSValue' },
    ],
    previousStatement: 'JSStmt',
    nextStatement: 'JSStmt',
    colour: C,
    tooltip: 'Desenha só o contorno de um retângulo (sem preencher).',
  },
  {
    type: 'sz_canvas_clear_rect',
    message0: 'Limpar uma área com pincel %1',
    args0: [{ type: 'field_name_picker', name: 'CTX', text: 'ctx', kind: 'variable' }],
    message1: 'em x %1 y %2',
    args1: [
      { type: 'input_value', name: 'X', check: 'JSValue' },
      { type: 'input_value', name: 'Y', check: 'JSValue' },
    ],
    message2: 'largura %1 altura %2',
    args2: [
      { type: 'input_value', name: 'W', check: 'JSValue' },
      { type: 'input_value', name: 'H', check: 'JSValue' },
    ],
    previousStatement: 'JSStmt',
    nextStatement: 'JSStmt',
    colour: C,
    tooltip: 'Apaga só um pedaço retangular da tela (deixa transparente).',
  },
  {
    type: 'sz_canvas_round_rect',
    message0: 'Desenhar retângulo arredondado com pincel %1',
    args0: [{ type: 'field_name_picker', name: 'CTX', text: 'ctx', kind: 'variable' }],
    message1: 'em x %1 y %2 com largura %3 altura %4',
    args1: [
      { type: 'input_value', name: 'X', check: 'JSValue' },
      { type: 'input_value', name: 'Y', check: 'JSValue' },
      { type: 'input_value', name: 'W', check: 'JSValue' },
      { type: 'input_value', name: 'H', check: 'JSValue' },
    ],
    message2: 'raio dos cantos %1',
    args2: [{ type: 'input_value', name: 'R', check: 'JSValue' }],
    previousStatement: 'JSStmt',
    nextStatement: 'JSStmt',
    colour: C,
    tooltip:
      'Desenha um retângulo de cantos arredondados, preenchido (ótimo para caixas e botões).',
  },
  {
    type: 'sz_canvas_ellipse',
    message0: 'Desenhar elipse com pincel %1',
    args0: [{ type: 'field_name_picker', name: 'CTX', text: 'ctx', kind: 'variable' }],
    message1: 'no centro x %1 y %2',
    args1: [
      { type: 'input_value', name: 'X', check: 'JSValue' },
      { type: 'input_value', name: 'Y', check: 'JSValue' },
    ],
    message2: 'raio horizontal %1 vertical %2',
    args2: [
      { type: 'input_value', name: 'RX', check: 'JSValue' },
      { type: 'input_value', name: 'RY', check: 'JSValue' },
    ],
    previousStatement: 'JSStmt',
    nextStatement: 'JSStmt',
    colour: C,
    tooltip: 'Desenha uma elipse preenchida (raio horizontal e vertical diferentes = oval).',
  },
  {
    type: 'sz_canvas_arc_slice',
    message0: 'Desenhar fatia com pincel %1',
    args0: [{ type: 'field_name_picker', name: 'CTX', text: 'ctx', kind: 'variable' }],
    message1: 'no centro x %1 y %2 com raio %3',
    args1: [
      { type: 'input_value', name: 'X', check: 'JSValue' },
      { type: 'input_value', name: 'Y', check: 'JSValue' },
      { type: 'input_value', name: 'R', check: 'JSValue' },
    ],
    message2: 'do ângulo %1 até %2 em radianos',
    args2: [
      { type: 'input_value', name: 'START', check: 'JSValue' },
      { type: 'input_value', name: 'END', check: 'JSValue' },
    ],
    previousStatement: 'JSStmt',
    nextStatement: 'JSStmt',
    colour: C,
    tooltip: 'Desenha uma fatia/pizza: um pedaço de círculo entre dois ângulos (em radianos).',
  },
  {
    type: 'sz_canvas_quadratic_curve',
    message0: 'Curva no pincel %1',
    args0: [{ type: 'field_name_picker', name: 'CTX', text: 'ctx', kind: 'variable' }],
    message1: 'puxada pelo ponto x %1 y %2',
    args1: [
      { type: 'input_value', name: 'CPX', check: 'JSValue' },
      { type: 'input_value', name: 'CPY', check: 'JSValue' },
    ],
    message2: 'terminando em x %1 y %2',
    args2: [
      { type: 'input_value', name: 'X', check: 'JSValue' },
      { type: 'input_value', name: 'Y', check: 'JSValue' },
    ],
    previousStatement: 'JSStmt',
    nextStatement: 'JSStmt',
    colour: C,
    tooltip:
      'Continua o traçado com uma curva suave (um ponto de controle puxa a curva). Use entre "começar traçado" e "preencher/contornar".',
  },
  {
    type: 'sz_canvas_bezier_curve',
    message0: 'Curva dupla no pincel %1',
    args0: [{ type: 'field_name_picker', name: 'CTX', text: 'ctx', kind: 'variable' }],
    message1: 'puxada por x %1 y %2 e x %3 y %4',
    args1: [
      { type: 'input_value', name: 'CP1X', check: 'JSValue' },
      { type: 'input_value', name: 'CP1Y', check: 'JSValue' },
      { type: 'input_value', name: 'CP2X', check: 'JSValue' },
      { type: 'input_value', name: 'CP2Y', check: 'JSValue' },
    ],
    message2: 'terminando em x %1 y %2',
    args2: [
      { type: 'input_value', name: 'X', check: 'JSValue' },
      { type: 'input_value', name: 'Y', check: 'JSValue' },
    ],
    previousStatement: 'JSStmt',
    nextStatement: 'JSStmt',
    colour: C,
    tooltip: 'Curva com dois pontos de controle (curva em S). Use dentro de um traçado.',
  },
  {
    type: 'sz_canvas_shadow',
    message0: 'Brilho/sombra do pincel %1 cor %2 desfoque %3',
    args0: [
      { type: 'field_name_picker', name: 'CTX', text: 'ctx', kind: 'variable' },
      { type: 'input_value', name: 'COLOR', check: 'JSValue' },
      { type: 'input_value', name: 'BLUR', check: 'JSValue' },
    ],
    inputsInline: true,
    previousStatement: 'JSStmt',
    nextStatement: 'JSStmt',
    colour: C,
    tooltip:
      'Liga um brilho/sombra colorido no que for desenhado depois (desfoque 0 = sem brilho).',
  },
  {
    type: 'sz_canvas_stroke_text',
    message0: 'Escrever contorno %1 com pincel %2 em x %3 y %4',
    args0: [
      { type: 'input_value', name: 'TEXT', check: 'JSValue' },
      { type: 'field_name_picker', name: 'CTX', text: 'ctx', kind: 'variable' },
      { type: 'input_value', name: 'X', check: 'JSValue' },
      { type: 'input_value', name: 'Y', check: 'JSValue' },
    ],
    inputsInline: true,
    previousStatement: 'JSStmt',
    nextStatement: 'JSStmt',
    colour: C,
    tooltip: 'Escreve um texto só com o contorno (usa a cor do contorno).',
  },
  {
    type: 'sz_canvas_line_dash',
    message0: 'Traço tracejado do pincel %1 tamanho %2',
    args0: [
      { type: 'field_name_picker', name: 'CTX', text: 'ctx', kind: 'variable' },
      { type: 'input_value', name: 'SEGMENT', check: 'JSValue' },
    ],
    inputsInline: true,
    previousStatement: 'JSStmt',
    nextStatement: 'JSStmt',
    colour: C,
    tooltip: 'Deixa as linhas tracejadas (pontilhadas). Tamanho 0 volta a ser linha contínua.',
  },
  {
    type: 'sz_canvas_measure_text',
    message0: 'largura do texto %1 no pincel %2',
    args0: [
      { type: 'input_value', name: 'TEXT', check: 'JSValue' },
      { type: 'field_name_picker', name: 'CTX', text: 'ctx', kind: 'variable' },
    ],
    inputsInline: true,
    output: 'JSValue',
    colour: C,
    tooltip: 'Quantos pixels de largura o texto ocupa com a fonte atual (use para centralizar).',
  },
  {
    type: 'sz_canvas_point_in_path',
    message0: 'o ponto x %1 y %2 está dentro do traçado (pincel %3) ?',
    args0: [
      { type: 'input_value', name: 'X', check: 'JSValue' },
      { type: 'input_value', name: 'Y', check: 'JSValue' },
      { type: 'field_name_picker', name: 'CTX', text: 'ctx', kind: 'variable' },
    ],
    inputsInline: true,
    output: 'JSValue',
    colour: C,
    tooltip:
      'Verdadeiro se o ponto (x, y) cai DENTRO do traçado atual (o desenhado por último). Ótimo para saber se o clique acertou uma forma.',
  },
  {
    type: 'sz_canvas_point_in_stroke',
    message0: 'o ponto x %1 y %2 está na linha do traçado (pincel %3) ?',
    args0: [
      { type: 'input_value', name: 'X', check: 'JSValue' },
      { type: 'input_value', name: 'Y', check: 'JSValue' },
      { type: 'field_name_picker', name: 'CTX', text: 'ctx', kind: 'variable' },
    ],
    inputsInline: true,
    output: 'JSValue',
    colour: C,
    tooltip: 'Verdadeiro se o ponto (x, y) cai EM CIMA da linha (contorno) do traçado atual.',
  },
  // ---- Entrada na mão: tecla apertada? e posição do mouse/dedo ----
  {
    type: 'sz_input_key_pressed',
    message0: 'a tecla %1 está apertada?',
    args0: [
      {
        type: 'field_dropdown',
        name: 'KEY',
        options: [
          ['→ seta direita', 'ArrowRight'],
          ['← seta esquerda', 'ArrowLeft'],
          ['↑ seta para cima', 'ArrowUp'],
          ['↓ seta para baixo', 'ArrowDown'],
          ['barra de espaço', 'Space'],
          ['Enter', 'Enter'],
        ],
      },
    ],
    output: 'JSValue',
    colour: C,
    tooltip: 'Verdadeiro enquanto a tecla está sendo segurada. Use dentro de um "se".',
  },
  {
    type: 'sz_input_pointer_x',
    message0: 'x do mouse/dedo',
    args0: [],
    output: 'JSValue',
    colour: C,
    tooltip: 'Posição horizontal do mouse ou do dedo dentro da tela de desenho.',
  },
  {
    type: 'sz_input_pointer_y',
    message0: 'y do mouse/dedo',
    args0: [],
    output: 'JSValue',
    colour: C,
    tooltip: 'Posição vertical do mouse ou do dedo dentro da tela de desenho.',
  },
]

// Sub-categorias do Canvas (estilo Programação/Jogo 2D). Tipos ainda não
// definidos (blocos novos) são ignorados pelo toolbox até existirem.
export const CANVAS_GROUPS: { name: string; colour: string; types: string[] }[] = [
  {
    name: '🖥️ Tela',
    colour: '#16b87a',
    types: [
      'sz_html_canvas',
      'sz_canvas_setup',
      'sz_canvas_set_size',
      'sz_canvas_clear',
      'sz_canvas_clear_rect',
    ],
  },
  {
    name: '🎨 Pincel',
    colour: '#22c98a',
    types: [
      'sz_canvas_fill_style',
      'sz_canvas_stroke_style',
      'sz_canvas_line_width',
      'sz_canvas_global_alpha',
      'sz_canvas_gradient',
      'sz_canvas_shadow',
      'sz_canvas_line_dash',
    ],
  },
  {
    name: '⬛ Formas',
    colour: '#0f9d66',
    types: [
      'sz_canvas_fill_rect',
      'sz_canvas_stroke_rect',
      'sz_canvas_round_rect',
      'sz_canvas_arc',
      'sz_canvas_ellipse',
      'sz_canvas_arc_slice',
    ],
  },
  {
    name: '✏️ Traçado',
    colour: '#2ed69a',
    types: [
      'sz_canvas_begin_path',
      'sz_canvas_move_to',
      'sz_canvas_line_to',
      'sz_canvas_quadratic_curve',
      'sz_canvas_bezier_curve',
      'sz_canvas_arc_to',
      'sz_canvas_rect',
      'sz_canvas_close_path',
      'sz_canvas_stroke',
      'sz_canvas_fill',
      'sz_canvas_clip',
      'sz_canvas_point_in_path',
      'sz_canvas_point_in_stroke',
    ],
  },
  {
    name: '🔤 Texto',
    colour: '#138f5e',
    types: [
      'sz_canvas_font',
      'sz_canvas_text_align',
      'sz_canvas_text_baseline',
      'sz_canvas_fill_text',
      'sz_canvas_stroke_text',
      'sz_canvas_measure_text',
    ],
  },
  {
    name: '🔄 Transformar',
    colour: '#3ad9a3',
    types: [
      'sz_canvas_save',
      'sz_canvas_restore',
      'sz_canvas_translate',
      'sz_canvas_rotate',
      'sz_canvas_scale',
    ],
  },
  {
    name: '🖼️ Imagem',
    colour: '#1aa870',
    types: [
      'sz_val_image',
      'sz_js_new_image',
      'sz_js_image_onload',
      'sz_js_image_onerror',
      'sz_canvas_draw_image',
    ],
  },
  {
    name: '🎞️ Animação & entrada',
    colour: '#0d7d50',
    types: [
      'sz_canvas_anim_loop',
      'sz_canvas_cancel_anim',
      'sz_canvas_request_frame',
      'sz_canvas_request_frame_do',
      'sz_canvas_keyboard',
      'sz_input_key_pressed',
      'sz_input_pointer_x',
      'sz_input_pointer_y',
    ],
  },
]

// IDENTIDADE: cada sub-grupo recebe um TOM da cor base da categoria (Canvas),
// derivado claro→escuro (categoryShades) — os literais em CANVAS_GROUPS são placeholders.
const CANVAS_SHADES = categoryShades(CATEGORY_COLORS.canvas, CANVAS_GROUPS.length)
CANVAS_GROUPS.forEach((g, i) => {
  g.colour = CANVAS_SHADES[i] ?? CATEGORY_COLORS.canvas
})
const CANVAS_COLOUR_BY_TYPE = new Map<string, string>(
  CANVAS_GROUPS.flatMap((g) => g.types.map((t) => [t, g.colour] as const)),
)
for (const b of CANVAS_BLOCKS) {
  const colour = CANVAS_COLOUR_BY_TYPE.get(b.type)
  if (colour) b.colour = colour
}
