import { CATEGORY_COLORS } from '../theme'
import type { BlockDefinition } from './types'

const C = CATEGORY_COLORS.canvas

export const CANVAS_BLOCKS: BlockDefinition[] = [
  {
    type: 'sz_canvas_setup',
    message0: 'Pegar canvas id %1 e guardar contexto em %2',
    args0: [
      { type: 'field_input', name: 'CANVAS_ID', text: 'tela' },
      { type: 'field_input', name: 'CTX', text: 'ctx' },
    ],
    previousStatement: 'JSStmt',
    nextStatement: 'JSStmt',
    colour: C,
  },
  {
    type: 'sz_canvas_set_size',
    message0: 'Definir tamanho do canvas %1 largura %2 altura %3',
    args0: [
      { type: 'field_input', name: 'CTX', text: 'ctx' },
      { type: 'input_value', name: 'W', check: 'JSValue' },
      { type: 'input_value', name: 'H', check: 'JSValue' },
    ],
    inputsInline: true,
    previousStatement: 'JSStmt',
    nextStatement: 'JSStmt',
    colour: C,
    tooltip:
      'Muda a largura e a altura do canvas dinamicamente (ex.: tela cheia com a largura/altura da janela).',
  },
  {
    type: 'sz_canvas_clear',
    message0: 'Limpar tela %1',
    args0: [{ type: 'field_input', name: 'CTX', text: 'ctx' }],
    previousStatement: 'JSStmt',
    nextStatement: 'JSStmt',
    colour: C,
  },
  {
    type: 'sz_canvas_fill_style',
    message0: 'Definir cor do pincel %1 como %2',
    args0: [
      { type: 'field_input', name: 'CTX', text: 'ctx' },
      { type: 'input_value', name: 'COLOR', check: 'JSValue' },
    ],
    inputsInline: true,
    previousStatement: 'JSStmt',
    nextStatement: 'JSStmt',
    colour: C,
  },
  {
    type: 'sz_canvas_fill_rect',
    message0: 'Desenhar retângulo %1 em x %2 y %3 largura %4 altura %5',
    args0: [
      { type: 'field_input', name: 'CTX', text: 'ctx' },
      { type: 'input_value', name: 'X', check: 'JSValue' },
      { type: 'input_value', name: 'Y', check: 'JSValue' },
      { type: 'input_value', name: 'W', check: 'JSValue' },
      { type: 'input_value', name: 'H', check: 'JSValue' },
    ],
    inputsInline: true,
    previousStatement: 'JSStmt',
    nextStatement: 'JSStmt',
    colour: C,
  },
  {
    type: 'sz_canvas_arc',
    message0: 'Desenhar círculo %1 em x %2 y %3 raio %4',
    args0: [
      { type: 'field_input', name: 'CTX', text: 'ctx' },
      { type: 'input_value', name: 'X', check: 'JSValue' },
      { type: 'input_value', name: 'Y', check: 'JSValue' },
      { type: 'input_value', name: 'R', check: 'JSValue' },
    ],
    inputsInline: true,
    previousStatement: 'JSStmt',
    nextStatement: 'JSStmt',
    colour: C,
  },
  {
    type: 'sz_canvas_fill_text',
    message0: 'Desenhar texto %1 com pincel %2 em x %3 y %4',
    args0: [
      { type: 'field_input', name: 'TEXT', text: 'Olá' },
      { type: 'field_input', name: 'CTX', text: 'ctx' },
      { type: 'input_value', name: 'X', check: 'JSValue' },
      { type: 'input_value', name: 'Y', check: 'JSValue' },
    ],
    inputsInline: true,
    previousStatement: 'JSStmt',
    nextStatement: 'JSStmt',
    colour: C,
  },
  {
    type: 'sz_canvas_anim_loop',
    // O rótulo "A cada frame fazer" e os controles +/− são montados pelo mutator
    // (sz_anim_loop_mutator); aqui ficamos só com o corpo.
    message0: '%1',
    args0: [{ type: 'input_statement', name: 'BODY' }],
    previousStatement: 'JSStmt',
    nextStatement: 'JSStmt',
    colour: C,
    mutator: 'sz_anim_loop_mutator',
    tooltip:
      'Repete o corpo a cada quadro. Clique no + para guardar o id da animação numa variável e poder pará-la depois com "parar animação". Deixe o bloco no nível principal para a variável ficar acessível.',
  },
  {
    type: 'sz_canvas_cancel_anim',
    message0: 'parar animação %1',
    args0: [{ type: 'input_value', name: 'HANDLE', check: 'JSValue' }],
    inputsInline: true,
    previousStatement: 'JSStmt',
    nextStatement: 'JSStmt',
    colour: C,
    tooltip: 'Para a animação, cancelando o id guardado por "A cada frame fazer".',
  },
  {
    type: 'sz_canvas_keyboard',
    message0: 'Ler teclado simples em variável %1',
    args0: [{ type: 'field_input', name: 'NAME', text: 'teclas' }],
    previousStatement: 'JSStmt',
    nextStatement: 'JSStmt',
    colour: C,
  },
  // ---- Canvas extras (Fase 2.3) ----
  {
    type: 'sz_canvas_draw_image',
    message0: 'Desenhar imagem %1 no pincel %2 em x %3 y %4 largura %5 altura %6',
    args0: [
      { type: 'field_input', name: 'SRC', text: 'https://exemplo.com/img.png' },
      { type: 'field_input', name: 'CTX', text: 'ctx' },
      { type: 'input_value', name: 'X', check: 'JSValue' },
      { type: 'input_value', name: 'Y', check: 'JSValue' },
      { type: 'input_value', name: 'W', check: 'JSValue' },
      { type: 'input_value', name: 'H', check: 'JSValue' },
    ],
    inputsInline: true,
    previousStatement: 'JSStmt',
    nextStatement: 'JSStmt',
    colour: C,
  },
  {
    type: 'sz_canvas_save',
    message0: 'Salvar estado do pincel %1',
    args0: [{ type: 'field_input', name: 'CTX', text: 'ctx' }],
    previousStatement: 'JSStmt',
    nextStatement: 'JSStmt',
    colour: C,
  },
  {
    type: 'sz_canvas_restore',
    message0: 'Restaurar estado do pincel %1',
    args0: [{ type: 'field_input', name: 'CTX', text: 'ctx' }],
    previousStatement: 'JSStmt',
    nextStatement: 'JSStmt',
    colour: C,
  },
  {
    type: 'sz_canvas_translate',
    message0: 'Mover pincel %1 em x %2 y %3',
    args0: [
      { type: 'field_input', name: 'CTX', text: 'ctx' },
      { type: 'input_value', name: 'X', check: 'JSValue' },
      { type: 'input_value', name: 'Y', check: 'JSValue' },
    ],
    inputsInline: true,
    previousStatement: 'JSStmt',
    nextStatement: 'JSStmt',
    colour: C,
  },
  {
    type: 'sz_canvas_rotate',
    message0: 'Girar pincel %1 em %2 radianos',
    args0: [
      { type: 'field_input', name: 'CTX', text: 'ctx' },
      { type: 'field_number', name: 'ANGLE', value: 0, precision: 0.01 },
    ],
    previousStatement: 'JSStmt',
    nextStatement: 'JSStmt',
    colour: C,
  },
  {
    type: 'sz_canvas_scale',
    message0: 'Escalar pincel %1 em x %2 y %3',
    args0: [
      { type: 'field_input', name: 'CTX', text: 'ctx' },
      { type: 'field_number', name: 'SX', value: 1, precision: 0.1 },
      { type: 'field_number', name: 'SY', value: 1, precision: 0.1 },
    ],
    previousStatement: 'JSStmt',
    nextStatement: 'JSStmt',
    colour: C,
  },
  {
    type: 'sz_canvas_gradient',
    message0: 'Gradiente linear pincel %1 em variável %2 de (%3,%4) a (%5,%6) com cor %7 → %8',
    args0: [
      { type: 'field_input', name: 'CTX', text: 'ctx' },
      { type: 'field_input', name: 'NAME', text: 'g' },
      { type: 'field_number', name: 'X0', value: 0 },
      { type: 'field_number', name: 'Y0', value: 0 },
      { type: 'field_number', name: 'X1', value: 200 },
      { type: 'field_number', name: 'Y1', value: 0 },
      { type: 'field_colour_sz', name: 'C0', colour: '#22d3ee' },
      { type: 'field_colour_sz', name: 'C1', colour: '#a78bfa' },
    ],
    previousStatement: 'JSStmt',
    nextStatement: 'JSStmt',
    colour: C,
  },
]
