import { CATEGORY_COLORS, categoryShades } from '../theme'
import type { BlockDefinition } from './types'

const C = CATEGORY_COLORS.js

/**
 * Blocos da LINGUAGEM JavaScript: variáveis, console/alert, controle de fluxo,
 * listas, timers e Web APIs (storage/fetch). A MANIPULAÇÃO DO DOM (eventos,
 * busca de elementos, propriedades, classes, criação) vive em `dom.ts`
 * (categoria "DOM", entre CSS e JavaScript na toolbox).
 */
export const JS_BLOCKS: BlockDefinition[] = [
  {
    type: 'sz_js_array_push',
    placement: 'command',
    message0: 'na lista %1 adicionar %2',
    args0: [
      { type: 'field_name_picker', name: 'NAME', text: 'lista', kind: 'group' },
      { type: 'input_value', name: 'VALUE', check: 'JSValue' },
    ],
    inputsInline: true,
    previousStatement: 'JSStmt',
    nextStatement: 'JSStmt',
    colour: C,
    tooltip: 'Acrescenta um valor ao fim da lista.',
  },
  {
    type: 'sz_js_array_remove',
    placement: 'command',
    message0: 'na lista %1 remover o %2',
    args0: [
      { type: 'field_name_picker', name: 'NAME', text: 'lista', kind: 'group' },
      {
        type: 'field_dropdown',
        name: 'END',
        options: [
          ['último', 'pop'],
          ['primeiro', 'shift'],
        ],
      },
    ],
    inputsInline: true,
    previousStatement: 'JSStmt',
    nextStatement: 'JSStmt',
    colour: C,
    tooltip: 'Remove o último ou o primeiro item da lista.',
  },
  {
    type: 'sz_js_array_splice',
    placement: 'command',
    message0: 'na lista %1 remover %2 item(ns) a partir da posição %3',
    args0: [
      { type: 'field_name_picker', name: 'NAME', text: 'lista', kind: 'group' },
      { type: 'input_value', name: 'COUNT', check: 'JSValue' },
      { type: 'input_value', name: 'START', check: 'JSValue' },
    ],
    inputsInline: true,
    previousStatement: 'JSStmt',
    nextStatement: 'JSStmt',
    colour: C,
    tooltip: 'Remove uma quantidade de itens da lista a partir de uma posição.',
  },
  {
    type: 'sz_js_console_log_text',
    placement: 'command',
    message0: 'Mostrar texto no console %1',
    args0: [{ type: 'field_input', name: 'VALUE', text: 'Olá' }],
    previousStatement: 'JSStmt',
    nextStatement: 'JSStmt',
    colour: C,
    tooltip:
      'Mostra uma mensagem na área de console para acompanhar o que o programa está fazendo.',
  },
  {
    type: 'sz_js_console_log_var',
    placement: 'command',
    message0: 'Mostrar valor da variável %1 no console',
    args0: [{ type: 'field_name_picker', name: 'NAME', text: 'contador', kind: 'variable' }],
    previousStatement: 'JSStmt',
    nextStatement: 'JSStmt',
    colour: C,
    tooltip: 'Mostra no console o valor guardado em uma variável.',
  },
  {
    type: 'sz_js_console_log_value',
    placement: 'command',
    message0: 'Mostrar no console %1',
    args0: [{ type: 'input_value', name: 'VALUE', check: 'JSValue' }],
    inputsInline: true,
    previousStatement: 'JSStmt',
    nextStatement: 'JSStmt',
    colour: C,
    tooltip: 'Mostra qualquer valor no console, como um texto montado, um objeto ou uma conta.',
  },
  {
    type: 'sz_js_alert_text',
    placement: 'command',
    message0: 'Mostrar aviso com texto %1',
    args0: [{ type: 'field_input', name: 'VALUE', text: 'Olá!' }],
    previousStatement: 'JSStmt',
    nextStatement: 'JSStmt',
    colour: C,
    tooltip: 'Mostra uma janelinha de aviso na tela.',
  },
  {
    type: 'sz_js_alert_var',
    placement: 'command',
    message0: 'Mostrar aviso com valor da variável %1',
    args0: [{ type: 'field_name_picker', name: 'NAME', text: 'contador', kind: 'variable' }],
    previousStatement: 'JSStmt',
    nextStatement: 'JSStmt',
    colour: C,
    tooltip: 'Mostra uma janelinha de aviso com o valor de uma variável.',
  },
  {
    type: 'sz_js_var_declare',
    placement: 'command',
    message0: 'declarar variável %1',
    args0: [{ type: 'field_input', name: 'NAME', text: 'x' }],
    previousStatement: 'JSStmt',
    nextStatement: 'JSStmt',
    colour: C,
    tooltip: 'Declara uma variável sem valor inicial.',
  },
  {
    type: 'sz_js_var_create',
    placement: 'command',
    message0: 'Criar variável %1 com valor %2',
    args0: [
      { type: 'field_input', name: 'NAME', text: 'contador' },
      { type: 'input_value', name: 'VALUE', check: 'JSValue' },
    ],
    inputsInline: true,
    previousStatement: 'JSStmt',
    nextStatement: 'JSStmt',
    colour: C,
    tooltip: 'Cria uma variável e guarda nela um valor: número, conta, aleatório, etc.',
  },
  {
    type: 'sz_js_const_create',
    placement: 'command',
    message0: 'Criar constante %1 com valor %2',
    args0: [
      { type: 'field_input', name: 'NAME', text: 'PI' },
      { type: 'input_value', name: 'VALUE', check: 'JSValue' },
    ],
    inputsInline: true,
    previousStatement: 'JSStmt',
    nextStatement: 'JSStmt',
    colour: C,
    tooltip: 'Cria uma constante: um valor que não muda depois de criado.',
  },
  {
    type: 'sz_js_var_assign',
    placement: 'command',
    message0: 'Alterar variável %1 para %2',
    args0: [
      { type: 'field_name_picker', name: 'NAME', text: 'contador', kind: 'mutable-variable' },
      { type: 'input_value', name: 'VALUE', check: 'JSValue' },
    ],
    inputsInline: true,
    previousStatement: 'JSStmt',
    nextStatement: 'JSStmt',
    colour: C,
    tooltip: 'Muda o valor de uma variável que já existe.',
  },
  {
    // OCULTO (hidden): não aparece na paleta — é só para o round-trip fiel de um
    // statement que apenas AVALIA um valor e descarta (ex.: `this.game.gameOver;`,
    // um no-op comum em código copiado). Sem ele, essa linha viraria "código
    // avançado". A criança não precisa deste bloco para programar.
    type: 'sz_js_expr_statement',
    placement: 'command',
    message0: 'avaliar %1',
    args0: [{ type: 'input_value', name: 'VALUE', check: 'JSValue' }],
    inputsInline: true,
    previousStatement: 'JSStmt',
    nextStatement: 'JSStmt',
    colour: C,
    hidden: true,
    tooltip: 'Calcula um valor e o descarta.',
  },
  {
    type: 'sz_js_var_increment',
    placement: 'command',
    message0: 'Somar %1 em variável %2',
    args0: [
      { type: 'field_number', name: 'DELTA', value: 1 },
      { type: 'field_name_picker', name: 'NAME', text: 'contador', kind: 'mutable-variable' },
    ],
    previousStatement: 'JSStmt',
    nextStatement: 'JSStmt',
    colour: C,
    tooltip: 'Soma ou tira uma quantidade do valor atual de uma variável.',
  },
  {
    // Os ramos "senão se"/"senão" são criados pelo mutator (+/− estilo MakeCode);
    // o bloco nasce só com "Se … então [C]". Ver `blocks/ifElseMutator.ts`.
    type: 'sz_js_if_else',
    placement: 'command',
    message0: 'Se %1',
    args0: [{ type: 'input_value', name: 'COND', check: 'JSValue' }],
    message1: 'então %1',
    args1: [{ type: 'input_statement', name: 'THEN' }],
    inputsInline: true,
    previousStatement: 'JSStmt',
    nextStatement: 'JSStmt',
    colour: C,
    mutator: 'sz_if_else_mutator',
    tooltip:
      'Executa o "então" quando a condição for verdadeira. Use + para juntar "senão se" e "senão".',
  },
  {
    type: 'sz_js_repeat',
    placement: 'command',
    message0: 'Repetir %1 vezes',
    args0: [{ type: 'input_value', name: 'TIMES', check: 'JSValue' }],
    message1: 'fazer %1',
    args1: [{ type: 'input_statement', name: 'DO' }],
    inputsInline: true,
    previousStatement: 'JSStmt',
    nextStatement: 'JSStmt',
    colour: C,
    tooltip: 'Repete os blocos de dentro a quantidade de vezes escolhida.',
  },
  {
    type: 'sz_js_while',
    placement: 'command',
    message0: 'enquanto %1',
    args0: [{ type: 'input_value', name: 'COND', check: 'JSValue' }],
    message1: 'fazer %1',
    args1: [{ type: 'input_statement', name: 'DO' }],
    inputsInline: true,
    previousStatement: 'JSStmt',
    nextStatement: 'JSStmt',
    colour: C,
    tooltip:
      'Repete o "fazer" enquanto a condição for verdadeira. Garanta que a condição um dia fique falsa, senão o laço não termina.',
  },
  {
    type: 'sz_js_do_while',
    placement: 'command',
    message0: 'fazer %1',
    args0: [{ type: 'input_statement', name: 'DO' }],
    message1: 'enquanto %1',
    args1: [{ type: 'input_value', name: 'COND', check: 'JSValue' }],
    inputsInline: true,
    previousStatement: 'JSStmt',
    nextStatement: 'JSStmt',
    colour: C,
    tooltip: 'Executa o "fazer" pelo menos uma vez e repete enquanto a condição for verdadeira.',
  },
  {
    type: 'sz_js_break',
    message0: 'sair do laço',
    previousStatement: 'JSStmt',
    nextStatement: 'JSStmt',
    colour: C,
    placement: { root: [], nested: ['loop-body'], role: 'command' },
    tooltip: 'Interrompe o laço (loop) atual imediatamente.',
  },
  {
    type: 'sz_js_continue',
    message0: 'pular para a próxima volta',
    previousStatement: 'JSStmt',
    nextStatement: 'JSStmt',
    colour: C,
    placement: { root: [], nested: ['loop-body'], role: 'command' },
    tooltip: 'Pula o resto desta volta e vai direto para a próxima repetição do laço.',
  },
  {
    type: 'sz_js_throw',
    placement: 'command',
    message0: 'disparar erro com mensagem %1',
    args0: [{ type: 'input_value', name: 'MESSAGE', check: 'JSValue' }],
    inputsInline: true,
    previousStatement: 'JSStmt',
    nextStatement: 'JSStmt',
    colour: C,
    tooltip:
      'Dispara um erro com uma mensagem (throw new Error). Use com "tentar … se der erro" para encerrar/desviar (ex.: fim de jogo).',
  },
  {
    type: 'sz_js_object_assign',
    placement: 'command',
    message0: 'copiar propriedades de %1 para %2',
    args0: [
      { type: 'field_name_picker', name: 'SOURCE', text: 'origem', kind: 'variable' },
      { type: 'field_name_picker', name: 'TARGET', text: 'destino', kind: 'variable' },
    ],
    inputsInline: true,
    previousStatement: 'JSStmt',
    nextStatement: 'JSStmt',
    colour: C,
    tooltip:
      'Copia todas as propriedades de um objeto para outro (Object.assign), atualizando o destino de uma vez.',
  },
  {
    type: 'sz_js_switch',
    placement: 'command',
    message0: 'escolha %1',
    args0: [{ type: 'input_value', name: 'SUBJECT', check: 'JSValue' }],
    message1: 'casos %1',
    args1: [{ type: 'input_statement', name: 'CASES', check: 'SwitchCase' }],
    message2: 'senão (padrão) %1',
    args2: [{ type: 'input_statement', name: 'DEFAULT' }],
    previousStatement: 'JSStmt',
    nextStatement: 'JSStmt',
    colour: C,
    tooltip:
      'Escolhe um caminho conforme o valor (switch). Arraste blocos "caso" dentro. O "senão" roda quando nenhum caso bate.',
  },
  {
    type: 'sz_js_case',
    placement: 'switch-case',
    message0: 'caso o valor for %1',
    args0: [{ type: 'input_value', name: 'MATCH', check: 'JSValue' }],
    message1: 'fazer %1',
    args1: [{ type: 'input_statement', name: 'DO' }],
    previousStatement: 'SwitchCase',
    nextStatement: 'SwitchCase',
    colour: C,
    tooltip: 'Um caso do "escolha": se o valor bater, roda o "fazer" (e para, break automático).',
  },
  {
    type: 'sz_js_for_of',
    placement: 'command',
    message0: 'para cada %1 de %2',
    args0: [
      { type: 'field_input', name: 'ITEM', text: 'item' },
      { type: 'field_name_picker', name: 'NAME', text: 'lista', kind: 'group' },
    ],
    message1: 'fazer %1',
    args1: [{ type: 'input_statement', name: 'DO' }],
    inputsInline: true,
    previousStatement: 'JSStmt',
    nextStatement: 'JSStmt',
    colour: C,
    tooltip:
      'Percorre cada item de uma lista. Sem posição/índice. Use "para cada item" se precisar do índice.',
  },
  {
    type: 'sz_js_for_range',
    placement: 'command',
    message0: 'contar %1 de %2 até %3 (passo %4)',
    args0: [
      { type: 'field_input', name: 'VAR', text: 'i' },
      { type: 'input_value', name: 'FROM', check: 'JSValue' },
      { type: 'input_value', name: 'TO', check: 'JSValue' },
      { type: 'input_value', name: 'STEP', check: 'JSValue' },
    ],
    message1: 'fazer %1',
    args1: [{ type: 'input_statement', name: 'DO' }],
    inputsInline: true,
    previousStatement: 'JSStmt',
    nextStatement: 'JSStmt',
    colour: C,
    tooltip: 'Laço de contagem: vai de "de" até "até" (exclusivo) somando o passo a cada volta.',
  },
  {
    type: 'sz_js_try_catch',
    placement: 'command',
    message0: 'tentar %1',
    args0: [{ type: 'input_statement', name: 'BODY' }],
    message1: 'se der erro %1 fazer %2',
    args1: [
      { type: 'field_input', name: 'ERR', text: 'erro' },
      { type: 'input_statement', name: 'HANDLER' },
    ],
    message2: 'no fim, sempre %1',
    args2: [{ type: 'input_statement', name: 'FINALLY' }],
    previousStatement: 'JSStmt',
    nextStatement: 'JSStmt',
    colour: C,
    tooltip:
      'Tenta executar o "tentar"; se acontecer um erro, executa o "se der erro" (com a mensagem na variável); o "no fim" roda sempre. Deixe o "no fim" vazio se não precisar.',
  },
  {
    type: 'sz_js_for_each',
    placement: 'command',
    message0: 'para cada item %1 (posição %2) na lista %3',
    args0: [
      { type: 'field_input', name: 'ITEM', text: 'item' },
      { type: 'field_input', name: 'INDEX', text: '' },
      { type: 'input_value', name: 'ARRAY', check: 'JSValue' },
    ],
    message1: 'fazer %1',
    args1: [{ type: 'input_statement', name: 'DO' }],
    inputsInline: true,
    previousStatement: 'JSStmt',
    nextStatement: 'JSStmt',
    colour: C,
    tooltip:
      'Repete o "fazer" para cada item da lista. Deixe a posição em branco se não precisar dela.',
  },
  {
    type: 'sz_js_set_timeout',
    placement: 'command',
    message0: 'depois de %1 ms',
    args0: [{ type: 'input_value', name: 'MS', check: 'JSValue' }],
    message1: 'fazer %1',
    args1: [{ type: 'input_statement', name: 'DO' }],
    inputsInline: true,
    previousStatement: 'JSStmt',
    nextStatement: 'JSStmt',
    colour: C,
    tooltip: 'Espera um tempo (em milissegundos) e então executa o "fazer".',
  },
  {
    type: 'sz_js_set_interval',
    placement: 'loop-periodic',
    migration: 'lift-periodic-loop',
    message0: 'repetir a cada %1 ms',
    args0: [{ type: 'input_value', name: 'MS', check: 'JSValue' }],
    message1: 'fazer %1',
    args1: [{ type: 'input_statement', name: 'DO' }],
    inputsInline: true,
    previousStatement: 'JSStmt',
    nextStatement: 'JSStmt',
    colour: C,
    tooltip: 'Repete o "fazer" a cada intervalo de tempo em milissegundos.',
  },
  {
    type: 'sz_js_set_timeout_seconds',
    placement: 'command',
    message0: 'depois de %1 segundos',
    args0: [{ type: 'input_value', name: 'S', check: 'JSValue' }],
    message1: 'fazer %1',
    args1: [{ type: 'input_statement', name: 'DO' }],
    inputsInline: true,
    previousStatement: 'JSStmt',
    nextStatement: 'JSStmt',
    colour: C,
    tooltip: 'Espera a quantidade de segundos escolhida e então executa os blocos de dentro.',
  },
  {
    type: 'sz_js_set_interval_seconds',
    placement: 'loop-periodic',
    migration: 'lift-periodic-loop',
    message0: 'repetir a cada %1 segundos',
    args0: [{ type: 'input_value', name: 'S', check: 'JSValue' }],
    message1: 'fazer %1',
    args1: [{ type: 'input_statement', name: 'DO' }],
    inputsInline: true,
    previousStatement: 'JSStmt',
    nextStatement: 'JSStmt',
    colour: C,
    tooltip: 'Repete os blocos de dentro no intervalo de segundos escolhido.',
  },
  // ---- ⏳ Assíncrono (avançado) ----
  {
    type: 'sz_js_await',
    message0: 'esperar %1 terminar',
    args0: [{ type: 'input_value', name: 'VALUE', check: 'JSValue' }],
    inputsInline: true,
    previousStatement: 'JSStmt',
    nextStatement: 'JSStmt',
    colour: C,
    placement: { root: [], nested: ['async-function-body'], role: 'command' },
    tooltip: 'Espera uma promessa terminar antes de seguir. Use dentro de uma função assíncrona.',
  },
  {
    type: 'sz_js_set_timeout_call',
    placement: 'command',
    message0: 'depois de %1 ms, chamar a função %2',
    args0: [
      { type: 'input_value', name: 'MS', check: 'JSValue' },
      { type: 'field_name_picker', name: 'FN', text: 'resolve', kind: 'function' },
    ],
    inputsInline: true,
    previousStatement: 'JSStmt',
    nextStatement: 'JSStmt',
    colour: C,
    tooltip: 'Espera um tempo e então chama a função escolhida.',
  },
  {
    type: 'sz_val_new_promise',
    message0: 'uma promessa que avisa quando terminar com %1 %2 fazendo %3',
    args0: [
      { type: 'field_input', name: 'PARAM', text: 'resolve' },
      { type: 'input_dummy' },
      { type: 'input_statement', name: 'DO', check: 'JSStmt' },
    ],
    output: 'JSValue',
    colour: C,
    tooltip:
      'Cria uma tarefa que avisa quando terminou. Dentro dela, chame a função de aviso quando tudo estiver pronto.',
  },
  {
    type: 'sz_val_promise_all',
    message0: 'esperar todas as promessas de %1',
    args0: [{ type: 'input_value', name: 'LIST', check: 'JSValue' }],
    inputsInline: true,
    output: 'JSValue',
    colour: C,
    tooltip: 'Espera todas as tarefas de uma lista terminarem.',
  },
  {
    type: 'sz_js_storage_set',
    placement: 'command',
    message0: 'guardar em %1 a chave %2 com o valor %3',
    args0: [
      {
        type: 'field_dropdown',
        name: 'STORE',
        options: [
          ['permanente (fica entre visitas)', 'local'],
          ['só nesta sessão (zera ao fechar)', 'session'],
        ],
      },
      { type: 'field_input', name: 'KEY', text: 'nome' },
      { type: 'input_value', name: 'VALUE', check: 'JSValue' },
    ],
    inputsInline: true,
    previousStatement: 'JSStmt',
    nextStatement: 'JSStmt',
    colour: C,
    tooltip:
      'Salva um valor no navegador. O permanente fica salvo entre visitas; o da sessão só vale nesta aba.',
  },
  {
    type: 'sz_js_fetch_json',
    placement: 'command',
    message0: 'buscar JSON da URL %1',
    args0: [{ type: 'field_input', name: 'URL', text: 'https://api.exemplo.com/dados' }],
    message1: 'quando chegar, guardar em %1 e fazer %2',
    args1: [
      { type: 'field_input', name: 'OK', text: 'dados' },
      { type: 'input_statement', name: 'BODY' },
    ],
    message2: 'se der erro, guardar em %1 e fazer %2',
    args2: [
      { type: 'field_input', name: 'ERR', text: 'erro' },
      { type: 'input_statement', name: 'CATCH' },
    ],
    previousStatement: 'JSStmt',
    nextStatement: 'JSStmt',
    colour: C,
    tooltip:
      'Busca dados de uma URL e converte para JSON. Os dados ficam na variável "quando chegar"; um erro fica na variável "se der erro". Precisa de permissão de rede no preview (o professor libera a origem).',
  },
]

/**
 * Sub-categorias da LINGUAGEM JavaScript (à la Scratch/MakeCode): cada grupo tem
 * ÍCONE e uma cor da FAMÍLIA do JS (tons de amarelo/âmbar/ouro), preservando a
 * identidade "JS é amarelo". Cada bloco herda a cor do grupo. (Não há grupo de
 * "Texto" porque os valores de texto vivem na categoria "Valores".)
 */
export const JS_GROUPS: { name: string; colour: string; types: string[] }[] = [
  {
    name: '🏷️ Variáveis',
    colour: '#f5a623',
    types: [
      'sz_js_var_declare',
      'sz_js_var_create',
      'sz_js_const_create',
      'sz_js_var_assign',
      'sz_js_var_increment',
    ],
  },
  {
    name: '❓ Lógica & Se',
    colour: '#f7c948',
    types: ['sz_js_if_else', 'sz_js_switch', 'sz_js_case', 'sz_js_try_catch', 'sz_js_throw'],
  },
  {
    name: '🔁 Repetições',
    colour: '#f0b016',
    types: [
      'sz_js_repeat',
      'sz_js_while',
      'sz_js_do_while',
      'sz_js_break',
      'sz_js_continue',
      'sz_js_for_of',
      'sz_js_for_range',
      'sz_js_for_each',
      'sz_js_set_timeout',
      'sz_js_set_interval',
      'sz_js_set_timeout_seconds',
      'sz_js_set_interval_seconds',
    ],
  },
  {
    name: '📋 Listas',
    colour: '#dd9a0a',
    types: ['sz_js_array_push', 'sz_js_array_remove', 'sz_js_array_splice'],
  },
  {
    name: '🖥️ Console & Avisos',
    colour: '#f5c33a',
    types: [
      'sz_js_console_log_text',
      'sz_js_console_log_var',
      'sz_js_console_log_value',
      'sz_js_alert_text',
      'sz_js_alert_var',
    ],
  },
  { name: '💾 Dados & Web', colour: '#b9820a', types: ['sz_js_storage_set', 'sz_js_fetch_json'] },
  {
    name: '⏳ Assíncrono',
    colour: '#a67608',
    types: ['sz_js_await', 'sz_val_new_promise', 'sz_val_promise_all', 'sz_js_set_timeout_call'],
  },
]

// IDENTIDADE: cada sub-grupo recebe um TOM do ÂMBAR da Programação, derivado
// claro→escuro (categoryShades) — os literais em JS_GROUPS são placeholders.
const JS_SHADES = categoryShades(CATEGORY_COLORS.js, JS_GROUPS.length)
JS_GROUPS.forEach((g, i) => {
  g.colour = JS_SHADES[i] ?? CATEGORY_COLORS.js
})
const JS_COLOUR_BY_TYPE = new Map<string, string>(
  JS_GROUPS.flatMap((g) => g.types.map((t) => [t, g.colour] as const)),
)
for (const b of JS_BLOCKS) {
  const colour = JS_COLOUR_BY_TYPE.get(b.type)
  if (colour) b.colour = colour
}
