import { CATEGORY_COLORS } from '../theme'
import type { BlockDefinition } from './types'

const C = CATEGORY_COLORS.js

export const JS_BLOCKS: BlockDefinition[] = [
  {
    type: 'sz_js_on_click',
    message0: 'Quando clicarem (click) %1 %2',
    args0: [
      {
        type: 'field_dropdown',
        name: 'TARGET_KIND',
        options: [
          ['no elemento id', 'id'],
          ['na variável', 'var'],
        ],
      },
      { type: 'field_input', name: 'TARGET', text: 'meuBotao' },
    ],
    message1: 'fazer %1',
    args1: [{ type: 'input_statement', name: 'DO' }],
    previousStatement: 'JSStmt',
    nextStatement: 'JSStmt',
    colour: C,
  },
  {
    type: 'sz_js_on_click_anywhere',
    message0: 'Quando clicarem em qualquer lugar da tela',
    message1: 'fazer %1',
    args1: [{ type: 'input_statement', name: 'DO' }],
    previousStatement: 'JSStmt',
    nextStatement: 'JSStmt',
    colour: C,
    tooltip:
      'Reage a um clique em qualquer parte da página (document). Use "posição do clique" para saber onde clicaram.',
  },
  {
    type: 'sz_js_array_push',
    message0: 'na lista %1 adicionar %2',
    args0: [
      { type: 'field_input', name: 'NAME', text: 'lista' },
      { type: 'input_value', name: 'VALUE', check: 'JSValue' },
    ],
    inputsInline: true,
    previousStatement: 'JSStmt',
    nextStatement: 'JSStmt',
    colour: C,
    tooltip: 'Acrescenta um valor ao fim da lista (arr.push(valor)).',
  },
  {
    type: 'sz_js_array_remove',
    message0: 'na lista %1 remover o %2',
    args0: [
      { type: 'field_input', name: 'NAME', text: 'lista' },
      {
        type: 'field_dropdown',
        name: 'END',
        options: [
          ['último', 'pop'],
          ['primeiro', 'shift'],
        ],
      },
    ],
    inputsInline: true,
    previousStatement: 'JSStmt',
    nextStatement: 'JSStmt',
    colour: C,
    tooltip: 'Remove o último (pop) ou o primeiro (shift) item da lista.',
  },
  {
    type: 'sz_js_array_splice',
    message0: 'na lista %1 remover %2 item(ns) a partir da posição %3',
    args0: [
      { type: 'field_input', name: 'NAME', text: 'lista' },
      { type: 'input_value', name: 'COUNT', check: 'JSValue' },
      { type: 'input_value', name: 'START', check: 'JSValue' },
    ],
    inputsInline: true,
    previousStatement: 'JSStmt',
    nextStatement: 'JSStmt',
    colour: C,
    tooltip:
      'Remove uma quantidade de itens da lista a partir de uma posição (arr.splice(início, qtd)).',
  },
  {
    type: 'sz_js_console_log_text',
    message0: 'Mostrar texto no console (console.log) %1',
    args0: [{ type: 'field_input', name: 'VALUE', text: 'Olá' }],
    previousStatement: 'JSStmt',
    nextStatement: 'JSStmt',
    colour: C,
  },
  {
    type: 'sz_js_console_log_var',
    message0: 'Mostrar valor da variável %1 no console (console.log)',
    args0: [{ type: 'field_input', name: 'NAME', text: 'contador' }],
    previousStatement: 'JSStmt',
    nextStatement: 'JSStmt',
    colour: C,
  },
  {
    type: 'sz_js_alert_text',
    message0: 'Mostrar aviso (alert) com texto %1',
    args0: [{ type: 'field_input', name: 'VALUE', text: 'Olá!' }],
    previousStatement: 'JSStmt',
    nextStatement: 'JSStmt',
    colour: C,
    tooltip: 'Mostra uma janelinha de aviso na tela (alert).',
  },
  {
    type: 'sz_js_alert_var',
    message0: 'Mostrar aviso (alert) com valor da variável %1',
    args0: [{ type: 'field_input', name: 'NAME', text: 'contador' }],
    previousStatement: 'JSStmt',
    nextStatement: 'JSStmt',
    colour: C,
    tooltip: 'Mostra uma janelinha de aviso com o valor de uma variável (alert).',
  },
  {
    // Legado: substituído por sz_js_set_property_text. Mantido (oculto da
    // paleta) para que projetos antigos salvos com este bloco ainda carreguem.
    type: 'sz_js_set_text',
    message0: 'Alterar texto (textContent) do elemento id %1 para %2',
    args0: [
      { type: 'field_input', name: 'TARGET', text: 'saida' },
      { type: 'field_input', name: 'VALUE', text: 'Novo texto' },
    ],
    previousStatement: 'JSStmt',
    nextStatement: 'JSStmt',
    colour: C,
    hidden: true,
  },
  {
    type: 'sz_js_set_property_text',
    message0: 'Alterar %1 %2 %3 para %4',
    args0: [
      {
        type: 'field_dropdown',
        name: 'PROP',
        options: [
          ['o texto (textContent)', 'textContent'],
          ['o valor (value)', 'value'],
          ['o conteúdo HTML (innerHTML)', 'innerHTML'],
        ],
      },
      {
        type: 'field_dropdown',
        name: 'TARGET_KIND',
        options: [
          ['do elemento id', 'id'],
          ['da variável', 'var'],
        ],
      },
      { type: 'field_input', name: 'TARGET', text: 'saida' },
      { type: 'field_input', name: 'VALUE', text: 'Novo texto' },
    ],
    previousStatement: 'JSStmt',
    nextStatement: 'JSStmt',
    colour: C,
    tooltip:
      'Escreve um texto fixo numa propriedade de um elemento (por id) ou da variável que o guarda.',
  },
  {
    type: 'sz_js_set_property_var',
    message0: 'Alterar %1 %2 %3 para o valor da variável %4',
    args0: [
      {
        type: 'field_dropdown',
        name: 'PROP',
        options: [
          ['o texto (textContent)', 'textContent'],
          ['o valor (value)', 'value'],
          ['o conteúdo HTML (innerHTML)', 'innerHTML'],
        ],
      },
      {
        type: 'field_dropdown',
        name: 'TARGET_KIND',
        options: [
          ['do elemento id', 'id'],
          ['da variável', 'var'],
        ],
      },
      { type: 'field_input', name: 'TARGET', text: 'saida' },
      { type: 'field_input', name: 'NAME', text: 'conteudo' },
    ],
    previousStatement: 'JSStmt',
    nextStatement: 'JSStmt',
    colour: C,
    tooltip: 'Escreve o valor de uma variável numa propriedade do elemento (por id ou variável).',
  },
  {
    type: 'sz_js_set_property_calc',
    message0: 'Alterar %1 %2 %3 para %4',
    args0: [
      {
        type: 'field_dropdown',
        name: 'PROP',
        options: [
          ['o texto (textContent)', 'textContent'],
          ['o valor (value)', 'value'],
          ['o conteúdo HTML (innerHTML)', 'innerHTML'],
        ],
      },
      {
        type: 'field_dropdown',
        name: 'TARGET_KIND',
        options: [
          ['do elemento id', 'id'],
          ['da variável', 'var'],
        ],
      },
      { type: 'field_input', name: 'TARGET', text: 'saida' },
      {
        type: 'field_dropdown',
        name: 'CALC',
        options: [
          ['o ano atual (new Date().getFullYear())', 'year'],
          ['a data de hoje (toLocaleDateString)', 'date'],
          ['a hora agora (toLocaleTimeString)', 'time'],
        ],
      },
    ],
    previousStatement: 'JSStmt',
    nextStatement: 'JSStmt',
    colour: C,
    tooltip:
      'Escreve um valor calculado da data/hora (ano atual, data de hoje ou hora) numa propriedade do elemento.',
  },
  {
    type: 'sz_js_set_property',
    message0: 'alterar %1 %2 %3 para o valor %4',
    args0: [
      {
        type: 'field_dropdown',
        name: 'PROP',
        options: [
          ['o texto (textContent)', 'textContent'],
          ['o valor (value)', 'value'],
          ['o conteúdo HTML (innerHTML)', 'innerHTML'],
        ],
      },
      {
        type: 'field_dropdown',
        name: 'TARGET_KIND',
        options: [
          ['do elemento id', 'id'],
          ['da variável', 'var'],
        ],
      },
      { type: 'field_input', name: 'TARGET', text: 'saida' },
      { type: 'input_value', name: 'VALUE', check: 'JSValue' },
    ],
    inputsInline: true,
    previousStatement: 'JSStmt',
    nextStatement: 'JSStmt',
    colour: C,
    tooltip:
      'Escreve uma propriedade do elemento com qualquer valor (texto montado, conta, etc.). Use "juntar texto" para montar HTML.',
  },
  {
    type: 'sz_js_get_property',
    message0: 'Pegar %1 %2 %3 e guardar em %4',
    args0: [
      {
        type: 'field_dropdown',
        name: 'PROP',
        options: [
          ['o texto (textContent)', 'textContent'],
          ['o valor (value)', 'value'],
          ['o conteúdo HTML (innerHTML)', 'innerHTML'],
        ],
      },
      {
        type: 'field_dropdown',
        name: 'TARGET_KIND',
        options: [
          ['do elemento id', 'id'],
          ['da variável', 'var'],
        ],
      },
      { type: 'field_input', name: 'TARGET', text: 'saida' },
      { type: 'field_input', name: 'NAME', text: 'conteudo' },
    ],
    previousStatement: 'JSStmt',
    nextStatement: 'JSStmt',
    colour: C,
    tooltip:
      'Lê uma propriedade (o texto ou o valor digitado) de um elemento por id ou variável e guarda numa variável.',
  },
  {
    type: 'sz_js_var_declare',
    message0: 'declarar variável %1',
    args0: [{ type: 'field_input', name: 'NAME', text: 'x' }],
    previousStatement: 'JSStmt',
    nextStatement: 'JSStmt',
    colour: C,
    tooltip: 'Declara uma variável (let) sem valor inicial — gera `let x;`.',
  },
  {
    type: 'sz_js_var_create',
    message0: 'Criar variável %1 com valor %2',
    args0: [
      { type: 'field_input', name: 'NAME', text: 'contador' },
      { type: 'input_value', name: 'VALUE', check: 'JSValue' },
    ],
    inputsInline: true,
    previousStatement: 'JSStmt',
    nextStatement: 'JSStmt',
    colour: C,
    tooltip: 'Cria uma variável (let) e guarda nela um valor — número, conta, aleatório, etc.',
  },
  {
    type: 'sz_js_const_create',
    message0: 'Criar constante %1 com valor %2',
    args0: [
      { type: 'field_input', name: 'NAME', text: 'PI' },
      { type: 'input_value', name: 'VALUE', check: 'JSValue' },
    ],
    inputsInline: true,
    previousStatement: 'JSStmt',
    nextStatement: 'JSStmt',
    colour: C,
    tooltip: 'Cria uma constante (const): um valor que não muda depois de criado.',
  },
  {
    type: 'sz_js_var_assign',
    message0: 'Alterar variável %1 para %2',
    args0: [
      { type: 'field_input', name: 'NAME', text: 'contador' },
      { type: 'input_value', name: 'VALUE', check: 'JSValue' },
    ],
    inputsInline: true,
    previousStatement: 'JSStmt',
    nextStatement: 'JSStmt',
    colour: C,
    tooltip: 'Muda o valor de uma variável que já existe.',
  },
  {
    type: 'sz_js_var_increment',
    message0: 'Somar %1 em variável %2',
    args0: [
      { type: 'field_number', name: 'DELTA', value: 1 },
      { type: 'field_input', name: 'NAME', text: 'contador' },
    ],
    previousStatement: 'JSStmt',
    nextStatement: 'JSStmt',
    colour: C,
  },
  {
    type: 'sz_js_if_else',
    message0: 'Se (if) %1',
    args0: [{ type: 'input_value', name: 'COND', check: 'JSValue' }],
    message1: 'então %1',
    args1: [{ type: 'input_statement', name: 'THEN' }],
    message2: 'senão %1',
    args2: [{ type: 'input_statement', name: 'ELSE' }],
    inputsInline: true,
    previousStatement: 'JSStmt',
    nextStatement: 'JSStmt',
    colour: C,
    tooltip: 'Executa o "então" quando a condição for verdadeira; senão, o "senão".',
  },
  {
    type: 'sz_js_repeat',
    message0: 'Repetir (for) %1 vezes',
    args0: [{ type: 'field_number', name: 'TIMES', value: 5, min: 0 }],
    message1: 'fazer %1',
    args1: [{ type: 'input_statement', name: 'DO' }],
    previousStatement: 'JSStmt',
    nextStatement: 'JSStmt',
    colour: C,
  },
  {
    type: 'sz_js_for_each',
    message0: 'para cada item %1 (posição %2) na lista %3',
    args0: [
      { type: 'field_input', name: 'ITEM', text: 'item' },
      { type: 'field_input', name: 'INDEX', text: '' },
      { type: 'field_input', name: 'NAME', text: 'lista' },
    ],
    message1: 'fazer %1',
    args1: [{ type: 'input_statement', name: 'DO' }],
    inputsInline: true,
    previousStatement: 'JSStmt',
    nextStatement: 'JSStmt',
    colour: C,
    tooltip:
      'Repete o "fazer" para cada item da lista (arr.forEach). Deixe a posição em branco se não precisar dela.',
  },
  {
    type: 'sz_js_set_timeout',
    message0: 'depois de %1 ms',
    args0: [{ type: 'input_value', name: 'MS', check: 'JSValue' }],
    message1: 'fazer %1',
    args1: [{ type: 'input_statement', name: 'DO' }],
    inputsInline: true,
    previousStatement: 'JSStmt',
    nextStatement: 'JSStmt',
    colour: C,
    tooltip: 'Espera um tempo (em milissegundos) e então executa o "fazer" (setTimeout).',
  },
  {
    type: 'sz_js_set_interval',
    message0: 'repetir a cada %1 ms',
    args0: [{ type: 'input_value', name: 'MS', check: 'JSValue' }],
    message1: 'fazer %1',
    args1: [{ type: 'input_statement', name: 'DO' }],
    inputsInline: true,
    previousStatement: 'JSStmt',
    nextStatement: 'JSStmt',
    colour: C,
    tooltip: 'Repete o "fazer" a cada intervalo de tempo em milissegundos (setInterval).',
  },
  // ---- DOM extras (Fase 2.3) ----
  {
    type: 'sz_js_on_mouseover',
    message0: 'Quando o mouse passar (mouseover) %1 %2',
    args0: [
      {
        type: 'field_dropdown',
        name: 'TARGET_KIND',
        options: [
          ['sobre o elemento id', 'id'],
          ['sobre a variável', 'var'],
        ],
      },
      { type: 'field_input', name: 'TARGET', text: 'meuElemento' },
    ],
    message1: 'fazer %1',
    args1: [{ type: 'input_statement', name: 'DO' }],
    previousStatement: 'JSStmt',
    nextStatement: 'JSStmt',
    colour: C,
  },
  {
    type: 'sz_js_on_submit',
    message0: 'Quando enviar (submit) %1 %2',
    args0: [
      {
        type: 'field_dropdown',
        name: 'TARGET_KIND',
        options: [
          ['o formulário id', 'id'],
          ['a variável', 'var'],
        ],
      },
      { type: 'field_input', name: 'TARGET', text: 'meuForm' },
    ],
    message1: 'fazer %1',
    args1: [{ type: 'input_statement', name: 'DO' }],
    previousStatement: 'JSStmt',
    nextStatement: 'JSStmt',
    colour: C,
  },
  {
    type: 'sz_js_on_input',
    message0: 'Quando digitar (input) %1 %2',
    args0: [
      {
        type: 'field_dropdown',
        name: 'TARGET_KIND',
        options: [
          ['no elemento id', 'id'],
          ['na variável', 'var'],
        ],
      },
      { type: 'field_input', name: 'TARGET', text: 'meuInput' },
    ],
    message1: 'fazer %1',
    args1: [{ type: 'input_statement', name: 'DO' }],
    previousStatement: 'JSStmt',
    nextStatement: 'JSStmt',
    colour: C,
  },
  {
    type: 'sz_js_query_selector',
    message0: 'Pegar elemento (querySelector) via seletor %1 e guardar em %2',
    args0: [
      { type: 'field_input', name: 'SELECTOR', text: '#caixa' },
      { type: 'field_input', name: 'NAME', text: 'caixa' },
    ],
    previousStatement: 'JSStmt',
    nextStatement: 'JSStmt',
    colour: C,
  },
  {
    type: 'sz_js_get_element_by_id',
    message0: 'Pegar elemento (getElementById) id %1 e guardar em %2',
    args0: [
      { type: 'field_input', name: 'ID', text: 'meuBotao' },
      { type: 'field_input', name: 'NAME', text: 'meuBotao' },
    ],
    previousStatement: 'JSStmt',
    nextStatement: 'JSStmt',
    colour: C,
    tooltip: 'Guarda o elemento de um id numa variável (document.getElementById).',
  },
  {
    type: 'sz_js_on_event_named',
    message0: 'quando %1 em %2 %3 chamar a função %4',
    args0: [
      {
        type: 'field_dropdown',
        name: 'EVENT',
        options: [
          ['clicar (click)', 'click'],
          ['passar o mouse (mouseover)', 'mouseover'],
          ['tirar o mouse (mouseout)', 'mouseout'],
          ['enviar (submit)', 'submit'],
          ['digitar (input)', 'input'],
          ['mudar (change)', 'change'],
          ['apertar tecla (keydown)', 'keydown'],
          ['soltar tecla (keyup)', 'keyup'],
        ],
      },
      {
        type: 'field_dropdown',
        name: 'TARGET_KIND',
        options: [
          ['o elemento id', 'id'],
          ['a variável', 'var'],
        ],
      },
      { type: 'field_input', name: 'TARGET', text: 'meuBotao' },
      { type: 'field_input', name: 'HANDLER', text: 'fazerAlgo' },
    ],
    inputsInline: true,
    previousStatement: 'JSStmt',
    nextStatement: 'JSStmt',
    colour: C,
    tooltip:
      'Liga um evento a uma função já criada (el.addEventListener("click", funcao)). Dentro da função, "elemento atual (this)" é o elemento que disparou.',
  },
  {
    type: 'sz_js_create_element',
    message0: 'criar elemento %1 e guardar em %2',
    args0: [
      { type: 'field_input', name: 'TAG', text: 'div' },
      { type: 'field_input', name: 'NAME', text: 'elemento' },
    ],
    inputsInline: true,
    previousStatement: 'JSStmt',
    nextStatement: 'JSStmt',
    colour: C,
    tooltip:
      'Cria um novo elemento HTML em memória e guarda numa variável (document.createElement).',
  },
  {
    type: 'sz_js_append_child',
    message0: 'dentro de %1 adicionar %2',
    args0: [
      { type: 'field_input', name: 'PARENT', text: 'pai' },
      { type: 'field_input', name: 'CHILD', text: 'filho' },
    ],
    inputsInline: true,
    previousStatement: 'JSStmt',
    nextStatement: 'JSStmt',
    colour: C,
    tooltip: 'Coloca um elemento dentro de outro (pai.appendChild(filho)).',
  },
  {
    type: 'sz_js_set_dataset',
    message0: 'no elemento %1 %2 guardar no dado %3 o valor %4',
    args0: [
      {
        type: 'field_dropdown',
        name: 'TARGET_KIND',
        options: [
          ['id', 'id'],
          ['variável', 'var'],
        ],
      },
      { type: 'field_input', name: 'TARGET', text: 'elemento' },
      { type: 'field_input', name: 'KEY', text: 'chave' },
      { type: 'input_value', name: 'VALUE', check: 'JSValue' },
    ],
    inputsInline: true,
    previousStatement: 'JSStmt',
    nextStatement: 'JSStmt',
    colour: C,
    tooltip: 'Guarda um valor num data-attribute do elemento (el.dataset.chave = valor).',
  },
  {
    type: 'sz_js_class_op',
    message0: '%1 classe (classList) %2 %3 %4',
    args0: [
      {
        type: 'field_dropdown',
        name: 'OP',
        options: [
          ['adicionar', 'add'],
          ['remover', 'remove'],
          ['alternar', 'toggle'],
        ],
      },
      { type: 'field_input', name: 'CLASS', text: 'ativo' },
      {
        type: 'field_dropdown',
        name: 'TARGET_KIND',
        options: [
          ['no elemento id', 'id'],
          ['na variável', 'var'],
          ['no elemento atual (this)', 'this'],
        ],
      },
      { type: 'field_input', name: 'TARGET', text: 'meuElemento' },
    ],
    previousStatement: 'JSStmt',
    nextStatement: 'JSStmt',
    colour: C,
  },
]
