/** Reproducible IR for the three versions. Run with --check to detect source drift. */
import { readFileSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'
import { SNOW_DESCRIPTION, snowDescentSource } from '../src/examples/snowDescentSource'
import { normalizeSZIR, SZIRV2Schema } from '../src/ir'
import { parseJS } from '../src/parsers/js'

function stripIds(value: unknown): unknown {
  if (Array.isArray(value)) return value.map(stripIds)
  if (!value || typeof value !== 'object') return value
  return Object.fromEntries(
    Object.entries(value)
      .filter(([key]) => key !== '__id')
      .map(([key, child]) => [key, stripIds(child)]),
  )
}
function assertStructured(value: unknown): void {
  if (!value || typeof value !== 'object') return
  const record = value as Record<string, unknown>
  if (['rawJS', 'rawHTML', 'rawCSS', 'memberCall'].includes(String(record.type)))
    throw new Error(`Unstructured example: ${JSON.stringify(record)}`)
  for (const child of Object.values(record)) assertStructured(child)
}
for (const variant of ['canvas', 'g2d', 'gk'] as const) {
  const ir = SZIRV2Schema.parse(
    normalizeSZIR({
      html:
        variant === 'canvas'
          ? [
              {
                type: 'canvas',
                id: 'neve',
                width: 640,
                height: 720,
                attrs: { tabindex: '0', 'aria-label': SNOW_DESCRIPTION },
              },
            ]
          : [],
      css:
        variant === 'gk'
          ? []
          : [
              {
                selector: 'body',
                declarations: {
                  margin: '0',
                  background: '#102d46',
                  display: 'grid',
                  'place-items': 'center',
                  'min-height': '100dvh',
                  overflow: 'hidden',
                },
              },
              {
                selector: 'canvas',
                declarations: {
                  width: 'min(100vw, 88.8889dvh)',
                  height: 'auto',
                  display: 'block',
                  'touch-action': 'none',
                },
              },
            ],
      js: parseJS(snowDescentSource(variant)),
      extensions:
        variant === 'canvas'
          ? []
          : [{ extensionId: variant === 'g2d' ? 'game-2d' : 'game-2d-advanced' }],
    }),
  )
  assertStructured(ir)
  const target = join(import.meta.dir, `../src/examples/__gen_snowDescent_${variant}.ts`)
  const body = `// Generated by scripts/gen-snow-descent.ts. Do not edit.\nimport type { SZIRV2 } from '../ir'\nexport const SNOW_IR = ${JSON.stringify(stripIds(ir), null, 2)} as SZIRV2\n`
  if (process.argv.includes('--check')) {
    const current = await import(target)
    if (JSON.stringify(stripIds(current.SNOW_IR)) !== JSON.stringify(stripIds(ir)))
      throw new Error(`Snow ${variant} drift; run gen:snow-descent`)
  } else {
    writeFileSync(target, body)
    const result = Bun.spawnSync([process.execPath, 'x', 'biome', 'format', '--write', target])
    if (result.exitCode !== 0) throw new Error(result.stderr.toString())
    if (!readFileSync(target, 'utf8').includes('SNOW_IR')) throw new Error('Generation failed')
  }
  console.log(`snow ${variant}: structured IR verified`)
}
