import type { BlockDefinition } from '../../blockly/blocks/types'
import {
  GAME_TWO_D_BLOCK_COLOR as C,
  GAME_TWO_D_EVENT_COLOR as EVENT_C,
} from './blockCatalogShared'

import { GAME_TWO_D_PERIODIC_TOOLTIPS } from './pedagogy'

export const gameTwoDGroupAndHudBlocks = [
  // ---- Grupos de sprites: MUITOS sprites (v0.6.0) ----
  {
    type: 'sz_g2d_create_group',
    placement: 'start-only-command',
    message0: 'Criar grupo de sprites %1',
    args0: [{ type: 'field_input', name: 'NAME', text: 'asteroides' }],
    previousStatement: 'JSStmt',
    nextStatement: 'JSStmt',
    colour: C,
    tooltip:
      'Cria um grupo vazio para guardar MUITOS sprites do mesmo tipo (tiros, inimigos, estrelas).',
  },
  {
    type: 'sz_g2d_spawn_in_group',
    placement: 'command',
    message0:
      'No grupo %1 criar um sprite chamado %2 em x %3 y %4 largura %5 altura %6 cor %7 com vx %8 vy %9',
    args0: [
      { type: 'field_name_picker', name: 'GROUP', text: 'asteroides', kind: 'group' },
      // Nome OPCIONAL do sprite recém-criado (vazio = sem nome, como antes): dá
      // uma "alça" para os blocos seguintes (animar, dar vida, virar…). Campo
      // que DECLARA um nome segue `field_input`, nunca seletor.
      { type: 'field_input', name: 'NAME', text: '' },
      { type: 'input_value', name: 'X', check: 'JSValue' },
      { type: 'input_value', name: 'Y', check: 'JSValue' },
      { type: 'input_value', name: 'W', check: 'JSValue' },
      { type: 'input_value', name: 'H', check: 'JSValue' },
      { type: 'field_colour_sz', name: 'COLOR', colour: '#9ca3af' },
      { type: 'input_value', name: 'VX', check: 'JSValue' },
      { type: 'input_value', name: 'VY', check: 'JSValue' },
    ],
    inputsInline: true,
    previousStatement: 'JSStmt',
    nextStatement: 'JSStmt',
    colour: C,
    tooltip:
      'Cria um sprite colorido e coloca no grupo. Use x/y com "número aleatório" para nascer em lugares diferentes; vx/vy dão a velocidade. O nome é opcional: preencha quando quiser fazer algo com esse sprite logo depois (animar, dar vida…).',
  },
  {
    type: 'sz_g2d_spawn_image_in_group',
    placement: 'command',
    message0:
      'No grupo %1 criar um sprite chamado %2 em x %3 y %4 largura %5 altura %6 com imagem %7 vx %8 vy %9',
    args0: [
      { type: 'field_name_picker', name: 'GROUP', text: 'inimigos', kind: 'group' },
      // Nome OPCIONAL — ver o gêmeo colorido acima.
      { type: 'field_input', name: 'NAME', text: '' },
      { type: 'input_value', name: 'X', check: 'JSValue' },
      { type: 'input_value', name: 'Y', check: 'JSValue' },
      { type: 'input_value', name: 'W', check: 'JSValue' },
      { type: 'input_value', name: 'H', check: 'JSValue' },
      { type: 'field_asset_picker', name: 'IMAGE', text: 'inimigo' },
      { type: 'input_value', name: 'VX', check: 'JSValue' },
      { type: 'input_value', name: 'VY', check: 'JSValue' },
    ],
    inputsInline: true,
    previousStatement: 'JSStmt',
    nextStatement: 'JSStmt',
    colour: C,
    tooltip:
      'Como "criar no grupo", mas o sprite mostra uma imagem da sua biblioteca (use o nome do asset). O nome é opcional: preencha quando quiser animar ou mexer nesse sprite logo depois.',
  },
  {
    type: 'sz_g2d_update_group',
    placement: 'command',
    message0: 'Atualizar (mover) o grupo %1',
    args0: [{ type: 'field_name_picker', name: 'GROUP', text: 'asteroides', kind: 'group' }],
    previousStatement: 'JSStmt',
    nextStatement: 'JSStmt',
    colour: C,
    tooltip: 'Move cada sprite do grupo pela sua velocidade (vx/vy). Use a cada quadro.',
  },
  {
    type: 'sz_g2d_apply_gravity_group',
    placement: 'command',
    message0: 'Aplicar a gravidade do mundo aos sprites do grupo %1',
    args0: [{ type: 'field_name_picker', name: 'GROUP', text: 'inimigos', kind: 'group' }],
    previousStatement: 'JSStmt',
    nextStatement: 'JSStmt',
    colour: C,
    tooltip:
      'Soma a gravidade do mundo à velocidade vertical de cada sprite do grupo neste quadro. Use antes de atualizar o grupo.',
  },
  {
    type: 'sz_g2d_draw_group',
    placement: 'command',
    message0: 'Desenhar o grupo %1',
    args0: [{ type: 'field_name_picker', name: 'GROUP', text: 'asteroides', kind: 'group' }],
    previousStatement: 'JSStmt',
    nextStatement: 'JSStmt',
    colour: C,
    tooltip: 'Desenha todos os sprites do grupo. Use a cada quadro, depois de mover.',
  },
  {
    type: 'sz_g2d_draw_group_by_y',
    placement: 'command',
    message0: 'Desenhar o grupo %1 ordenado pela base',
    args0: [{ type: 'field_name_picker', name: 'GROUP', text: 'cenario', kind: 'group' }],
    previousStatement: 'JSStmt',
    nextStatement: 'JSStmt',
    colour: C,
    tooltip:
      'Desenha o grupo do fundo para a frente: quem tem a BASE (o pé) mais para baixo na tela aparece na frente. É a profundidade dos jogos vistos de cima (o herói passa ATRÁS da árvore).',
  },
  {
    type: 'sz_g2d_for_each_in_group',
    placement: 'command',
    bodyExecution: 'sync-callback',
    message0: 'Para cada sprite %1 do grupo %2',
    args0: [
      { type: 'field_input', name: 'ITEM', text: 'sprite' },
      { type: 'field_name_picker', name: 'GROUP', text: 'asteroides', kind: 'group' },
    ],
    message1: 'fazer %1',
    args1: [{ type: 'input_statement', name: 'BODY' }],
    inputsInline: true,
    previousStatement: 'JSStmt',
    nextStatement: 'JSStmt',
    colour: C,
    tooltip:
      'Roda o que está dentro para cada sprite do grupo (o sprite da vez fica no nome que você escolher).',
  },
  {
    type: 'sz_g2d_count_group',
    message0: 'quantos sprites tem no grupo %1',
    args0: [{ type: 'field_name_picker', name: 'GROUP', text: 'asteroides', kind: 'group' }],
    output: 'JSValue',
    colour: C,
    tooltip: 'Quantidade de sprites no grupo agora. Use dentro de um "se" ou numa conta.',
  },
  {
    type: 'sz_g2d_clear_group',
    placement: 'command',
    message0: 'Esvaziar o grupo %1',
    args0: [{ type: 'field_name_picker', name: 'GROUP', text: 'asteroides', kind: 'group' }],
    previousStatement: 'JSStmt',
    nextStatement: 'JSStmt',
    colour: C,
    tooltip: 'Tira todos os sprites do grupo de uma vez (ex.: ao reiniciar a fase).',
  },
  {
    type: 'sz_g2d_prune_offscreen',
    placement: 'command',
    bodyExecution: 'sync-callback',
    message0: 'Tirar do grupo %1 quem sair da tela, para cada um (chamado %2)',
    args0: [
      { type: 'field_name_picker', name: 'GROUP', text: 'asteroides', kind: 'group' },
      { type: 'field_input', name: 'ITEM', text: 'sprite' },
    ],
    message1: 'fazer %1',
    args1: [{ type: 'input_statement', name: 'BODY' }],
    inputsInline: true,
    previousStatement: 'JSStmt',
    nextStatement: 'JSStmt',
    colour: C,
    tooltip:
      'Remove do grupo os sprites que saíram da tela e roda o "fazer" para cada um (ex.: perder uma vida quando um asteroide escapa). Só tira quem já foi embora de verdade: o que nasce fora da tela e ainda está vindo continua no jogo.',
  },
  {
    type: 'sz_g2d_add_to_group',
    placement: 'command',
    message0: 'Pôr o sprite %1 no grupo %2',
    args0: [
      { type: 'field_sprite_picker', name: 'SPRITE', text: 'heroi' },
      { type: 'field_name_picker', name: 'GROUP', text: 'inimigos', kind: 'group' },
    ],
    previousStatement: 'JSStmt',
    nextStatement: 'JSStmt',
    colour: C,
    tooltip:
      'Põe um sprite que já existe dentro do grupo. A partir daí, tudo que o grupo faz (atualizar, desenhar, colisões) vale para ele também. Repetido não entra duas vezes.',
  },
  {
    type: 'sz_g2d_remove_from_group',
    placement: 'command',
    message0: 'Tirar o sprite %1 do grupo %2',
    args0: [
      { type: 'field_sprite_picker', name: 'SPRITE', text: 'asteroide' },
      { type: 'field_name_picker', name: 'GROUP', text: 'asteroides', kind: 'group' },
    ],
    previousStatement: 'JSStmt',
    nextStatement: 'JSStmt',
    colour: C,
    tooltip:
      'Tira um sprite do grupo (ex.: o asteroide que foi atingido). Use o nome do sprite da vez.',
  },

  // ---- Colisão de grupo + temporizadores (hats/eventos) ----
  {
    type: 'sz_g2d_on_group_overlap',
    placement: 'loop-command',
    bodyExecution: 'sync-callback',
    message0: 'Para cada colisão entre os grupos %1 e %2',
    args0: [
      { type: 'field_name_picker', name: 'A', text: 'tiros', kind: 'group' },
      { type: 'field_name_picker', name: 'B', text: 'asteroides', kind: 'group' },
    ],
    message1: 'chamar os sprites de %1 e %2',
    args1: [
      { type: 'field_input', name: 'ANAME', text: 'tiro' },
      { type: 'field_input', name: 'BNAME', text: 'asteroide' },
    ],
    message2: 'fazer %1',
    args2: [{ type: 'input_statement', name: 'BODY' }],
    inputsInline: true,
    previousStatement: 'JSStmt',
    nextStatement: 'JSStmt',
    colour: EVENT_C,
    tooltip:
      'Para cada par de sprites (um de cada grupo) que se encostam, roda o "fazer" com os dois sprites. Use dentro do "a cada quadro".',
  },
  {
    type: 'sz_g2d_every_frames',
    placement: 'loop-periodic',
    migration: 'lift-periodic-loop',
    message0: 'A cada %1 quadros',
    args0: [{ type: 'input_value', name: 'N', check: 'JSValue' }],
    message1: 'fazer %1',
    args1: [{ type: 'input_statement', name: 'BODY' }],
    inputsInline: true,
    previousStatement: 'JSStmt',
    nextStatement: 'JSStmt',
    colour: EVENT_C,
    tooltip: GAME_TWO_D_PERIODIC_TOOLTIPS.frames,
  },
  {
    type: 'sz_g2d_every_seconds',
    placement: 'loop-periodic',
    migration: 'lift-periodic-loop',
    message0: 'A cada %1 segundos',
    args0: [{ type: 'input_value', name: 'SECS', check: 'JSValue' }],
    message1: 'fazer %1',
    args1: [{ type: 'input_statement', name: 'BODY' }],
    inputsInline: true,
    previousStatement: 'JSStmt',
    nextStatement: 'JSStmt',
    colour: EVENT_C,
    tooltip: GAME_TWO_D_PERIODIC_TOOLTIPS.seconds,
  },
  {
    type: 'sz_g2d_after_seconds',
    placement: 'loop-periodic',
    migration: 'lift-periodic-loop',
    message0: 'Depois de %1 segundos',
    args0: [{ type: 'input_value', name: 'SECS', check: 'JSValue' }],
    message1: 'fazer %1',
    args1: [{ type: 'input_statement', name: 'BODY' }],
    inputsInline: true,
    previousStatement: 'JSStmt',
    nextStatement: 'JSStmt',
    colour: EVENT_C,
    tooltip: GAME_TWO_D_PERIODIC_TOOLTIPS.after,
  },

  // ---- HUD no canvas: placar, texto, vidas e barra (v0.6.0) ----
  {
    type: 'sz_g2d_draw_score',
    placement: 'command',
    message0: 'Mostrar placar %1 valor %2 em x %3 y %4 cor %5 tamanho %6',
    args0: [
      { type: 'field_input', name: 'LABEL', text: 'Pontos:' },
      { type: 'input_value', name: 'VALUE', check: 'JSValue' },
      { type: 'input_value', name: 'X', check: 'JSValue' },
      { type: 'input_value', name: 'Y', check: 'JSValue' },
      { type: 'field_colour_sz', name: 'COLOR', colour: '#ffffff' },
      { type: 'input_value', name: 'SIZE', check: 'JSValue' },
    ],
    inputsInline: true,
    previousStatement: 'JSStmt',
    nextStatement: 'JSStmt',
    colour: C,
    tooltip: 'Escreve "rótulo valor" (ex.: Pontos: 5) na tela. Ligue o valor à variável do placar.',
  },
  {
    type: 'sz_g2d_draw_label',
    placement: 'command',
    message0: 'Escrever %1 em x %2 y %3 cor %4 tamanho %5 alinhado %6',
    args0: [
      { type: 'field_input', name: 'TEXT', text: 'Nave contra Asteroides' },
      { type: 'input_value', name: 'X', check: 'JSValue' },
      { type: 'input_value', name: 'Y', check: 'JSValue' },
      { type: 'field_colour_sz', name: 'COLOR', colour: '#ffffff' },
      { type: 'input_value', name: 'SIZE', check: 'JSValue' },
      {
        type: 'field_dropdown',
        name: 'ALIGN',
        options: [
          ['à esquerda', 'left'],
          ['no centro', 'center'],
          ['à direita', 'right'],
        ],
      },
    ],
    inputsInline: true,
    previousStatement: 'JSStmt',
    nextStatement: 'JSStmt',
    colour: C,
    tooltip: 'Escreve um texto fixo na tela (ex.: um título). Escolha o alinhamento.',
  },
  {
    type: 'sz_g2d_draw_hearts',
    hidden: true,
    placement: 'command',
    message0: 'Desenhar %1 vidas (corações) em x %2 y %3 tamanho %4 cor %5',
    args0: [
      { type: 'input_value', name: 'COUNT', check: 'JSValue' },
      { type: 'input_value', name: 'X', check: 'JSValue' },
      { type: 'input_value', name: 'Y', check: 'JSValue' },
      { type: 'input_value', name: 'SIZE', check: 'JSValue' },
      { type: 'field_colour_sz', name: 'COLOR', colour: '#ff5d5d' },
    ],
    inputsInline: true,
    previousStatement: 'JSStmt',
    nextStatement: 'JSStmt',
    colour: C,
    tooltip: 'Desenha uma fileira de corações (ligue a "quantidade" à variável de vidas).',
  },
  {
    type: 'sz_g2d_draw_bar',
    placement: 'command',
    message0: 'Barra de %1 / %2 em x %3 y %4 largura %5 altura %6 cor %7',
    args0: [
      { type: 'input_value', name: 'VALUE', check: 'JSValue' },
      { type: 'input_value', name: 'MAX', check: 'JSValue' },
      { type: 'input_value', name: 'X', check: 'JSValue' },
      { type: 'input_value', name: 'Y', check: 'JSValue' },
      { type: 'input_value', name: 'W', check: 'JSValue' },
      { type: 'input_value', name: 'H', check: 'JSValue' },
      { type: 'field_colour_sz', name: 'COLOR', colour: '#35e8ff' },
    ],
    inputsInline: true,
    previousStatement: 'JSStmt',
    nextStatement: 'JSStmt',
    colour: C,
    tooltip: 'Barra de progresso/vida: o preenchimento é a fração valor / máximo.',
  },

  // ---- Estado / telas (cenas) ----
  {
    type: 'sz_g2d_set_stage_description',
    placement: 'start-only-command',
    message0: 'Descrever o jogo para leitor de tela %1',
    args0: [
      {
        type: 'field_input',
        name: 'DESCRIPTION',
        text: 'Pegue as moedas. Use as setas para andar.',
      },
    ],
    previousStatement: 'JSStmt',
    nextStatement: 'JSStmt',
    colour: C,
    tooltip:
      'Explica o objetivo e os controles para quem não vê o canvas. Coloque em “Ao iniciar”.',
  },
  {
    type: 'sz_g2d_set_scene',
    placement: 'command',
    message0: 'Ir para a tela %1',
    args0: [{ type: 'field_name_picker', name: 'SCENE', text: 'inicio', kind: 'gamestate' }],
    previousStatement: 'JSStmt',
    nextStatement: 'JSStmt',
    colour: C,
    tooltip: 'Muda a tela atual do jogo. Escolha uma existente ou invente um nome (ex.: ganhou1).',
  },
  {
    type: 'sz_g2d_scene_is',
    message0: 'a tela atual é %1 ?',
    args0: [{ type: 'field_name_picker', name: 'SCENE', text: 'inicio', kind: 'gamestate' }],
    output: 'JSValue',
    colour: C,
    tooltip: 'Verdadeiro se o jogo está naquela tela. Use dentro de um "se".',
  },
  {
    type: 'sz_g2d_show_screen',
    placement: 'command',
    message0: 'Mostrar tela com título %1 subtítulo %2 dica %3 fundo %4',
    args0: [
      { type: 'input_value', name: 'TITLE', check: 'JSValue' },
      { type: 'input_value', name: 'SUBTITLE', check: 'JSValue' },
      { type: 'input_value', name: 'HINT', check: 'JSValue' },
      { type: 'field_colour_sz', name: 'BG', colour: '#02111f' },
    ],
    inputsInline: true,
    previousStatement: 'JSStmt',
    nextStatement: 'JSStmt',
    colour: C,
    tooltip:
      'Cobre a tela com um aviso central (título + subtítulo + dica). Ótimo para as telas de início, vitória e derrota.',
  },
  {
    type: 'sz_g2d_restart',
    placement: {
      root: [],
      nested: [
        'event-body',
        'user-gesture-body',
        'loop-body',
        'syntactic-loop-body',
        'function-body',
        'async-function-body',
        'derived-method-body',
      ],
      role: 'command',
    },
    message0: 'Reiniciar o jogo',
    args0: [],
    previousStatement: 'JSStmt',
    nextStatement: 'JSStmt',
    colour: C,
    tooltip:
      'Use dentro de um evento, laço ou função. Limpa a partida e executa novamente as três áreas do projeto.',
  },

  // ---- Cenário: fundo de estrelas + arrastar com o dedo (v0.6.0) ----
  {
    type: 'sz_g2d_starfield',
    placement: 'command',
    message0: 'Desenhar fundo de estrelas (velocidade %1)',
    args0: [{ type: 'input_value', name: 'SPEED', check: 'JSValue' }],
    inputsInline: true,
    previousStatement: 'JSStmt',
    nextStatement: 'JSStmt',
    colour: C,
    tooltip:
      'Desenha um céu de estrelas que rola para baixo (fundo de jogo espacial). Use no começo do "a cada quadro", depois de limpar a tela.',
  },
  {
    type: 'sz_g2d_drag_x',
    placement: 'command',
    message0: 'Mover o sprite %1 com o dedo/mouse (só na horizontal)',
    args0: [{ type: 'field_sprite_picker', name: 'SPRITE', text: 'nave' }],
    previousStatement: 'JSStmt',
    nextStatement: 'JSStmt',
    colour: C,
    tooltip: 'A nave acompanha o dedo/mouse no eixo X, ótimo para jogar no celular.',
  },

  {
    type: 'sz_g2d_setup_stage',
    placement: 'start-only-command',
    message0: 'Preparar o jogo em tela cheia, tela %1 × %2, fundo %3',
    args0: [
      { type: 'input_value', name: 'W', check: 'JSValue' },
      { type: 'input_value', name: 'H', check: 'JSValue' },
      { type: 'field_colour_sz', name: 'BG', colour: '#0b1020' },
    ],
    inputsInline: true,
    previousStatement: 'JSStmt',
    nextStatement: 'JSStmt',
    colour: C,
    tooltip:
      'Atalho para começar: prepara a tela responsiva e centralizada. Use uma vez em “Ao iniciar”.',
  },
  {
    type: 'sz_g2d_setup_full',
    placement: 'start-only-command',
    message0: 'Preparar o jogo para ocupar a tela toda, fundo %1',
    args0: [{ type: 'field_colour_sz', name: 'BG', colour: '#0b1020' }],
    inputsInline: true,
    previousStatement: 'JSStmt',
    nextStatement: 'JSStmt',
    colour: C,
    tooltip:
      'Prepara um canvas sem dimensões fixas, ocupando toda a janela. Use uma vez em “Ao iniciar”.',
  },

  // ---- Kit "Nave & Asteroides": desenhos prontos + efeitos (v0.7.0) ----
  {
    type: 'sz_g2d_fit_screen',
    placement: 'start-only-command',
    message0: 'Fazer a tela preencher %1% da janela (mantendo a proporção)',
    args0: [{ type: 'input_value', name: 'PERCENT', check: 'JSValue' }],
    inputsInline: true,
    previousStatement: 'JSStmt',
    nextStatement: 'JSStmt',
    colour: C,
    tooltip:
      'Faz o canvas ocupar quase toda a janela e se reajustar sozinho quando ela muda de tamanho; os desenhos escalam juntos, sem distorcer. Use uma vez no começo.',
  },

  {
    type: 'sz_g2d_spawn_bullet',
    placement: 'command',
    message0: 'Criar tiro no grupo %1 em x %2 y %3 raio %4 cor %5 vx %6 vy %7',
    args0: [
      { type: 'field_name_picker', name: 'GROUP', text: 'tiros', kind: 'group' },
      { type: 'input_value', name: 'X', check: 'JSValue' },
      { type: 'input_value', name: 'Y', check: 'JSValue' },
      { type: 'input_value', name: 'R', check: 'JSValue' },
      { type: 'field_colour_sz', name: 'COLOR', colour: '#9cff57' },
      { type: 'input_value', name: 'VX', check: 'JSValue' },
      { type: 'input_value', name: 'VY', check: 'JSValue' },
    ],
    inputsInline: true,
    previousStatement: 'JSStmt',
    nextStatement: 'JSStmt',
    colour: C,
    tooltip:
      'Cria um tiro (bolinha brilhante) no grupo, no ponto x/y, indo na velocidade vx/vy (vy negativo = sobe).',
  },
  {
    type: 'sz_g2d_arrows_x',
    placement: 'command',
    message0: 'Mover o sprite %1 com as setas <- -> (velocidade %2)',
    args0: [
      { type: 'field_sprite_picker', name: 'SPRITE', text: 'nave' },
      { type: 'input_value', name: 'SPEED', check: 'JSValue' },
    ],
    inputsInline: true,
    previousStatement: 'JSStmt',
    nextStatement: 'JSStmt',
    colour: C,
    tooltip:
      'Move o sprite só na horizontal com as setas esquerda/direita. Combine com "prender o sprite na tela".',
  },
  {
    type: 'sz_g2d_blink',
    placement: 'command',
    message0: 'Fazer o sprite %1 piscar por %2 quadros',
    args0: [
      { type: 'field_sprite_picker', name: 'SPRITE', text: 'nave' },
      { type: 'input_value', name: 'FRAMES', check: 'JSValue' },
    ],
    inputsInline: true,
    previousStatement: 'JSStmt',
    nextStatement: 'JSStmt',
    colour: C,
    tooltip:
      'O sprite pisca (fica intermitente) por N quadros - ótimo para a invencibilidade depois de levar dano.',
  },

  {
    // ---- Figuras: sprite desenhado por código (v0.23.0) ----
    type: 'sz_g2d_define_shape',
    placement: 'mold-declaration',
    bodyExecution: 'deferred-callback',
    message0: 'Desenhar a figura %1 assim:',
    args0: [{ type: 'field_input', name: 'NAME', text: 'heroi' }],
    message1: 'fazer %1',
    args1: [{ type: 'input_statement', name: 'BODY' }],
    inputsInline: true,
    previousStatement: 'JSStmt',
    nextStatement: 'JSStmt',
    colour: C,
    tooltip:
      'Monta um desenho com formas (retângulo, círculo, linha…) e dá um nome a ele. Depois, "Criar sprite com a figura" usa esse desenho. Você desenha DENTRO do quadro do sprite: x/y começam no cantinho (0,0). Dá para usar também os blocos de Canvas aqui dentro.',
  },
  {
    type: 'sz_g2d_create_shape_sprite',
    placement: 'start-only-command',
    message0: 'Criar sprite %1 em x %2 y %3 largura %4 altura %5 com a figura %6',
    args0: [
      { type: 'field_input', name: 'SPRITE', text: 'heroi' },
      { type: 'input_value', name: 'X', check: 'JSValue' },
      { type: 'input_value', name: 'Y', check: 'JSValue' },
      { type: 'input_value', name: 'W', check: 'JSValue' },
      { type: 'input_value', name: 'H', check: 'JSValue' },
      { type: 'field_name_picker', name: 'SHAPE', text: 'heroi', kind: 'shape' },
    ],
    inputsInline: true,
    previousStatement: 'JSStmt',
    nextStatement: 'JSStmt',
    colour: C,
    tooltip:
      'Cria um sprite que usa uma figura que você desenhou. O sprite anda, gira, vira e colide como qualquer outro. Só que o visual é o seu desenho.',
  },
  {
    type: 'sz_g2d_set_shape',
    placement: 'command',
    message0: 'Trocar a figura do sprite %1 para %2',
    args0: [
      { type: 'field_sprite_picker', name: 'SPRITE', text: 'heroi' },
      { type: 'field_name_picker', name: 'SHAPE', text: 'heroi', kind: 'shape' },
    ],
    inputsInline: true,
    previousStatement: 'JSStmt',
    nextStatement: 'JSStmt',
    colour: C,
    tooltip: 'Faz o sprite passar a usar outra figura (troca o desenho dele).',
  },
  {
    type: 'sz_g2d_paint_rect',
    placement: 'command',
    message0: 'Desenhar retângulo em x %1 y %2 largura %3 altura %4 cor %5',
    args0: [
      { type: 'input_value', name: 'X', check: 'JSValue' },
      { type: 'input_value', name: 'Y', check: 'JSValue' },
      { type: 'input_value', name: 'W', check: 'JSValue' },
      { type: 'input_value', name: 'H', check: 'JSValue' },
      { type: 'field_colour_sz', name: 'COLOR', colour: '#ec4899' },
    ],
    inputsInline: true,
    previousStatement: 'JSStmt',
    nextStatement: 'JSStmt',
    colour: C,
    tooltip: 'Desenha um retângulo cheio dentro da figura (x/y começam no cantinho do sprite).',
  },
  {
    type: 'sz_g2d_paint_circle',
    placement: 'command',
    message0: 'Desenhar círculo em x %1 y %2 raio %3 cor %4',
    args0: [
      { type: 'input_value', name: 'X', check: 'JSValue' },
      { type: 'input_value', name: 'Y', check: 'JSValue' },
      { type: 'input_value', name: 'R', check: 'JSValue' },
      { type: 'field_colour_sz', name: 'COLOR', colour: '#ec4899' },
    ],
    inputsInline: true,
    previousStatement: 'JSStmt',
    nextStatement: 'JSStmt',
    colour: C,
    tooltip: 'Desenha um círculo cheio dentro da figura (x/y = o centro do círculo).',
  },
  {
    type: 'sz_g2d_paint_ellipse',
    placement: 'command',
    message0: 'Desenhar oval em x %1 y %2 largura %3 altura %4 cor %5',
    args0: [
      { type: 'input_value', name: 'X', check: 'JSValue' },
      { type: 'input_value', name: 'Y', check: 'JSValue' },
      { type: 'input_value', name: 'W', check: 'JSValue' },
      { type: 'input_value', name: 'H', check: 'JSValue' },
      { type: 'field_colour_sz', name: 'COLOR', colour: '#ec4899' },
    ],
    inputsInline: true,
    previousStatement: 'JSStmt',
    nextStatement: 'JSStmt',
    colour: C,
    tooltip: 'Desenha uma oval cheia dentro da figura (cabe num retângulo x/y largura/altura).',
  },
  {
    type: 'sz_g2d_paint_triangle',
    placement: 'command',
    message0: 'Desenhar triângulo em (%1, %2) (%3, %4) (%5, %6) cor %7',
    args0: [
      { type: 'input_value', name: 'X1', check: 'JSValue' },
      { type: 'input_value', name: 'Y1', check: 'JSValue' },
      { type: 'input_value', name: 'X2', check: 'JSValue' },
      { type: 'input_value', name: 'Y2', check: 'JSValue' },
      { type: 'input_value', name: 'X3', check: 'JSValue' },
      { type: 'input_value', name: 'Y3', check: 'JSValue' },
      { type: 'field_colour_sz', name: 'COLOR', colour: '#ec4899' },
    ],
    inputsInline: true,
    previousStatement: 'JSStmt',
    nextStatement: 'JSStmt',
    colour: C,
    tooltip: 'Desenha um triângulo cheio ligando os três pontos dentro da figura.',
  },
  {
    type: 'sz_g2d_paint_line',
    placement: 'command',
    message0: 'Desenhar linha de x %1 y %2 até x %3 y %4 cor %5 espessura %6',
    args0: [
      { type: 'input_value', name: 'X1', check: 'JSValue' },
      { type: 'input_value', name: 'Y1', check: 'JSValue' },
      { type: 'input_value', name: 'X2', check: 'JSValue' },
      { type: 'input_value', name: 'Y2', check: 'JSValue' },
      { type: 'field_colour_sz', name: 'COLOR', colour: '#ec4899' },
      { type: 'input_value', name: 'WIDTH', check: 'JSValue' },
    ],
    inputsInline: true,
    previousStatement: 'JSStmt',
    nextStatement: 'JSStmt',
    colour: C,
    tooltip: 'Desenha uma linha entre dois pontos dentro da figura.',
  },
  {
    type: 'sz_g2d_shape_w',
    message0: 'a largura da figura',
    output: 'JSValue',
    colour: C,
    tooltip:
      'A largura do sprite que está sendo desenhado agora (útil para centralizar o desenho).',
  },
  {
    type: 'sz_g2d_shape_h',
    message0: 'a altura da figura',
    output: 'JSValue',
    colour: C,
    tooltip: 'A altura do sprite que está sendo desenhado agora.',
  },
  {
    type: 'sz_g2d_create_ship',
    placement: 'start-only-command',
    message0: 'Criar nave %1 em x %2 y %3 largura %4 altura %5, cor do corpo %6 cor das asas %7',
    args0: [
      { type: 'field_input', name: 'NAME', text: 'nave' },
      { type: 'input_value', name: 'X', check: 'JSValue' },
      { type: 'input_value', name: 'Y', check: 'JSValue' },
      { type: 'input_value', name: 'W', check: 'JSValue' },
      { type: 'input_value', name: 'H', check: 'JSValue' },
      { type: 'field_colour_sz', name: 'BODY', colour: '#35e8ff' },
      { type: 'field_colour_sz', name: 'WINGS', colour: '#2568ff' },
    ],
    inputsInline: true,
    previousStatement: 'JSStmt',
    nextStatement: 'JSStmt',
    colour: C,
    tooltip:
      'Cria uma nave desenhada (corpo + asas com as cores que você escolher, cabine e foguinho que pulsa sozinho). O foguinho já vem animado.',
  },
  {
    type: 'sz_g2d_spawn_asteroid',
    placement: 'command',
    message0: 'No grupo %1 criar um asteroide em x %2 y %3 tamanho %4 cor %5 com vx %6 vy %7',
    args0: [
      { type: 'field_name_picker', name: 'GROUP', text: 'asteroides', kind: 'group' },
      { type: 'input_value', name: 'X', check: 'JSValue' },
      { type: 'input_value', name: 'Y', check: 'JSValue' },
      { type: 'input_value', name: 'SIZE', check: 'JSValue' },
      { type: 'field_colour_sz', name: 'COLOR', colour: '#8d8f9b' },
      { type: 'input_value', name: 'VX', check: 'JSValue' },
      { type: 'input_value', name: 'VY', check: 'JSValue' },
    ],
    inputsInline: true,
    previousStatement: 'JSStmt',
    nextStatement: 'JSStmt',
    colour: C,
    tooltip:
      'Cria um asteroide já desenhado (pedra irregular que gira, com crateras) e coloca no grupo. Cada um nasce com um formato único.',
  },
  {
    type: 'sz_g2d_explode',
    placement: 'command',
    message0: 'Soltar explosão no sprite %1 cor %2',
    args0: [
      { type: 'field_sprite_picker', name: 'SPRITE', text: 'asteroide' },
      { type: 'field_colour_sz', name: 'COLOR', colour: '#ffb13b' },
    ],
    previousStatement: 'JSStmt',
    nextStatement: 'JSStmt',
    colour: C,
    tooltip:
      'Solta um jato de partículas (da cor escolhida + estilhaços cinza) no centro do sprite.',
  },
  {
    type: 'sz_g2d_play_shoot',
    placement: 'command',
    message0: 'Tocar som de tiro',
    args0: [],
    previousStatement: 'JSStmt',
    nextStatement: 'JSStmt',
    colour: C,
    tooltip: 'Um "pew" curto (som sintetizado, sem precisar de arquivo).',
  },
  {
    type: 'sz_g2d_play_explosion',
    placement: 'command',
    message0: 'Tocar som de explosão',
    args0: [],
    previousStatement: 'JSStmt',
    nextStatement: 'JSStmt',
    colour: C,
    tooltip: 'Um "bum" de ruído que decai (som sintetizado, sem precisar de arquivo).',
  },
  {
    type: 'sz_g2d_on_sprite_group_overlap',
    placement: 'loop-command',
    bodyExecution: 'sync-callback',
    message0: 'Para cada sprite do grupo %1 que colidir com o sprite %2',
    args0: [
      { type: 'field_name_picker', name: 'GROUP', text: 'asteroides', kind: 'group' },
      { type: 'field_sprite_picker', name: 'SPRITE', text: 'nave' },
    ],
    message1: 'chamar o sprite de %1',
    args1: [{ type: 'field_input', name: 'ANAME', text: 'inimigo' }],
    message2: 'fazer %1',
    args2: [{ type: 'input_statement', name: 'BODY' }],
    inputsInline: true,
    previousStatement: 'JSStmt',
    nextStatement: 'JSStmt',
    colour: EVENT_C,
    tooltip:
      'Para cada sprite do grupo que encostar no seu sprite (ex.: a nave), roda o "fazer" com aquele sprite. Use dentro do "a cada quadro".',
  },
] satisfies BlockDefinition[]
