import type { BlockDefinition } from '../../blockly/blocks/types'
import {
  GAME_TWO_D_BLOCK_COLOR as C,
  GAME_TWO_D_EVENT_COLOR as EVENT_C,
} from './blockCatalogShared'

const ACTION_OPTIONS: Array<[string, string]> = [
  ['esquerda', 'left'],
  ['direita', 'right'],
  ['cima', 'up'],
  ['baixo', 'down'],
  ['pular', 'jump'],
  ['correr / agir', 'action'],
  ['selecionar', 'select'],
  ['começar', 'start'],
  ['pausar', 'pause'],
]

export const gameTwoDClassicBlocks: BlockDefinition[] = [
  {
    type: 'sz_g2d_enable_classic_controls',
    placement: 'start-only-command',
    message0: 'Ativar controles clássicos %1',
    args0: [
      {
        type: 'field_dropdown',
        name: 'MODE',
        options: [
          ['automáticos no celular', 'auto'],
          ['sempre visíveis', 'always'],
          ['sem botões na tela', 'off'],
        ],
      },
    ],
    previousStatement: 'JSStmt',
    nextStatement: 'JSStmt',
    colour: C,
    tooltip:
      'Liga teclado e botões de toque acessíveis. Aceita mais de um dedo para andar e pular ao mesmo tempo.',
  },
  {
    type: 'sz_g2d_action_down',
    message0: 'a ação %1 está sendo segurada?',
    args0: [{ type: 'field_dropdown', name: 'ACTION', options: [...ACTION_OPTIONS] }],
    output: 'JSValue',
    colour: EVENT_C,
    tooltip: 'Consulta uma ação do jogo sem depender de uma tecla específica.',
  },
  {
    type: 'sz_g2d_action_pressed',
    message0: 'a ação %1 acabou de ser apertada?',
    args0: [{ type: 'field_dropdown', name: 'ACTION', options: [...ACTION_OPTIONS] }],
    output: 'JSValue',
    colour: EVENT_C,
    tooltip: 'Verdadeiro durante um quadro na borda do aperto, sem repetir enquanto segura.',
  },
  {
    type: 'sz_g2d_on_action_pressed',
    placement: 'event',
    bodyExecution: 'deferred-callback',
    userGesture: true,
    message0: 'Quando a ação %1 for apertada',
    args0: [{ type: 'field_dropdown', name: 'ACTION', options: [...ACTION_OPTIONS] }],
    message1: 'fazer %1',
    args1: [{ type: 'input_statement', name: 'BODY' }],
    previousStatement: 'JSStmt',
    nextStatement: 'JSStmt',
    colour: EVENT_C,
    tooltip:
      'Roda para teclado, botões de toque e tecnologia assistiva. Também recebe a ação pausar enquanto o jogo está pausado.',
  },
  {
    type: 'sz_g2d_classic_platformer',
    placement: 'command',
    message0: 'Mover o sprite %1 como plataforma clássica, velocidade %2 pulo %3',
    args0: [
      { type: 'field_sprite_picker', name: 'SPRITE', text: 'heroi' },
      { type: 'input_value', name: 'SPEED', check: 'JSValue' },
      { type: 'input_value', name: 'JUMP', check: 'JSValue' },
    ],
    inputsInline: true,
    previousStatement: 'JSStmt',
    nextStatement: 'JSStmt',
    colour: C,
    tooltip:
      'Movimento completo com aceleração, corrida, derrapagem, agachamento, gravidade e altura variável do pulo. Colida com o Mundo depois.',
  },
  {
    type: 'sz_g2d_create_vector_tileset',
    placement: 'start-only-command',
    message0: 'Criar conjunto de tiles vetoriais %1 com tiles de %2 px',
    args0: [
      { type: 'field_input', name: 'NAME', text: 'tiles' },
      { type: 'input_value', name: 'SIZE', check: 'JSValue' },
    ],
    previousStatement: 'JSStmt',
    nextStatement: 'JSStmt',
    colour: C,
    tooltip: 'Cria um tileset desenhado pelas Figuras do projeto, sem imagens externas.',
  },
  {
    type: 'sz_g2d_define_vector_tile',
    placement: 'start-only-command',
    message0: 'No conjunto %1 definir tile %2 com a figura %3 como %4',
    args0: [
      { type: 'field_name_picker', name: 'TILESET', text: 'tiles', kind: 'g2d-vector-tileset' },
      { type: 'input_value', name: 'INDEX', check: 'JSValue' },
      { type: 'field_name_picker', name: 'SHAPE', text: 'bloco', kind: 'shape' },
      {
        type: 'field_dropdown',
        name: 'ROLE',
        options: [
          ['decoração', 'decor'],
          ['sólido', 'solid'],
          ['plataforma', 'platform'],
        ],
      },
    ],
    inputsInline: true,
    previousStatement: 'JSStmt',
    nextStatement: 'JSStmt',
    colour: C,
    tooltip: 'Associa um índice a uma Figura e define se ela colide.',
  },
  {
    type: 'sz_g2d_create_vector_tilemap',
    placement: 'start-only-command',
    message0: 'Criar mapa vetorial %1 com o conjunto %2 e grade %3',
    args0: [
      { type: 'field_input', name: 'NAME', text: 'mapa' },
      { type: 'field_name_picker', name: 'TILESET', text: 'tiles', kind: 'g2d-vector-tileset' },
      { type: 'field_tile_grid', name: 'GRID', text: '0 0 0 0;0 0 0 0' },
    ],
    previousStatement: 'JSStmt',
    nextStatement: 'JSStmt',
    colour: C,
    tooltip: 'Monta um mapa com a mesma geometria e colisão dos mapas de imagem.',
  },
  {
    type: 'sz_g2d_for_each_tile_contact',
    placement: 'command',
    bodyExecution: 'sync-callback',
    message0: 'Para cada tile que %1 toca no lado %2 do mapa %3 chamar de %4',
    args0: [
      { type: 'field_sprite_picker', name: 'SPRITE', text: 'heroi' },
      {
        type: 'field_dropdown',
        name: 'SIDE',
        options: [
          ['qualquer', 'any'],
          ['cabeça', 'head'],
          ['pés', 'feet'],
          ['esquerda', 'left'],
          ['direita', 'right'],
        ],
      },
      { type: 'field_name_picker', name: 'MAP', text: 'mapa', kind: 'tilemap' },
      { type: 'field_input', name: 'CONTACT', text: 'contato' },
    ],
    message1: 'fazer %1',
    args1: [{ type: 'input_statement', name: 'BODY' }],
    previousStatement: 'JSStmt',
    nextStatement: 'JSStmt',
    colour: EVENT_C,
    tooltip:
      'Depois da colisão, percorre cada tile exato atingido e informa o lado. Útil para blocos quebráveis e surpresas.',
  },
  {
    type: 'sz_g2d_tile_contact_is',
    message0: 'o contato %1 é com o tile %2?',
    args0: [
      { type: 'field_input', name: 'CONTACT', text: 'contato' },
      { type: 'input_value', name: 'INDEX', check: 'JSValue' },
    ],
    inputsInline: true,
    output: 'JSValue',
    colour: EVENT_C,
    tooltip: 'Compara o índice original do tile atingido antes de decidir a recompensa ou mudança.',
  },
  {
    type: 'sz_g2d_set_tile_at_contact',
    placement: 'command',
    message0: 'No contato %1 trocar o tile para %2',
    args0: [
      { type: 'field_input', name: 'CONTACT', text: 'contato' },
      { type: 'input_value', name: 'INDEX', check: 'JSValue' },
    ],
    previousStatement: 'JSStmt',
    nextStatement: 'JSStmt',
    colour: C,
    tooltip: 'Muda exatamente o tile informado pelo contato; -1 quebra/remove.',
  },
  {
    type: 'sz_g2d_set_enemy_stomp_mode',
    placement: 'start-only-command',
    message0: 'Ao pisar no tipo %1 usar modo %2',
    args0: [
      { type: 'field_name_picker', name: 'TYPE', text: 'inimigos', kind: 'enemytype' },
      {
        type: 'field_dropdown',
        name: 'MODE',
        options: [
          ['derrotar', 'defeat'],
          ['causar 1 de dano', 'damage'],
          ['achatar por um instante', 'squash'],
          ['virar casco móvel', 'shell'],
          ['espinhoso (não aceita pisada)', 'spiky'],
        ],
      },
    ],
    previousStatement: 'JSStmt',
    nextStatement: 'JSStmt',
    colour: C,
    tooltip: 'Escolhe o resultado da pisada sem alterar tipos de inimigo já existentes.',
  },
  {
    type: 'sz_g2d_update_enemy_shells',
    placement: 'command',
    message0: 'Atualizar os cascos do tipo %1 no Mundo %2',
    args0: [
      { type: 'field_name_picker', name: 'TYPE', text: 'inimigos', kind: 'enemytype' },
      { type: 'field_name_picker', name: 'WORLD', text: 'mundo', kind: 'g2d-world' },
    ],
    previousStatement: 'JSStmt',
    nextStatement: 'JSStmt',
    colour: C,
    tooltip: 'Move cascos, rebate nas paredes do Mundo e derrota inimigos atingidos.',
  },
  {
    type: 'sz_g2d_draw_pixel_text',
    placement: 'command',
    message0: 'Escrever texto pixel %1 em x %2 y %3 pixel %4 cor %5 alinhado %6',
    args0: [
      { type: 'field_input', name: 'TEXT', text: 'REINO ZERO' },
      { type: 'input_value', name: 'X', check: 'JSValue' },
      { type: 'input_value', name: 'Y', check: 'JSValue' },
      { type: 'input_value', name: 'SIZE', check: 'JSValue' },
      { type: 'field_colour_sz', name: 'COLOR', colour: '#ffffff' },
      {
        type: 'field_dropdown',
        name: 'ALIGN',
        options: [
          ['à esquerda', 'left'],
          ['no centro', 'center'],
          ['à direita', 'right'],
        ],
      },
    ],
    inputsInline: true,
    previousStatement: 'JSStmt',
    nextStatement: 'JSStmt',
    colour: C,
    tooltip: 'Desenha letras em uma grade 5×7 no canvas, sem carregar fonte.',
  },
  {
    type: 'sz_g2d_draw_fade',
    placement: 'command',
    message0: 'Cobrir a tela com fade de %1 porcento na cor %2',
    args0: [
      { type: 'input_value', name: 'PERCENT', check: 'JSValue' },
      { type: 'field_colour_sz', name: 'COLOR', colour: '#000000' },
    ],
    previousStatement: 'JSStmt',
    nextStatement: 'JSStmt',
    colour: C,
    tooltip: 'Desenha uma cobertura de 0 a 100% para transições de cena.',
  },
]
