import type { BlockDefinition } from '../../blockly/blocks/types'
import {
  GAME_TWO_D_BLOCK_COLOR as C,
  GAME_TWO_D_EVENT_COLOR as EVENT_C,
} from './blockCatalogShared'

export const gameTwoDKitBlocks = [
  // ---- Pulo no chão (genérico, Movimento) ----
  {
    type: 'sz_g2d_jump_on_ground',
    placement: 'command',
    message0: 'Fazer o sprite %1 pular no chão, força do pulo %2',
    args0: [
      { type: 'field_sprite_picker', name: 'SPRITE', text: 'dino' },
      { type: 'input_value', name: 'JUMP', check: 'JSValue' },
    ],
    inputsInline: true,
    previousStatement: 'JSStmt',
    nextStatement: 'JSStmt',
    colour: C,
    tooltip:
      'Pula com ↑/Espaço/W ou um toque na tela e pousa na borda atraída. Para o sprite cair, encaixe "Aplicar a gravidade do mundo" logo acima. Ótimo para jogos de corrida e de pulo. Use dentro do "a cada quadro".',
  },

  // ---- Kit dino (v0.9.0): desenhos prontos + sons para um jogo de corrida ----
  {
    type: 'sz_g2d_create_dino',
    placement: 'start-only-command',
    message0: 'Criar dinossauro %1 em x %2 y %3 tamanho %4 cor %5',
    args0: [
      { type: 'field_input', name: 'NAME', text: 'dino' },
      { type: 'input_value', name: 'X', check: 'JSValue' },
      { type: 'input_value', name: 'Y', check: 'JSValue' },
      { type: 'input_value', name: 'SIZE', check: 'JSValue' },
      { type: 'field_colour_sz', name: 'COLOR', colour: '#5fb45f' },
    ],
    inputsInline: true,
    previousStatement: 'JSStmt',
    nextStatement: 'JSStmt',
    colour: C,
    tooltip:
      'Cria um dinossauro desenhado (com perninhas que correm sozinhas). A pose muda quando ele pula ou abaixa.',
  },
  {
    type: 'sz_g2d_control_dino',
    placement: 'command',
    message0: 'Controlar o dinossauro %1, força do pulo %2',
    args0: [
      { type: 'field_sprite_picker', name: 'SPRITE', text: 'dino' },
      { type: 'input_value', name: 'JUMP', check: 'JSValue' },
    ],
    inputsInline: true,
    previousStatement: 'JSStmt',
    nextStatement: 'JSStmt',
    colour: C,
    tooltip:
      'Pula com ↑/Espaço ou toque na metade de cima da tela; abaixa com ↓ ou segurando o dedo embaixo. Já vem com chão e poeira. Para o dino cair, encaixe o "Aplicar a gravidade do mundo" logo acima. Use dentro do "a cada quadro".',
  },
  {
    type: 'sz_g2d_spawn_obstacle',
    placement: 'command',
    message0: 'No grupo %1 criar obstáculo %2 em x %3 tamanho %4 com vx %5',
    args0: [
      { type: 'field_name_picker', name: 'GROUP', text: 'obstaculos', kind: 'group' },
      {
        type: 'field_dropdown',
        name: 'SHAPE',
        options: [
          ['cacto', 'cactus'],
          ['pedra', 'rock'],
          ['pássaro (voa alto)', 'bird'],
          ['surpresa (sorteia)', 'random'],
        ],
      },
      { type: 'input_value', name: 'X', check: 'JSValue' },
      { type: 'input_value', name: 'SIZE', check: 'JSValue' },
      { type: 'input_value', name: 'VX', check: 'JSValue' },
    ],
    inputsInline: true,
    previousStatement: 'JSStmt',
    nextStatement: 'JSStmt',
    colour: C,
    tooltip:
      'Cria um obstáculo desenhado e coloca no grupo. Cacto e pedra nascem no chão (pule por cima); o pássaro vem no alto (abaixe por baixo). Ligue o x na borda direita e um vx negativo para ele vir vindo.',
  },
  {
    type: 'sz_g2d_spawn_egg',
    placement: 'command',
    message0: 'No grupo %1 criar um ovo (bônus) em x %2 y %3 com vx %4',
    args0: [
      { type: 'field_name_picker', name: 'GROUP', text: 'ovos', kind: 'group' },
      { type: 'input_value', name: 'X', check: 'JSValue' },
      { type: 'input_value', name: 'Y', check: 'JSValue' },
      { type: 'input_value', name: 'VX', check: 'JSValue' },
    ],
    inputsInline: true,
    previousStatement: 'JSStmt',
    nextStatement: 'JSStmt',
    colour: C,
    tooltip:
      'Cria um ovo desenhado (item de bônus) e coloca no grupo. Quando o dino encostar, dá pontos extras.',
  },
  {
    type: 'sz_g2d_forest',
    placement: 'command',
    message0: 'Desenhar fundo de floresta (velocidade %1)',
    args0: [{ type: 'input_value', name: 'SPEED', check: 'JSValue' }],
    inputsInline: true,
    previousStatement: 'JSStmt',
    nextStatement: 'JSStmt',
    colour: C,
    tooltip:
      'Desenha um céu com sol, nuvens, morros e uma faixa de grama que rola (parallax). Use no começo do "a cada quadro", depois de limpar a tela. O dino corre sobre a grama.',
  },
  {
    type: 'sz_g2d_play_jump',
    placement: 'command',
    message0: 'Tocar som de pulo',
    args0: [],
    previousStatement: 'JSStmt',
    nextStatement: 'JSStmt',
    colour: C,
    tooltip: 'Um "biip" curto subindo de tom (som sintetizado, sem precisar de arquivo).',
  },
  {
    type: 'sz_g2d_play_dino_hurt',
    placement: 'command',
    message0: 'Tocar som de dano',
    args0: [],
    previousStatement: 'JSStmt',
    nextStatement: 'JSStmt',
    colour: C,
    tooltip: 'Um rosnado grave que decai (som sintetizado, sem precisar de arquivo).',
  },
  {
    type: 'sz_g2d_play_collect',
    placement: 'command',
    message0: 'Tocar som de coletar',
    args0: [],
    previousStatement: 'JSStmt',
    nextStatement: 'JSStmt',
    colour: C,
    tooltip: 'Duas notinhas alegres (som sintetizado), ótimo ao pegar o ovo bônus.',
  },

  // ---- Nave clássica: girar + impulsionar na direção apontada (v0.10.0) ----
  {
    type: 'sz_g2d_steer_thrust',
    placement: 'command',
    message0: 'Controlar o sprite %1 como nave, velocidade %2 giro %3',
    args0: [
      { type: 'field_sprite_picker', name: 'SPRITE', text: 'nave' },
      { type: 'input_value', name: 'SPEED', check: 'JSValue' },
      { type: 'input_value', name: 'TURN', check: 'JSValue' },
    ],
    inputsInline: true,
    previousStatement: 'JSStmt',
    nextStatement: 'JSStmt',
    colour: C,
    tooltip:
      'Controle clássico de nave: vira com as setas ← → (ou A/D), acelera na direção apontada com a seta ↑ (ou W) e desliza com atrito ao soltar. "giro" é quantos graus ela vira por quadro. Use a cada quadro.',
  },
  {
    type: 'sz_g2d_rotate_sprite',
    placement: 'command',
    message0: 'Girar o sprite %1 em %2 graus',
    args0: [
      { type: 'field_sprite_picker', name: 'SPRITE', text: 'nave' },
      { type: 'input_value', name: 'DEG', check: 'JSValue' },
    ],
    inputsInline: true,
    previousStatement: 'JSStmt',
    nextStatement: 'JSStmt',
    colour: C,
    tooltip:
      'Gira o sprite alguns graus (positivo = sentido horário, negativo = anti-horário). 0 graus = apontando pra cima.',
  },
  {
    type: 'sz_g2d_point_sprite',
    placement: 'command',
    message0: 'Apontar o sprite %1 para %2 graus',
    args0: [
      { type: 'field_sprite_picker', name: 'SPRITE', text: 'nave' },
      { type: 'input_value', name: 'DEG', check: 'JSValue' },
    ],
    inputsInline: true,
    previousStatement: 'JSStmt',
    nextStatement: 'JSStmt',
    colour: C,
    tooltip:
      'Vira o sprite direto para um ângulo (0 = pra cima, 90 = pra direita, 180 = pra baixo, 270 = pra esquerda).',
  },
  {
    type: 'sz_g2d_thrust',
    placement: 'command',
    message0: 'Impulsionar o sprite %1 para a frente, força %2',
    args0: [
      { type: 'field_sprite_picker', name: 'SPRITE', text: 'nave' },
      { type: 'input_value', name: 'FORCE', check: 'JSValue' },
    ],
    inputsInline: true,
    previousStatement: 'JSStmt',
    nextStatement: 'JSStmt',
    colour: C,
    tooltip:
      'Acelera o sprite na direção que ele está apontando (soma à velocidade). Combine com “Mover usando vx e vy” e “frear aos poucos” para o efeito de nave no espaço.',
  },
  {
    type: 'sz_g2d_apply_friction',
    placement: 'command',
    message0: 'Frear o sprite %1 aos poucos (atrito %2)',
    args0: [
      { type: 'field_sprite_picker', name: 'SPRITE', text: 'nave' },
      { type: 'input_value', name: 'FACTOR', check: 'JSValue' },
    ],
    inputsInline: true,
    previousStatement: 'JSStmt',
    nextStatement: 'JSStmt',
    colour: C,
    tooltip:
      'Vai diminuindo a velocidade do sprite (multiplica por um fator entre 0 e 1). Perto de 1 desliza bastante; menor freia rápido.',
  },
  {
    type: 'sz_g2d_sprite_angle',
    message0: 'a direção (em graus) do sprite %1',
    args0: [{ type: 'field_sprite_picker', name: 'SPRITE', text: 'nave' }],
    output: 'JSValue',
    colour: C,
    tooltip:
      'O ângulo que o sprite está apontando, em graus (0 = pra cima, horário). Use numa conta ou num "se".',
  },
  {
    type: 'sz_g2d_shoot_from',
    placement: 'command',
    message0: 'Atirar do sprite %1 para a frente, no grupo %2, velocidade %3 cor %4',
    args0: [
      { type: 'field_sprite_picker', name: 'SPRITE', text: 'nave' },
      { type: 'field_name_picker', name: 'GROUP', text: 'tiros', kind: 'group' },
      { type: 'input_value', name: 'SPEED', check: 'JSValue' },
      { type: 'field_colour_sz', name: 'COLOR', colour: '#9cff57' },
    ],
    inputsInline: true,
    previousStatement: 'JSStmt',
    nextStatement: 'JSStmt',
    colour: C,
    tooltip:
      'Cria um tiro na ponta do sprite, saindo na direção que ele aponta. Use no "quando apertar a tecla Espaço".',
  },
  {
    type: 'sz_g2d_spawn_asteroid_edge',
    placement: 'command',
    message0: 'No grupo %1 soltar um asteroide de uma borda, tamanho %2 cor %3 velocidade %4',
    args0: [
      { type: 'field_name_picker', name: 'GROUP', text: 'asteroides', kind: 'group' },
      { type: 'input_value', name: 'SIZE', check: 'JSValue' },
      { type: 'field_colour_sz', name: 'COLOR', colour: '#8d8f9b' },
      { type: 'input_value', name: 'SPEED', check: 'JSValue' },
    ],
    inputsInline: true,
    previousStatement: 'JSStmt',
    nextStatement: 'JSStmt',
    colour: C,
    tooltip:
      'Solta um asteroide vindo de uma das bordas da tela (sorteada), já indo em direção ao centro. Use dentro de "a cada X segundos" para nascerem sem parar.',
  },

  // ---- Kit gorilas (v0.11.0): batalha de bananas (artilharia) ----
  {
    type: 'sz_g2d_create_city',
    placement: 'start-only-command',
    message0: 'Criar cidade de prédios %1',
    args0: [{ type: 'field_input', name: 'NAME', text: 'cidade' }],
    previousStatement: 'JSStmt',
    nextStatement: 'JSStmt',
    colour: C,
    tooltip:
      'Sorteia uma cidade de prédios (com janelas e vento) e guarda numa variável. É nela que os gorilas ficam e a banana abre crateras.',
  },
  {
    type: 'sz_g2d_draw_city',
    placement: 'command',
    message0: 'Desenhar a cidade %1',
    args0: [{ type: 'field_name_picker', name: 'CITY', text: 'cidade', kind: 'variable' }],
    previousStatement: 'JSStmt',
    nextStatement: 'JSStmt',
    colour: C,
    tooltip:
      'Desenha o céu, a lua e os prédios com janelas, já com as crateras "furadas". Use no começo do "a cada quadro", depois de limpar a tela.',
  },
  {
    type: 'sz_g2d_place_thrower',
    placement: 'start-only-command',
    message0: 'Pôr o gorila %1 na cidade %2 no lado %3 cor %4',
    args0: [
      { type: 'field_input', name: 'NAME', text: 'gorila1' },
      { type: 'field_name_picker', name: 'CITY', text: 'cidade', kind: 'variable' },
      {
        type: 'field_dropdown',
        name: 'SIDE',
        options: [
          ['esquerdo', 'left'],
          ['direito', 'right'],
        ],
      },
      { type: 'field_colour_sz', name: 'COLOR', colour: '#6b4a2b' },
    ],
    previousStatement: 'JSStmt',
    nextStatement: 'JSStmt',
    colour: C,
    tooltip:
      'Cria um gorila no alto de um prédio perto da ponta (esquerda ou direita) e guarda numa variável. Faça um para cada jogador.',
  },
  {
    type: 'sz_g2d_new_wind',
    placement: 'command',
    message0: 'Sortear o vento da cidade %1',
    args0: [{ type: 'field_name_picker', name: 'CITY', text: 'cidade', kind: 'variable' }],
    previousStatement: 'JSStmt',
    nextStatement: 'JSStmt',
    colour: C,
    tooltip: 'Sorteia um novo vento (empurra a banana para um lado). Use a cada troca de turno.',
  },
  {
    type: 'sz_g2d_draw_wind',
    placement: 'command',
    message0: 'Desenhar a seta do vento da cidade %1',
    args0: [{ type: 'field_name_picker', name: 'CITY', text: 'cidade', kind: 'variable' }],
    previousStatement: 'JSStmt',
    nextStatement: 'JSStmt',
    colour: C,
    tooltip:
      'Desenha uma seta no topo: o tamanho mostra a força do vento e o lado mostra a direção. Use no "a cada quadro".',
  },
  {
    type: 'sz_g2d_aim_drag',
    placement: 'command',
    message0: 'Mirar arrastando a partir do gorila %1',
    args0: [{ type: 'field_sprite_picker', name: 'THROWER', text: 'gorila1' }],
    previousStatement: 'JSStmt',
    nextStatement: 'JSStmt',
    colour: C,
    tooltip:
      'Enquanto segura o mouse/dedo, aponte para onde quer jogar (mais longe = mais forte) e veja a linha pontilhada da trajetória. Solte para lançar. Use no gorila da vez, no "a cada quadro".',
  },
  {
    type: 'sz_g2d_aim_released',
    message0: 'soltou a mira do gorila %1 ?',
    args0: [{ type: 'field_sprite_picker', name: 'THROWER', text: 'gorila1' }],
    output: 'JSValue',
    colour: C,
    tooltip:
      'Verdadeiro no instante em que a criança SOLTA a mira (depois de arrastar). Use num "se" para então "Jogar a banana".',
  },
  {
    type: 'sz_g2d_throw_banana',
    placement: 'command',
    message0: 'Jogar a banana do gorila %1 na cidade %2',
    args0: [
      { type: 'field_sprite_picker', name: 'THROWER', text: 'gorila1' },
      { type: 'field_name_picker', name: 'CITY', text: 'cidade', kind: 'variable' },
    ],
    previousStatement: 'JSStmt',
    nextStatement: 'JSStmt',
    colour: C,
    tooltip: 'Lança a banana do gorila com a mira atual. Só dá pra ter uma banana voando por vez.',
  },
  {
    type: 'sz_g2d_update_banana',
    placement: 'command',
    message0: 'Mover a banana da cidade %1',
    args0: [{ type: 'field_name_picker', name: 'CITY', text: 'cidade', kind: 'variable' }],
    previousStatement: 'JSStmt',
    nextStatement: 'JSStmt',
    colour: C,
    tooltip:
      'Move a banana um pouquinho: a gravidade puxa para baixo e o vento da cidade empurra para o lado. Use no "a cada quadro".',
  },
  {
    type: 'sz_g2d_draw_banana',
    placement: 'command',
    message0: 'Desenhar a banana da cidade %1',
    args0: [{ type: 'field_name_picker', name: 'CITY', text: 'cidade', kind: 'variable' }],
    previousStatement: 'JSStmt',
    nextStatement: 'JSStmt',
    colour: C,
    tooltip: 'Desenha a banana voando (com um rastro). Use no "a cada quadro".',
  },
  {
    type: 'sz_g2d_banana_hit_thrower',
    message0: 'a banana da cidade %1 acertou o gorila %2 ?',
    args0: [
      { type: 'field_name_picker', name: 'CITY', text: 'cidade', kind: 'variable' },
      { type: 'field_sprite_picker', name: 'THROWER', text: 'gorila2' },
    ],
    output: 'JSValue',
    colour: C,
    tooltip:
      'Verdadeiro se a banana encostou no gorila (acerto = vitória). Passe o gorila INIMIGO. Use num "se".',
  },
  {
    type: 'sz_g2d_banana_hit_city',
    message0: 'a banana da cidade %1 bateu num prédio ?',
    args0: [{ type: 'field_name_picker', name: 'CITY', text: 'cidade', kind: 'variable' }],
    output: 'JSValue',
    colour: C,
    tooltip:
      'Verdadeiro quando a banana bate num prédio (abre uma cratera) ou sai da tela. É a hora de TROCAR de turno. Atenção: já abre o buraco e some com a banana.',
  },
  {
    type: 'sz_g2d_play_whistle',
    placement: 'command',
    message0: 'Tocar som de banana caindo',
    args0: [],
    previousStatement: 'JSStmt',
    nextStatement: 'JSStmt',
    colour: C,
    tooltip: 'Um assobio que desce de tom (som sintetizado, sem precisar de arquivo).',
  },
  {
    type: 'sz_g2d_play_boom',
    placement: 'command',
    message0: 'Tocar som de explosão',
    args0: [],
    previousStatement: 'JSStmt',
    nextStatement: 'JSStmt',
    colour: C,
    tooltip: 'Um "bum" curto de explosão (som sintetizado), ótimo quando a banana acerta.',
  },
  {
    type: 'sz_g2d_computer_turn',
    placement: 'command',
    message0: 'O robô do gorila %1 joga na cidade %2 mirando no %3',
    args0: [
      { type: 'field_sprite_picker', name: 'THROWER', text: 'gorila2' },
      { type: 'field_name_picker', name: 'CITY', text: 'cidade', kind: 'variable' },
      { type: 'field_sprite_picker', name: 'ENEMY', text: 'gorila1' },
    ],
    previousStatement: 'JSStmt',
    nextStatement: 'JSStmt',
    colour: C,
    tooltip:
      'O robô mira sozinho (simula vários lançamentos e escolhe o melhor), pensa um instante e joga a banana. Use no "a cada quadro", na vez do robô. Um tiro por vez. Passe o gorila INIMIGO no último campo.',
  },
  {
    type: 'sz_g2d_draw_aim_readout',
    placement: 'command',
    message0: 'Mostrar ângulo e força da mira',
    args0: [],
    previousStatement: 'JSStmt',
    nextStatement: 'JSStmt',
    colour: C,
    tooltip:
      'Mostra no canto o ângulo (graus) e a força do último arremesso/mira, bom para acompanhar o que o robô escolheu.',
  },

  // ---- Kit equilibrista v2 (v0.42.0): sprite + caminho ----
  {
    type: 'sz_g2d_stickhero_sprite',
    placement: 'start-only-command',
    message0: 'Criar equilibrista %1 largura %2 altura %3 cor %4',
    args0: [
      { type: 'field_input', name: 'NAME', text: 'equilibrista' },
      { type: 'input_value', name: 'W', check: 'JSValue' },
      { type: 'input_value', name: 'H', check: 'JSValue' },
      { type: 'field_colour_sz', name: 'COLOR', colour: '#d6455d' },
    ],
    inputsInline: true,
    previousStatement: 'JSStmt',
    nextStatement: 'JSStmt',
    colour: C,
    tooltip:
      'Cria o EQUILIBRISTA: um sprite comum, do tamanho e cor que você escolher. Como é um sprite, os blocos de sprite funcionam nele (trocar a figura ou a imagem, por exemplo). Faça uma vez, no começo.',
  },
  {
    type: 'sz_g2d_stickpath_create',
    placement: 'start-only-command',
    message0: 'Criar o caminho de plataformas %1 com plataformas cor %2 e bastão cor %3',
    args0: [
      { type: 'field_input', name: 'NAME', text: 'caminho' },
      { type: 'field_colour_sz', name: 'PLATFORM_COLOR', colour: '#0ea5a0' },
      { type: 'field_colour_sz', name: 'STICK_COLOR', colour: '#1b2330' },
    ],
    inputsInline: true,
    previousStatement: 'JSStmt',
    nextStatement: 'JSStmt',
    colour: C,
    tooltip:
      'Cria o CAMINHO do jogo (estilo Stick Hero): as plataformas, o bastão e as árvores do fundo. As regras agem no caminho; o equilibrista é o sprite que anda por ele. Faça uma vez, no começo.',
  },
  {
    type: 'sz_g2d_stickpath_scenery',
    placement: 'command',
    message0: 'Desenhar o cenário do caminho %1 (céu, colinas e árvores)',
    args0: [{ type: 'field_name_picker', name: 'PATH', text: 'caminho', kind: 'variable' }],
    previousStatement: 'JSStmt',
    nextStatement: 'JSStmt',
    colour: C,
    tooltip:
      'Desenha o fundo do jogo no tamanho do palco. Use no começo do "a cada quadro", antes das plataformas e do equilibrista.',
  },
  {
    type: 'sz_g2d_stickpath_grow',
    placement: 'command',
    message0: 'Crescer o bastão do caminho %1 (rapidez %2)',
    args0: [
      { type: 'field_name_picker', name: 'PATH', text: 'caminho', kind: 'variable' },
      { type: 'input_value', name: 'SPEED', check: 'JSValue' },
    ],
    inputsInline: true,
    previousStatement: 'JSStmt',
    nextStatement: 'JSStmt',
    colour: C,
    tooltip:
      'O bastão cresce enquanto este bloco rodar. Monte a regra do mouse você mesmo: se "o mouse ou dedo está segurado?" então crescer, senão derrubar. Use dentro do "a cada quadro".',
  },
  {
    type: 'sz_g2d_stickpath_drop',
    placement: 'command',
    message0: 'Derrubar o bastão do caminho %1',
    args0: [{ type: 'field_name_picker', name: 'PATH', text: 'caminho', kind: 'variable' }],
    previousStatement: 'JSStmt',
    nextStatement: 'JSStmt',
    colour: C,
    tooltip:
      'Solta o bastão: ele tomba sobre o buraco. Só faz efeito se o bastão estava crescendo (é o "senão" da regra do mouse). Use dentro do "a cada quadro".',
  },
  {
    type: 'sz_g2d_stickpath_walk',
    placement: 'command',
    message0: 'Fazer o equilibrista %1 andar pelo caminho %2 (rapidez %3)',
    args0: [
      { type: 'field_sprite_picker', name: 'SPRITE', text: 'equilibrista' },
      { type: 'field_name_picker', name: 'PATH', text: 'caminho', kind: 'variable' },
      { type: 'input_value', name: 'SPEED', check: 'JSValue' },
    ],
    inputsInline: true,
    previousStatement: 'JSStmt',
    nextStatement: 'JSStmt',
    colour: C,
    tooltip:
      'A física do jogo: o bastão derrubado gira até deitar, o equilibrista anda por ele, atravessa quando alcança a próxima plataforma e cai quando não alcança. Também posiciona o sprite. Use dentro do "a cada quadro".',
  },
  {
    type: 'sz_g2d_stickpath_draw',
    placement: 'command',
    message0: 'Desenhar as plataformas e o bastão do caminho %1',
    args0: [{ type: 'field_name_picker', name: 'PATH', text: 'caminho', kind: 'variable' }],
    previousStatement: 'JSStmt',
    nextStatement: 'JSStmt',
    colour: C,
    tooltip:
      'Desenha as plataformas (com a marca do acerto perfeito) e o bastão, nas cores do caminho. O equilibrista você desenha com o bloco "Desenhar o sprite". Use no fim do "a cada quadro".',
  },
  {
    type: 'sz_g2d_stickpath_on_cross',
    placement: 'event',
    message0: 'Quando o equilibrista atravessar uma plataforma do caminho %1',
    args0: [{ type: 'field_name_picker', name: 'PATH', text: 'caminho', kind: 'variable' }],
    message1: 'fazer %1',
    args1: [{ type: 'input_statement', name: 'BODY' }],
    inputsInline: true,
    previousStatement: 'JSStmt',
    nextStatement: 'JSStmt',
    colour: EVENT_C,
    tooltip:
      'Registre UMA vez, fora do "a cada quadro". Toda travessia roda o "fazer": some os pontos na SUA variável de placar e toque um som.',
  },
  {
    type: 'sz_g2d_stickpath_on_perfect',
    placement: 'event',
    message0: 'Quando o equilibrista acertar bem no meio no caminho %1',
    args0: [{ type: 'field_name_picker', name: 'PATH', text: 'caminho', kind: 'variable' }],
    message1: 'fazer %1',
    args1: [{ type: 'input_statement', name: 'BODY' }],
    inputsInline: true,
    previousStatement: 'JSStmt',
    nextStatement: 'JSStmt',
    colour: EVENT_C,
    tooltip:
      'Registre UMA vez, fora do "a cada quadro". Quando o bastão cair bem no marquinho do meio da plataforma, o "fazer" roda: dê pontos extras e um brilho na tela.',
  },
  {
    type: 'sz_g2d_stickpath_fell',
    message0: 'o equilibrista caiu no caminho %1 ?',
    args0: [{ type: 'field_name_picker', name: 'PATH', text: 'caminho', kind: 'variable' }],
    output: 'JSValue',
    colour: C,
    tooltip: 'Verdadeiro quando o equilibrista caiu no buraco (fim de jogo). Use num "se".',
  },

  // ---- Kit balão v2 (v0.42.0): sprite + caminho ----
  {
    type: 'sz_g2d_balloon_sprite',
    placement: 'start-only-command',
    message0: 'Criar balão %1 em x %2 y %3 largura %4 altura %5, cor do balão %6 cor do cesto %7',
    args0: [
      { type: 'field_input', name: 'NAME', text: 'balao' },
      { type: 'input_value', name: 'X', check: 'JSValue' },
      { type: 'input_value', name: 'Y', check: 'JSValue' },
      { type: 'input_value', name: 'W', check: 'JSValue' },
      { type: 'input_value', name: 'H', check: 'JSValue' },
      { type: 'field_colour_sz', name: 'BODY', colour: '#D62828' },
      { type: 'field_colour_sz', name: 'BASKET', colour: '#8a5a2b' },
    ],
    inputsInline: true,
    previousStatement: 'JSStmt',
    nextStatement: 'JSStmt',
    colour: C,
    tooltip:
      'Cria o BALÃO: um sprite comum com combustível próprio (começa com 100). Como é um sprite, os blocos de sprite funcionam nele (trocar a figura ou a imagem, por exemplo). Faça uma vez, no começo.',
  },
  {
    type: 'sz_g2d_balloonpath_create',
    placement: 'start-only-command',
    message0: 'Criar o caminho de árvores %1',
    args0: [{ type: 'field_input', name: 'NAME', text: 'caminho' }],
    previousStatement: 'JSStmt',
    nextStatement: 'JSStmt',
    colour: C,
    tooltip:
      'Cria o CAMINHO do voo (estilo balão de ar quente): as árvores que vêm pela frente e a contagem de metros. Faça uma vez, no começo.',
  },
  {
    type: 'sz_g2d_balloonpath_scenery',
    placement: 'command',
    message0: 'Desenhar o cenário do caminho %1 (céu, colinas, chão e árvores)',
    args0: [{ type: 'field_name_picker', name: 'PATH', text: 'caminho', kind: 'variable' }],
    previousStatement: 'JSStmt',
    nextStatement: 'JSStmt',
    colour: C,
    tooltip:
      'Desenha o fundo do voo no tamanho do palco. Use no começo do "a cada quadro", antes do balão.',
  },
  {
    type: 'sz_g2d_balloon_fire',
    placement: 'command',
    message0: 'Acender o fogo do balão %1 (força %2)',
    args0: [
      { type: 'field_sprite_picker', name: 'SPRITE', text: 'balao' },
      { type: 'input_value', name: 'FORCE', check: 'JSValue' },
    ],
    inputsInline: true,
    previousStatement: 'JSStmt',
    nextStatement: 'JSStmt',
    colour: C,
    tooltip:
      'O fogo empurra o balão para cima e gasta combustível (mais alto, mais gasto). Sem combustível, o fogo não acende. Monte a regra do mouse: se "o mouse ou dedo está segurado?" então acender o fogo. Use dentro do "a cada quadro".',
  },
  {
    type: 'sz_g2d_balloon_fly',
    placement: 'command',
    message0: 'Fazer o balão %1 voar e cair devagar',
    args0: [{ type: 'field_sprite_picker', name: 'SPRITE', text: 'balao' }],
    previousStatement: 'JSStmt',
    nextStatement: 'JSStmt',
    colour: C,
    tooltip:
      'A física do voo: sem o fogo aceso, o balão desce devagar e pousa no chão (nunca afunda). Use dentro do "a cada quadro", depois do fogo.',
  },
  {
    type: 'sz_g2d_balloonpath_scroll',
    placement: 'command',
    message0: 'Avançar o caminho %1 com o balão %2 (velocidade %3)',
    args0: [
      { type: 'field_name_picker', name: 'PATH', text: 'caminho', kind: 'variable' },
      { type: 'field_sprite_picker', name: 'SPRITE', text: 'balao' },
      { type: 'input_value', name: 'SPEED', check: 'JSValue' },
    ],
    inputsInline: true,
    previousStatement: 'JSStmt',
    nextStatement: 'JSStmt',
    colour: C,
    tooltip:
      'O mundo anda para trás enquanto o balão está no ar (parece voar para frente), os metros contam e o jogo confere se o balão encostou numa árvore. Use dentro do "a cada quadro", depois de voar.',
  },
  {
    type: 'sz_g2d_balloonpath_on_tree',
    placement: 'event',
    message0: 'Quando o balão bater numa árvore do caminho %1',
    args0: [{ type: 'field_name_picker', name: 'PATH', text: 'caminho', kind: 'variable' }],
    message1: 'fazer %1',
    args1: [{ type: 'input_statement', name: 'BODY' }],
    inputsInline: true,
    previousStatement: 'JSStmt',
    nextStatement: 'JSStmt',
    colour: EVENT_C,
    tooltip:
      'Registre UMA vez, fora do "a cada quadro". Quando o balão encostar numa árvore, o "fazer" roda: explosão, tremida e a SUA regra de fim de jogo (trocar de tela, por exemplo).',
  },
  {
    type: 'sz_g2d_balloonpath_meters',
    message0: 'os metros voados no caminho %1',
    args0: [{ type: 'field_name_picker', name: 'PATH', text: 'caminho', kind: 'variable' }],
    output: 'JSValue',
    colour: C,
    tooltip: 'A distância (em metros) que o balão já voou pelo caminho.',
  },
  {
    type: 'sz_g2d_balloon_fuel_left',
    message0: 'o combustível do balão %1',
    args0: [{ type: 'field_sprite_picker', name: 'SPRITE', text: 'balao' }],
    output: 'JSValue',
    colour: C,
    tooltip:
      'Quanto combustível resta no balão (0 a 100). Use com "Mostrar barra" ou num "se" para avisar quando estiver baixo.',
  },
  {
    type: 'sz_g2d_balloon_landed_out',
    message0: 'o balão %1 pousou sem combustível ?',
    args0: [{ type: 'field_sprite_picker', name: 'SPRITE', text: 'balao' }],
    output: 'JSValue',
    colour: C,
    tooltip:
      'Verdadeiro quando o combustível acabou e o balão pousou no chão (fim de jogo). Use num "se".',
  },
] satisfies BlockDefinition[]
