import type { BlockDefinition } from '../../blockly/blocks/types'
import {
  GAME_TWO_D_BLOCK_COLOR as C,
  GAME_TWO_D_EVENT_COLOR as EVENT_C,
} from './blockCatalogShared'

const ACTION_OPTIONS: Array<[string, string]> = [
  ['esquerda', 'left'],
  ['direita', 'right'],
  ['cima', 'up'],
  ['baixo', 'down'],
  ['pular', 'jump'],
  ['correr / agir', 'action'],
  ['selecionar', 'select'],
  ['começar', 'start'],
  ['pausar', 'pause'],
]

export const gameTwoDClassicBlocks: BlockDefinition[] = [
  {
    type: 'sz_g2d_enable_classic_controls',
    placement: 'start-only-command',
    message0: 'Ativar controles clássicos %1',
    args0: [
      {
        type: 'field_dropdown',
        name: 'MODE',
        options: [
          ['automáticos no celular', 'auto'],
          ['sempre visíveis', 'always'],
          ['sem botões na tela', 'off'],
        ],
      },
    ],
    previousStatement: 'JSStmt',
    nextStatement: 'JSStmt',
    colour: C,
    tooltip:
      'Liga teclado e botões de toque acessíveis. Aceita mais de um dedo para andar e pular ao mesmo tempo.',
  },
  {
    type: 'sz_g2d_action_down',
    message0: 'a ação %1 está sendo segurada?',
    args0: [{ type: 'field_dropdown', name: 'ACTION', options: [...ACTION_OPTIONS] }],
    output: 'JSValue',
    colour: EVENT_C,
    tooltip: 'Consulta uma ação do jogo sem depender de uma tecla específica.',
  },
  {
    type: 'sz_g2d_action_pressed',
    message0: 'a ação %1 acabou de ser apertada?',
    args0: [{ type: 'field_dropdown', name: 'ACTION', options: [...ACTION_OPTIONS] }],
    output: 'JSValue',
    colour: EVENT_C,
    tooltip: 'Verdadeiro durante um quadro na borda do aperto, sem repetir enquanto segura.',
  },
  {
    type: 'sz_g2d_on_action_pressed',
    placement: 'event',
    bodyExecution: 'deferred-callback',
    userGesture: true,
    message0: 'Quando a ação %1 for apertada',
    args0: [{ type: 'field_dropdown', name: 'ACTION', options: [...ACTION_OPTIONS] }],
    message1: 'fazer %1',
    args1: [{ type: 'input_statement', name: 'BODY' }],
    previousStatement: 'JSStmt',
    nextStatement: 'JSStmt',
    colour: EVENT_C,
    tooltip:
      'Roda para teclado, botões de toque e tecnologia assistiva. Também recebe a ação pausar enquanto o jogo está pausado.',
  },
  {
    type: 'sz_g2d_classic_platformer',
    placement: 'command',
    message0: 'Mover o sprite %1 como plataforma clássica, velocidade %2 pulo %3',
    args0: [
      { type: 'field_sprite_picker', name: 'SPRITE', text: 'heroi' },
      { type: 'input_value', name: 'SPEED', check: 'JSValue' },
      { type: 'input_value', name: 'JUMP', check: 'JSValue' },
    ],
    inputsInline: true,
    previousStatement: 'JSStmt',
    nextStatement: 'JSStmt',
    colour: C,
    tooltip:
      'Movimento completo com aceleração, corrida, derrapagem, agachamento, gravidade e altura variável do pulo. Colida com o Mundo depois.',
  },
  {
    type: 'sz_g2d_create_vector_tileset',
    placement: 'start-only-command',
    message0: 'Criar conjunto de tiles vetoriais %1 com tiles de %2 px',
    args0: [
      { type: 'field_input', name: 'NAME', text: 'tiles' },
      { type: 'input_value', name: 'SIZE', check: 'JSValue' },
    ],
    previousStatement: 'JSStmt',
    nextStatement: 'JSStmt',
    colour: C,
    tooltip: 'Cria um tileset desenhado pelas Figuras do projeto, sem imagens externas.',
  },
  {
    type: 'sz_g2d_define_vector_tile',
    placement: 'start-only-command',
    message0: 'No conjunto %1 definir tile %2 com a figura %3 como %4',
    args0: [
      { type: 'field_name_picker', name: 'TILESET', text: 'tiles', kind: 'g2d-vector-tileset' },
      { type: 'input_value', name: 'INDEX', check: 'JSValue' },
      { type: 'field_name_picker', name: 'SHAPE', text: 'bloco', kind: 'shape' },
      {
        type: 'field_dropdown',
        name: 'ROLE',
        options: [
          ['decoração', 'decor'],
          ['sólido', 'solid'],
          ['plataforma', 'platform'],
          ['atravessa e avisa', 'contact'],
        ],
      },
    ],
    inputsInline: true,
    previousStatement: 'JSStmt',
    nextStatement: 'JSStmt',
    colour: C,
    tooltip:
      'Associa um índice a uma Figura e diz o que ela faz: decoração não colide, sólido segura, plataforma só segura por cima. "Atravessa e avisa" deixa o herói passar e mesmo assim conta no "Para cada tile", que é como se faz moeda, lava e água.',
  },
  {
    type: 'sz_g2d_create_vector_tilemap',
    placement: 'start-only-command',
    message0: 'Criar mapa vetorial %1 com o conjunto %2 e grade %3',
    args0: [
      { type: 'field_input', name: 'NAME', text: 'mapa' },
      { type: 'field_name_picker', name: 'TILESET', text: 'tiles', kind: 'g2d-vector-tileset' },
      { type: 'field_tile_grid', name: 'GRID', text: '0 0 0 0;0 0 0 0' },
    ],
    previousStatement: 'JSStmt',
    nextStatement: 'JSStmt',
    colour: C,
    tooltip: 'Monta um mapa com a mesma geometria e colisão dos mapas de imagem.',
  },
  {
    type: 'sz_g2d_load_vector_campaign_level',
    placement: 'resource-creator',
    message0: 'Carregar fase %1 da campanha vetorial %2',
    args0: [
      { type: 'input_value', name: 'INDEX', check: 'JSValue' },
      { type: 'field_json_data', name: 'MANIFEST', text: '{"levels":[]}' },
    ],
    message1: 'com conjuntos %1 e tiles de %2 px; nascer em x %3 y %4',
    args1: [
      { type: 'field_input', name: 'TILESETS', text: 'tiles' },
      { type: 'input_value', name: 'SIZE', check: 'JSValue' },
      { type: 'input_value', name: 'X', check: 'JSValue' },
      { type: 'input_value', name: 'Y', check: 'JSValue' },
    ],
    message2: 'guardar mapa %1 Mundo %2 Fase %3',
    args2: [
      { type: 'field_name_picker', name: 'MAP', text: 'mapaAtual', kind: 'variable' },
      { type: 'field_name_picker', name: 'WORLD', text: 'mundoAtual', kind: 'variable' },
      { type: 'field_name_picker', name: 'LEVEL', text: 'faseAtual', kind: 'variable' },
    ],
    message3: 'soltar inimigos dos tipos %1 na jornada %2',
    args3: [
      { type: 'field_input', name: 'ENEMIES', text: '' },
      { type: 'input_value', name: 'JOURNEY', check: 'JSValue' },
    ],
    previousStatement: 'JSStmt',
    nextStatement: 'JSStmt',
    colour: C,
    tooltip:
      'Cria somente a fase escolhida. O JSON guarda grades, dados e elencos; assim campanhas grandes não enchem a bancada com milhares de blocos repetidos.',
  },
  {
    type: 'sz_g2d_campaign_value',
    message0: 'dado %1 da fase carregada (ou %2)',
    args0: [
      { type: 'field_input', name: 'KEY', text: 'mundo' },
      { type: 'input_value', name: 'FALLBACK', check: 'JSValue' },
    ],
    inputsInline: true,
    output: 'JSValue',
    colour: C,
    tooltip:
      'Lê um dado da fase atual no JSON da campanha. Usa o valor alternativo quando o campo não existe.',
  },
  {
    type: 'sz_g2d_for_each_tile_contact',
    placement: 'command',
    bodyExecution: 'sync-callback',
    message0: 'Para cada tile que %1 toca no lado %2 do mapa %3 chamar de %4',
    args0: [
      { type: 'field_sprite_picker', name: 'SPRITE', text: 'heroi' },
      {
        type: 'field_dropdown',
        name: 'SIDE',
        options: [
          ['qualquer', 'any'],
          ['cabeça', 'head'],
          ['pés', 'feet'],
          ['esquerda', 'left'],
          ['direita', 'right'],
          ['dentro', 'inside'],
        ],
      },
      { type: 'field_name_picker', name: 'MAP', text: 'mapa', kind: 'tilemap' },
      { type: 'field_input', name: 'CONTACT', text: 'contato' },
    ],
    message1: 'fazer %1',
    args1: [{ type: 'input_statement', name: 'BODY' }],
    previousStatement: 'JSStmt',
    nextStatement: 'JSStmt',
    colour: EVENT_C,
    tooltip:
      'Depois da colisão, percorre cada tile exato atingido e informa o lado. Útil para blocos quebráveis e surpresas. O lado "dentro" é o das peças que se ATRAVESSA (moeda, lava, água) e só existe no mapa vetorial.',
  },
  {
    type: 'sz_g2d_tile_contact_is',
    message0: 'o contato %1 é com o tile %2?',
    args0: [
      { type: 'field_input', name: 'CONTACT', text: 'contato' },
      { type: 'input_value', name: 'INDEX', check: 'JSValue' },
    ],
    inputsInline: true,
    output: 'JSValue',
    colour: EVENT_C,
    tooltip: 'Compara o índice original do tile atingido antes de decidir a recompensa ou mudança.',
  },
  {
    type: 'sz_g2d_set_tile_at_contact',
    placement: 'command',
    message0: 'No contato %1 trocar o tile para %2',
    args0: [
      { type: 'field_input', name: 'CONTACT', text: 'contato' },
      { type: 'input_value', name: 'INDEX', check: 'JSValue' },
    ],
    previousStatement: 'JSStmt',
    nextStatement: 'JSStmt',
    colour: C,
    tooltip: 'Muda exatamente o tile informado pelo contato; -1 quebra/remove.',
  },
  {
    type: 'sz_g2d_set_enemy_stomp_mode',
    placement: 'start-only-command',
    message0: 'Ao pisar no tipo %1 usar modo %2',
    args0: [
      { type: 'field_name_picker', name: 'TYPE', text: 'inimigos', kind: 'enemytype' },
      {
        type: 'field_dropdown',
        name: 'MODE',
        options: [
          ['derrotar', 'defeat'],
          ['causar 1 de dano', 'damage'],
          ['achatar por um instante', 'squash'],
          ['virar casco (pisar recolhe, encostar chuta)', 'shell'],
          ['espinhoso (não aceita pisada)', 'spiky'],
        ],
      },
    ],
    previousStatement: 'JSStmt',
    nextStatement: 'JSStmt',
    colour: C,
    tooltip:
      'Escolhe o que acontece quando o sprite pisa neste tipo de inimigo. Precisa do bloco “Derrotar os inimigos do tipo … quando o sprite … pular em cima”; sem ele nada muda. Ponha em ⚙️ Ao iniciar.',
  },
  {
    type: 'sz_g2d_update_enemy_shells',
    placement: 'command',
    message0: 'Atualizar os cascos do tipo %1 no Mundo %2',
    args0: [
      { type: 'field_name_picker', name: 'TYPE', text: 'inimigos', kind: 'enemytype' },
      { type: 'field_name_picker', name: 'WORLD', text: 'mundo', kind: 'g2d-world' },
    ],
    previousStatement: 'JSStmt',
    nextStatement: 'JSStmt',
    colour: C,
    tooltip:
      'Obrigatório no modo “virar casco”: é este bloco que faz o casco andar, cair, rebater nas paredes do Mundo e derrotar quem ele atingir. Sem ele o casco fica parado para sempre. Ponha no “A cada quadro do jogo”.',
  },
  {
    type: 'sz_g2d_draw_pixel_text',
    placement: 'command',
    message0: 'Escrever texto pixel %1 em x %2 y %3 pixel %4 cor %5 alinhado %6',
    args0: [
      { type: 'field_input', name: 'TEXT', text: 'REINO ZERO' },
      { type: 'input_value', name: 'X', check: 'JSValue' },
      { type: 'input_value', name: 'Y', check: 'JSValue' },
      { type: 'input_value', name: 'SIZE', check: 'JSValue' },
      { type: 'field_colour_sz', name: 'COLOR', colour: '#ffffff' },
      {
        type: 'field_dropdown',
        name: 'ALIGN',
        options: [
          ['à esquerda', 'left'],
          ['no centro', 'center'],
          ['à direita', 'right'],
        ],
      },
    ],
    inputsInline: true,
    previousStatement: 'JSStmt',
    nextStatement: 'JSStmt',
    colour: C,
    tooltip: 'Desenha letras em uma grade 5×7 no canvas, sem carregar fonte.',
  },
  {
    type: 'sz_g2d_paint_shape_recipe',
    placement: 'command',
    message0: 'Desenhar receita vetorial %1',
    args0: [{ type: 'field_json_data', name: 'RECIPE', text: '[]' }],
    previousStatement: 'JSStmt',
    nextStatement: 'JSStmt',
    colour: C,
    tooltip:
      'Desenha várias formas fixas de uma só vez. Útil para figuras detalhadas sem criar centenas de blocos de coordenadas.',
  },
  {
    type: 'sz_g2d_draw_pixel_score',
    placement: 'command',
    message0: 'Escrever placar pixel %1 com o valor %2 em x %3 y %4 pixel %5 cor %6',
    args0: [
      { type: 'field_input', name: 'LABEL', text: 'PONTOS' },
      { type: 'input_value', name: 'VALUE', check: 'JSValue' },
      { type: 'input_value', name: 'X', check: 'JSValue' },
      { type: 'input_value', name: 'Y', check: 'JSValue' },
      { type: 'input_value', name: 'SIZE', check: 'JSValue' },
      { type: 'field_colour_sz', name: 'COLOR', colour: '#ffffff' },
    ],
    inputsInline: true,
    previousStatement: 'JSStmt',
    nextStatement: 'JSStmt',
    colour: C,
    tooltip:
      'Escreve um campo do placar na mesma fonte de pixel das telas: o nome em cima e o número embaixo. Use este quando o valor for uma variável, porque o "Escrever texto pixel" só aceita texto fixo.',
  },
  {
    type: 'sz_g2d_draw_fade',
    placement: 'command',
    message0: 'Cobrir a tela com fade de %1 por cento na cor %2',
    args0: [
      { type: 'input_value', name: 'PERCENT', check: 'JSValue' },
      { type: 'field_colour_sz', name: 'COLOR', colour: '#000000' },
    ],
    previousStatement: 'JSStmt',
    nextStatement: 'JSStmt',
    colour: C,
    tooltip: 'Desenha uma cobertura de 0 a 100% para transições de cena.',
  },
]
