import type { BlockDefinition } from '../../blockly/blocks/types'
import {
  GAME_TWO_D_BLOCK_COLOR as C,
  GAME_TWO_D_EVENT_COLOR as EVENT_C,
} from './blockCatalogShared'

export const gameTwoDFundamentalBlocks = [
  {
    type: 'sz_g2d_create_sprite',
    placement: 'start-only-command',
    message0: 'Criar sprite %1 em x %2 y %3 largura %4 altura %5 cor %6',
    args0: [
      { type: 'field_input', name: 'NAME', text: 'jogador' },
      { type: 'input_value', name: 'X', check: 'JSValue' },
      { type: 'input_value', name: 'Y', check: 'JSValue' },
      { type: 'input_value', name: 'W', check: 'JSValue' },
      { type: 'input_value', name: 'H', check: 'JSValue' },
      { type: 'field_colour_sz', name: 'COLOR', colour: '#22d3ee' },
    ],
    inputsInline: true,
    previousStatement: 'JSStmt',
    nextStatement: 'JSStmt',
    colour: C,
    tooltip:
      'Cria um personagem ou objeto retangular e guarda pelo nome escolhido. Faça isso uma vez em “Ao iniciar”.',
  },
  {
    type: 'sz_g2d_draw_sprite',
    placement: 'command',
    message0: 'Desenhar o sprite %1',
    args0: [{ type: 'field_sprite_picker', name: 'SPRITE', text: 'jogador' }],
    previousStatement: 'JSStmt',
    nextStatement: 'JSStmt',
    colour: C,
    tooltip: 'Desenha o sprite na tela do jogo. Use a cada quadro, depois de "Limpar a tela".',
  },
  {
    type: 'sz_g2d_set_position',
    placement: 'command',
    message0: 'Mudar a posição do sprite %1 para x %2 y %3',
    args0: [
      { type: 'field_sprite_picker', name: 'SPRITE', text: 'jogador' },
      { type: 'input_value', name: 'X', check: 'JSValue' },
      { type: 'input_value', name: 'Y', check: 'JSValue' },
    ],
    inputsInline: true,
    previousStatement: 'JSStmt',
    nextStatement: 'JSStmt',
    colour: C,
    tooltip: 'Leva o sprite para as coordenadas x e y escolhidas.',
  },
  {
    type: 'sz_g2d_set_velocity',
    placement: 'command',
    message0: 'Mudar a velocidade do sprite %1 para vx %2 vy %3',
    args0: [
      { type: 'field_sprite_picker', name: 'SPRITE', text: 'jogador' },
      { type: 'input_value', name: 'VX', check: 'JSValue' },
      { type: 'input_value', name: 'VY', check: 'JSValue' },
    ],
    inputsInline: true,
    previousStatement: 'JSStmt',
    nextStatement: 'JSStmt',
    colour: C,
    tooltip: 'Define quanto o sprite anda na horizontal (vx) e na vertical (vy) a cada quadro.',
  },
  {
    type: 'sz_g2d_collides',
    placement: 'command',
    message0: 'Guardar em %1 se sprite %2 colide com sprite %3',
    args0: [
      { type: 'field_input', name: 'NAME', text: 'bateu' },
      { type: 'field_sprite_picker', name: 'A', text: 'jogador' },
      { type: 'field_sprite_picker', name: 'B', text: 'inimigo' },
    ],
    previousStatement: 'JSStmt',
    nextStatement: 'JSStmt',
    colour: C,
    tooltip: 'Compara dois sprites e guarda sim ou não na variável escolhida.',
  },
  {
    type: 'sz_g2d_score',
    placement: 'start-only-command',
    message0: 'Criar pontuação %1 começando em %2',
    args0: [
      { type: 'field_input', name: 'NAME', text: 'pontos' },
      { type: 'input_value', name: 'INITIAL', check: 'JSValue' },
    ],
    inputsInline: true,
    previousStatement: 'JSStmt',
    nextStatement: 'JSStmt',
    colour: C,
    tooltip: 'Cria uma variável de pontuação com o valor inicial escolhido.',
  },
  {
    type: 'sz_g2d_game_over',
    placement: 'command',
    message0: 'Mostrar fim de jogo com o texto %1',
    args0: [{ type: 'input_value', name: 'TEXT', check: 'JSValue' }],
    inputsInline: true,
    previousStatement: 'JSStmt',
    nextStatement: 'JSStmt',
    colour: C,
    tooltip: 'Escreve um texto grande na tela (ex.: ao perder ou vencer).',
  },
  {
    type: 'sz_g2d_on_start',
    placement: 'legacy-start',
    migration: 'unwrap-start',
    message0: 'Quando o jogo começar',
    message1: 'preparar %1',
    args1: [{ type: 'input_statement', name: 'BODY' }],
    previousStatement: 'JSStmt',
    nextStatement: 'JSStmt',
    colour: EVENT_C,
    hidden: true,
    tooltip:
      'Bloco antigo mantido apenas para abrir projetos salvos. Em projetos novos, use “⚙️ Ao iniciar”, “⚡ Quando acontecer” e “🔁 Enquanto estiver rodando”.',
  },
  {
    type: 'sz_g2d_update_each_frame',
    placement: 'loop-update',
    message0: 'A cada quadro do jogo',
    message1: 'fazer %1',
    args1: [{ type: 'input_statement', name: 'BODY' }],
    inputsInline: true,
    previousStatement: 'JSStmt',
    nextStatement: 'JSStmt',
    colour: C,
    tooltip: 'Repete o que está dentro a cada quadro (≈60 vezes por segundo), é o coração do jogo.',
  },
  {
    type: 'sz_g2d_clear',
    placement: 'command',
    message0: 'Limpar a tela',
    args0: [],
    previousStatement: 'JSStmt',
    nextStatement: 'JSStmt',
    colour: C,
    tooltip:
      'Apaga tudo o que foi desenhado. Use no começo de cada quadro, antes de desenhar de novo.',
  },

  // ---- Física ----
  {
    type: 'sz_g2d_set_gravity',
    placement: 'command',
    message0: 'Botar a gravidade do mundo em %1',
    args0: [{ type: 'input_value', name: 'VALUE', check: 'JSValue' }],
    inputsInline: true,
    previousStatement: 'JSStmt',
    nextStatement: 'JSStmt',
    colour: C,
    tooltip:
      'Define a gravidade do mundo para física, plataforma, pulo e inimigos terrestres. Use 0 para desligar ou um valor negativo para puxar para cima.',
  },
  {
    type: 'sz_g2d_apply_velocity',
    placement: 'command',
    message0: 'Aplicar velocidade e gravidade ao sprite %1',
    args0: [{ type: 'field_sprite_picker', name: 'SPRITE', text: 'jogador' }],
    previousStatement: 'JSStmt',
    nextStatement: 'JSStmt',
    colour: C,
    tooltip: 'Move o sprite pela sua velocidade (vx/vy) e soma a gravidade ao vy.',
  },
  {
    type: 'sz_g2d_bounce_edges',
    placement: 'command',
    message0: 'Quicar o sprite %1 nas bordas da tela',
    args0: [{ type: 'field_sprite_picker', name: 'SPRITE', text: 'bola' }],
    previousStatement: 'JSStmt',
    nextStatement: 'JSStmt',
    colour: C,
    tooltip: 'Faz o sprite quicar nas bordas da tela, invertendo a velocidade.',
  },
  {
    type: 'sz_g2d_circle_collides',
    placement: 'command',
    message0: 'Guardar em %1 se sprite %2 encosta no sprite %3 (em círculo)',
    args0: [
      { type: 'field_input', name: 'NAME', text: 'bateu' },
      { type: 'field_sprite_picker', name: 'A', text: 'jogador' },
      { type: 'field_sprite_picker', name: 'B', text: 'inimigo' },
    ],
    previousStatement: 'JSStmt',
    nextStatement: 'JSStmt',
    colour: C,
    tooltip: 'Colisão por círculo (mais justa para objetos redondos que a caixa retangular).',
  },
  {
    type: 'sz_g2d_set_hitbox_scale',
    placement: 'command',
    message0: 'Usar área de colisão de %1 % do tamanho para o sprite %2',
    args0: [
      { type: 'input_value', name: 'PERCENT', check: 'JSValue' },
      { type: 'field_sprite_picker', name: 'SPRITE', text: 'jogador' },
    ],
    inputsInline: true,
    previousStatement: 'JSStmt',
    nextStatement: 'JSStmt',
    colour: C,
    tooltip:
      'Muda o tamanho da área de colisão do sprite: menor que 100% = colisão mais justa para DANO; maior = mais fácil de PEGAR (moedas). Vale para as perguntas de encostar; "impedir de atravessar" continua usando o tamanho cheio. Veja a área real com "Mostrar a caixa de colisão".',
  },

  // ---- Áudio ----
  {
    type: 'sz_g2d_play_sound',
    placement: 'command',
    message0: 'Tocar som de %1 Hz por %2 ms',
    args0: [
      { type: 'input_value', name: 'FREQ', check: 'JSValue' },
      { type: 'input_value', name: 'MS', check: 'JSValue' },
    ],
    inputsInline: true,
    previousStatement: 'JSStmt',
    nextStatement: 'JSStmt',
    colour: C,
    tooltip:
      'Toca um bip sintetizado (sem precisar de arquivo). Ex.: 440 Hz = lá; agudo = número maior.',
  },
  {
    type: 'sz_g2d_play_fx',
    placement: 'command',
    message0: 'Tocar efeito %1',
    args0: [
      {
        type: 'field_dropdown',
        name: 'FX',
        options: [
          ['moeda', 'coin'],
          ['joia', 'gem'],
          ['vida', 'heal'],
          ['power-up', 'powerup'],
          ['subir de nível', 'levelup'],
          ['coletar', 'collect'],
          ['tiro', 'laser'],
          ['tiro grande', 'shoot'],
          ['explosão', 'explosion'],
          ['batida', 'hit'],
          ['dano', 'hurt'],
          ['socar', 'punch'],
          ['pulo', 'jump'],
          ['aterrissar', 'land'],
          ['zunido', 'whoosh'],
          ['passo', 'step'],
          ['quicar', 'bounce'],
          ['assobio', 'whistle'],
          ['vitória', 'win'],
          ['derrota', 'gameover'],
          ['começar', 'start'],
          ['alarme', 'alarm'],
          ['clique', 'click'],
          ['confirmar', 'confirm'],
          ['erro', 'error'],
          ['selecionar', 'select'],
          ['aviso', 'blip'],
        ],
      },
    ],
    previousStatement: 'JSStmt',
    nextStatement: 'JSStmt',
    colour: C,
    tooltip: 'Toca um efeito sonoro pronto (sintetizado, sem arquivo). Escolha um no menu.',
  },
  {
    type: 'sz_g2d_play_note',
    placement: 'command',
    message0: 'Tocar a nota %1 por %2 ms',
    args0: [
      {
        type: 'field_dropdown',
        name: 'NOTE',
        options: [
          ['dó', 'C'],
          ['ré', 'D'],
          ['mi', 'E'],
          ['fá', 'F'],
          ['sol', 'G'],
          ['lá', 'A'],
          ['si', 'B'],
          ['dó agudo', 'C5'],
        ],
      },
      { type: 'input_value', name: 'MS', check: 'JSValue' },
    ],
    inputsInline: true,
    previousStatement: 'JSStmt',
    nextStatement: 'JSStmt',
    colour: C,
    tooltip: 'Toca uma nota musical (dó, ré, mi…). Junte várias para fazer uma melodia.',
  },
  {
    type: 'sz_g2d_play_music',
    placement: 'resource-creator',
    message0: 'Tocar música de fundo %1',
    args0: [
      {
        type: 'field_dropdown',
        name: 'MUSIC',
        options: [
          ['aventura', 'adventure'],
          ['alegre', 'happy'],
          ['tensão', 'tense'],
          ['calma', 'calm'],
          ['vitória', 'victory'],
        ],
      },
    ],
    previousStatement: 'JSStmt',
    nextStatement: 'JSStmt',
    colour: C,
    tooltip:
      'Toca uma musiquinha de fundo em loop. Use em “Ao iniciar”, “Quando acontecer” ou numa função, nunca em “Enquanto estiver rodando”. Repetir a mesma música não recomeça a faixa.',
  },
  {
    type: 'sz_g2d_stop_music',
    placement: 'command',
    message0: 'Parar a música de fundo',
    previousStatement: 'JSStmt',
    nextStatement: 'JSStmt',
    colour: C,
    tooltip: 'Para a música de fundo que estiver tocando.',
  },

  // ---- Tier 1: Mira e contas ----
  {
    type: 'sz_g2d_aim_at',
    placement: 'command',
    message0: 'Apontar o sprite %1 para o sprite %2',
    args0: [
      { type: 'field_sprite_picker', name: 'SPRITE', text: 'nave' },
      { type: 'field_sprite_picker', name: 'TARGET', text: 'inimigo' },
    ],
    previousStatement: 'JSStmt',
    nextStatement: 'JSStmt',
    colour: C,
    tooltip: 'Gira o sprite para ficar de frente para o alvo.',
  },
  {
    type: 'sz_g2d_move_toward',
    placement: 'command',
    message0: 'Mover o sprite %1 na direção do sprite %2 com velocidade %3',
    args0: [
      { type: 'field_sprite_picker', name: 'SPRITE', text: 'inimigo' },
      { type: 'field_sprite_picker', name: 'TARGET', text: 'jogador' },
      { type: 'input_value', name: 'SPEED', check: 'JSValue' },
    ],
    inputsInline: true,
    previousStatement: 'JSStmt',
    nextStatement: 'JSStmt',
    colour: C,
    tooltip: 'Faz o sprite perseguir o alvo, andando um pouquinho na direção dele a cada quadro.',
  },
  {
    type: 'sz_g2d_distance',
    message0: 'a distância entre o sprite %1 e o sprite %2',
    args0: [
      { type: 'field_sprite_picker', name: 'A', text: 'jogador' },
      { type: 'field_sprite_picker', name: 'B', text: 'inimigo' },
    ],
    output: 'JSValue',
    colour: C,
    tooltip: 'Quantos pixels separam os dois sprites (pelos centros). Use numa conta ou num "se".',
  },
  {
    type: 'sz_g2d_angle_to',
    message0: 'o ângulo (em graus) do sprite %1 até o sprite %2',
    args0: [
      { type: 'field_sprite_picker', name: 'A', text: 'nave' },
      { type: 'field_sprite_picker', name: 'B', text: 'inimigo' },
    ],
    output: 'JSValue',
    colour: C,
    tooltip: 'A direção (0 = pra cima, horário) do primeiro sprite até o segundo.',
  },
  {
    type: 'sz_g2d_random_between',
    message0: 'um número de %1 a %2',
    args0: [
      { type: 'input_value', name: 'MIN', check: 'JSValue' },
      { type: 'input_value', name: 'MAX', check: 'JSValue' },
    ],
    inputsInline: true,
    output: 'JSValue',
    colour: C,
    tooltip:
      'Sorteia um número inteiro entre os dois valores (incluindo as pontas). Limites com vírgula são ajustados para os inteiros internos; se o intervalo não tiver nenhum inteiro, usa o mais próximo do meio.',
  },
  {
    type: 'sz_g2d_random_chance',
    message0: 'tem chance de %1%%?',
    args0: [{ type: 'input_value', name: 'PERCENT', check: 'JSValue' }],
    inputsInline: true,
    output: 'JSValue',
    colour: EVENT_C,
    tooltip:
      'Verdadeiro com a chance escolhida. Ex.: 30 = acontece em ~30% das vezes. Use num "se".',
  },
  {
    type: 'sz_g2d_random_x',
    message0: 'um x aleatório para largura %1',
    args0: [{ type: 'input_value', name: 'SIZE', check: 'JSValue' }],
    output: 'JSValue',
    colour: C,
    tooltip:
      'Sorteia uma posição x onde essa largura inteira cabe na tela. Ligue “a largura do sprite” para ele não nascer cortado na borda.',
  },
  {
    type: 'sz_g2d_random_y',
    message0: 'um y aleatório para altura %1',
    args0: [{ type: 'input_value', name: 'SIZE', check: 'JSValue' }],
    output: 'JSValue',
    colour: C,
    tooltip:
      'Sorteia uma posição y onde essa altura inteira cabe na tela. Ligue “a altura do sprite” para ele não nascer cortado na borda.',
  },

  // ---- Tier 1: Vida e tempo ----
  {
    type: 'sz_g2d_set_health',
    placement: 'start-only-command',
    message0: 'Dar ao sprite %1 %2 de vida',
    args0: [
      { type: 'field_sprite_picker', name: 'SPRITE', text: 'jogador' },
      { type: 'input_value', name: 'AMOUNT', check: 'JSValue' },
    ],
    inputsInline: true,
    previousStatement: 'JSStmt',
    nextStatement: 'JSStmt',
    colour: C,
    tooltip:
      'Define a vida atual e a vida máxima do sprite. Coloque em “Ao iniciar” para não restaurar a vida a cada quadro.',
  },
  {
    type: 'sz_g2d_change_health',
    placement: 'command',
    message0: 'Mudar a vida do sprite %1 em %2',
    args0: [
      { type: 'field_sprite_picker', name: 'SPRITE', text: 'jogador' },
      { type: 'input_value', name: 'DELTA', check: 'JSValue' },
    ],
    inputsInline: true,
    previousStatement: 'JSStmt',
    nextStatement: 'JSStmt',
    colour: C,
    tooltip:
      'Soma à vida do sprite (número negativo tira vida). Não passa do máximo nem fica abaixo de 0.',
  },
  {
    type: 'sz_g2d_damage_sprite',
    placement: 'command',
    message0: 'Machucar o sprite %1 em %2 e deixá-lo invencível por %3 quadros',
    args0: [
      { type: 'field_sprite_picker', name: 'SPRITE', text: 'jogador' },
      { type: 'input_value', name: 'AMOUNT', check: 'JSValue' },
      { type: 'input_value', name: 'FRAMES', check: 'JSValue' },
    ],
    inputsInline: true,
    previousStatement: 'JSStmt',
    nextStatement: 'JSStmt',
    colour: C,
    tooltip:
      'Tira vida uma vez e ignora novos danos enquanto o sprite pisca. Evita perder todas as vidas num contato contínuo.',
  },
  {
    type: 'sz_g2d_get_health',
    message0: 'a vida do sprite %1',
    args0: [{ type: 'field_sprite_picker', name: 'SPRITE', text: 'jogador' }],
    output: 'JSValue',
    colour: C,
    tooltip: 'Quanto de vida o sprite tem agora.',
  },
  {
    type: 'sz_g2d_get_max_health',
    message0: 'a vida máxima do sprite %1',
    args0: [{ type: 'field_sprite_picker', name: 'SPRITE', text: 'jogador' }],
    output: 'JSValue',
    colour: C,
    tooltip: 'Quanto de vida o sprite recebeu em “Ao iniciar”.',
  },
  {
    type: 'sz_g2d_has_health',
    message0: 'o sprite %1 ainda tem vida?',
    args0: [{ type: 'field_sprite_picker', name: 'SPRITE', text: 'jogador' }],
    output: 'JSValue',
    colour: EVENT_C,
    tooltip: 'Verdadeiro enquanto a vida do sprite é maior que zero. Use num "se".',
  },
  {
    type: 'sz_g2d_health_depleted',
    message0: 'as vidas do sprite %1 acabaram?',
    args0: [{ type: 'field_sprite_picker', name: 'SPRITE', text: 'jogador' }],
    output: 'JSValue',
    colour: EVENT_C,
    tooltip:
      'Verdadeiro quando a vida foi preparada e chegou a zero. Assim você não precisa usar o bloco “não”.',
  },
  {
    type: 'sz_g2d_is_invincible',
    message0: 'o sprite %1 está invencível?',
    args0: [{ type: 'field_sprite_picker', name: 'SPRITE', text: 'jogador' }],
    output: 'JSValue',
    colour: EVENT_C,
    tooltip:
      'Verdadeiro enquanto o sprite está piscando e não pode receber outro dano. Use com “não” para fazer um efeito só quando o dano puder acontecer.',
  },
  {
    type: 'sz_g2d_draw_sprite_health',
    placement: 'command',
    message0: 'Desenhar as vidas do sprite %1 como %2 em x %3 y %4 tamanho %5 cor %6',
    args0: [
      { type: 'field_sprite_picker', name: 'SPRITE', text: 'jogador' },
      {
        type: 'field_dropdown',
        name: 'STYLE',
        options: [
          ['corações', 'hearts'],
          ['barra', 'bar'],
        ],
      },
      { type: 'input_value', name: 'X', check: 'JSValue' },
      { type: 'input_value', name: 'Y', check: 'JSValue' },
      { type: 'input_value', name: 'SIZE', check: 'JSValue' },
      { type: 'field_colour_sz', name: 'COLOR', colour: '#ff5d5d' },
    ],
    inputsInline: true,
    previousStatement: 'JSStmt',
    nextStatement: 'JSStmt',
    colour: C,
    tooltip:
      'Lê a vida do sprite automaticamente. Em corações, tamanho é o diâmetro; em barra, é a largura.',
  },
  {
    type: 'sz_g2d_cooldown_ready',
    message0: 'o sprite %1 pode agir? (recarga de %2 quadros)',
    args0: [
      { type: 'field_sprite_picker', name: 'SPRITE', text: 'nave' },
      { type: 'input_value', name: 'FRAMES', check: 'JSValue' },
    ],
    inputsInline: true,
    output: 'JSValue',
    colour: EVENT_C,
    tooltip: 'Verdadeiro no máximo a cada N quadros (ótimo para a cadência de tiro). Use num "se".',
  },
  {
    type: 'sz_g2d_prune_old',
    placement: 'command',
    message0: 'Tirar do grupo %1 quem viveu mais de %2 segundos',
    args0: [
      { type: 'field_name_picker', name: 'GROUP', text: 'tiros', kind: 'group' },
      { type: 'input_value', name: 'SECONDS', check: 'JSValue' },
    ],
    inputsInline: true,
    previousStatement: 'JSStmt',
    nextStatement: 'JSStmt',
    colour: C,
    tooltip: 'Remove do grupo os sprites mais velhos que o tempo dado (tiros somem sozinhos).',
  },

  // ---- Posição & tamanho do sprite (valores prontos p/ facilitar contas) ----
  {
    type: 'sz_g2d_sprite_x',
    message0: 'a posição x do sprite %1',
    args0: [{ type: 'field_sprite_picker', name: 'SPRITE', text: 'jogador' }],
    output: 'JSValue',
    colour: C,
    tooltip:
      'A posição x (borda esquerda) do sprite. Use numa conta ou pra posicionar outra coisa.',
  },
  {
    type: 'sz_g2d_sprite_y',
    message0: 'a posição y do sprite %1',
    args0: [{ type: 'field_sprite_picker', name: 'SPRITE', text: 'jogador' }],
    output: 'JSValue',
    colour: C,
    tooltip: 'A posição y (borda de cima) do sprite. Use numa conta ou pra posicionar outra coisa.',
  },
  {
    type: 'sz_g2d_sprite_w',
    message0: 'a largura do sprite %1',
    args0: [{ type: 'field_sprite_picker', name: 'SPRITE', text: 'jogador' }],
    output: 'JSValue',
    colour: C,
    tooltip: 'A largura do sprite, em pixels.',
  },
  {
    type: 'sz_g2d_sprite_h',
    message0: 'a altura do sprite %1',
    args0: [{ type: 'field_sprite_picker', name: 'SPRITE', text: 'jogador' }],
    output: 'JSValue',
    colour: C,
    tooltip: 'A altura do sprite, em pixels.',
  },
  {
    type: 'sz_g2d_center_x',
    message0: 'o centro x do sprite %1',
    args0: [{ type: 'field_sprite_picker', name: 'SPRITE', text: 'jogador' }],
    output: 'JSValue',
    colour: C,
    tooltip:
      'O x do MEIO do sprite (já soma metade da largura). Ótimo pra atirar/mirar do centro da nave.',
  },
  {
    type: 'sz_g2d_center_y',
    message0: 'o centro y do sprite %1',
    args0: [{ type: 'field_sprite_picker', name: 'SPRITE', text: 'jogador' }],
    output: 'JSValue',
    colour: C,
    tooltip:
      'O y do MEIO do sprite (já soma metade da altura). Ótimo pra atirar/mirar do centro da nave.',
  },

  // ---- Velocidade & movimento do sprite (valores prontos p/ decidir) ----
  {
    type: 'sz_g2d_sprite_vx',
    message0: 'a velocidade x do sprite %1',
    args0: [{ type: 'field_sprite_picker', name: 'SPRITE', text: 'jogador' }],
    output: 'JSValue',
    colour: C,
    tooltip:
      'A velocidade horizontal (vx) do sprite: positiva = indo pra direita, negativa = pra esquerda, 0 = parado na horizontal.',
  },
  {
    type: 'sz_g2d_sprite_vy',
    message0: 'a velocidade y do sprite %1',
    args0: [{ type: 'field_sprite_picker', name: 'SPRITE', text: 'jogador' }],
    output: 'JSValue',
    colour: C,
    tooltip:
      'A velocidade vertical (vy) do sprite: positiva = descendo, negativa = subindo, 0 = parado na vertical.',
  },
  {
    type: 'sz_g2d_sprite_speed',
    message0: 'a velocidade total do sprite %1',
    args0: [{ type: 'field_sprite_picker', name: 'SPRITE', text: 'jogador' }],
    output: 'JSValue',
    colour: C,
    tooltip: 'O quão rápido o sprite se move (junta vx e vy). É sempre 0 ou positivo.',
  },
  {
    type: 'sz_g2d_is_moving',
    message0: 'o sprite %1 está se movendo?',
    args0: [{ type: 'field_sprite_picker', name: 'SPRITE', text: 'jogador' }],
    output: 'JSValue',
    colour: C,
    tooltip: 'Verdadeiro quando o sprite tem alguma velocidade (na horizontal ou na vertical).',
  },
  {
    type: 'sz_g2d_is_moving_h',
    message0: 'o sprite %1 está se movendo na horizontal?',
    args0: [{ type: 'field_sprite_picker', name: 'SPRITE', text: 'jogador' }],
    output: 'JSValue',
    colour: C,
    tooltip: 'Verdadeiro quando o sprite anda para os lados (vx diferente de zero).',
  },
  {
    type: 'sz_g2d_is_moving_v',
    message0: 'o sprite %1 está se movendo na vertical?',
    args0: [{ type: 'field_sprite_picker', name: 'SPRITE', text: 'jogador' }],
    output: 'JSValue',
    colour: C,
    tooltip: 'Verdadeiro quando o sprite sobe ou desce (vy diferente de zero).',
  },

  // ---- Tier 1: Aparência (espelhar, transparência, tamanho) ----
  {
    type: 'sz_g2d_flip_sprite',
    placement: 'command',
    message0: 'Virar o sprite %1 para %2',
    args0: [
      { type: 'field_sprite_picker', name: 'SPRITE', text: 'jogador' },
      {
        type: 'field_dropdown',
        name: 'DIR',
        options: [
          ['esquerda', 'left'],
          ['direita', 'right'],
        ],
      },
    ],
    previousStatement: 'JSStmt',
    nextStatement: 'JSStmt',
    colour: C,
    tooltip: 'Espelha o desenho do sprite na horizontal (para ele "olhar" para o outro lado).',
  },
  {
    type: 'sz_g2d_set_opacity',
    placement: 'command',
    message0: 'Mudar a transparência do sprite %1 para %2 %',
    args0: [
      { type: 'field_sprite_picker', name: 'SPRITE', text: 'jogador' },
      { type: 'input_value', name: 'PERCENT', check: 'JSValue' },
    ],
    inputsInline: true,
    previousStatement: 'JSStmt',
    nextStatement: 'JSStmt',
    colour: C,
    tooltip: '100% = totalmente visível; 0% = invisível. Bom para fantasmas, fades e piscadas.',
  },
  {
    type: 'sz_g2d_set_size',
    placement: 'command',
    message0: 'Mudar o tamanho do sprite %1 para largura %2 altura %3',
    args0: [
      { type: 'field_sprite_picker', name: 'SPRITE', text: 'jogador' },
      { type: 'input_value', name: 'W', check: 'JSValue' },
      { type: 'input_value', name: 'H', check: 'JSValue' },
    ],
    inputsInline: true,
    previousStatement: 'JSStmt',
    nextStatement: 'JSStmt',
    colour: C,
    tooltip: 'Define a largura e a altura do sprite (a colisão acompanha o novo tamanho).',
  },
  {
    type: 'sz_g2d_scale_sprite',
    placement: 'command',
    message0: 'Multiplicar o tamanho do sprite %1 por %2',
    args0: [
      { type: 'field_sprite_picker', name: 'SPRITE', text: 'jogador' },
      { type: 'input_value', name: 'FACTOR', check: 'JSValue' },
    ],
    inputsInline: true,
    previousStatement: 'JSStmt',
    nextStatement: 'JSStmt',
    colour: C,
    tooltip: 'Cresce (maior que 1) ou encolhe (menor que 1) o sprite a partir do centro.',
  },

  // ---- Tier 1: Mundo ----
  {
    type: 'sz_g2d_wrap_edges',
    placement: 'command',
    message0: 'Dar a volta na tela com o sprite %1',
    args0: [{ type: 'field_sprite_picker', name: 'SPRITE', text: 'nave' }],
    previousStatement: 'JSStmt',
    nextStatement: 'JSStmt',
    colour: C,
    tooltip: 'Saiu por um lado da tela, reaparece no lado oposto (estilo Pac-Man/Asteroids).',
  },

  // ---- Tier 1: Pausa (estado do jogo) ----
  {
    type: 'sz_g2d_pause',
    placement: 'command',
    message0: 'Pausar o jogo',
    previousStatement: 'JSStmt',
    nextStatement: 'JSStmt',
    colour: C,
    tooltip:
      'Congela os blocos “A cada quadro” e os contatos. Eventos de tecla e clique continuam funcionando para você poder mandar continuar.',
  },
  {
    type: 'sz_g2d_resume',
    placement: 'command',
    message0: 'Continuar o jogo',
    previousStatement: 'JSStmt',
    nextStatement: 'JSStmt',
    colour: C,
    tooltip: 'Tira o jogo da pausa.',
  },
  {
    type: 'sz_g2d_is_paused',
    message0: 'o jogo está pausado?',
    output: 'JSValue',
    colour: EVENT_C,
    tooltip: 'Verdadeiro quando o jogo está pausado. Use num "se".',
  },

  // ---- Tier 2: Câmera (rola o mundo; o HUD fica fixo) ----
  {
    type: 'sz_g2d_camera_follow',
    placement: 'command',
    message0: 'Fazer a câmera seguir o sprite %1 (mundo %2 x %3)',
    args0: [
      { type: 'field_sprite_picker', name: 'SPRITE', text: 'jogador' },
      { type: 'input_value', name: 'WORLDW', check: 'JSValue' },
      { type: 'input_value', name: 'WORLDH', check: 'JSValue' },
    ],
    inputsInline: true,
    previousStatement: 'JSStmt',
    nextStatement: 'JSStmt',
    colour: C,
    tooltip:
      'A câmera centraliza no sprite (mundo maior que a tela), presa às bordas do mundo. Desenhe o HUD DEPOIS do mundo. Ele não se move.',
  },
  {
    type: 'sz_g2d_set_camera',
    placement: 'command',
    message0: 'Mover a câmera para x %1 y %2',
    args0: [
      { type: 'input_value', name: 'X', check: 'JSValue' },
      { type: 'input_value', name: 'Y', check: 'JSValue' },
    ],
    inputsInline: true,
    previousStatement: 'JSStmt',
    nextStatement: 'JSStmt',
    colour: C,
    tooltip: 'Posiciona a câmera na mão (canto superior esquerdo do que aparece na tela).',
  },
  {
    type: 'sz_g2d_camera_x',
    message0: 'a posição x da câmera',
    output: 'JSValue',
    colour: C,
    tooltip: 'Onde a câmera está no eixo x, útil para fundos em parallax.',
  },
  {
    type: 'sz_g2d_camera_y',
    message0: 'a posição y da câmera',
    output: 'JSValue',
    colour: C,
    tooltip: 'Onde a câmera está no eixo y, útil para fundos em parallax.',
  },

  // ---- Tier 2: Mapa destrutível (pela posição de um sprite) ----
  {
    type: 'sz_g2d_break_tile_at',
    placement: 'command',
    message0: 'Quebrar o tile do mapa %1 onde está o sprite %2',
    args0: [
      { type: 'field_name_picker', name: 'MAP', text: 'mapa', kind: 'tilemap' },
      { type: 'field_sprite_picker', name: 'SPRITE', text: 'jogador' },
    ],
    previousStatement: 'JSStmt',
    nextStatement: 'JSStmt',
    colour: C,
    tooltip: 'Apaga o tile que está sob o sprite (mineração/destruição). Vira espaço vazio.',
  },
  {
    type: 'sz_g2d_set_tile',
    placement: 'command',
    message0: 'No mapa %1, pôr o tile número %2 onde está o sprite %3',
    args0: [
      { type: 'field_name_picker', name: 'MAP', text: 'mapa', kind: 'tilemap' },
      { type: 'input_value', name: 'INDEX', check: 'JSValue' },
      { type: 'field_sprite_picker', name: 'SPRITE', text: 'jogador' },
    ],
    inputsInline: true,
    previousStatement: 'JSStmt',
    nextStatement: 'JSStmt',
    colour: C,
    tooltip: 'Coloca um tile (pelo número do tileset) na célula sob o sprite. Bom para construir.',
  },
  {
    type: 'sz_g2d_tile_at',
    message0: 'o número do tile do mapa %1 onde está o sprite %2',
    args0: [
      { type: 'field_name_picker', name: 'MAP', text: 'mapa', kind: 'tilemap' },
      { type: 'field_sprite_picker', name: 'SPRITE', text: 'jogador' },
    ],
    output: 'JSValue',
    colour: C,
    tooltip:
      'O número do tile na célula sob o sprite (-1 se estiver vazio). Use num "se" ou numa conta.',
  },

  // ---- Tier 2: Ordem de desenho dentro de um grupo ----
  {
    type: 'sz_g2d_bring_to_front',
    placement: 'command',
    message0: 'Trazer o sprite %1 para a frente no grupo %2',
    args0: [
      { type: 'field_sprite_picker', name: 'SPRITE', text: 'jogador' },
      { type: 'field_name_picker', name: 'GROUP', text: 'inimigos', kind: 'group' },
    ],
    previousStatement: 'JSStmt',
    nextStatement: 'JSStmt',
    colour: C,
    tooltip: 'Faz o sprite ser desenhado por ÚLTIMO no grupo (aparece na frente dos outros).',
  },
  {
    type: 'sz_g2d_send_to_back',
    placement: 'command',
    message0: 'Mandar o sprite %1 para trás no grupo %2',
    args0: [
      { type: 'field_sprite_picker', name: 'SPRITE', text: 'jogador' },
      { type: 'field_name_picker', name: 'GROUP', text: 'inimigos', kind: 'group' },
    ],
    previousStatement: 'JSStmt',
    nextStatement: 'JSStmt',
    colour: C,
    tooltip: 'Faz o sprite ser desenhado PRIMEIRO no grupo (fica atrás dos outros).',
  },

  // ---- Tier 2: Depuração ----
  {
    type: 'sz_g2d_draw_hitbox',
    placement: 'command',
    message0: 'Mostrar a caixa de colisão do sprite %1',
    args0: [{ type: 'field_sprite_picker', name: 'SPRITE', text: 'jogador' }],
    previousStatement: 'JSStmt',
    nextStatement: 'JSStmt',
    colour: C,
    tooltip: 'Desenha um contorno rosa na área de colisão do sprite (para depurar colisões).',
  },
  {
    type: 'sz_g2d_show_fps',
    placement: 'command',
    message0: 'Mostrar os quadros por segundo (FPS) em x %1 y %2',
    args0: [
      { type: 'input_value', name: 'X', check: 'JSValue' },
      { type: 'input_value', name: 'Y', check: 'JSValue' },
    ],
    inputsInline: true,
    previousStatement: 'JSStmt',
    nextStatement: 'JSStmt',
    colour: C,
    tooltip: 'Escreve quantos quadros por segundo o jogo está rodando (para ver a performance).',
  },
  {
    // Moldura no ELEMENTO do canvas (não desenhada por dentro): não gasta pixel
    // do jogo, nada a apaga e não custa nada por quadro. Família do "mostrar a
    // caixa de colisão": serve para enxergar o que normalmente é invisível.
    type: 'sz_g2d_stage_border',
    placement: 'start-only-command',
    message0: 'Mostrar a borda da tela, cor %1 espessura %2',
    args0: [
      { type: 'field_colour_sz', name: 'COLOR', colour: '#e2e8f0' },
      { type: 'input_value', name: 'WIDTH', check: 'JSValue' },
    ],
    inputsInline: true,
    previousStatement: 'JSStmt',
    nextStatement: 'JSStmt',
    colour: C,
    tooltip:
      'Desenha uma moldura colorida em volta da tela do jogo, para ver onde começa e termina a área de desenho. Ótimo para explicar o palco. Para tirar, apague o bloco.',
  },
] satisfies BlockDefinition[]
