/** Contrato interno do ciclo de vida compartilhado pelo gerador, runtime e testes. */
export interface GameTwoDLifecycleApi {
  gameLoop(fn: () => void, id?: string): () => void
  onStart(fn: () => void, id?: string): void
  onPointer(fn: (x: number, y: number) => void, id?: string): void
  onKey(key: string, fn: () => void, id?: string): void
  pointer: { x: number; y: number; down: boolean }
  restart(): void
  setupStage(width: number, height: number, background: string, description?: string): void
  sceneIs(name: string): boolean
}

/**
 * Inventário compilável da API pública interna injetada em `window.SZGame2D`.
 *
 * O runtime continua JavaScript didático, montado como texto para o iframe. Esta
 * lista é a fronteira tipada entre ele e os geradores: a auditoria executa o
 * bootstrap e exige igualdade exata entre estas chaves e o objeto real.
 */
export const GAME_TWO_D_API_KEYS = [
  'createSprite',
  'drawSprite',
  'clear',
  'fitScreen',
  'setupStage',
  'setupStageFull',
  'spawnBullet',
  'arrowsX',
  'blink',
  'isColliding',
  'onStart',
  'gameLoop',
  'keys',
  'setGravity',
  'applyVelocity',
  'bounceOnEdges',
  'circleCollides',
  'playSound',
  'playFx',
  'playMusic',
  'stopMusic',
  'playNote',
  'distance',
  'angleTo',
  'aimAt',
  'moveToward',
  'randomBetween',
  'randomChance',
  'setHealth',
  'changeHealth',
  'getHealth',
  'spriteX',
  'spriteY',
  'spriteW',
  'spriteH',
  'centerX',
  'centerY',
  'spriteVx',
  'spriteVy',
  'spriteSpeed',
  'isMoving',
  'isMovingH',
  'isMovingV',
  'randomX',
  'randomY',
  'hasHealth',
  'cooldownReady',
  'pruneOld',
  'flipSprite',
  'setOpacity',
  'setSize',
  'scaleSprite',
  'wrapEdges',
  'pauseGame',
  'resumeGame',
  'isPaused',
  'cameraFollow',
  'setCamera',
  'cameraX',
  'cameraY',
  'setTileAtSprite',
  'breakTileAtSprite',
  'tileAtSprite',
  'bringToFront',
  'sendToBack',
  'drawHitbox',
  'showFps',
  'onPointer',
  'onKey',
  'onOverlap',
  'keyDown',
  'touches',
  'pointer',
  'loadImage',
  'loadSpriteSheet',
  'setImage',
  'setAnimation',
  'drawFrame',
  'setStateAnimation',
  'autoAnimate',
  'defineShape',
  'setShape',
  'createShapeSprite',
  'shapeW',
  'shapeH',
  'paintRect',
  'paintCircle',
  'paintEllipse',
  'paintTriangle',
  'paintLine',
  'platformer',
  'topDown',
  'followPointer',
  'clampToScreen',
  'flash',
  'shake',
  'emitParticles',
  'drawParticles',
  'createTileMap',
  'createTileMapFromAsset',
  'drawTileMap',
  'collideTileMap',
  'collideGroup',
  'collideSprite',
  'tileAt',
  'createGroup',
  'spawn',
  'updateGroup',
  'updateGroupNoGravity',
  'drawGroup',
  'forEachInGroup',
  'countGroup',
  'clearGroup',
  'removeFromGroup',
  'pruneOffscreen',
  'overlapGroups',
  'everyFrames',
  'everySeconds',
  'drawScore',
  'drawLabel',
  'drawHearts',
  'drawBar',
  'setScene',
  'getScene',
  'sceneIs',
  'showScreen',
  'restart',
  'drawStarfield',
  'dragX',
  'createShip',
  'spawnAsteroid',
  'explodeSprite',
  'playShoot',
  'playExplosion',
  'overlapSpriteGroup',
  'createEnemyType',
  'setEnemyStateAnimation',
  'setEnemyTypeParam',
  'spawnEnemy',
  'updateEnemyType',
  'drawEnemyType',
  'onEnemyDefeated',
  'overlapEnemyShots',
  'enemyDamage',
  'hurtByEnemy',
  'rotateSprite',
  'pointSprite',
  'thrust',
  'applyFriction',
  'steerThrust',
  'spriteAngleDeg',
  'shootFrom',
  'spawnAsteroidFromEdge',
  'jumpOnGround',
  'createDino',
  'controlDino',
  'spawnObstacle',
  'spawnEgg',
  'drawForest',
  'playJump',
  'playDinoHurt',
  'playCollect',
  'createCity',
  'drawCity',
  'placeThrower',
  'newWind',
  'drawWind',
  'aimDrag',
  'aimReleased',
  'throwBanana',
  'updateBanana',
  'drawBanana',
  'bananaHitThrower',
  'bananaHitCity',
  'playWhistle',
  'computerTurn',
  'drawAimReadout',
  'createStickHero',
  'updateStickHero',
  'stickHeroScore',
  'stickHeroOver',
  'restartStickHero',
  'createBalloon',
  'updateBalloon',
  'balloonScore',
  'balloonFuel',
  'balloonOver',
  'restartBalloon',
] as const

export type GameTwoDApiKey = (typeof GAME_TWO_D_API_KEYS)[number]

type GameTwoDGenericMethod = (...args: unknown[]) => unknown

/**
 * Forma completa disponível para consumidores internos. Os métodos centrais têm
 * assinaturas específicas; os demais continuam explicitamente inventariados e
 * serão refinados por domínio conforme forem usados fora do gerador textual.
 */
export type GameTwoDRuntimeApi = GameTwoDLifecycleApi &
  Record<Exclude<GameTwoDApiKey, keyof GameTwoDLifecycleApi | 'keys'>, GameTwoDGenericMethod> & {
    keys: { left: boolean; right: boolean; up: boolean; down: boolean }
  }
