import { NATIVE_IMPORT_COPY } from './nativeImportCopy'

export const BBMODEL_IMPORT_COPY = {
  ...NATIVE_IMPORT_COPY,
  intro:
    'Traga um modelo do Blockbench para montar, pintar e animar na oficina. Primeiro confira a prévia; sua criação só muda quando você confirmar.',
  filesHint:
    'Escolha o .bbmodel e suas imagens PNG ou JPEG. Se houver subpastas, escolha a pasta completa. Agora aceitamos modelos livres (free), nas versões 4.9, 4.10 e 5.0.',
  limitsHint:
    'Podemos adaptar movimentos locais, pintura em quadros e camadas de tamanho completo com mistura normal, sem deslocamento. Materiais PBR completos e regras de controladores ainda não são convertidos. Não abrimos plugins nem executamos expressões do arquivo.',
  principalPlaceholder: 'Escolha o arquivo Blockbench',
  noEntry: 'Não encontrei um arquivo .bbmodel no conjunto. Adicione o modelo principal.',
  reading: 'Conhecendo as peças e a pintura…',
  appearance: 'Pintura e iluminação',
  appearanceHint:
    'Estas são escolhas para a prévia, não uma cópia exata da aparência no Blockbench. Confira o resultado antes de confirmar.',
  geometry: 'Peças e superfícies',
  omitted: 'O que pode ficar de fora',
  omittedHint:
    'Por padrão, paramos quando algo não pode ser trazido. Só escolha deixar conteúdo de fora se quiser uma cópia sem ele. O original não muda.',
  reject: 'Parar e explicar o que não pode entrar',
  sourcePreference: 'Quando há duas versões da imagem',
  embedded: 'Preferir a imagem guardada no modelo',
  files: 'Preferir a imagem dos arquivos escolhidos',
  normals: 'Luz nas faces',
  nativeNormals: 'Recalcular para a oficina; pode ficar mais facetado',
  lighting: 'Iluminação da pintura',
  nativeLighting: 'Usar a iluminação da oficina; pode mudar o brilho',
  untextured: 'Faces sem imagem de pintura',
  uniform: 'Usar a cor escolhida abaixo',
  color: 'Cor para faces sem pintura',
  alpha: 'Opacidade dessa cor',
  doubleSided: 'Mostrar os dois lados das faces sem pintura',
  autoSides: 'Quando a textura deixa os lados no automático',
  front: 'Mostrar só a frente',
  double: 'Mostrar os dois lados',
  quads: 'Faces com quatro cantos',
  sourceTriangles: 'Dividir em dois triângulos como na origem',
  editableQuads: 'Manter quatro cantos; o desenho pode mudar',
  nonPositiveCubes: 'Cubos planos ou invertidos',
  preserveCubes: 'Manter as medidas e registrar no relatório',
  missingUvs: 'Cantos sem posição de pintura',
  zeroUvs: 'Usar o início da imagem nesses cantos',
  groupFlags: 'Grupos ocultos ou travados',
  inheritFlags: 'Aplicar o estado do grupo às peças dentro dele',
  outsideUvs: 'Pintura fora do quadro',
  clampUvs: 'Estender a cor da borda do quadro',
  repeatWrap: 'Imagens que se repetem nas bordas',
  renderOrder: 'Ordem especial de desenho das peças',
  discardOrder: 'Usar a ordem da oficina e registrar',
  seamLabels: 'Etiquetas de união e corte da malha',
  discardSeams: 'Não trazer as etiquetas; manter os cantos de pintura',
  cubeShade: 'Marca de sombra dos cubos',
  discardShade: 'Não trazer a marca e registrar',
  renderModes: 'Efeitos especiais de textura',
  standardModes: 'Usar pintura comum; o efeito pode desaparecer',
  pbrGroups: 'Conjuntos de materiais PBR',
  textureOnly: 'Usar só a imagem ligada à face, sem o conjunto PBR',
  rgba16: 'Imagens com precisão extra de cor',
  roundColors: 'Ajustar à precisão da oficina e registrar',
  layers: 'Camadas de pintura ativas',
  editableLayers: 'Manter separadas com a mistura do Molda; a transparência pode mudar',
  paintReview: 'Confira as camadas da pintura',
  paintOrder:
    'De baixo para cima: as últimas camadas ficam por cima das primeiras. Camadas ocultas continuam guardadas para editar.',
  paintSummary: (images: number, layers: number) =>
    `${layers} ${layers === 1 ? 'camada editável' : 'camadas editáveis'} em ${images} ${images === 1 ? 'imagem' : 'imagens'}. A pintura veio das camadas, não da imagem pronta.`,
  paintLayersUnit: (count: number) => (count === 1 ? 'camada' : 'camadas'),
  paintVisible: 'visível',
  paintHidden: 'oculta',
  paintNameChanged: 'Nome ajustado para a oficina; o nome de origem está no relatório.',
  paintSizeChanged: 'O tamanho anotado era diferente. Usamos o tamanho real do PNG, sem recortar.',
  paintColorChanged: 'Precisão de cor ajustada para 8 bits, conforme sua escolha.',
  paintPrevious: 'Imagens anteriores',
  paintNext: 'Próximas imagens',
  paintPage: (page: number, total: number) => `Pinturas: página ${page} de ${total}`,
  unlisted: 'Peças fora da lista de montagem',
  append: 'Trazer essas peças ao final da lista',
  omitUnlisted: 'Não trazer essas peças e registrar',
  unsupportedNodes: 'Peças de um tipo ainda não aceito',
  omitSubtree: 'Não trazer a peça nem o que está dentro dela',
  unsupportedFaces: 'Faces ainda não aceitas',
  omitFaces: 'Não trazer essas superfícies; manter os pontos',
  exportFlags: 'Marcas de peças que não devem ser exportadas',
  discardExport: 'Trazer as peças sem guardar essa marca',
  unmapped: 'Informações sem equivalente na oficina',
  discardUnmapped: 'Não guardar essas informações e registrar cada campo',
  movements: 'Trazer os movimentos',
  animations: 'Movimentos das peças',
  omitAnimations: 'Trazer só a forma inicial, sem movimentos',
  convertAnimations: 'Trazer e adaptar os movimentos para revisar',
  controllers: 'Regras que ligam um movimento a outro',
  omitControllers: 'Não trazer os controladores nem executar suas regras',
  summary: (parts: number, images: number, triangles: number) =>
    `${parts} peças · ${images} imagens · ${triangles.toLocaleString('pt-BR')} triângulos de desenho`,
  sourceSummary: (version: string, omitted: number, unused: number) =>
    `Modelo livre ${version}. Peças não trazidas: ${omitted}. Texturas sem uso: ${unused}.`,
} as const
