/**
 * Copy do Molda, 100% em português e centralizada. Sem travessão, sem jargão
 * ("etapa", "curso-base" são varridos pelos testes do kids). Texto de UI vive
 * AQUI (os componentes só referenciam), para revisão de tom num lugar só.
 */

import type { SkyPresetChoice } from '../sky/params'
import type { MoldaTemplateId } from '../templates/catalog'
import type { MoldaAssetKind, ShapeId } from './model'

export const COPY = {
  appName: 'Molda',
  gallery: {
    title: 'Minhas criações 3D',
    subtitle: 'Modelos, texturas e céus para os seus jogos 3D.',
    create: 'Criar novo',
    empty: 'Nada por aqui ainda. Toque em "Criar novo" para montar a sua primeira criação!',
    emptyCta: 'Começar minha primeira criação',
    loading: 'Abrindo a sua galeria...',
    loadError: 'Não consegui abrir a sua galeria. Tente de novo daqui a pouco.',
    retry: 'Tentar de novo',
    open: 'Abrir',
    rename: 'Renomear',
    duplicate: 'Duplicar',
    remove: 'Apagar',
    removeConfirmTitle: 'Apagar esta criação?',
    removeConfirmBody: 'Ela vai sumir da galeria. Não dá para desfazer.',
    removeConfirm: 'Apagar',
    cancel: 'Cancelar',
    storageBudget:
      'Sua galeria chegou ao limite de 96 MB. Apague uma criação grande para continuar salvando.',
    downloadAll: 'Baixar tudo',
    downloadPreparing: 'Preparando o seu pacote... Os céus demoram um pouquinho.',
    downloadReady: 'Baixei a sua galeria! Procure o .zip na pasta de downloads.',
    downloadFailed: 'Não consegui montar o pacote agora. Tente de novo daqui a pouco.',
    importJson: 'Trazer de volta',
    importHint: 'Escolha o .zip ou o .molda.json que você baixou antes.',
    imported: (count: number) =>
      count === 1 ? 'Trouxe 1 criação de volta!' : `Trouxe ${count} criações de volta!`,
    importedNone: 'Esse arquivo não tinha nenhuma criação que eu conseguisse ler.',
    importFailed:
      'Não consegui ler esse arquivo. Ele veio do "Baixar tudo" do Molda (.zip ou .molda.json)?',
    restoreTooLarge: 'Esse backup é grande demais. Escolha um arquivo de até 32 MB.',
    restoreZipMissing: 'Esse .zip não tem a galeria do Molda.',
    restoreZipDuplicate:
      'Esse .zip tem mais de uma galeria do Molda e não é seguro trazê-lo de volta.',
    /** O LEIA-ME.txt de dentro do "Baixar tudo". */
    readme: {
      intro: [
        'Suas criações 3D do Molda! 🧊',
        '',
        'Cada pasta tem um tipo de criação, pronta para o Estúdio ou para qualquer editor 3D:',
        '  modelos/   arquivos .glb  → no Jogo 3D, o bloco "Criar o objeto ... com o modelo"',
        '  texturas/  arquivos .png  → o bloco "Vestir ... com a imagem"',
        '  ceus/      arquivos .hdr  → o bloco "Usar o céu 360°"',
        '',
        'No Estúdio, o jeito mais fácil continua sendo o botão "Trazer do Molda" do painel de imagens.',
        'Para voltar com tudo para o Molda, use o botão "Trazer de volta" e escolha este .zip.',
        'O arquivo galeria.molda.json é o backup completo: não apague.',
      ],
      model: (name: string, file: string, parts: number, triangles: number) =>
        `• Modelo "${name}": modelos/${file}.glb (${parts === 1 ? '1 peça' : `${parts} peças`}, ${triangles} triângulos)`,
      texture: (name: string, file: string, size: number) =>
        `• Textura "${name}": texturas/${file}.png (${size} × ${size} pixels)`,
      sky: (name: string, file: string, width: number, height: number) =>
        `• Céu "${name}": ceus/${file}.hdr (360°, ${width} × ${height})`,
      skipped: (kindTitle: string, name: string) =>
        `• ${kindTitle} "${name}" ficou fora dos arquivos prontos (sem peças ou grande demais para o Estúdio), mas está no backup.`,
    },
    search: 'Buscar criação',
    searchPlaceholder: 'Buscar por nome ou tipo',
    searchClear: 'Limpar busca',
    searchClearAll: 'Limpar busca e filtros',
    searchEmpty: 'Nenhuma criação combina com essa busca.',
    syncing: 'Buscando na sua conta as criações que ainda não chegaram...',
    filterKind: 'Tipo',
    filterAll: 'Todos',
    filterAria: {
      all: 'Mostrar todos os tipos',
      model: 'Mostrar só modelos',
      texture: 'Mostrar só texturas',
      sky: 'Mostrar só céus',
    },
    resultCount: (count: number, total: number) =>
      count === total ? (count === 1 ? '1 criação' : `${count} criações`) : `${count} de ${total}`,
    openStudio: 'Abrir o Estúdio',
    studioHint: 'No Estúdio, procure "Trazer do Molda" no painel de imagens.',
    cardMenu: (name: string) => `Mais opções de ${name}`,
    updated: 'Mexido',
  },
  kinds: {
    model: {
      title: 'Modelo',
      plural: 'Modelos',
      description: 'Monte peças e pinte a pele direto no modelo.',
      emoji: '🧊',
      file: '.glb',
    },
    texture: {
      title: 'Textura',
      plural: 'Texturas',
      description: 'Uma folha de pixels para vestir cubos e bolas.',
      emoji: '🧱',
      file: '.png',
    },
    sky: {
      title: 'Céu',
      plural: 'Céus',
      description: 'Um céu 360° que ilumina a cena inteira.',
      emoji: '🌤️',
      file: '.hdr',
    },
  } satisfies Record<
    MoldaAssetKind,
    { title: string; plural: string; description: string; emoji: string; file: string }
  >,
  shapes: {
    box: 'Caixa',
    wedge: 'Rampa',
    cylinder: 'Cilindro',
    sphere: 'Bola',
  } satisfies Record<ShapeId, string>,
  skyPresets: {
    dia: 'Dia',
    entardecer: 'Entardecer',
    noite: 'Noite',
    nublado: 'Nublado',
    alienigena: 'Alienígena',
    custom: 'Do seu jeito',
  } satisfies Record<SkyPresetChoice, string>,
  newAsset: {
    title: 'Criar novo',
    stepKind: 'O que você quer criar?',
    stepOptions: 'Como vai ser?',
    stepName: 'Que nome vai ter?',
    progress: (current: number, total: number) => `Passo ${current} de ${total}`,
    texelsLabel: 'Texels por bloco',
    texelsHint: 'Quantos pontinhos de tinta cabem em cada bloco da grade. Dá para mudar depois.',
    texelsOptions: {
      2: 'Poucos',
      4: 'Normal',
      8: 'Muitos',
    } as Record<number, string>,
    sizeLabel: 'Tamanho da folha',
    sizeHint: 'Em pixels. 32 é um bom começo.',
    presetLabel: 'Comece com',
    presetHint: 'Você ajusta o sol, as cores e as nuvens depois.',
    nameLabel: 'Nome',
    namePlaceholder: 'ex: nave, casa, grama',
    nameHint: 'Só letras, números e hífen. É o nome que o Estúdio vai usar.',
    nameInvalid: 'Use só letras, números e hífen.',
    nameTaken: 'Já existe uma criação com esse nome.',
    back: 'Voltar',
    next: 'Continuar',
    create: 'Criar',
    cancel: 'Cancelar',
  },
  /** "Modelos prontos": o 4º cartão do Criar novo e a grade de escolha. */
  templates: {
    card: {
      emoji: '✨',
      title: 'Modelos prontos',
      description: 'Comece de um modelo pronto e mude do seu jeito.',
    },
    stepTitle: 'Escolha um modelo para começar',
    items: {
      personagem: {
        title: 'Personagem',
        description: 'Um boneco de blocos com o rosto já pintado.',
      },
      carro: { title: 'Carro', description: 'Rodas, vidros e faróis. Pinte do seu jeito.' },
      arvore: { title: 'Árvore', description: 'Tronco, copa de bolas e frutinhas.' },
      casa: { title: 'Casa', description: 'Paredes, telhado de duas águas, porta e janelas.' },
      nave: { title: 'Nave espacial', description: 'Asas, motores e uma cabine de vidro.' },
    } satisfies Record<MoldaTemplateId, { title: string; description: string }>,
  },
  rename: {
    title: 'Renomear',
    label: 'Novo nome',
    save: 'Salvar',
    cancel: 'Cancelar',
    open: 'Feche a criação antes de renomear.',
  },
  editor: {
    back: 'Voltar',
    backToGallery: 'Voltar para a galeria',
    undo: 'Desfazer',
    redo: 'Refazer',
    saved: 'Salvo',
    saving: 'Salvando...',
    dirty: 'Mudanças por salvar',
    saveError: 'Não consegui salvar. Sua galeria pode ter chegado ao limite.',
    download: 'Baixar',
    modelSummary: (parts: number) => (parts === 1 ? '1 peça' : `${parts} peças`),
    textureSummary: (size: number) => `${size} × ${size} pixels`,
    skyPresetLabel: 'Tipo de céu',
    /** A bancada do MODELO (Montar). */
    model: {
      mode: { build: 'Montar', paint: 'Pintar' },
      toolbox: 'Ferramentas',
      addGroup: 'Adicionar',
      add: {
        box: 'Caixa',
        wedge: 'Rampa',
        cylinder: 'Cilindro',
        sphere: 'Bola',
      } satisfies Record<ShapeId, string>,
      tools: { move: 'Mover', rotate: 'Girar', scale: 'Tamanho' },
      duplicate: 'Duplicar',
      remove: 'Apagar',
      mirror: 'Espelhar no X',
      snapHalf: 'Encaixe de meio bloco',
      parts: 'Peças',
      partsCount: (count: number, max: number) => `${count}/${max}`,
      partsEmpty: 'Nenhuma peça. Adicione uma caixa para começar.',
      twinTag: 'espelho',
      partsFull: 'Chegou ao limite de peças. Apague alguma para adicionar outra.',
      placeHint: 'Agora toque no chão ou numa peça para colocar a forma.',
      colors: 'Cores',
      addColor: 'Nova cor',
      paletteLabel: 'Paleta',
      colorsFull: 'A paleta já tem o máximo de cores extras.',
      properties: 'Propriedades',
      noSelection: 'Toque numa peça para ver as propriedades.',
      twinSelected: 'Esta peça é o espelho de outra: mexa na peça original.',
      name: 'Nome',
      shape: 'Forma',
      position: 'Posição',
      size: 'Tamanho',
      rotation: 'Giro',
      axis: { x: 'X', y: 'Y', z: 'Z' },
      dims: { w: 'Largura', h: 'Altura', d: 'Fundo' },
      views: {
        front: 'Frente',
        back: 'Trás',
        left: 'Esquerda',
        right: 'Direita',
        top: 'Cima',
        frame: 'Enquadrar',
      },
      grid: 'Grade',
      status: (parts: number, max: number, triangles: number) =>
        `${parts}/${max} peças · ${triangles} triângulos`,
      unsupported:
        'Não consegui abrir o 3D neste navegador. Tente no Chrome ou no Edge mais recentes.',
      panelsToggle: 'Peças e propriedades',
      thumbPending: 'Preparando a miniatura...',
      statusAtlas: (size: number) => `atlas ${size}×${size}`,
      /** O modo PINTAR. */
      paint: {
        tools: {
          pencil: 'Lápis',
          eraser: 'Borracha',
          fillFace: 'Balde na face',
          fillPart: 'Balde na peça',
          picker: 'Conta-gotas',
        },
        mirror: 'Espelho de pintura',
        sizeLabel: 'Tamanho do lápis',
        sizes: { 1: 'Fino', 2: 'Médio', 3: 'Grosso' } as Record<number, string>,
        texelsLabel: 'Texels por bloco',
        texelsHint: 'Trocar re-desenha as peles no tamanho novo.',
        atlasFull:
          'Modelo grande demais para pintar tudo. Diminua os texels por bloco ou tire peças.',
        activeColor: 'Cor do lápis',
        removeColor: 'Apagar esta cor',
        removeColorBase:
          'As 16 cores da paleta são fixas. Só as cores que você adicionou podem ser apagadas.',
        removedColor: 'Cor apagada.',
        /** "Vestir a peça com uma textura" da galeria. */
        apply: {
          button: 'Vestir com textura',
          title: 'Vestir a peça com uma textura',
          pick: 'Suas texturas',
          empty: 'Você ainda não tem texturas. Crie uma na galeria e volte aqui.',
          modeLabel: 'Como vestir',
          modeTile: 'Repetir',
          modeStretch: 'Esticar',
          apply: 'Vestir',
          applied: 'Peça vestida!',
          selectPart: 'Toque numa peça primeiro.',
        },
      },
      download: {
        glb: 'Baixar .glb',
        ready: 'Baixei o modelo! Procure na pasta de downloads.',
        tooBig:
          'O modelo ficou grande demais para o Estúdio. Diminua os texels por bloco ou tire peças.',
        empty: 'Adicione uma peça antes de baixar.',
        failed: 'Não consegui preparar o arquivo agora.',
      },
    },
    /** O editor da TEXTURA. */
    texture: {
      stage: 'Folha de pixels',
      tiled: 'Repetida 3×3',
      preview3d: 'Prévia 3D',
      tools: { pencil: 'Lápis', eraser: 'Borracha', fill: 'Balde', picker: 'Conta-gotas' },
      seamless: 'Sem emenda',
      shiftHalf: 'Deslocar meio',
      transparentHint: 'A borracha deixa o pixel transparente. No jogo, transparente vira preto.',
      unsupported: 'Sem prévia 3D neste navegador.',
      download: {
        png: 'Baixar .png',
        ready: 'Baixei a textura! Procure na pasta de downloads.',
        tooBig: 'A textura ficou grande demais para o Estúdio.',
        failed: 'Não consegui preparar o arquivo agora.',
      },
    },
    /** O editor do CÉU. */
    sky: {
      preview: 'Prévia do céu',
      controls: 'Controles do céu',
      presetsPanel: 'Céu de partida',
      sun: 'Sol',
      elevation: 'Altura do sol',
      azimuth: 'Direção do sol',
      size: 'Tamanho do sol',
      intensity: 'Brilho do sol',
      colors: 'Cores',
      top: 'Topo',
      horizon: 'Horizonte',
      ground: 'Chão',
      clouds: 'Nuvens',
      amount: 'Quantidade',
      softness: 'Suavidade',
      shuffle: 'Sortear nuvens',
      stars: 'Estrelas',
      exposure: 'Exposição',
      degrees: (value: number) => `${value}°`,
      percent: (value: number) => `${Math.round(value * 100)}%`,
      unsupported:
        'Não consegui abrir a prévia 3D neste navegador. O céu continua sendo salvo e baixado normalmente.',
      download: {
        hdr: 'Baixar .hdr',
        preparing: 'Preparando o céu...',
        ready: 'Baixei o céu! Procure na pasta de downloads.',
        tooBig: 'O céu ficou grande demais para o Estúdio.',
        failed: 'Não consegui preparar o arquivo agora.',
      },
    },
    comingSoon: {
      model: 'A bancada de montar e pintar chega no próximo passo do Molda.',
      texture: 'A folha de pintar chega no próximo passo do Molda.',
      sky: 'Os controles do sol, das cores e das nuvens chegam no próximo passo do Molda.',
    } satisfies Record<MoldaAssetKind, string>,
    notFound: 'Essa criação não está mais aqui. Escolha outra na sua galeria.',
  },
  toast: {
    created: (name: string) => `"${name}" criado!`,
    renamed: 'Renomeado!',
    duplicated: 'Duplicado!',
    removed: 'Apagado.',
    saveFailed: 'Não consegui salvar a criação.',
  },
  a11y: {
    galleryGrid: 'Suas criações',
    assetCard: (name: string, kind: string) => `${kind} ${name}`,
    closeDialog: 'Fechar',
    kindFilter: 'Filtrar por tipo',
    newAssetKind: (kind: string) => `Criar ${kind.toLowerCase()}`,
    openTemplates: 'Escolher um modelo pronto',
    templateCard: (title: string) => `Modelo pronto ${title}`,
    skyThumb: (preset: string) => `Céu ${preset.toLowerCase()}`,
    textureThumb: 'Prévia da textura',
    modelThumb: 'Prévia do modelo',
    editorStatus: 'Estado do salvamento',
    viewport: 'Palco 3D',
    partItem: (name: string, shape: string) => `${name}, ${shape.toLowerCase()}`,
    colorSwatch: (index: number, hex: string) => `Cor ${index} ${hex}`,
    decrease: (label: string) => `Diminuir ${label.toLowerCase()}`,
    increase: (label: string) => `Aumentar ${label.toLowerCase()}`,
    paletteSelect: 'Escolher a paleta',
  },
} as const

export type MoldaCopy = typeof COPY
