import { NATIVE_IMPORT_COPY } from './nativeImportCopy'

export const OBJ_IMPORT_COPY = {
  ...NATIVE_IMPORT_COPY,
  intro:
    'Traga um modelo OBJ para montar e pintar. Primeiro você verá uma prévia; sua criação só muda quando você confirmar.',
  filesHint:
    'Escolha o .obj, os materiais .mtl e as imagens juntos. Se houver subpastas, escolha a pasta completa para manter os caminhos. OBJ não traz movimentos ou ossos.',
  principalPlaceholder: 'Escolha o arquivo OBJ',
  noEntry: 'Não encontrei um arquivo .obj no conjunto. Adicione o modelo principal.',
  reading: 'Conhecendo as partes e os materiais…',
  appearance: 'Como o modelo vai aparecer',
  appearanceHint:
    'Estas escolhas são um ponto de partida, não uma detecção automática. Confira as cores e o relevo na prévia. Mudar uma escolha pede outra prévia.',
  doubleSided: 'Mostrar os dois lados das faces',
  colorAlpha: 'Usar também a transparência da imagem de cor',
  normalY: 'Orientação do relevo',
  normalPositive: 'Padrão positivo (OpenGL)',
  normalNegative: 'Padrão negativo (DirectX)',
  colorSpaces: 'Leitura das cores',
  baseSpace: 'Cores escritas no material (Kd)',
  colorSpace: 'Imagens de cor',
  scalarSpace: 'Imagens de brilho e transparência',
  linear: 'Valores lineares',
  srgb: 'Cores sRGB',
  conflicts: 'Quando o arquivo tem escolhas repetidas',
  maps: 'Mapas e aproximações',
  libraryMode: 'Várias listas de materiais (mtllib)',
  librarySingle: 'Pedir escolha se houver várias listas',
  libraryDeclaration: 'Usar a lista declarada para cada parte',
  libraryAll: 'Procurar em todas as listas, em ordem',
  duplicateMaterials: 'Materiais com o mesmo nome',
  repeatedProperties: 'Propriedades repetidas no material',
  repeatedOptions: 'Opções repetidas de uma imagem',
  roleConflicts: 'Imagens diferentes para o mesmo papel',
  reject: 'Parar e mostrar o que precisa de escolha',
  first: 'Usar a primeira declaração',
  last: 'Usar a última declaração',
  missingMaterials: 'Quando falta um material pelo nome',
  defaultMaterial: 'Usar branco e registrar no relatório',
  opacityConflict: 'Quando d e Tr definem transparência juntos',
  opacityD: 'Usar d (opacidade)',
  opacityTr: 'Usar Tr (transparência)',
  unsupportedMaps: 'Imagens sem papel compatível',
  omitMaps: 'Trazer sem essas imagens e registrar',
  bump: 'Imagem bump, normalmente usada como altura',
  bumpNormal: 'Interpretar como imagem de normais RGB',
  specularMap: 'Imagem map_Ns',
  roughnessMap: 'Interpretar como rugosidade',
  transparencyMap: 'Imagem map_Tr',
  opacityMap: 'Interpretar como opacidade',
  invertedOpacityMap: 'Interpretar como transparência e inverter',
  phongRoughness: 'Brilho Ns sem mapa de rugosidade',
  blenderRoughness: 'Aproximar usando a fórmula do Blender',
  illumination: 'Outros modelos de iluminação (illum)',
  pbrIllumination: 'Adaptar para a iluminação da oficina',
  opacitySampling: 'Máscara de transparência com outro tamanho',
  nearestOpacity: 'Ajustar usando o pixel mais próximo',
  emptyObjects: 'Objetos vazios',
  preserveEmpty: 'Guardar como grupos vazios',
  omitEmpty: 'Trazer sem eles e registrar',
  summary: (parts: number, materials: number, triangles: number) =>
    `${parts} partes · ${materials} materiais · ${triangles.toLocaleString('pt-BR')} triângulos de desenho`,
  unusedMaterials: (count: number) =>
    `${count} declarações de material não usadas pelas faces não foram convertidas. Guarde o conjunto original.`,
} as const
